- frontend/src/core/editor/components/connectedEditor.js
- frontend/src/modules/fluenteditor/components/RichTranslationForm.js
- frontend/src/modules/fluenteditor/components/RichTranslationForm.test.js
- frontend/src/modules/genericeditor/components/GenericTranslationForm.js
In https://github.com/mozilla/pontoon/commit/ceaaa1b95104ffce5b1f26eabadd97e22c7af209 we moved `handleShortcuts` to `connectedEditor` and reused the method in Generic and Source Editor.
This patch does that for the Rich Editor as well, by adding the ability to pass overriden functions as callbacks.
It also passes the overriden `saveTranslation` function for the Generic Editor, which was left out in ceaaa1b95104ffce5b1f26eabadd97e22c7af209 and caused problems.
> Reuse handle shortcuts

- frontend/package.json
- frontend/src/App.css
- frontend/src/core/editor/actions.js
- frontend/src/modules/history/actions.js
- frontend/yarn.lock
Unlike in Translate.Current, where we show the progress bar for almost any AJAX call,
in Translate.Next we only show it when changes are made to a single translation,
i.e. on save, (un)approve, (un)reject and delete operations.
We already show different progress bars/loaders when searching or filtering entities,
switching resources or performing batch actions and there's no reason to duplicate them.
In fact, duplicating loaders might negatively impact perceived performance. So does
"extending" the progress bar in Translate.Current, which starts at Translation save
and ends only when Helper tabs end loading for the next entity.
We should however consider:
1. Removing or repositioning translation action notifications, because they overlap with the progress bar.
2. Removing existing loaders …
> Fix bug 1547274: Implement a 'nanoscopic' NProgress bar at the top

- pontoon/base/static/css/style.css
- pontoon/base/templates/registration/login.html
The "Sign In" button on the standalone page appeared (to me, anyhow) disabled.  (I think this is because it was getting the default button colors, which seem to be designed for a green, not white, background.)
Before:
After:
> Style "Sign In" button on standalone login page

- frontend/src/core/placeable/parsers/fluentFunction.js
- frontend/src/core/placeable/parsers/fluentFunction.test.js
- frontend/src/core/placeable/parsers/fluentParametrizedTerm.js
- frontend/src/core/placeable/parsers/fluentParametrizedTerm.test.js
- frontend/src/core/placeable/parsers/fluentString.js
- frontend/src/core/placeable/parsers/fluentString.test.js
- frontend/src/core/placeable/parsers/fluentTerm.js
- frontend/src/core/placeable/parsers/fluentTerm.test.js
I've also checked other similar (but non-Fluent) placeables (e.g. python*, java*) and they work fine.
> Fix bug 1583764: Properly detect multiple peer Fluent placeables

- frontend/src/core/utils/fluent/extractAccessKeyCandidates.js
- frontend/src/core/utils/fluent/extractAccessKeyCandidates.test.js
We remove content between each `{` and `}` pair instead of parsing messages (which doesn't work for half-translated strings) and removing non-`TextElement` elements.
> Fix bug 1584579: Exclude placeables from access key candidates if key not translated

- docs/admin/deployment.rst
- pontoon/settings/base.py
- pontoon/teams/templates/teams/team.html
The Bugs tab on the Team page (e.g. https://pontoon.mozilla.org/fr/bugs/) lists should not be enabled for those outside of Mozilla.
This fix adds an environment variable and then utilizes the value set in that variable to determine if the Bugs tab should display or not.
> Fix bug 1567402 - Make bugs tab disabled by default

- pontoon/base/migrations/0098_move_ms_locales_to_db.py
- pontoon/base/migrations/0130_translation_active_unique_constraint.py
- pontoon/base/migrations/0134_google_translate_code.py
- requirements/default.txt
Hey @mathjazz 
Tests are failing on Python 3 because the database migrations throw errors (I'll post them as comments).
I've fixed the migrations and updated the `django-bulk-update` package to the latest version.
Can you look at this? Thanks :-)
> Bug 1585252 - Fix database migrations on Python 3

- frontend/public/static/locale/en-US/translate.ftl
- frontend/src/core/notification/messages.js
- frontend/src/modules/entitydetails/components/EntityDetails.js
- frontend/src/modules/entitydetails/components/EntityNavigation.css
- frontend/src/modules/entitydetails/components/EntityNavigation.js
- frontend/src/modules/entitydetails/components/EntityNavigation.test.js
Add a feature to generate a permanent link to a string, without any (or at least mutable) queryset parameters (e.g. status filters).
This fix adds a link which when clicked will add the correct URL (without additional parameters) to the clipboard and display a message to let the user know the copy has been made.
> Fix bug 1501356 - Add ability to generate a permalink to a string

- Makefile
- pontoon/base/models.py
- pontoon/base/tests/__init__.py
- pontoon/batch/tests/test_views.py
- pontoon/sync/changeset.py
- pontoon/sync/formats/compare_locales.py
- pontoon/sync/formats/silme.py
- pontoon/sync/tests/formats/__init__.py
- pontoon/sync/tests/formats/test_compare_locales.py
- pontoon/tags/tests/test_views.py
- pontoon/teams/tests/test_views.py
- pontoon/translate/tests/test_views.py
Hey!
I've decided to fix 120 tests to speed things up. ~110 left to go.
I'll update the commit message to give more context about errors that had been fixed.
List of fixed tests for Python 3:
```
file=pontoon/base/tests/managers/test_entity.py name=test_mgr_entity_reset_active_translations
file=pontoon/contributors/tests/test_views.py name=test_invalid_email
file=pontoon/contributors/tests/test_views.py name=test_invalid_first_name
file=pontoon/contributors/tests/test_views.py name=test_missing_profile_fields
file=pontoon/contributors/tests/test_views.py name=test_user_locales_order
file=pontoon/contributors/tests/test_views.py name=test_valid_first_name
file=pontoon/pretranslation/tests/test_pretranslate.py name=test_get_translations
file=pontoon/sync/tests/test_changeset.py …
```
> Bug 1585251 fix typeerorr bugs

- frontend/public/static/locale/en-US/translate.ftl
- frontend/public/static/locale/fr/translate.ftl
- frontend/src/core/user/components/UserMenu.css
- frontend/src/core/user/components/UserMenu.js
- pontoon/base/static/css/fontawesome-all.css
- pontoon/base/static/css/style.css
- pontoon/base/templates/django/base.html
- pontoon/base/templates/header.html
This pull request fixes the issue [1567394](https://bugzilla.mozilla.org/show_bug.cgi?id=1567394). It allows a user to access the issue tracker from the Pontoon app and also give feedback via [pontoon's](https://discourse.mozilla.org/c/pontoon) feedback page.
- Clone this repository 
- Git checkout to `katherine95:access-issue-tracker`branch.
- Follow the setup guidelines to set up pontoon locally
- Run `make run`
- Login to Pontoon
- Navigate to your profile and click on it.
- Click on `Hack it on Github`  and `Give feedback`.
- Both should redirect you to Github and pontoon's feedback page respectively.
> Fix bug 1567394 - Allow access to issue tracker

- frontend/src/modules/entitydetails/components/EntityDetails.js
Displays "You have unsaved changes" message on executing review actions if there is a new translation in the translation input.
> Fix bug 1508474 - Add check for unsaved changes before executing review actions

- pontoon/base/static/css/table.css
- pontoon/teams/templates/teams/widgets/team_list.html
This fix make a long locale code in [teams] (https://pontoon.mozilla.org/teams/) page cut out and replaced by ellipsis (...) instead of showing them in two lines. This way long codes will not break the layout of the column or the table.
The outcome of this change :
> Fix Bug 1588468 - Prevent long Locale codes to break layout

- frontend/src/core/user/components/UserMenu.js
- frontend/src/modules/history/components/Translation.js
Setting width/height on user avatars prevents the surrounding UI from jumping while the image is loading.
Relatedly, we're also making the alt= attribute empty to prevent (rather meaningless) text from appearing during loading. Gmail, FB, TW, BZ all seem to pull the same trick.
@Henikilan Could you please review this?
> No bug: Set width/height on user avatars

- frontend/README.md
This change updates the README file on string identifiers for localized content based on official naming scheme decided on [bug 1528926](https://bugzilla.mozilla.org/show_bug.cgi?id=1528926#c7).
> Bug 1589344 - [Readme] String identifiers update

- docker/run_webapp.sh
- pontoon/settings/base.py
- pontoon/settings/dev.py
- pontoon/translate/views.py
Because of the way we set up static files for Translate.Next, in order to load them from the webpack server, we broke autoreloading of django static files. One had to rebuild the docker image in order to get updated static files. The problem was that the WhiteNoise middleware was taking over serving files, and in doing so only served from collected static files, thus never serving updated files in dev. With WhiteNoise disabled in dev, our static files serve function takes over and does the right thing at all time.
@mathjazz to be honest, I'm not sure I understand exactly what's happening there. WhiteNoise is supposed to serve files from disk when they get updated, but for whatever reason it doesn't. Anyway, this seems to work for me locally.
> Fix bug 1589137 - Autoreload django static files in dev.

- frontend/src/modules/search/components/FiltersPanel.js
- frontend/src/modules/search/components/FiltersPanel.test.js
- frontend/src/modules/search/components/SearchBox.js
Reset search placeholder icon when the filter selection is not applied
[1344120](https://bugzilla.mozilla.org/show_bug.cgi?id=1344120)
> Fix bug 1344120 - Reset search placeholder icon

- frontend/src/modules/fluentoriginal/components/RichString.test.js
- frontend/src/modules/fluentoriginal/components/SimpleString.test.js
- frontend/src/modules/fluentoriginal/components/SourceString.test.js
There are React components that are not tested in fluentoriginal module. 
The details for added tests are :
- SourceString Component 
- SimpleString Component 
- RichString Component 
FluentOriginalString did not get tested because it will be testing getSyntaxType() which already covered in https://github.com/mozilla/pontoon/blob/master/frontend/src/core/utils/fluent/getSyntaxType.test.js
> Bug 1579655 - Write tests for fluentoriginal module

- frontend/src/modules/entitieslist/components/Entity.css
- pontoon/base/static/css/translate.css
This pull request fixes the issue [1514555](https://bugzilla.mozilla.org/show_bug.cgi?id=1514555). It allows the string list to overflow instead of ellipsis.
- Clone this repository 
- Git checkout to `katherine95:1514555-remove-ellipsis` branch.
- Follow the setup guidelines to set up pontoon locally
- Run `make build` then `make run`
- Login to Pontoon
- Navigate to the tutorial project to load some string, e.g
`http://localhost:8000/projects/tutorial/playground/`
- The strings in the string list should overflow instead of ellipsis.
Before
After
> Fix bug 1514555 - Remove ellipsis and allow string to overflow

- frontend/public/static/locale/en-US/translate.ftl
- frontend/src/core/project/components/ProjectMenu.js
- frontend/src/core/project/components/ProjectMenu.test.js
- frontend/src/core/resource/components/ResourceMenu.js
- frontend/src/core/resource/components/ResourceMenu.test.js
This pull request fixes the issue [1588929](https://bugzilla.mozilla.org/show_bug.cgi?id=1588929). It has "All Resources" and "All Projects"  unaccented (unlocalized) in the main navigation bar:
- Clone this repository 
- Git checkout to `katherine95:1588929-localize-resources-projects` branch.
- Follow the setup guidelines to set up pontoon locally
- Run `make build` then `make run`
- Login to Pontoon
- Navigate to Resource menu (access it by clicking on "playground" in `http://localhost:8000/projects/tutorial/playground/`)
- "All Resources" and "All Projects" should both be localized
`localhost:8000/projects/tutorial/all-resources/?pseudolocalization=accented`
`localhost:8000/projects/all-projects/all-resources/?pseudolocalization=accented`
[x] Both "All Resources" and "All Projects" …
> Fix bug 1588929 - Localize 'All Projects' & 'All resources' in the main navigation bar

- frontend/src/core/editor/components/connectedEditor.js
- frontend/src/core/editor/components/connectedEditor.test.js
**What does this PR do?**
This pull request fixes the issue [1490026](https://bugzilla.mozilla.org/show_bug.cgi?id=1490026). It disables keyboard triggers when the editor is in read only, so that non authenticated users can not trigger keyboard updates on the editor. 
**How can this be tested**
- Go to any translate page. 
- Make sure you are logged out.
- Press Tab 2 times to focus the translation field.
- Press Enter to submit the translation
> Fix bug 1490026 - Disable keyboard triggers when editor is read only

- frontend/src/modules/fluenteditor/components/Editor.js
In editor.js->componentDidUpdate add else if to check the content copied from machinery tab.
In case parsed to fluent message content is Junk, convert it to complex
[Bug 1555259](https://bugzilla.mozilla.org/show_bug.cgi?id=1555259)
> Bug 1555259: Copying from Machinery to Source editor results in a broken string

- pontoon/homepage/static/css/homepage.css
This is the problem we're fixing:
> No bug: Edit Homepage button should not cover menus

- pontoon/homepage/templates/homepage_content.html
I'm keeping the class name unchanged, otherwise it will break the CSS for instances that update from upstream but don't update the homepage content.
> Fix bug 1593616: Replace Get in touch with Give Feedback

- pontoon/batch/forms.py
- pontoon/batch/tests/test_views.py
- pontoon/checks/tests/test_models.py
- pontoon/checks/tests/test_translate_toolkit.py
- pontoon/contributors/tests/test_views.py
- pontoon/sync/changeset.py
- pontoon/sync/formats/json_extensions.py
- pontoon/sync/formats/lang.py
- pontoon/sync/formats/silme.py
- pontoon/sync/formats/xliff.py
- pontoon/sync/tests/formats/test_json_extensions.py
- pontoon/sync/tests/formats/test_silme.py
- pontoon/sync/vcs/models.py
- pontoon/sync/vcs/repositories.py
There's an intentional change to the serialization of the json for web extensions, it's now dropping the trailing `" "` in `, \n`.
> bug 1585251, more test fixes for python3

- pontoon/base/static/css/table.css
- pontoon/projects/templates/projects/widgets/project_list.html
Just noticed styling of "Not synced yet" elements is different in the localization/teams dashboards compared to the projects/admin dashboards.
> No bug: Unify styling & sorting of  items in Progress column

- pontoon/base/tests/views/test_locale_agnostic.py
- pontoon/base/views.py
We're getting server errors:
```
Traceback:
File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic/hooks/framework_django.py", line 544, in wrapper
return wrapped(*args, **kwargs)
File "/app/pontoon/base/views.py", line 132, in translate_locale_agnostic
if locale
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic/hooks/framework_django.py", line 647, in wrapper
return execute(*args, **kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic/hooks/framework_django.py", line 646, in execute
return wrapped(viewname, *args, **kwargs)
File …
```
> Bug 1588471: Fix bad reverse URL arguments

- .travis.yml
From now on, all changes will have to ensure they do not break our Python 3 support!
> No bug - Disallow failures for Python 3 tests.

- frontend/src/modules/entitieslist/components/Entity.css
Empty translations should occupy vertical space to prevent jumping on save
> A followup to the 3-column layout

- frontend/package.json
- frontend/src/App.js
- frontend/src/modules/resourceprogress/components/ResourceProgress.css
- frontend/src/modules/resourceprogress/components/ResourceProgress.js
- frontend/src/modules/resourceprogress/components/ResourceProgress.test.js
- frontend/src/modules/search/components/SearchBox.js
- frontend/yarn.lock
This pull request fixes the issue [1395179](https://bugzilla.mozilla.org/show_bug.cgi?id=1395179). It ensures the status numbers in the progress menu are clickable.
- Clone this repository 
- Git checkout to `katherine95:1395179-clickable-status-numbers` branch.
- Follow the setup guidelines to set up pontoon locally
- Run `make run`
- Login to Pontoon
- Navigate to the progress menu and click the percentage.
- Click on the status numbers. For example, click  the number under "MISSING"
Expected result:
It navigates to `http://localhost:8000/translate/en-GB/tutorial/all-resources/?status=missing&string=1`
> Fix bug 1395179 - Fix status numbers in progress menu to be clickable

- docker/Dockerfile
When creating containers with docker-compose, volumes containing the source code from the host are created. From inside a docker container, it was not possible to make changes in those volumes, because of a permission issue. This commit sets the GID of the pontoon group so that it matches what will, in most cases, be the group of the user in the host (1000). That allows to make changes inside volumes. Note that if a user has a different group GID (for example, 1001, because they are the second user created on the host) then this will not work. But most folks work on their personal computer so that should not happen too often, and I do not have a good solution for that anyway. This is strictly better than before.
> No bug - Allow changing files from volumes in docker.

- Makefile
- pontoon/base/middleware.py
Unfortunately, I couldn't find a better way to handle this.
To give you the fuller background:
On Python 2, Raygun4py fails to send an exception with the Unicode message and throws the UnicodeDecodeError. To avoid this, the middleware casts the exception to the `str` object.
On Python 3, Raygun4py requires an instance of an Exception instead of a string.
@pike @adngdb r?
> Fix bug 1597558 - Send errors to Raygun.io on Python 3.

- pontoon/base/views.py
Without this patch, we'll produce `AttributeErrors` for non-authed users.
> No bug: No error on entities load for non-authenticated users

- frontend/src/modules/history/components/History.css
If History items overflow, the entire translate view gets a scrollbar. No good.
> No bug: Scroll History, not the entire page

- docs/admin/deployment.rst
- pontoon/wsgi.py
This PR allows to use a dotenv file to configure Pontoon when deployed as a WSGI app. The path of the dotenv file can be configured through the `DOTENV_PATH` environment variable.
To test this PR, you can do the following:
1. Write a dotenv file with the Pontoon configuration in it,
2. install gunicorn or any other WSGI server (`pip install gunicorn`)
3. run the application (`DOTENV_PATH=./dotenv.conf gunicorn pontoon.wsgi:application`)
Pontoon should have its config read from the file.
> Fix bug 1601564: Allows reading dotenv config in WSGI application

- docs/admin/deployment.rst
- pontoon/base/management/commands/update_auth_providers.py
- pontoon/settings/base.py
This PR adds the support of the GitLab authentication method to Pontoon.
To try it out, you will need a GitLab instance (you can probably use gitlab.com).
1. Set following environment variable: 
* `AUTHENTICATION_METHOD=gitlab`
* `GITLAB_URL=https://gitlab.com`
2. Follow the instructions of [this article](https://www.wanadev.fr/196-pontoon-sauthentifier-avec-gitlab/) to setup the applications, but skip the part about patching Pontoon as this patch is provided by this PR (the article is in French but [Google Translate should help](https://translate.google.com/translate?sl=auto&tl=en&u=https%3A%2F%2Fwww.wanadev.fr%2F196-pontoon-sauthentifier-avec-gitlab%2F)). If you do not have an admin account on the GitLab server (on gitlab.com for example), you may be able to [create an …
> Fix bug 1602732: GitLab authentication method

- pontoon/base/static/css/style.css
- pontoon/base/static/js/table.js
- pontoon/localizations/templates/localizations/widgets/resource_list.html
- pontoon/projects/templates/projects/widgets/project_list.html
- pontoon/tags/templates/tags/widgets/tag_list.html
- pontoon/teams/templates/teams/widgets/team_list.html
Priority and Unreviewed columns for projects had an initial ascending sort order.
This fix reverses that so the priority and unreviewed columns now sort by descending order.
> Fixed Bug 1602374: Columns should be sorting descending with first click

- pontoon/tags/tests/utils/test_tagged.py
- pontoon/tags/utils/latest_activity.py
- pontoon/tags/utils/translations.py
Properly display approved translation date & user in the latest activity column of the Tags dashboard.
@jotes Could you please take a look, given that you've been working on tags in the past?
> Fix bug 1604073: Tags latest activity

- pontoon/base/static/js/main.js
- pontoon/machinery/templates/machinery/machinery.html
This is a regression from #1474.
There's another bugfix in a followup commit.
> Fix bug 1605064: Make /machinery work again by restoring team selector

- frontend/public/static/locale/en-US/translate.ftl
- frontend/src/core/editor/actions.js
- frontend/src/core/editor/components/EditorMainAction.js
- frontend/src/core/editor/components/EditorMainAction.test.js
- frontend/src/core/editor/components/EditorMenu.css
- frontend/src/core/editor/components/EditorMenu.js
- frontend/src/core/editor/components/connectedEditor.js
- frontend/src/core/editor/reducer.js
- frontend/src/modules/batchactions/components/ApproveAll.js
- frontend/src/modules/batchactions/components/RejectAll.js
- frontend/src/modules/batchactions/components/ReplaceAll.js
This prevents users from spamming the "save" button, which if done fast enough can lead to the same translation being sent several times. Now as soon as the user clicks the Save button, it becomes disabled until the `sendTranslation` action is entirely finished. I am also using this opportunity to introduce spinners and label update on buttons, as a proposal. It is a pattern that I like, so I would like to generalize it on the app.
TODO:
> Fix bug 1602973 - Make sure users cannot send the same translation twice.

- frontend/src/modules/fluenteditor/components/RichTranslationForm.js
- frontend/src/modules/fluenteditor/components/RichTranslationForm.test.js
Should we also generate accesskeys from the attribute positioned right before the "accesskey" attribute if none of the attributes is called "label"?
That would cover cases like https://github.com/mozilla-l10n/pontoon-ftl/commit/5a67087243f6017f4bf5c66aacda30f0b5ec80c4.
> Fix bug 1601002: Show full-width input if no accesskey candidates available

- pontoon/administration/forms.py
- pontoon/administration/static/css/admin_project.css
- pontoon/administration/static/js/admin_project.js
- pontoon/administration/templates/admin_project.html
- pontoon/administration/urls.py
- pontoon/administration/views.py
- pontoon/pretranslation/tasks.py
- pontoon/sync/changeset.py
- pontoon/sync/core.py
- pontoon/sync/tasks.py
- pontoon/sync/tests/test_tasks.py
We are looking to trigger the pretranslation in 3 cases:
I would like to know your views about the UI on the admin page and check if the all the cases work fine.  Thanks (:
> Fix bug 1552802: Add support for pretranslation in admin panel.

- pontoon/sync/__init__.py
- pontoon/sync/core.py
- pontoon/sync/exceptions.py
- pontoon/sync/formats/compare_locales.py
- pontoon/sync/formats/ftl.py
- pontoon/sync/formats/json_extensions.py
- pontoon/sync/formats/silme.py
- pontoon/sync/tasks.py
- pontoon/sync/tests/test_tasks.py
- pontoon/sync/vcs/models.py
I've tested this on stage by syncing Firefox:
https://mozilla-pontoon-staging.herokuapp.com/sync/log/91143/
I then tried to sync Firefox two more times:
* during `sync_sources`: https://mozilla-pontoon-staging.herokuapp.com/sync/log/91144/
* during `sync_translations`: https://mozilla-pontoon-staging.herokuapp.com/sync/log/91145/
In both cases, `RuntimeError` was raised as expected, preventing the consequent tasks from running.
> Fix bug 1608660: Prevent sync tasks of any type to run concurrently for the same project

- pontoon/base/templates/widgets/priority.html
Python 3.0 has simplified the rules for ordering comparisons: The ordering
comparison operators (<, <=, >=, >) raise a TypeError exception when the
operands don’t have a meaningful natural ordering.
Thus, expressions like 0 > None are no longer valid, and raise a TypeError
instead of returning False.
> Validate priority before comparison

- frontend/src/core/comments/components/AddComment.css
- frontend/src/core/comments/components/AddComment.js
- frontend/src/core/comments/components/Comment.css
- frontend/src/modules/history/components/Translation.js
- pontoon/base/views.py
This fix allows for the textarea in Add Comment to grow as the user types.
________________
I have actually set up a way to grow the textarea either in a downward direction or an upward direction (similar to Slack). However, both options pose additional challenges that I have not yet found solutions for.
**Downward growth** (which is what is active): If there are multiple comments and the Add Comment textarea grows to the point that the outer `history` div begins scrolling then every keypress causes the `history` scroll to jump back up which is not a good experience.
**Upward growth** (can be activated by uncommenting the CSS in `AddComent.css`): This has a fluid growth action, but it does not effect the `history` div which means the overflow is never switched to scroll and the textarea …
> Fix  Bug 1611512  - Add ability for Add Comment input to grow as you type

- frontend/src/core/comments/components/AddComment.js
- frontend/src/core/comments/components/Comment.js
- frontend/src/core/user/components/UserAvatar.js
- frontend/src/modules/history/components/Translation.js
@abowler2 Could you please review this?
We broke user avatars for users that don't have Gravatar URLs, e.g. if Translation is Imported:
https://pontoon.mozilla.org/it/firefox/all-resources/?string=74127
> Show default avatar for users without Gravatar URLs

- Makefile
Uids and Gids on macOS start from very low numbers (e.g. 20) and they overlap with the ids of the existing services.
This commit hardcodes the UID and GID but keeps them parametrizable via commandline.
@Pike @adngdb r?
> Fix bug 1612814 - Harcode UID and GID to fix builds on macOS

- pontoon/base/models.py
- pontoon/batch/views.py
- pontoon/pretranslation/pretranslate.py
- pontoon/pretranslation/tasks.py
- pontoon/pretranslation/tests/test_tasks.py
Hey! There are two changes from #1553 
* Run checks "elegantly" using the `bulk_run_checks` method the downside of which I thought was time taken for stats calculation
* Use [bulk_update](https://github.com/mozilla/pontoon/blob/master/pontoon/batch/views.py#L33-L57) logic for stats calculation (We can also try to modify the original method a bit to make it suitable for pretranslation use case i.e. single project & multiple locales. 
I tested both versions on [pontoon-test](https://github.com/mathjazz/pontoon-test/) for a single locale. Here are the time taken for different parts:
**The current PR** 
- Collecting Translations Finished: 50.1863968372345
- Checks Finished: 0.5103518962860107
- Mark as changed Finished: 0.08880019187927246
- Update Stats Finished: 0.5324735641479492
#1553 
- …
> Fix Bug 1584180: run quality checks using bulk_run_checks and simplify stats.

- frontend/package.json
- frontend/yarn.lock
- package.json
The following two packages are now written in TypeScript.
- @fluent/bundle 0.15.0
- @fluent/syntax 0.15.0
The API has not changed except for the fact that it's now not possible to pass a JSON dump of an AST to `FluentSerialize`; instead a proper `SyntaxNode` object is required. This applies to `serialize`, `serializeEntry` and `serializeExpression` and `serializeVariantKey`.
I tested this locally and everything looks fine.
> Update @fluent/bundle 0.15, @fluent/syntax 0.15

- frontend/src/core/diff/withDiff.js
- frontend/src/modules/machinery/components/Translation.js
This patch makes the diff consistent in the Machinery and History tab.
Before:
https://pontoon.mozilla.org/sl/firefox/browser/chrome/browser/browser.dtd/?string=153898
After
https://mozilla-pontoon-staging.herokuapp.com/sl/firefox/browser/chrome/browser/browser.dtd/?string=153898
> Invert diff in the History panel

- frontend/src/core/user/components/UserNotification.css
- frontend/src/core/user/components/UserNotification.js
- frontend/src/core/user/components/UserNotificationsMenu.css
- frontend/src/core/user/reducer.js
- pontoon/base/models.py
- pontoon/base/static/css/style.css
- pontoon/base/templatetags/helpers.py
- pontoon/base/views.py
- pontoon/contributors/templates/contributors/widgets/notifications_menu.html
This patch sends notifications when comments get submitted.
On translation comment (bound to translation), we notify:
- translation author
- authors of any other translation comments in the thread
On team comment (bound to entity-locale pair), we notify:
- any locale managers
- any locale translators
- any project-locale translators
- authors of any other team comments in the thread
- any translation authors
- authors of any translation comments
> Fix bug 1621720: Send notifications on comment submissions

- pontoon/base/views.py
This patch fixes a server error when translation comment is submitted to a translation without an author:
```
[ERROR:django.request] 2020-03-20 11:38:41,252 Internal Server Error: /add-comment/
File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
File "/usr/local/lib/python3.7/site-packages/django/views/decorators/http.py", line 40, in inner …
```
> Fix sending comments to imported translations

- pontoon/sync/templates/sync/commit_message.jinja
The Co-authored-by trailer allows you to state that PR has multiple authors, and using this trailer allows platforms like GitHub to reflect that in the UI.
reference: https://help.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors
> Use Co-authored-by in the commit message.

- frontend/package.json
- frontend/yarn.lock
This reverts commit be4e43709bdf537c206751983ac9ec871d89b325.
A distinguished software engineer [once](https://github.com/mozilla/pontoon/pull/1602#issuecomment-606476544) said: "If it works, don't touch anything". Then went ahead and updated the library, and the update caused all sorts of trouble in his local development environment for over a day.
> Revert "Update react-scripts (#1602)"

- pontoon/translate/views.py
If you try to sign in on the translate view, authentication succeeds, but you end up with a server error.
@jotes r?
```
File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
File "/app/pontoon/translate/views.py", line 139, in translate
return catchall_dev(request, context=context)
File "/usr/local/lib/python3.7/site-packages/django/views/decorato …
```
> Bug 1607696: Fix Sign in in Translate view

- docs/admin/deployment.rst
The command given in the deployment documentation's "Creating an Admin User" section was previously using the `--noinput` flag, which results in the user being created without a password. This PR resolves the problem by removing that flag, so that a password prompt is given instead.
See [this conversation](https://matrix.to/#/!MbTYYvqUzXvkHwsqtR:mozilla.org/$gvUxEzdrsAcqdp9mN1ja-P3CdNmy-_94yPxq6t5G9zI?via=mozilla.org&via=delire.party) in the Pontoon chat for a few more details.
> Update createsuperuser command in deployment docs

- frontend/src/modules/batchactions/components/BatchActions.css
- frontend/src/modules/batchactions/components/BatchActions.js
After selecting an entity for batch editing, the batch editor opens. If you want to select all strings for batch editing, you need to move the mouse all the way to the opposite site of the screen.
By switching the Select All button and N Strings Selected title, that path becomes much shorter.
@abowler2 Could you please review this?
> Fix bug 1629586: Switch order of Select All & N Strings Selected

- frontend/src/modules/fluenteditor/components/RichTranslationForm.css
- frontend/src/modules/fluenteditor/components/RichTranslationForm.js
- frontend/src/modules/fluenteditor/components/RichTranslationForm.test.js
- frontend/src/modules/fluentoriginal/components/RichString.css
- frontend/src/modules/fluentoriginal/components/RichString.js
- frontend/src/modules/fluentoriginal/components/RichString.test.js
This patch brings support for showing attribute names in select expression variants:
https://bugzilla.mozilla.org/show_bug.cgi?id=1625443
You can test it on stage:
https://mozilla-pontoon-staging.herokuapp.com/de/fluent-test/demo.ftl/?string=205407
> Fix bug 1625443: Show attribute label in variant labels

- frontend/src/core/comments/components/AddComment.css
This patch aligns comment input box styling between Chrome and Firefox. It's already working for other input boxes.
@abowler2 r?
> Unify comments styling between Chrome and Firefox

- pontoon/translations/views.py
We name the parameter paths in all other calls
@jotes I noticed this small inconsistency while reviewing your patch. Could you please review? :-)
> Rename resources to paths

- pontoon/tags/tests/utils/test_tags.py
- pontoon/tags/utils/tags.py
There's a bug in the Tags widget in the Project Admin, which doesn't show the right resources under the 'Shared' tag. We never "search" for tags, we just filter, so the query should be exact (instead of using contains).
@jotes You were the last one touching this code, could you please review? :-)
> Fix bug 1637851: Use exact search in tag getter

- pontoon/base/views.py
I noticed we're ordering comments from newest to oldest on prod:
https://pontoon.mozilla.org/sl/android-l10n/mozilla-mobile/fenix/app/src/main/res/values/strings.xml/?string=200405
Let's revert that.
@abowler2 r?
> Order comments from oldest to newest

- docs/admin/deployment.rst
- pontoon/settings/base.py
I've added comment trying to explain what this is about.
> Fix bug 1639492: Make SYNC_TASK_TIMEOUT an environment variable

- pontoon/tags/utils/latest_activity.py
https://github.com/mozilla/pontoon/commit/aa6a91b820a36ea76db2dd43428b688edcc0a93b broke [tag dashboards](https://pontoon.mozilla.org/sl/firefox/tags/):
```
File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
File "/app/pontoon/base/utils.py", line 110, in wrap
return f(request, *args, **kwargs)
File "/app/pontoon/localizations/views.py", line …
```
> Bug 1604038: Fix avatar display on Tag pages

- pontoon/api/schema.py
- pontoon/api/tests/test_schema.py
Introduces includeSystem parameter which is by default false. Tested with below graphql query on local box and getting expected result.
```
query {
projects(includeDisabled: true, includeSystem: false) {
name
}
locale(code:"mr") {
name
googleTranslateCode
localizations(includeSystem: true) {
project {
name
}
}
}
}
```
@mathjazz r?
> Fix bug 1635743 [API] Exclude system projects from default

- pontoon/actionlog/models.py
- pontoon/base/admin.py
- pontoon/base/models.py
- pontoon/contributors/utils.py
- pontoon/terminology/models.py
If we didn't modify the ForeignKey constraint on the Comment, Action Log etc, django admin ui shows these entities on the confirmation page. Thus marked it as Null.
> Fix bug 1561663 Admins should be able to remove an account

- pontoon/sync/vcs/repositories.py
@jotes I misled you into this change, which I believe should be reverted. We should keep "Pontoon" as committer, and only use translation author as author.
> Bug 1567400: Git commit as VCS_SYNC user, not translation author

- pontoon/base/models.py
We're sending the locale code instead of Systran code to the API when retrieving the profile owner. That means we don't get any matches for locales like `es-ES`, which use the `es` engine.
> Send Systran code to server when retrieving profile owner

- pontoon/translations/forms.py
- pontoon/translations/tests/test_forms.py
Add custom validation, which does not strip whitespace from the translation field.
> Fix bug 1632206: Preserve whitespace in submitted translations

- frontend/public/static/locale/en-US/translate.ftl
- frontend/src/core/user/components/UserMenu.js
- pontoon/base/utils.py
- pontoon/terminology/urls.py
- pontoon/terminology/utils.py
- pontoon/terminology/views.py
The patch is deployed to stage:
https://mozilla-pontoon-staging.herokuapp.com/fr/firefox/all-resources/
To test, go to any translate page, click on the profile menu (top right) and select "Download Terminology". The .tbx file for the given locale will be downloaded.
> Fix bug 1658420: Download terminology (.tbx)

- pontoon/base/utils.py
- pontoon/terminology/urls.py
- pontoon/terminology/utils.py
- pontoon/terminology/views.py
We're adding the ability to download Terminology in the legacy TBX 2.0 format (URL-only).
> Fix bug 1658420: Enable downloads of Terminology in TBX 2008 (v2) format

- frontend/package.json
- frontend/yarn.lock
This should fix the bug.
I tried to upgrade to the latest version first (3.4.3), but that prevented frontend server from even starting for me locally. I was getting the following error:
```
HTTPConnectionPool(host='localhost', port=3000):
Max retries exceeded with url: /sl/tutorial/playground/
(Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbf961f17f0>:
Failed to establish a new connection: [Errno 111] Connection refused'))
```
> Fix bug 1666446: Upgrade react-scripts to prevent frontend breakage

- specs/0107-pretranslated-status.md
Pretranslations are assigned translation status Fuzzy, which allows us to:
1. Immediately send them to version control system.
2. Make them available in the product.
3. Inform localizers that they should be given another look.
4. Run quality checks on them to identify any errors or warnings.
The caveat however is that translation status Fuzzy is also used for [fuzzy](https://www.gnu.org/software/gettext/manual/html_node/Fuzzy-Entries.html) translations of the Gettext system (filenames ending in .po), which are **not** used in the product. That means bullet point #2 isn't valid for projects using the Gettext system - pretranslated strings in .po files will not make it to the product unless human translator approves them.
This is the spec for the feature to mitigate that issue and make …
> Bug 1666320: Introduce Pretranslated status (spec)

- CONTRIBUTING.rst
The previous link pointed to some blogspam page.
> Fix Project Fluent link in documentation

- docker/config/webapp.env.template
- pontoon/settings/base.py
Sync button in Project Admin is not enabled by default on production instances (unlike in development instances), which is inconsistent with the [docs](https://mozilla-pontoon.readthedocs.io/en/latest/user/localizing-your-projects.html#adding-a-new-project-to-pontoon).
> Fix bug 1667765: Enable Sync button by default in production

- README.md
Many end-users who enter Pontoon's chat channel, probably do so by obtaining the link here _(as I did! :raised_eyebrow: )_
This helps to guide users to the right place for discussing their questions.
*Thanks to @flodolo,  for pointing that out.*
> Update README clarifying chat channel scope

- frontend/src/modules/entitydetails/components/Metadata.css
While reviewing #1676, I've noticed that links aren't green anymore and that the divider lost spacing:
https://pontoon.mozilla.org/sl/firefox/all-resources/?string=74127
In #1684 we changed the element name, but didn't update affected CSS.
> Fix Metadata CSS regression caused by bug 1611510

- frontend/src/core/user/components/UserMenu.js
- pontoon/base/templates/widgets/heading_info.html
- pontoon/base/tests/views/test_tmx.py
- pontoon/base/urls.py
- pontoon/base/views.py
1)Changed the url for translation memory (line 133)  in UserMenu.js file
2)Changed the url for translations (line 153)  in UserMenu.js file
3)Removed the parameters locale and slug passed in the url for
downloading translation memory (line 59)  in pontoon/base/ urls.py
4)Modified the view download_translation_memory in pontoon/base/views.py
to accept only 2 parameters i.e. request and filename and introduced a
new variable vars to extract locale and slug using split function.
5)Changed the view name download in pontoon/base/views.py to translations
(line 694) and changed the urls,name corresponding to it in
pontoon/base/ urls.py (line 81)
> Fix Bug 1666199 Unify download URL schema

- frontend/src/modules/machinery/components/Machinery.css
- frontend/src/modules/search/components/SearchBox.css
This patch changes the cursor on the search box magnifier icon from cursor to text in order to prevent users from thinking the icon acts as a button.
The patch can be tested on stage:
https://mozilla-pontoon-staging.herokuapp.com/sl/firefox/all-resources/?string=74127
> Fix bug 1668362: Use text cursor on search box icon

- .prettierignore
- pontoon/base/templates/django/socialaccount/authentication_error.html
Working on [Bug 1669192](https://bugzilla.mozilla.org/show_bug.cgi?id=1669192) uncovered a syntax error within the `authentication_error.html` file that was causing the app to crash instead of showing the "Sign in Failure" page.
This patch fixes that error and also includes adding `*html`  to the `prettierignore` file so that those are not reformatted with Prettier.
> Authentication Error bug fix

- pontoon/base/tests/__init__.py
- pontoon/contributors/tests/test_views.py
- pontoon/db/tests/test_lookups.py
- pontoon/projects/tests/test_views.py
- pontoon/settings/base.py
- pontoon/sync/tests/formats/__init__.py
- pontoon/sync/tests/formats/test_compare_locales.py
- pontoon/sync/tests/formats/test_ftl.py
- pontoon/sync/tests/formats/test_lang.py
- pontoon/sync/tests/formats/test_silme.py
- pontoon/sync/tests/test_changeset.py
- pontoon/sync/tests/test_checks.py
- pontoon/sync/tests/test_core.py
- pontoon/sync/tests/test_models.py
- pontoon/sync/tests/test_sync_projects.py
- pontoon/sync/tests/test_tasks.py
- pontoon/sync/tests/test_vcs.py
- pontoon/sync/tests/test_vcs_models.py
- requirements/constraints.txt
- requirements/default.txt
- requirements/dev.txt
The package doesn't officially support Django >=3.0, and `nose` is not maintained anymore. All usages were replaced by appropriate `pytest` equivalents.
I deleted the `TEST_RUNNER` definition in the settings. We could change it to run `pytest` instead when calling `./manage.py test` (see instructions [here](https://pytest-django.readthedocs.io/en/latest/faq.html#how-can-i-use-manage-py-test-with-pytest-django)), but I don't think that's worth it since we use the `pytest` command directly.
> Bug 1627655: Remove django-nose dependency

- pontoon/api/tests/test_schema.py
- pontoon/api/tests/test_urls.py
- pontoon/api/tests/test_util.py
I didn't want to reinvent the wheel in #1682. There's no need for parametrization in Unittest when it's available in Pytest OOTB.
> Fix 1417530 - Convert the api tests from Unittest to Pytest.

- requirements/default.txt
Using GitHub to authenticate a signin was causing an error. The authentication would complete on GitHub but when redirected to Pontoon an error occurred.
In looking into this it was discovered that GitHub changed the way it handles authentication from using query params to using headers instead. The django-allauth package was updated with this change in v0.42.0.
Pontoon was still using v0.41.0 and updating to v0.42.0 fixes the issue.
> Fix Bug 1669192 - Unable to authorize with GitHub

- pontoon/settings/base.py
- requirements/default.txt
The new version is compatible with Django 3.1. The `ANONYMOUS_USER_ID` setting has been removed since django-guardian 1.4.2.
> Bug 1627655: Update django-guardian

- pontoon/base/templatetags/helpers.py
- pontoon/base/tests/test_helpers.py
As a follow-up to #1704, I removed some more helpers.
The DjangoJSONEncoder already supports datetime and Promise objects, and thisyear+naturalday were unused.
The previous encoder also handled QuerySet objects, but I couldn't find any place where this is actually used.
> Remove more unused templatetags helpers

- pontoon/administration/views.py
- requirements/default.txt
All CSV features we use are natively supported by Python. In particular, the DictWriter takes care of missing row entries and treats them as an empty string.
> Remove backports.csv dependency

- pontoon/settings/base.py
- requirements/default.txt
The new version supports Django 3.1. The CORS_ORIGIN_ALLOW_ALL setting was renamed to CORS_ALLOW_ALL_ORIGINS.
> Bug 1627655: Update django-cors-headers

- pontoon/base/migrations/0001_squashed_0154_auto_20200206_1736.py
- pontoon/base/models.py
- pontoon/base/tests/managers/test_entity.py
- pontoon/sync/changeset.py
- pontoon/sync/management/commands/import_pootle.py
- pontoon/sync/models.py
- requirements/default.txt
The package has not been updated for 3 years, and is not tested on current Django versions. Thus, we use the Django-native `bulk_update` method instead.
The Django-native method, as opposed to the package method, does not return the number of updated objects, so I got rid of that in the single test where it was used. Also, I adjusted the `EntityQuerySet.bulk_update` method to not throw a `DeprecationWarning`, and take care of the word count.
> Bug 1627655: Remove django-bulk-update dependency

- pontoon/sync/templates/sync/commit_message.jinja
By convention, a new line is used before git commit message trailers (such as 'Co-authored-by').
Currently the commit message template explicitly removes newlines. This change keeps a single newline before the 'Co-authored-by' trailer.
This changes commit messages from
```
My commit message
Co-authored-by: Example 1
Co-authored-by: Example 2
```
to
```
My commit message
Co-authored-by: Example 1
Co-authored-by: Example 2
```
> Keep a new line before commit message trailers

- pontoon/settings/base.py
- requirements/default.txt
The new version is tested on Django 3.0. The option CHILD_SRC is deprecated in favor of FRAME_SRC and WORKER_SRC.
> Bug 1627655: Update django-csp

- pontoon/base/admin.py
- pontoon/base/apps.py
- pontoon/settings/base.py
- requirements/default.txt
The package is natively replaced by Django. We use CSRF_USE_SESSIONS to force Django to save the CSRF  tokens in the session instead of in a cookie. We also get rid of the patching of the AppConfig and AdminSite.
The changes to the admin site were needed because after deleting the `SessionCsrfAdminSite`, Django complained about the re-registering of the `User`. I fixed this as suggested in the [Django docs](https://docs.djangoproject.com/en/3.1/topics/auth/customizing/#extending-the-existing-user-model), and I also removed the redundant Group/GroupAdmin registration.
> Fix bug 1672713: Remove django-session-csrf dependency

- requirements/constraints.txt
- requirements/default.txt
The new version supports Django 3.1, and futures is not a dependency any more.
I'm not sure how to properly test this locally, so this should probably be tested in staging.
> Bug 1627655: Update django-pipeline dependency

- frontend/src/modules/teamcomments/components/Count.js
- frontend/src/modules/teamcomments/components/Count.test.js
- pontoon/base/views.py
This patch makes Pinned comments globally visible to all locales.
The 2nd commit unifies team comments tab count behavior with other tabs counts.
> Bug 1611510: Make pinned comments globally visible

- frontend/src/core/comments/components/AddComment.js
One should be able to mention people with fancy names like `@théo` or `@matjaž`.
> Fix bug 1674173: Add support for non-ASCII characters in mentions

- frontend/src/modules/fluenteditor/components/RichEditor.js
- frontend/src/modules/fluenteditor/components/RichTranslationForm.js
When transitioning from a translation that is open in a simple editor to a suggestion that is open in a rich editor the app would crash. The problem happened when trying to serialize a translation that is already serialized
To fix this I am only sending the data to be serialized if it is updated.
> Fix Bug 1624370 -  Rich Editor crash

- frontend/src/core/comments/components/AddComment.css
When adding a comment if the text extended beyond the end of the line it would split the word and continue on the next line. This was being caused by the `word-break` property that was originally set when the comment input was a textarea. With the switch to the Slate editor this is no longer needed and long text now wraps to the next line without breaking.
> Fix Bug 1675438 - Poorly wrapped text in comment

- pontoon/base/models.py
- pontoon/sync/management/commands/sync_projects.py
- pontoon/sync/tests/test_sync_projects.py
This patch ignores the `sync_disabled` flag on force-sync and makes error messages clearer.
@jotes Could you help with the review, pretty please?
> Fix bug 1676927: Enable force sync for projects with sync disabled

- frontend/src/modules/machinery/components/Machinery.js
- frontend/src/modules/machinery/components/Machinery.test.js
This patch fixes two similar bugs which caused inconsistencies between what is displayed in the Machinery search field and Machinery results.
1. Clear search field after switching to a different entity.
1. Restore custom input in search field, e.g. when switching from Locales tab back to Machinery.
> Fix bug 1676751: Make sure Machinery search matches results

- pontoon/terminology/tests/test_models.py
The tests were slow because `update_terminology_project_stats` was called when creating a new `Term`. We now mock the calls to this expensive function. The whole `pytest` suite now only takes about 2.5 minutes.
I couldn't find an easy way to pass parameters from `TermFactory.create` to `Term.save` in order to optionally skip the stat updates. This is why I chose the mocking/patching option.
> Fix bug 1674159: Fix slow terminology tests

- specs/0000-template.md
This patch adds a template for writing specifications, which must be used when submitting a feature specification for Pontoon. It builds upon specifications that have landed so far.
It's also the last step before we can mark [Specification Process](https://wiki.mozilla.org/L10n:Pontoon_Roadmap#Specification_Process) as done on our Roadmap.
We'll include more details about the process of writing specifications in the [Development Process](https://wiki.mozilla.org/L10n:Pontoon_Roadmap#Development_Process) document.
@adngdb Would you be able to review this?
> Fix bug 1676857: Add template for writing specifications

- pontoon/contributors/tests/test_views.py
- pontoon/contributors/views.py
- pontoon/settings/base.py
Misc:
* Improve the performance of Contributors tests - achieved by decreasing the number of objects produced by the test fixtures.
* Introduce a new configuration option to set the page size of the events on the Contributor's timeline.
@mathjazz r? The execution time of the tests in this module dropped from ~30s to ~10s.
> Bug 1417530 - Migrate Contributors unit-tests to Pytest.

- frontend/src/core/comments/components/Comment.js
- frontend/src/core/comments/components/Comment.test.js
The comment editor handled the RTL text properly but, when the comment displayed it miss-ordered the sentence if English letters were inside the arab/kurdish setence.
It appears that having the direction set in the parent div caused the direction to be set by the first element, which is the username/email.  I've moved the attribute `dir: auto` from the parent div to a div that directly wraps the comment.
I've not been able to test that this picks up the correct direction with `auto`, but it does display correctly when directly set to the `rtl` value.
> Fix Bug 1647124 - RTL support in comments

- frontend/src/core/editor/components/EditorMainAction.js
Seems like we forgot to port this node to the new react-fluent syntax.
> Fix bug 1614588: Make Save/Suggest/Approve spinner appear again

- CONTRIBUTING.rst
In the past we used to compile Fluent manually and had to provide instructions how to do that:
https://github.com/mozilla/pontoon/pull/1539
Now that this is no longer needed, the remaining information isn't that important and doesn't fit here.
> Remove "Integration with fluent" from CONTRIBUTING

- frontend/public/static/locale/en-US/translate.ftl
- frontend/src/modules/interactivetour/components/InteractiveTour.js
Addressing bug 1673238: Fixed interactive tour, added two tabs for comments and terms that point to the comments and terms sections. Pointed the machinery and locales tabs to the machinery and locales section. I was not sure what description I should put for the comments and terms tabs in the interactive tour.
> Fix Bug 1673238: Interactive tour shows wrong elements for Machinery/Locales

- pontoon/base/forms.py
- pontoon/sync/formats/__init__.py
- pontoon/sync/tests/formats/test_formats.py
XLIFF file format supports .xliff and .xlf extensions. Previously, we only support the extension of the target file.
Also, due to bug 1530139, projects using TOML configuration files require Gettext files to use the .pot extension on upload, which are used for templates (source files). With this fix, .po (used for l10n files is also supported).
> Fix bug 1633148: Support alternative file extenions on upload

- pontoon/sync/tests/test_vcs_models.py
- pontoon/sync/vcs/models.py
When detecting changes to translated resources in VCS, we need to identify which of the changed paths belongs to a localizable resource (and ignore others).
The logic that does that makes assumptions about the file and folder structure which are not valid for projects using project configuration. Hence this patch adds a new logic for such projects, which makes use of the ProjectFiles matcher of the compare-locales library.
The logic also converts the changed paths to the canonical form for representing resources used across Pontoon codebase (reference path insted of l10n path) and assigns the list of changed locales to each path.
As a side effect, this patch also fixes [bug 1608045](https://bugzilla.mozilla.org/show_bug.cgi?id=1608045), which is another symptom of the very same problem.
> Fix bug 1633149: Detect changes to translated resources on sync

- frontend/src/modules/machinery/components/Machinery.css
- frontend/src/modules/machinery/components/Machinery.js
- frontend/src/modules/machinery/components/Machinery.test.js
The ability to reset the Machinery Search input to its original state is not currently intuitive (user must clear the input and hit enter). 
This PR follows the [specification for Concordance Search](https://github.com/mozilla/pontoon/blob/master/specs/0106-concordance-search.md) and switches the 'search' icon to a 'close' button (`x`) when a search is made. When the 'close' button is clicked the search input will be cleared and returned to its original state.
This does not currently work for the FTL files due to [Bug 1676750](https://bugzilla.mozilla.org/show_bug.cgi?id=1676750). The input is cleared but the original state is not restored.
> Fix Bug 1679654 - Add ability to reset machinery search field

- frontend/src/core/api/locale.js
- frontend/src/core/api/project.js
- pontoon/administration/urls.py
- pontoon/administration/views.py
- pontoon/allauth_urls.py
- pontoon/api/urls.py
- pontoon/base/templatetags/helpers.py
- pontoon/base/urls.py
- pontoon/base/utils.py
- pontoon/batch/urls.py
- pontoon/contributors/urls.py
- pontoon/homepage/urls.py
- pontoon/in_context/urls.py
- pontoon/localizations/urls.py
- pontoon/machinery/urls.py
- pontoon/projects/urls.py
- pontoon/sync/urls.py
- pontoon/tags/urls.py
- pontoon/tags/views.py
- pontoon/teams/urls.py
- pontoon/teams/views.py
- pontoon/terminology/urls.py
- pontoon/tour/urls.py
- pontoon/translate/urls.py
- pontoon/translations/urls.py
- pontoon/urls.py
This fixes all Django deprecation warnings caused by our code. It is split up into 3 commits, which you can review individually.
The largest change concerns all `urls.py` files. The previously used `django.conf.urls.url` is deprecated, and almost all of our regex uses are now replaced by explicit path strings. In the process, I greatly simplified the regex usage.
Note that the previous GraphQL regex made the API available at any URL starting with `/graphql` (including `/graphql/`), but now it is only exactly that URL.
> Fix bug 1678452: Fix Django deprecation warnings

- frontend/src/core/editor/actions.js
- frontend/src/core/editor/hooks/useCopyOriginalIntoEditor.js
- frontend/src/core/editor/reducer.js
- frontend/src/modules/fluenteditor/components/FluentEditor.js
- frontend/src/modules/fluenteditor/components/FluentEditor.test.js
- frontend/src/modules/history/actions.js
This fixes the following problems:
- The content becoming empty when clicking on the selected entity in the list.
- The content being empty in the next entity after approving.
- The content not being correctly parsed when using the Copy button.
> Fix bug 1646010 - Correct various bugs around the Fluent editor

- frontend/src/modules/entitydetails/components/EntityDetails.js
I found two other places where it looks like we should change the order. But I haven't changed it, because I wasn't able to produce any issues.
https://github.com/mozilla/pontoon/blob/master/frontend/src/modules/entitieslist/components/EntitiesList.js#L219
https://github.com/mozilla/pontoon/blob/master/frontend/src/modules/search/components/SearchBox.js#L379
> Fix bug 1681293: Make sure editor is reset on keyboard navigation

- pontoon/base/views.py
- pontoon/machinery/views.py
Passing GET parameters of wrong type can sometimes result in server errors. That happens particularly often when crawlers or attackers make requests to the views which take integers as inputs (e.g. IDs), causing ValueErrors.
Some of our views have protection against that, but many don't. This patch fixes that by validating GET parameters that need to be integers.
> Fix bug 1682122: Validate GET parameters that need to be integers

- frontend/src/modules/machinery/components/Machinery.js
- frontend/src/modules/machinery/components/Translation.js
- frontend/src/modules/machinery/components/Translation.test.js
Currently when searching within the Machinery tab, the results will replace the contents of the editor when clicked on.  As per the [concordance search spec](https://github.com/mozilla/pontoon/blob/master/specs/0106-concordance-search.md), the search results should just be added instead.  This patch makes that change.
> Fix Bug 1679709 - Clicking on each machinery search result adds the text to the editor

- .eslintrc.js
- docker/config/webapp.env.template
- docs/admin/deployment.rst
- pontoon/base/static/css/style.css
- pontoon/base/static/js/lib/Chart.bundle.js
- pontoon/base/static/js/tabs.js
- pontoon/insights/static/css/insights.css
- pontoon/insights/static/js/insights.js
- pontoon/insights/templates/insights/widgets/active_users.html
- pontoon/insights/templates/insights/widgets/insights.html
- pontoon/insights/templates/insights/widgets/tooltip.html
- pontoon/insights/utils.py
- pontoon/settings/base.py
- pontoon/teams/templates/teams/includes/insights.html
- pontoon/teams/templates/teams/team.html
- pontoon/teams/urls.py
- pontoon/teams/views.py
This is [Step 4/4](https://wiki.mozilla.org/L10n:Pontoon_Roadmap#Community_Health_Dashboard) of the [Community Health Dashboard](https://github.com/mozilla/pontoon/blob/fddf18f45546cb3c9d59285437e18c72de7ed577/specs/0108-community-health-dashboard.md) implementation.
It adds the frontend code: the actual dashboard with charts that visualize the data collected and stored in previous steps. Two changes have been made that are not part of the spec:
1. The `ENABLE_INSIGHTS_TAB` setting has been introduced and documented to enable the Insights tab. It's enabled by default in dev environment and disabled in prod. That's because `collect_insights` job needs to run in order to be able to show any data. With the new setting admins have the ability to only enable the feature when they start …
> Fix bug 1680056: Implement community health dashboard frontend

- frontend/src/core/resource/components/ResourceItem.css
- frontend/src/core/resource/components/ResourceItem.js
Before:
After:
I was also thinking about adding `direction:rtl`, which adds ellipsis at the beginning. But it seemed even more confusing.
> Fix bug 1684086: Prevent resource path overflow in resource menu

- frontend/README.md
It felt more appropriate to add this to the `Tools documentation` section at the end of the ReadMe, but let me know if you think it needs to also be in the `Tools` table at the top
> Add link to Slate docs to Frontend ReadMe documentation

- docker/Dockerfile
- requirements/default.in
- requirements/default.txt
- requirements/dev.txt
- requirements/lint.txt
- requirements/test.txt
- runtime.txt
I've tested locally and on stage and didn't spot any issues.
The amount of diff in the `.txt` files is probably caused by the latest version of `pip-tools` I installed locally.
Could we replace `compile-all.sh` with a `make compile-requirements` and compile requirements in Docker?
> Update lxml to 4.6.2 and python to 3.8.7

- frontend/src/core/editor/actions.js
- frontend/src/core/editor/hooks/useCopyOtherLocaleTranslation.js
- frontend/src/core/editor/hooks/useHandleShortcuts.js
- frontend/src/core/editor/index.js
- frontend/src/core/editor/reducer.js
- frontend/src/modules/entitydetails/components/EntityDetails.js
- frontend/src/modules/entitydetails/components/Helpers.js
- frontend/src/modules/machinery/components/Translation.js
- frontend/src/modules/otherlocales/components/OtherLocales.js
- frontend/src/modules/otherlocales/components/Translation.css
- frontend/src/modules/otherlocales/components/Translation.js
- frontend/src/modules/otherlocales/index.js
- frontend/src/modules/otherlocales/selectors.js
Overall it resembles the implementation of the Machinery tab, although some extra changes have been necessary to be able to use hooks (that's why there's extra noise in the diff).
> Fix bug 1686369: implement Tab shortcut for 'Locales' tab

- pontoon/base/tests/models/test_translation.py
We had to land a hotfix for the error we'd catch with a test like this: https://github.com/mozilla/pontoon/commit/7181fd430bac94725eab7880d1eb8e54f8192eb6.
> Fix bug 1686711: Add basic unit test for Translation.machinery_sources_values

- .eslintrc.js
These two globals are not present anymore. This is a follow-up of #1814.
> No bug - ESLint: remove fullpage.js globals

- package-lock.json
This should've been removed as part of c52a603.
> No bug - package-lock.json: remove obsolete fluent-syntax

- frontend/public/static/locale/en-US/translate.ftl
- frontend/src/core/editor/components/KeyboardShortcuts.css
- frontend/src/core/editor/components/KeyboardShortcuts.js
- frontend/src/core/editor/hooks/useHandleShortcuts.js
- frontend/src/core/editor/reducer.js
- frontend/src/modules/machinery/components/Translation.js
- frontend/src/modules/otherlocales/components/Translation.js
That leaves the default and expected behavior of the Tab key unchanged,
which is critical for accessibility and usability.
Also included:
- Add shortcut to the Locales tab tooltip
- Fix keyboard shortcut display in the panel
https://mozilla-pontoon-staging.herokuapp.com/projects/firefox/all-resources/
> Fix bug 1687328: Replace Tab keyboard shortcut with Ctrl + Shift + Up/Down

- docker/Dockerfile
- pontoon/settings/base.py
- requirements/default.in
- requirements/default.txt
- requirements/dev.txt
- requirements/test.txt
Yuglify doesn't understand ES2015+ code, whereas Terser handles it well.
> Fix bug 1687371 - pipeline: delegate JS compression to Terser

- frontend/src/core/comments/components/AddComment.css
Add Comment input box in the Comments tab is smaller than the submit button.
We don't have that problem in translation comments, because line-height is
defined in History.css.
> Fix Add Comment input height to match submit button

- frontend/src/core/lightbox/components/Lightbox.js
- frontend/src/core/lightbox/components/Lightbox.test.js
The editor would constantly fire `lightbox/CLOSE` actions upon
pressing any of space/esc/enter keys.
> Fix bug 1689653: avoid lightbox actions when closed

- frontend/src/core/plural/components/PluralSelector.js
- frontend/src/core/plural/components/PluralSelector.test.js
- frontend/src/modules/entitieslist/components/EntitiesList.js
- frontend/src/modules/entitieslist/components/EntitiesList.test.js
- frontend/src/modules/entitydetails/components/EntityDetails.js
- frontend/src/modules/entitydetails/components/EntityDetails.test.js
- frontend/src/modules/navbar/components/Navigation.js
- frontend/src/modules/search/components/SearchBox.js
- frontend/src/modules/search/components/SearchBox.test.js
- frontend/src/test/store.js
Changing from/to initial textarea values would result in redundant
re-renders due to subscribing to `unsavedChangesExist` and
`unsavedChangesIgnored` redux state changes.
Implementation-wise, this accesses `unsavedchanges` state directly,
without subscribing to its changes because the state members are not
used for rendering purposes.
For direct store access react-redux strongly suggests to leverage the
`useStore()` API, because accessing the store via context is an
implementation detail and it might change in the future. That's why the
components connecting redux state -> props have been converted to hooks.
It'd also have been possible to avoid these intermediate components and
co-locate redux state directly within components, however that would
require more invasive changes, creeping …
> Fix bug 1688570: improve performance of initial editor change

- frontend/src/core/plural/selectors.js
- frontend/src/core/utils/hooks/useOnDiscard.js
- frontend/src/core/utils/hooks/useOnDiscard.test.js
- frontend/src/core/utils/index.js
This will be used as a replacement for react-onclickoutside, because the functionality only needs a few lines of code and it's more explicit than using a HoC.
Because 10 components of different complexity are affected, it's going to be way easier to review if we move with individual PRs, one component at a time. So the plan would be:
1. Introduce this hook
2. Replace every single use of `onClickOutside()` with `useOnDiscard()`
3. Remove react-onclickoutside
> Bug 1688571: add discard functionality hook

- frontend/src/core/user/components/UserNotificationsMenu.js
- frontend/src/core/user/components/UserNotificationsMenu.test.js
- frontend/src/core/user/index.js
This now only listens for `click` events when the menu is visible by
the means of leveraging the `useOnDiscard` hook.
> Bug 1688571: fix negative performance side-effects of `UserNotificationsMenu`

- frontend/src/modules/resourceprogress/components/ResourceProgress.js
- frontend/src/modules/resourceprogress/components/ResourceProgress.test.js
> Bug 1688571: fix negative performance side-effects of `ResourceProgress`

- frontend/src/core/editor/components/EditorSettings.js
- frontend/src/core/editor/components/EditorSettings.test.js
> Bug 1688571: fix negative performance side-effects of `EditorSettings`

- frontend/src/core/editor/components/KeyboardShortcuts.js
> Bug 1688571: fix negative performance side-effects of `KeyboardShortcuts`

- frontend/src/modules/entitydetails/components/Metadata.js
- frontend/src/modules/entitydetails/components/TermsPopup.js
> Bug 1688571: fix negative performance side-effects of `TermsPopup`

- frontend/src/core/resource/components/ResourceMenu.js
- frontend/src/core/resource/components/ResourceMenu.test.js
> Bug 1688571: fix negative performance side-effects of `ResourceMenu`

- frontend/src/core/project/components/ProjectMenu.js
- frontend/src/core/project/components/ProjectMenu.test.js
- frontend/src/modules/navbar/components/Navigation.js
> Bug 1688571: fix negative performance side-effects of `ProjectMenu`

- frontend/src/modules/projectinfo/components/ProjectInfo.js
- frontend/src/modules/projectinfo/components/ProjectInfo.test.js
> Bug 1688571: fix negative performance side-effects of `ProjectInfo`

- frontend/src/core/comments/components/AddComment.js
- frontend/src/core/comments/components/AddComment.test.js
- frontend/src/core/comments/components/CommentsList.js
- frontend/src/modules/entitydetails/components/EntityDetails.js
- frontend/src/modules/entitydetails/components/Helpers.js
- frontend/src/modules/history/components/History.js
- frontend/src/modules/history/components/Translation.js
- frontend/src/modules/teamcomments/components/TeamComments.js
We currently collect user data twice in the `EntityDetails` component and pass it as two different props (`user` and `users`):
1. EntityDetails > History > Translation > CommentsList > AddComment
1. EntityDetails > Helpers > TeamComments > CommentsList > AddComment
It's enough to collect and pass the same data once. :)
> Fix bug 1690500: Only collect and pass user data once

- pontoon/machinery/templates/machinery/microsoft_terminology.jinja
- pontoon/machinery/views.py
Microsoft Terminology added support for HTTPS, so let's use it! We still have to use HTTP in the SOAP header, though - otherwise it 500s.
Note that the issue with the service availability has been resolved independently of this change.
> Bug 1690485: Use HTTPS for the Microsoft Terminology endpoint

- pontoon/base/static/css/style.css
- pontoon/base/static/js/main.js
- pontoon/contributors/static/js/settings.js
- pontoon/contributors/templates/contributors/settings.html
`main.js` file is loaded on each page, except for the translate view.
It contains code, which is no longer used, because it has been replaced by the new translate app (Translate.Next).
There's also code, which is only used by one view (as discovered in bug 1690563), so it should be moved to view-specific files.
And then there's code that is obsolete, or can be rewritten using native DOM APIs.
Let's clean it up!
> Fix bug 1690642: Cleanup main.js file

- frontend/src/core/diff/withDiff.js
- frontend/src/core/editor/hooks/useCopyMachineryTranslation.js
- frontend/src/core/editor/selectors.js
- frontend/src/modules/machinery/components/Translation.js
- frontend/src/modules/otherlocales/components/Translation.js
This PR avoids major part of redundant re-renders in the helper components. As I have observed, the components making use of diff functionality as well as the `Localized` components incur in perceptible performance cost.
Before:
After:
I think the result is good enough for the sake of bug 1688573.
It's worth noting though, there are a few other areas that could still be improved:
* The first keystroke produces a re-render in the helpers components because the editor's `changeSource` changes.
* `EditorMenu` > `MenuContent` constantly re-renders due to translation and translation length being changed. This becomes more expensive than expected because the button texts are wrapped in `Localized` elements.
* Every keystroke of the translation textarea triggers a series of redux actions, which …
> Fix bug 1688573: avoid redundant editor re-renders

- pontoon/checks/libraries/translate_toolkit.py
- pontoon/sync/formats/xliff.py
- pontoon/sync/tests/formats/test_xliff.py
- requirements/default.in
- requirements/default.txt
- requirements/dev.txt
- requirements/test.txt
* New API: `translate.lang.data.normalized_unicode` -> `translate.lang.data.normalize` ([click](https://github.com/translate/translate/commit/cc4ed15f79eb233e500c8a8c178f733d134fbb63))
* Drop deprecated `get_rich_source()` method ([click](https://github.com/translate/translate/commit/19abe9f19d4b5d3b645ce1986e5fa9402173fe8d))
* Ensure xml:space="preserve" is set when updating target ([click](https://github.com/translate/translate/commit/a17c23bbf344d3b614667e361562aab98d696774))
> Update to translate toolkit 3.3.2

- CONTRIBUTING.rst
- Remove differences in /pontoon and /fronten JS code conventions
- Factor out motivation for code formatting and generic make format command to a separate section
- Add note aboute ignoring eslint errors
> Update section about code formatting

- frontend/package.json
- frontend/yarn.lock
The package was introduced by bug 1433994 (#1162), which brought support for the Ace Editor.
The editor was removed by bug 1563457 (#1382), but the package remained.
> Remove unused brace package

- frontend/public/static/locale/en-US/translate.ftl
- frontend/src/core/term/components/Term.js
1) Wrapped the LI element in a LOCALIZED element with a Localized id='terms-Translation--copy'
2) Added the title 'Copy Into Translation' for the tooltip
3) Made an entry for the corresponding title in the translate.ftl file (Line 462)
> Fix Bug 1679565 Title Missing In Terms Panel and Popup

- pontoon/homepage/static/css/homepage.css
- pontoon/settings/base.py
The + and - operators in CSS calc() must be surrounded by whitespace:
https://developer.mozilla.org/en-US/docs/Web/CSS/calc()#notes
The yuglify CSS compressor we use removes them and breaks CSS.
I tried yuicompressor instead, which has the same bug: https://github.com/yui/yuicompressor/issues/59
Other CSS compressors I've checked look (even more) outdated. I haven't tested any.
The only other instance of calc() in our code uses - instead of +, which is fine.
> Fix bug 1692423: Replace broken CSS compressor with a no-op compressor

- pontoon/sync/tests/test_vcs_models.py
- pontoon/sync/utils.py
- pontoon/sync/vcs/models.py
- pontoon/sync/vcs/repositories.py
- requirements/default.in
- requirements/default.txt
- requirements/dev.txt
- requirements/test.txt
This reverts commit 32a695bc60b7359cffd8aaea9f18b6d5854e1c6b.
Per the README of the scandir project, the optimizations are
part of upstream python since 3.5
> Revert "Speed up os.walk() by replacing it with scandir.walk()"

- frontend/src/core/resource/components/ResourceMenu.js
> Fix bug 1688571: ensure `ResourceMenu` can be discarded

- requirements/dev.in
- requirements/dev.txt
Dj.debug brings some utils to help with development, but we don't seem to be using it much, because it doesn't support Python 3 and we haven't noticed it so far.
It's also [unmaintained](https://pypi.org/project/dj.debug/).
> Remove dj.debug

- pontoon/base/tests/views/data/tmx/valid_entries.tmx
- pontoon/base/tests/views/test_tmx.py
- pontoon/base/utils.py
- pontoon/base/views.py
Following string in translation memory has a special character considered invalid for XML format hence which prevents tmx file from parsing 
`"Portions of this content are c.1998–2019 by individual mozilla.org "
"contributors. Content available under a <a rel=\"external noopener\" "
"href=\"https://www.mozilla.org/foundation/licensing/website-"
"content/\">Creative Commons license</a>."`
Got rid of such characters from the source and target strings to generate a valid tmx file
Reference: https://stackoverflow.com/questions/1707890/fast-way-to-filter-illegal-xml-unicode-chars-in-python
> Fix bug 1681653: Remove invalid characters from TM strings while writing tmx files.

- frontend/src/modules/machinery/components/Translation.css
- pontoon/machinery/utils.py
- pontoon/machinery/views.py
This works if I remove the `distinct=True` (but then projects are duplicated), otherwise results in an error shown below. I guess that's because ordering of duplicate items could be ambiguous if items would be ordered by some other field.
I wonder if there's a more elegant way around this than implementing distinct or ordering in python.
```
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
File "/app/pontoon/machinery/views.py", line 80, in concordance_search
paginator = Paginator(get_concordance_search_data(text, locale), …
```
> Fix bug 1695226: Sort projects in Concordance search results by priority and disabled status

- frontend/src/modules/search/components/SearchBox.css
- frontend/src/modules/search/constants.js
- pontoon/base/models.py
- pontoon/base/tests/managers/test_entity.py
Added new filter to get strings with no or unrejected suggestions.
We first filter out entities with either approved or not rejected translations (for all plurals) and return a filter to not consider these.
> Fix bug 1478554: Add missing (no suggestions) filter to translate app

- docs/admin/deployment.rst
- pontoon/settings/base.py
This PR makes email settings configurable through the following environment variables:
```
EMAIL_HOST=
EMAIL_PORT=
EMAIL_USE_TLS=
EMAIL_HOST_USER=
EMAIL_HOST_PASSWORD=
```
Also,
* I updated the documentation accordingly
* I kept the previously hardcoded setting as default values
* The old `SENDGRID_USERNAME` and `SENDGRID_PASSWORD` settings will still work to not break any prod.
:)
> Makes email settings configurable

- .github/workflows/frontend.yml
The problems I had with the diffs were a rather obscure limit of files that are allowed when diffing with moves. Bump that.
Also, the prettified version from flow-to-ts strips newlines, move the prettify call separate.
> Bug 1698074, follow-up for prettier and diff

- docs/admin/deployment.rst
- manage.py
- requirements/default.in
- requirements/default.txt
Hello,
A very small PR that allows `manage.py` to read dotenv files from an alternative path defined by the `DOTENV_PATH` environment variable (like `wsgi.py` does).
This feature is already documented:
:)
> manage.py: read dotenv files from alternative path

- docs/admin/deployment.rst
- media/file/.gitignore
- media/git/.gitignore
- media/hg/.gitignore
- media/svn/.gitignore
- pontoon/settings/base.py
This PR makes the path of the `media/` folder configurable through the `MEDIA_ROOT` environment variable.
* By default this is configured to a `media/` folder located next to the `pontoon` Python module (like the currently hardcoded value)
* The documentation was updated accordingly
This fixes the bug #1699381 → https://bugzilla.mozilla.org/show_bug.cgi?id=1699381
> Fix bug 1699381: make the media folder configurable

- pontoon/sync/tasks.py
This is a hotfix for an obvious error.
I'll keep the bug open to increase test coverage and catch the error early.
> Bug 1703748: Prevent sync breakage due to a typo

- frontend/src/core/comments/components/AddComment.js
The current search functionality looks to see if the name for mentioning `startsWith` the string that is input into the search field. This causes problems when there are multiple people with the same name such as 'Juan' as only the first 5 results display.
This change switches the search function to check if the name `includes` the search string which should allow users to search mentions based on last names and/or parts of their name or username.
> Fix Bug 1702396 - Update mention search

- docs/admin/deployment.rst
- manage.py
- pontoon/base/celeryapp.py
- pontoon/wsgi.py
- requirements/default.in
- requirements/default.txt
- requirements/dev.txt
- requirements/test.txt
With this PR, `manage.py` call the `dotenv.read_dotenv()` function only
* if the `DOTENV_PATH` environment variable is defined,
* if the `.env` or `.env/.env` file is exists (both are checked by the `dotenv` module).
This will suppress useless warnings.
Related bug → https://bugzilla.mozilla.org/show_bug.cgi?id=1699455
> Fix bug 1699455: suppress warning when the dotenv file is missing

- pontoon/administration/tests/test_views.py
- pontoon/base/__init__.py
- pontoon/base/models.py
- pontoon/contributors/apps.py
- pontoon/homepage/apps.py
- pontoon/insights/apps.py
- pontoon/localizations/apps.py
- pontoon/machinery/apps.py
- pontoon/projects/apps.py
- pontoon/projects/tests/test_views.py
- pontoon/settings/base.py
- pontoon/tags/__init__.py
- pontoon/tags/apps.py
- pontoon/teams/apps.py
- pontoon/teams/tests/test_views.py
- requirements/default.in
- requirements/default.txt
- requirements/dev.txt
- requirements/test.txt
This upgrades Pontoon to Django 3.2, which means we should be good to go until April 2024 :smile: 
App configs are now automatically discovered, and most of our current app configs were redundant or had wrong names.
The `DEFAULT_AUTO_FIELD` is needed to prevent unwanted migrations in the future, when the default value will change to BigAutoField.
I'll submit a small additional PR to make use of the new `@admin.display` decorator.
> Fix bug 1704038: Upgrade to Django 3.2

- frontend/src/modules/entitydetails/components/Helpers.js
- frontend/src/modules/machinery/components/Machinery.js
- frontend/src/modules/machinery/components/Machinery.test.js
If you perform a concordance search and submit a translation immediately after, the previous source string (the one that was just translated) gets used as an input for Machinery along with the current string when the next string opens. i.e. we actually make two requests, and results from both appear in machinery.
Filter out the translations for which source != entity except for concordance search translations.
> Fix bug 1697583 : Filter out invalid machinery translations

- frontend/src/core/api/user.js
- frontend/src/core/user/actions.js
- frontend/src/core/user/components/UserControls.js
- frontend/src/core/user/components/UserNotification.css
- frontend/src/core/user/components/UserNotificationsMenu.css
- frontend/src/core/user/components/UserNotificationsMenu.js
- frontend/src/core/user/components/UserNotificationsMenu.test.js
- pontoon/base/static/js/main.js
- pontoon/base/templates/base.html
- pontoon/contributors/static/js/notifications.js
- pontoon/contributors/static/js/settings.js
- pontoon/contributors/templates/contributors/profile.html
- pontoon/contributors/templates/contributors/settings.html
- pontoon/contributors/templates/contributors/widgets/notifications_menu.html
- pontoon/contributors/views.py
- pontoon/localizations/templates/localizations/localization.html
- pontoon/projects/templates/projects/project.html
- pontoon/tags/templates/tags/tag.html
- pontoon/teams/static/js/info.js
- pontoon/teams/static/js/request.js
- pontoon/teams/templates/teams/includes/info.html
- pontoon/teams/templates/teams/team.html
- pontoon/teams/templates/teams/teams.html
- pontoon/urls.py
- pontoon/uxactionlog/forms.py
- pontoon/uxactionlog/urls.py
- pontoon/uxactionlog/views.py
This patch introduces collection of user interaction metrics of the existing notifications UI.
It also includes the following improvements:
* CSRF token is now globally accessible on all pages using the base template (https://github.com/mozilla/pontoon/pull/1931/commits/21aad3d05234269f17c1c144e1f5bea88f2f7a15), which allows us to collect metrics on all pages that contain the notification icon/menu.
* Click-area to open the notification menu and to mark notifications as read is now exactly the same (https://github.com/mozilla/pontoon/pull/1931/commits/40b218874fe6cd1ce0f1ff21af1a7245216955b8). That is currently not the case, which can result in notifications not being marked as read in some edge cases, even if the menu is opened.
* Notification animation times in the old and new frontend …
> Fix bug 1706936: Collect baseline notifications metrics

- pontoon/base/admin.py
- pontoon/checks/admin.py
- pontoon/sync/admin.py
This makes use of the new admin.display decorator from Django 3.2. Additionally, we use `format_html` instead of `mark_safe`.
> Bug 1704038: Make use of new admin.display decorator

- frontend/src/core/comments/components/AddComment.js
- frontend/src/core/editor/components/EditorSettings.js
- frontend/src/core/editor/components/KeyboardShortcuts.js
- frontend/src/core/project/components/ProjectMenu.js
- frontend/src/core/resource/components/ResourceMenu.js
- frontend/src/core/user/components/UserMenu.js
- frontend/src/core/user/components/UserNotificationsMenu.js
- frontend/src/core/utils/hooks/useOnDiscard.js
- frontend/src/modules/addonpromotion/components/AddonPromotion.js
- frontend/src/modules/batchactions/components/BatchActions.js
- frontend/src/modules/entitieslist/components/EntitiesList.js
- frontend/src/modules/entitydetails/components/EntityNavigation.js
- frontend/src/modules/machinery/components/Machinery.js
- frontend/src/modules/projectinfo/components/ProjectInfo.js
- frontend/src/modules/resourceprogress/components/ResourceProgress.js
- frontend/src/modules/search/components/FiltersPanel.js
- frontend/src/modules/search/components/SearchBox.js
This is another cleanup for TS, but also fixes some flow-ignores.
The gist is that the Synthetic events are only if you use the handler as jsx prop, but when you do `addEventHandler` (and `remove`), you want to use native event types.
> Use native events for addEventListener

- frontend/src/modules/entitydetails/components/Helpers.js
- frontend/src/modules/machinery/components/Machinery.js
- frontend/src/modules/machinery/components/Machinery.test.js
This reverts commit 9e16ba387706aeb7cf837973abca07c79a235f5a.
Bug 1697583 happens less often than 1707819, so let's return the problem solving to the original cause.
> Fix bug 1707819 by reverting fix for bug 1697583

- frontend/src/modules/interactivetour/components/InteractiveTour.tsx
We changed the layout in https://github.com/mozilla/pontoon/pull/1932, so we need to update tour selectors accordingly.
> Fix bug 1710475: Fix interactive tour selectors

- CONTRIBUTING.rst
- docs/dev/setup-virtualenv.rst
- docs/dev/setup.rst
- docs/index.rst
The documentation site did not have nearly any links to the GitHub repo; this adds such links.
This PR only touches documentation; I checked with the docs `make html` command that they render as expected.
> Fix bug 1720701: Add repo links to developer docs

- docs/dev/setup.rst
This doesn't fix the problem, but at least it documents a workaround for those affected.
> Bug 1720875: Add warning for M1 MacBook users to Developer Setup docs

- frontend/src/modules/entitieslist/components/EntitiesList.tsx
- frontend/src/modules/interactivetour/components/InteractiveTour.tsx
- frontend/src/modules/machinery/components/Translation.test.js
- frontend/src/modules/machinery/components/Translation.tsx
- frontend/src/modules/otherlocales/components/Translation.tsx
- frontend/src/test/utils.ts
- pontoon/base/static/js/main.js
- pontoon/homepage/static/js/homepage.js
This patch disables the smooth scrolling animation on Pontoon homepage when `prefers-reduced-motion` is used.
See MDN article on how to test it on your OS:
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion#user_preferences
> Fix bug 1720977: Honour prefers-reduced-motion on homepage

- pontoon/urls.py
Django admin login form appears when Django admin (`/a/`) is accessed by users that aren't authenticated or don't have permission to access it (i.e. non-admins).
On https://pontoon.mozilla.org/ we use Firefox Accounts, which is based on OAuth, so we don't store user passwords, which means the form is useless.
Other installs might use authentication methods that store usernames and passwords, in which case the form could be useful, but it also poses a security risk. Brute-force attack could be used to find valid credentials.
This patch disables the Django admin login form and shows the standard Pontoon 403 page instead.
> Fix bug 1720895: Disable Django admin login form

- frontend/src/core/editor/hooks/useCopyMachineryTranslation.ts
- frontend/src/modules/machinery/components/Machinery.tsx
- frontend/src/modules/machinery/components/Translation.tsx
As per the [Concordance search specs](https://github.com/mozilla/pontoon/blob/master/specs/0106-concordance-search.md) when clicking on a search term the term should be added to the editor and not replace the editor contents.  
This change was made in this [PR](https://github.com/mozilla/pontoon/pull/1771); however, changes made in this [patch](https://github.com/mozilla/pontoon/pull/1799) altered that functionality.
This work restores the expected behavior.
> Bug 1724658 - Concordance search term should be added to editor

- .github/workflows/js-lint.yml
- frontend/src/core/editor/hooks/useCopyMachineryTranslation.ts
Turns out we forgot to update paths for the linter after converting to TypeScript.
> Include .ts and .tsx files in GH Workflow lint

- pontoon/sync/formats/ftl.py
- pontoon/sync/formats/silme.py
- pontoon/sync/formats/xliff.py
- pontoon/sync/tests/formats/test_ftl.py
- pontoon/sync/tests/formats/test_silme.py
- pontoon/sync/tests/formats/test_xliff.py
We already fail gracefully on parsing errors for all other file formats, i.e. we log the error and continue syncing the next file. So let's do that for XLIFF files, too.
I'm also making two other related changes along the way:
- FTL and Silme libs handle parsing errors gracefully by themselves on a message level, so I'm just adding a note to the error handling blocks for these two formats.
- For FTL and Silme we now raise `ParseError` when we hit OSError, to be consistent with other monolingual formats.
> Fix bug 1726749: Fail gracefully on parsing errors in XLIFF files

- pontoon/base/models.py
- pontoon/contributors/templates/contributors/widgets/notifications_menu.html
This turned out to be a decent intro to Pontoon's structure. The logic I went with is that if the user has their homepage locale set, that's the one that's used for the strings; otherwise we default to the project's frontpage, as before. The notification itself is locale-less, so that info needs to come from somewhere.
The URL that's actually used is the locale-agnostic one, though, as that will check if the homepage locale actually exists for the project. The redirect should be really fast, but this allows for that check to only be done when a notification link is clicked. It would be possible to use this even if the homepage locale is unset, in which case the request's `Accept-Language` instead controls the redirect target. Would that be better than going to the project's frontpage?
In …
> Fix bug 1693321: Link to actionable strings from "new strings" notifications

- .github/actions/check-tsc/action.yml
- .github/actions/check-tsc/index.js
- .github/actions/check-tsc/package.json
- .github/workflows/frontend.yml
I wanted to make it easier to see the numbers of errors in a PR, and thought this could be done in two ways:
Add an extra log group for the tsc invocation, which collapses the full log. You can still expand the twisty if you want to know the details. It repeats the error count afterwards.
Collect the error count as step output, and thus enabling a summary step that just prints all the numbers together.
The best way to do that that I could come up with was to actually create an action to wrap tsc invocations.
> No bug, use in-tree action to group tsc checks output

- Makefile
- docker-compose.yml
Right now, data retention effectively works because the `postgresql` container is mentioned in `webapp`'s depends entry in `docker-compose.yml`, and the `make run` command does not explicitly start it. This means that it's started in the background, and then stays running because it's never actually stopped. But it may go away when e.g. the developer's computer is restarted.
This adds a named `pgdata` volume which explicitly persists the data, and a `make dropdb` command for explicitly wiping the database when that's desirable.
> Persist dev env postgres data in a named volume

- frontend/src/core/locale/getPluralExamples.test.js
- frontend/src/core/locale/getPluralExamples.ts
More context in the [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1726219) and the [Discourse post](https://discourse.mozilla.org/t/string-freezes-when-clicked/84627).
> Fix bug 1726219: Prevent infinite loop on generating plural examples

- docker/Dockerfile
- docker/postgres/Dockerfile
To persist a database across this change, dump & load it.
Filing this as a draft inititially, as I'm uncertain why (at least on my machine) the pip-installed lint requirements aren't included in the image, so e.g. `black` and `flake8` aren't available.
@Mitch4sho At least for me the update to Bullseye lets me drop the docker-compose `platform: linux/amd64` patch that was previously required on M1 macbooks.
> Fix bug 1720875: Update Debian Buster → Bullseye, Postgres 11 → 13, Node.js 10 → 14

- pontoon/sync/formats/xliff.py
- pontoon/sync/tests/formats/test_xliff.py
The original bug report was to avoid updating values in the `target-language` attribute for non-iOS projects. As per the discussion in l10n-community on Matrix, we've decided to go a step further and never update the `target-language` attribute. We only set it, if it's not set yet.
> Fix bug 1713058: Only set target-language if not set

- CONTRIBUTING.rst
- README.md
- SECURITY.md
- contribute.json
- docs/dev/first-contribution.rst
- specs/0000-template.md
One of the last steps of the migration of Pontoon bugs from Bugzilla to GitHub is to update the docs, which means merging this PR. So let's use this PR to track the process and collect feedback.
> Bug 1688846: Point contributing docs from Bugzilla to GitHub

- pontoon/base/tests/views/test_entity.py
- pontoon/base/views.py
This option used to be used by translate.old, but isn't used
in the translate frontend app.
Remove it to make the code a bit easier to reason about.
> Remove unused option from entities api

- pontoon/base/models.py
- pontoon/base/static/js/tabs.js
- pontoon/projects/templates/projects/project.html
- pontoon/projects/tests/test_views.py
- pontoon/projects/views.py
https://mozilla-pontoon-staging.herokuapp.com/projects/firefox-for-ios/?teams=ar,zh-CN,fr,de,it,pl,sl
> Fix #2313: Add ability to show project stats for a subset of teams

- frontend/package.json
- frontend/src/index.tsx
- frontend/yarn.lock
`javascript-time-ago` is installed as a dependency of react-time-ago. Since we import it explicitly, we should also install it explicitly.
This also solves the same problem as reported in the issue in local Docker setup introduced in https://github.com/mozilla/pontoon/commit/623d7bbb39934fe2152f78449efb25f3b273529e. I haven't been able to figure out what exactly is the culprit there, but apparently the `yarn.lock` file gets ignored.
In a followup, we should also look into upgrading to latest `javascript-time-ago` and use `yarn` instead of `npm` across the board (`post_compile` and CI).
> Fix #2325: List javascript-time-ago as an explicit dependency

- docs/dev/setup.rst
This is effectively reverting #1973.
The warning is no longer needed as of #2008.
> Remove warning for M1 MacBook from Developer Docs

- pontoon/machinery/views.py
SYSTRAN service currently returns 500 errors, because the endpoint URL, Credentials and Locale Profile IDs have been changed without prior notice.
This patch changes the URL. Credentials and Locale Profile IDs are obviously not stored in the codebase.
> Change SYSTRAN Translate URL

- pontoon/contributors/static/css/contributor.css
- pontoon/contributors/static/css/settings.css
- pontoon/contributors/templates/contributors/settings.html
CSS in the heading of the User Profile page is broken since #2349.
Let's fix it.
> Fix broken CSS on the Profile page

- .git-blame-ignore-revs
Excludes https://github.com/mozilla/pontoon/commit/87cb4090099b98553af87817a877019947f05be2.
> Exclude Black 21.10b0 reformatting from git blame

- frontend/src/core/editor/hooks/useUpdateUnsavedChanges.ts
- frontend/src/core/utils/fluent/convertSyntax.test.js
- frontend/src/core/utils/fluent/convertSyntax.ts
- frontend/src/core/utils/fluent/flattenMessage.test.js
- frontend/src/core/utils/fluent/flattenPatternElements.ts
- frontend/src/modules/fluenteditor/components/rich/RichTranslationForm.tsx
Closes #2366 
This refactors the behaviour of `flattenPatternElements()` to, well, flatten them some more. See the above issue for why this is a good idea.
If a Fluent message has a source like:
```fluent
msg = before { $foo ->
[one] one
*[other] other
} after
```
this will now be rendered and, if modified, saved as:
```fluent
msg = { $foo ->
[one] before one after
*[other] before other after
}
```
With the RichEditor, this means that for the above message a translator will see the fields `one` and `other`, rather than `Value`, `one`, `other`, `Value` as happens currently.
If a message has more than one selector, any whitespace immediately before each selector after the first will be kept out of the selector variants, so for instance this:
```fluent
my-entry =
There { $num ->
[one] is one …
```
> Flatten Fluent select messages more

- CONTRIBUTING.rst
- frontend/README.md
As of #1996, we only need to re-build the affected container after dependencies/requirements change.
> Update build command docs after dependency change

- frontend/src/modules/fluenteditor/components/rich/RichEditor.tsx
Fixes #2374
It would appear that the hook discussed at https://github.com/mozilla/pontoon/pull/2367#issuecomment-972871389 was the only thing handling the message flattening when copying from the original while in the rich editor, and I'd missed it previously.
This is fixed, and I've gone through and reviewed that (hopefully!) all other code paths updating a Fluent translation are not similarly missing an otherwise expected flattening.
> Flatten Fluent message when copying from original

- docker-compose.yml
Docker won't start up since the use of the property
target: and the mismatch with the version of the
docker-compose.yml (version: "2"). The minimum version
required to use target: is 2.3.
Changing the value of the version to 2.3 of the docker-compose.yml will
allow for the docker containers to start up.
> Fix #2372 wrong docker-compose version number

- frontend/src/modules/search/components/chart-options.ts
Fixes #2319 
The buttons at the bottom of the DATE/TIME range picker were having overlapping text. This adds spacing between them. Note that this adds spacing between _all_ of the buttons, not just the overlapping one from the issue, however it looks like we can't change the positioning of individual buttons with Highcharts, see [here](https://www.highcharts.com/docs/chart-design-and-style/style-by-css?_ga=2.63616175.1495014264.1638378248-1071920560.1638378248#what-can-be-styled).
> Add spacing to time range buttons

- frontend/src/core/editor/selectors.ts
- frontend/src/core/entities/selectors.test.js
- frontend/src/core/entities/selectors.ts
- frontend/src/core/navigation/selectors.ts
- frontend/src/core/plural/selectors.ts
- frontend/src/core/user/selectors.ts
This is mostly about fixing selectors to work on the `RootState`.
This reduces the TS errors for `--noImplicitAny`, but increases `--strictNullChecks`. The culprit there is `getSelectedEntity`, which used to be `any` and is `Entity | undefined` now.
I wonder what state we're in when that's undefined.
I also made things just `undefined` instead of `null | undefined`
> Some noImplicitAny TS fixes

- pontoon/base/forms.py
- pontoon/contributors/templates/contributors/settings.html
- pontoon/contributors/tests/test_views.py
- pontoon/contributors/views.py
> Fix bug 1748145: Temporarily remove ability to change contributor email address

- frontend/package.json
- frontend/src/modules/machinery/components/Machinery.tsx
- frontend/yarn.lock
Resolves: #2270 
This PR replaces the `Load more` button used for pagination in the Machinery tab with an infinite scroll utilizing a [React hook](https://github.com/onderonur/react-infinite-scroll-hook).
> Add infinite scroll hook to Machinery tab

- pontoon/base/static/css/style.css
On https://pontoon.mozilla.org/fr/firefox/contributors/, this happens:
This patch reduces the tab width to prevent the above ugliness, and prevents dashboard tabs from overflowing into a new line in general.
> Do not overflow dashboard tabs into new line

- pontoon/contributors/templates/contributors/profile.html
If you open https://pontoon.mozilla.org/contributors/dvgiVCmoeidF2xcqSnBHtpzLTFU/ in e.g. Safari, you'll notice misaligned email and permission entries:
This patch fixes that.
> Fix bad alignment on Contributor page on Webkit/Blink browsers

- frontend/src/core/comments/components/CommentsList.css
- frontend/src/core/comments/components/CommentsList.tsx
Fixes #2266 this PR is supposed to set pinned comments in the pinned section only; this is illustrated in the screenshot below.
> refactor pinned comments to be only in pinned comment section

- pontoon/api/README.md
- pontoon/api/urls.py
- pontoon/settings/dev.py
Content Security Policy should be only exempt if it absolutely cannot be used. It doesn't seem like this is the case for our GraphQL endpoint. The same goes for CSRF.
> Restore CSP and CSRF protection on /graphql

- frontend/src/modules/entitieslist/components/EntitiesList.tsx
- frontend/src/modules/fluenteditor/components/rich/RichTranslationForm.tsx
- frontend/src/modules/genericeditor/components/GenericTranslationForm.tsx
Fixes #2251 by adding an unsaved-changes check to the failed-checks reset that's meant to only be called during editing, rather than also applying when switching between different strings.
This is a little bit of a hack as it relies on `state.unsavedchanges.exist` to change after `state.editor.translation` changes in order to handle the corner cases of going from original -> broken -> original. But 1) it works, and 2) a truly proper fix would have me refactor editor state handling completely, and that's a big enough job that we'll need to prioritise it appropriately.
> Avoid resetting errors & warning during editor mount

- frontend/public/static/locale/en-US/translate.ftl
- frontend/public/static/locale/fr/translate.ftl
- frontend/src/core/notification/messages.tsx
> Correct 'unaproved' to 'unapproved' in relevant locations 

- .github/workflows/backend.yml
- .github/workflows/frontend.yml
- .github/workflows/heroku.yml
- .github/workflows/js-lint.yml
- .github/workflows/non-frontend-js.yml
- .github/workflows/py-lint.yml
Sometimes, it's useful to be able to manually start a CI job, e.g. when working on a feature branch. By adding an empty `workflow_dispatch` value to the GitHub actions' `on` object, this becomes possible: https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
> Add workflow_dispatch triggers for all actions

- pontoon/base/models.py
- pontoon/base/tests/models/test_repository.py
We should validate Repository URLs before they are stored into the DB.
The `repository_url_validator()` has been tested with all Repository URLs on pontoon.mozilla.org. It supports all HTTP(S), FTP(S), SSH and SVN+SSH URLs, as well as Git SCP-like SSH URL.
> Validate Repository URLs

- pontoon/insights/migrations/0009_fix_projectlocale_insights_data.py
- pontoon/insights/tasks.py
Fixes #2457 by not trying to use a project id as a locale id.
Historical data is fixed by re-running the migration script; `0009_fix_projectlocale_insights_data` is effectively a copy of `0006_projectlocale_insights_data`. As before, this may take multiple seconds to run on production data.
> Fix project+locale insights data

- pontoon/tour/views.py
This fixes the following server error, which occurs for non-authenticated users of Pontoon Tour:
```
[ERROR:django.request] 2022-04-03 19:55:23,337 Internal Server Error: /update-tour-status/
File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
File "/app/pontoon/base/utils.py", line 123, in wrap
return f(request, *args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/django/views/decorators/http.py", line 40, in inner
return func(request, *args, **kwargs)
File "/app/pontoon/tour/views.py", line …
```
> Prevent AttributeError on Tour for AnonymousUsers

- translate/src/modules/history/components/Translation.css
Checkbox colors in the History panel are off.
> Switch pretranslated/fuzzy checkbox colors

- translate/src/core/editor/hooks/useHandleShortcuts.ts
- translate/src/modules/search/components/SearchBox.test.js
- translate/src/modules/search/components/SearchBox.tsx
Fixes #2475 
In #2444, the keyboard shortcuts were switched from using the deprecated KeyboardEvent `keyCode` to `code`, when they should have been switched to using `key`. Both `code` and `key` use string identifiers for the keys, but `code` is concerned with physical keys while `key` with logical ones. This means that `code` has different values for the different return keys; `Enter` and `NumpadEnter`.
@mathjazz Are you able to test if this does anything for #2476, or if that's a different issue?
> Base keyboard shortcuts on key values rather than positions

- translate/src/core/api/base.ts
- translate/src/core/api/entity.ts
- translate/src/modules/history/actions.ts
Fixes #2474 
When a request is aborted, `fetch()` may still return a valid object (TIL). Calling then the response's `json()` method will throw an error with `name: 'AbortError'`. The APIBase class's `fetch()` wrapper will then log the error with `console.error()`, and return an empty object `{}`.
This probably breaks assumptions all over the place in the `translate` front-end as API results are never actually validated. In this particular instance, the assumption it's breaking is that the history will be an array. An empty object, on the other hand, has `undefined` length and no `find()` method, and thereby triggers the reported error condition.
This is a fix for this specific endpoint, rather than the general case.
> Always return an array from EntityAPI#getHistory()

- specs/0111-redesign-profile-page.md
- Email address should never we visible to all users.
- Replace the term "limited visibility" with more self-explanatory "users with translator rights".
- Move Latest activity section closer to the Other data in the sidebar section.
- Use the term "translator rights" consistently.
- Move email address visibility details from the Email address section to the Visibility section.
> Clarify visibility of data in the profile page

- pontoon/base/templates/widgets/heading_info.html
- pontoon/contributors/templates/contributors/settings.html
- pontoon/homepage/templates/homepage_content.html
- pontoon/localizations/templates/localizations/widgets/resource_list.html
- pontoon/projects/management/commands/send_deadline_notifications.py
- pontoon/projects/templates/projects/widgets/project_list.html
Fixes #2434.
I've kept deadline internally. Which means the only end-user facing leftover of "deadline" is in the API schema.
> Fix #2434: Rename Deadline to Target Date

- translate/README.md
Warm-reloading is not even used by the core Pontoon devs.
It also has poor browser support and requires hacking.
> Remove the warm-reloading README section

- requirements/default.in
- requirements/default.txt
Fixes #2493 by updating Silme.
We now use the repo within the mozilla org:
https://github.com/mozilla/silme
Release notes:
https://github.com/mozilla/silme/releases/tag/v0.11.0
https://github.com/mozilla/silme/releases/tag/v0.11.1
https://github.com/mozilla/silme/releases/tag/v0.11.2
> Bump Silme to 0.11.2

- package-lock.json
- translate/README.md
- translate/package.json
- translate/src/core/loaders/components/SkeletonLoader.tsx
- translate/src/modules/entitieslist/components/EntitiesList.test.js
- translate/src/modules/entitieslist/components/EntitiesList.tsx
- translate/src/modules/entitieslist/index.ts
- translate/src/modules/machinery/components/Machinery.tsx
Fixes #2420
The previously skipped EntitiesList tests are now un-skipped. Minimally mocking IntersectionObserver was... interesting.
> Replace react-infinite-scroller with react-infinite-scroll-hook

- Procfile
- docs/admin/maintenance.rst
This fixes a regression from #2498.
We upgraded celery from version 4 to version 5, which introduced a breaking change and broke with the following error:
```
You are using `--app` as an option of the worker sub-command:
celery worker --app celeryapp <...>
The support for this usage was removed in Celery 5.0. Instead you should use `--app` as a global option:
celery --app celeryapp worker <...>
Usage: celery worker [OPTIONS]
Try 'celery worker --help' for help.
Error: No such option: --app
```
> Make celery command version 5.x compatible

- pontoon/machinery/views.py
Microsoft Terminology Service endpoint is down ATM:
https://api.terminology.microsoft.com/Terminology.svc
It is essentially making the translate app unusable, because many other requests get stuck in a queue and time out.
This is just a temporary fix to disable the service. The proper fix, which will prevent external services to affect other requests, will come in a followup.
> Temporarily disable Microsoft Terminology Service

- pontoon/base/models.py
- pontoon/base/tests/models/test_entity.py
- pontoon/base/views.py
While working on #2050, I noticed that there were a couple of minor inefficiencies in `Entities` methods; they're fixed here.
This also drops the unused always-false `visible` field from the JSON output.
> Simplify `Entity.for_project_locale` and `Entity.map_entities`

- pontoon/projects/management/commands/send_review_notifications.py
- translate/public/locale/en-US/translate.ftl
- translate/src/api/entity.ts
- translate/src/context/location.test.js
- translate/src/context/location.tsx
- translate/src/modules/batchactions/actions.ts
- translate/src/modules/search/components/FiltersPanel.tsx
- translate/src/modules/search/components/SearchBox.css
- translate/src/modules/search/components/SearchBox.test.js
- translate/src/modules/search/components/SearchBox.tsx
Built on #2518, will be rebased once that's merged; only the last two commits are actually meant for this PR.
Fixes #2049 by adding support for a `list=13,42,99` URL query parameter. This is then used by the review-notification links, as discussed previously in https://github.com/mozilla/pontoon/pull/2456#discussion_r831972129.
In the UI, the list view is indicated by a custom search-box icon, [`list-alt`](https://fontawesome.com/v5/icons/list-alt?s=solid):
Internally, the argument uses the existing `entity_ids` payload parameter used by batch actions, with which `/get-entities/` returns an unpaginated list of matching entities. It's not possible to use the parameter together with any other filters like `status` or `search`. This allows for re-merging the just-added `fetchEntitiesById()` …
> Add support for list query parameter

- pontoon/machinery/views.py
This reverts commit 83d723ff1b57a12d4b2ca90e2ec83f56355a9b8d, because Microsoft Terminology Service endpoint is no longer down:
https://api.terminology.microsoft.com/Terminology.svc
I don't think we need to block this on https://github.com/mozilla/pontoon/issues/2532.
> Revert "Temporarily disable Microsoft Terminology Service (#2525)"

- translate/src/api/translation.ts
- translate/src/context/FailedChecksData.tsx
Fixes #2543, which was failing due to not validating that the API response matches the declared TS type; that lead to code making invalid assumptions, and failing to display the proceed-anyway dialog.
It wasn't only failing for approvals, but also submissions of messages with warnings.
Sorry, this one was my fault.
> Correctly set types of ApiFailedChecks members as optional

- pontoon/machinery/views.py
- translate/src/context/Editor.tsx
Fixes #2549 by not "fixing" the cursor position during manual edits. Spent ages looking in entirely the wrong place for this.
Python changes are completely separate, and were required to account for errors discovered when running the server locally with no network connectivity.
> Fix rich editor focus handling

- pontoon/contributors/templates/contributors/widgets/contributor_list.html
- pontoon/contributors/utils.py
- pontoon/contributors/views.py
- pontoon/teams/static/css/team.css
- pontoon/teams/templates/teams/includes/contributors.html
- pontoon/teams/views.py
This patch groups users on the Locales Contributors page (e.g. https://pontoon.mozilla.org/sl/contributors/) by the role they have within a locale.
Fixes #2157, at least the easy parts of it. Not sure we want to go very far beyond this (e.g. add a contact form). We could however add a Contact/Email button to listed managers.
> Group Team contributors by role

- translate/src/core/comments/components/AddComment.tsx
- translate/src/core/comments/components/MentionList.tsx
Workaround-y fix for https://github.com/mozilla/pontoon/issues/2298#issuecomment-1155742194, which is a slightly different bug from the originally reported issue.
The source of this problem appears to be a timing issue internal to `slate` or `slate-react`. Rather than trying to really figure out and fix the root cause there, let's just patch this so that the comment editor doesn't blow up.
> Silence failures in ReactEditor.toDOMRange() for MentionList position

- translate/public/locale/en-US/translate.ftl
- translate/src/context/Editor.tsx
- translate/src/core/editor/components/Editor.tsx
- translate/src/core/editor/components/MachinerySourceIndicator.css
- translate/src/core/editor/components/MachinerySourceIndicator.tsx
- translate/src/core/editor/hooks/useHandleShortcuts.ts
- translate/src/core/entities/useTranslationStatus.tsx
- translate/src/modules/entitieslist/components/Entity.tsx
- translate/src/modules/genericeditor/components/PluralSelector.css
- translate/src/modules/machinery/components/Translation.tsx
- translate/src/modules/otherlocales/components/Translation.tsx
~Built on top of #2536, so will need a rebase once it's merged. Actual changes here are the last two commits.~ Edit: Done.
Fixes #2050, so ping its original reporter @tomer.
Screenshot of the editor with the "Perfect match from translation memory" indicator shown:
UX is based on discussions with @mathjazz, as a noticeable but discreet indicator that should not move other elements in the view when its shown or hidden. Currently it's only shown for this specific case, but while playing around with it, it seems like it could work for all machinery matches. I'd be very happy to accept suggestions for better/alternative wording for it.
The indicator is only shown when in the "simple" view, and the automatic fill also only happens when the string may be initially shown in that view.
> Automatically fill editor for missing values with a perfect TM match

- pontoon/insights/static/css/insights.css
On some screen resolutions, the Age of unreviewed suggestions chart,
which is hidden by default, didn't render at all when being switch to.
> Always show Age of unreviewed chart

- docker/Dockerfile
Setup as described [here](https://mozilla-pontoon.readthedocs.io/en/latest/dev/setup.html) does not work as file permissions are wrong, using `COPY` with `--chown=pontoon:pontoon` fixes this.
> fix(docker): copy using chown for package.json and .env

- translate/src/context/Editor.tsx
- translate/src/modules/fluenteditor/components/RichTranslationForm.tsx
- translate/src/modules/genericeditor/components/GenericTranslationForm.test.js
- translate/src/modules/genericeditor/components/GenericTranslationForm.tsx
Fixes #2557
The editor state refactoring had carried along (and possibly broken?) some prior behaviour where focus handling was actively driven using `input.setSelectionRange()`. When doing certain editing operations, in particular when mixing RTL & LTR content, this lead to surprising/unhelpful results.
The right answer here isn't to add more customisation and more active control, it's to realise that the browser will almost always do the right thing if you let it. So most of said active control is removed here, and the `setEditorSelection()` action is told to always target the "end" of the selection, as that appears to correspond to the right thing even when mixing RTL & LTR content.
Automated testing of this behaviour is not really possible outside of actual browsers, and we don't have …
> Control cursor position less, trusting the browser to handle it right

- translate/src/modules/machinery/components/Machinery.css
Fixes #2389: Restore scrolling of the Locales panels when used inside the Terminology project.
@abowler2 Do you remember what was the [initial purpose](https://github.com/mozilla/pontoon/pull/1794/commits/f67f084d9f5c934a13d16fdb3bd8fba84a99769c#diff-7900fda55b9eaedcd6f9d31f2c33482e0963a33368fa5f9d4605669f31621872) of this code??
I don't see issues after I remove the given lines.
> Restore Locales scrolling in Terminology

- pontoon/base/templates/500.html
- pontoon/base/templates/base.html
- pontoon/base/templates/django/base.html
- translate/public/translate.html
Fixes #2576.
Pontoon color scheme is dark by default, and Chrome breaks it when the experimental
Auto Dark Theme flag is on. This patch opts-out of Chrome Auto Dark Theme.
Resources:
https://developer.chrome.com/blog/auto-dark-theme/#using-a-meta-tag
> Opt-out of Chrome Auto Dark Theme

- translate/src/modules/fluenteditor/components/RichTranslationForm.tsx
- translate/src/modules/genericeditor/components/GenericTranslationForm.tsx
- translate/src/modules/search/actions.ts
- translate/src/modules/search/components/SearchBox.tsx
- translate/src/modules/search/index.ts
- translate/src/modules/search/reducer.ts
Fixes #2572
The timing of redux state updates was a bit off, causing the weird UX. Rather than fix the timing, let's just get rid of the state, and trust the browser to track whether the search box is focused or not.
> Use document.activeElement rather than custom redux value to track SearchBox focus

- translate/src/core/editor/components/EditorMenu.test.js
- translate/src/core/editor/components/EditorMenu.tsx
- translate/src/core/user/reducer.ts
- translate/src/modules/entitydetails/components/EntityDetails.tsx
Fixes #2561 
While moving data handling from Redux to React Context, some of their default values changed from `null` to objects containing empty/initial values. This meant that checks like `!entity` or `!user` would never actually succeed, and were in fact dropped. Some of these initial values would then bleed through to the UI as e.g. `user.isAuthenticated` would be `false` and `entity.readonly` would be `true` while the relevant data was being fetched from the server, leading to an initial flash of content.
To fix this, a couple of checks are added for `entity.pk === 0` and `user.isAuthenticated === null` (a new state) to not render components while data is still being fetched.
> Do not render EntityDetails or EditorMenu while still loading data

- translate/src/context/HelperSelection.tsx
- translate/src/core/editor/hooks/useHandleShortcuts.ts
- translate/src/modules/machinery/components/Translation.tsx
- translate/src/modules/otherlocales/components/Translation.tsx
Fixes #2582 
Fixing the `key = value` part was missed in #2568, which made the same thing work for mouse interactions.
The selection highlight was a separate bug; an unneeded part of state was not fully dropped during the earlier Redux -> React Context migration, and it hid the highlight when using key shortcuts.
> Fix issues copying strings from Machinery & OtherLocales to editor using key shortcut

- translate/src/core/utils/hooks/useOnDiscard.ts
- translate/src/modules/projectinfo/components/ProjectInfo.tsx
Fixes #2563
The `useOnDiscard()` hook was mis-used in the ProjectInfo component. Its code documentation is improved to note a requirement for its `ref` to be a top-level element.
The other uses of the hook have also been reviewed to ensure that this same issue should not be present elsewhere.
> Add wrapper component for ProjectInfoDialog to satisfy useOnDiscard

- translate/src/context/EntityView.tsx
Fixes #2547 
The approval of one variant of a gettext message was causing a change in the entity data (as it should), but this was mistakenly triggering a `useEffect` hook in the EntityView provider that reset the `pluralForm` value. Hence when approving any such variant, the view would not advance to the next variant like it should.
To fix this, the `entity` and `pluralForm` updates are now handled in separate hooks within EntityViewProvider, with appropriate conditions as their triggers.
> Separate plural-form reset from entity updates in its provider

- package-lock.json
- package.json
- translate/package.json
- translate/src/store.ts
As much of the application state is already out of Redux, the verbosity of `redux-logger` is becoming more and more annoying, and less useful. So let's remove it.
> Drop redux-logger

- translate/src/App.tsx
- translate/src/api/user.ts
- translate/src/context/MentionUsers.tsx
- translate/src/core/comments/components/AddComment.test.js
- translate/src/core/comments/components/AddComment.tsx
- translate/src/core/comments/components/MentionList.tsx
- translate/src/core/user/actions.ts
- translate/src/core/user/reducer.ts
This is a patch for the bad initial loading behaviour identified in #2548. It's not a fix for the issue, but it's a step in a better direction.
With this change, data for @-mentionable users is only fetched when the first AddComment component is rendered, i.e. when one of the following happens:
- an authenticated user clicks on a "COMMENT" button next to a History translation,
- the "REQUEST CONTEXT or REPORT ISSUE" button is clicked, or
- when then team comments tab is opened.
To effect the change, the relevant data is moved to a new React Context.
This reduces the initial data load of Pontoon by about 35% on pontoon.mozilla.org. As a minor regression, there is now a short delay after clicking "REQUEST CONTEXT or REPORT ISSUE" before the contact person's data is entered into the edit …
> Only fetch /get-users/ when adding a comment

- pontoon/base/static/css/style.css
- pontoon/base/static/js/main.js
- pontoon/base/templates/django/base.html
- pontoon/base/templates/django/socialaccount/authentication_error.html
- pontoon/base/templates/header.html
- pontoon/base/templates/widgets/signin.html
- pontoon/contributors/static/css/profile.css
- pontoon/contributors/templates/contributors/profile.html
- translate/public/locale/en-US/translate.ftl
- translate/public/locale/fr/translate.ftl
- translate/src/core/editor/components/EditorMenu.css
- translate/src/core/editor/components/EditorMenu.tsx
- translate/src/core/user/components/FileUpload.tsx
- translate/src/core/user/components/SignIn.css
- translate/src/core/user/components/SignIn.tsx
- translate/src/core/user/components/SignInForm.tsx
- translate/src/core/user/index.ts
- translate/src/core/utils/components/CSRFToken.tsx
- translate/src/core/utils/index.ts
With the recent upgrade of `django-allauth`, when you try to log into Pontoon, you get first redirected to a log in page, on which you need to click on a button and then get redirected to the actual Firefox Accounts login page.
That's because POST requests are now required by default to initiate the handshake:
https://django-allauth.readthedocs.io/en/latest/release-notes.html#section-5
The following patch removes that extra step during the log in process by replacing sign in links with buttons, which submit a POST form.
> Use POST requests for social login endpoints

- pontoon/base/templatetags/helpers.py
- pontoon/contributors/static/css/profile.css
- pontoon/contributors/static/js/profile.js
- pontoon/contributors/templates/contributors/includes/timeline.html
- pontoon/contributors/templates/contributors/profile.html
- pontoon/contributors/tests/test_utils.py
- pontoon/contributors/urls.py
- pontoon/contributors/utils.py
- pontoon/contributors/views.py
- specs/0111-redesign-profile-page.md
Fixes #2487 definitively.
The patch implements contribution timeline, which can be filtered by contribution type and day.
It's deployed to stage (which uses ~2 weeks old prod data):
https://mozilla-pontoon-staging.herokuapp.com/contributors/93Rx_ofmgBDhnz4QZD1aHlOg0uY/
TODO:
> Add contribution timeline

- pontoon/base/models.py
- pontoon/base/templatetags/helpers.py
In https://github.com/mozilla/pontoon/commit/327962edb5a32c267ab4ed5a5d73b5fac7301c96#diff-4ebc5e9888b2962aecd470dd76f7d410b4e246f2d8323df57ed7dd0c8d5e3ade we changed `User.managed_locales` and `User.translated_locales` API, which broke `User.can_translate` among other things. As a consequence, some users were unable to review translations.
The `User` model extensions implemented using the `add_to_class()` method are not tested. We should fix this in a separate patch.
> Permissions fixes

- translate/src/context/Editor.test.js
- translate/src/context/Editor.tsx
- translate/src/core/editor/components/Editor.test.js
Fixes #2607 with a workaround
The detected "change" is effectively due to bad data; some FTL strings are stored in the database without the terminal newline that's always included in the output of our Fluent serialiser. I suspect that these may have been entered by editing and submitting strings using the advanced/raw view.
So one way to fix the problem would be to go through the data and normalise all of it to always include a newline, but I've opted here to add that normalisation in the front-end. It's likely that we'll refactor the internal representation of messages further as a part of the MF2 work, at which stage this may be dropped thanks to comparing parsed message structures rather than strings.
> Normalise initial FTL values to always end in newline

- translate/src/core/utils/fluent/extractAccessKeyCandidates.test.js
- translate/src/core/utils/fluent/extractAccessKeyCandidates.ts
- translate/src/modules/fluenteditor/components/RichTranslationForm.test.js
- translate/src/modules/fluenteditor/components/RichTranslationForm.tsx
Fixes #2603
The logic for detecting an accesskey is fixed and expanded to cover more cases. Previously, either the `label` attribute or the message value needed to have non-empty contents for the detection to succeed. Now:
- The input is rendered with accesskey styling independently of the number of candidate keys, but buttons next to it are rendered only if there at least two candidates.
- If a message has no `label` and no value, the `value` and `aria-label` attributes are also inspected.
- All non-letter and non-number candidates are dropped, though they may still be manually entered.
- Prefixed access keys are detected. If e.g. a message has attributes `buttonlabel` and `buttonaccesskey`, the former is used to generate the candidates for the latter.
> Refactor accesskey extraction to include more cases

- pontoon/sync/tasks.py
> Sync should run locales in order of locale code, not language name

- pontoon/base/static/css/table.css
- pontoon/base/templates/widgets/heading_info.html
- pontoon/base/templates/widgets/progress_chart.html
- translate/public/locale/en-US/translate.ftl
- translate/src/modules/resourceprogress/components/ResourceProgress.css
- translate/src/modules/resourceprogress/components/ResourceProgress.tsx
- translate/src/modules/search/constants.ts
Pretranslated status was hidden from the UI as part of #2463, which introduced the Pretranslated status and dropped Fuzzy. Now that we plan to start evaluating pretranslation, it's time to restore it.
This patch essentially reverts https://github.com/mozilla/pontoon/pull/2463/commits/0133d9aa307ff85bc52d87f2ea6076f7838749b5 and https://github.com/mozilla/pontoon/pull/2463/commits/3277af14eb72019a0539bf012061aee357af8dae.
> Re-enable Pretranslated status in dashboards, filters and progress charts

- pontoon/base/models.py
- pontoon/base/static/js/progress-chart.js
- pontoon/base/static/js/table.js
- pontoon/localizations/views.py
- pontoon/tags/tests/utils/test_tagged.py
- pontoon/tags/utils/chart.py
- translate/src/api/resource.ts
- translate/src/core/editor/hooks/useSendTranslation.ts
- translate/src/core/editor/hooks/useUpdateTranslationStatus.ts
- translate/src/core/resource/actions.ts
- translate/src/core/resource/components/ResourceMenu.tsx
- translate/src/core/resource/components/ResourcePercent.test.js
- translate/src/core/resource/components/ResourcePercent.tsx
- translate/src/core/resource/reducer.test.js
- translate/src/core/resource/reducer.ts
- translate/src/modules/batchactions/actions.ts
- translate/src/modules/resourceprogress/components/ResourceProgress.tsx
As of this patch, completion percentage calculations used in dashboards, charts and menus treat pretranslated strings as completed, since they end up being used in product.
> Include pretranslated in completion calculations

- bin/make_comm_source_repos.py
This script uses https://hg.mozilla.org/projects/comm-l10n/ repository to create repositories with source strings only for Thunderbird and Seamonkey.
It's a standalone script, rather than being included in [`mozilla-en-US.py`](https://github.com/mozilla/pontoon/blob/60e49bf07d16540a18501c934b310b30f46c067b/bin/mozilla-en-US.py), because the latter will be obsolete and removed soon; mobile has been long gone, Firefox can just use https://hg.mozilla.org/l10n/gecko-strings/, and this script will cover Thunderbird (including Lightning) and Seamonkey.
This is the output of the script:
https://hg.mozilla.org/users/m_owca.info/thunderbird
https://hg.mozilla.org/users/m_owca.info/seamonkey/
> Add script to generate source-only repos for Thunderbird and Seamonkey

- docs/admin/deployment.rst
- pontoon/machinery/management/commands/warm_up_automl_models.py
Fixes #2655.
The Google AutoML Translation has latency of ~15s caused by the loading time of a custom model into the chip. Since there are replicas, the high tail latency occurs for first N requests - one replica may successfully load the model, but the request may be routed to other replicas which are still loading. Once all replicas load the model, the normal latency should be 200 - 500ms.
Also, since the chips are shared with other models, models gets evicted from the chips if they aren't used for a longer period of time, resulting in high latency on the next following request.
To keep latency low, we need to make regular dummy warm-up requests using a management command, which needs to run at least every 10 minutes.
> Keep AutoML Translate latency low

- pontoon/base/utils.py
- pontoon/sync/changeset.py
Along with Approved strings, Pretranslated strings need to be serialized into localization files when generated for sync and file download.
> Serialize pretranslated translations to VCS and downloaded files

- translate/src/context/Editor.tsx
Fixes #2638
When only one entry is visible, submitting a new translation keeps the editor view on the same string. In that situation, the initial value of the string changes; this was not properly included in the dependencies of the `useEffect()` that updates the UnsavedChanges state
> Add missing dependency on initial value to UnsavedChanges update

- translate/src/api/machinery.ts
Fixes #2680.
We currently round Machinery quality percentage on frontend, which in very long strings results in e.g. 99.6 % matches to appear as perfect matches, which are copied into the editor automatically.
This patch replaces `Math.round()` with `Math.floor()`.
> Floor TM quality value

- translate/src/utils/message/getSimplePreview.test.js
- translate/src/utils/message/getSimplePreview.ts
Fixes #2685 
We need to use empty literals `{ "" }` on occasion to represent empty messages, but these should not be rendered in the simple view. This change should also allow for automatic 100% TM matches to work for missing terms, as the field value will then be empty by the time we get the TM results.
> In the simple view, use an empty string for empty Fluent literals

- pontoon/checks/libraries/pontoon_db.py
- pontoon/checks/tests/test_pontoon_db.py
**Edit:** Implementation completely changed from the original description; see comments below.
Fixes #2599 ~~using the solution discussed in mozilla/compare-locales#6.~~
CC @flodolo 
~~Adds a Fluent utility function `isEmptyMessage()` and uses it to disable the save action when the simple or rich editor inputs are empty.~~
~~The basic appearance of the button is kept unchanged, but the hover state is affected; the cursor for the disabled state uses a 🚫 indicator and the tooltip notes that saving an empty string is only possible using the advanced editor.~~
~~The label of the button makes more sense to be controlled with CSS `text-transform` rather than being hard-coded, and it doesn't really make sense to duplicate the formatted strings that are provided by FTL.~~
> Add warning for empty Fluent entries

- translate/src/modules/fluenteditor/components/RichTranslationForm.test.js
- translate/src/modules/fluenteditor/components/RichTranslationForm.tsx
Fix #2692.
If Fluent string contains plurals in attributes, prepend rich editor labels with attribute names, same as for other selec expressions in attributes.
> Render attribute names in plural string labels

- translate/src/context/Editor.tsx
- translate/src/utils/message/getReconstructedMessage.ts
Fixes #2707, a regression from #2684
During editing, input will not always parse as valid Fluent. One of the code paths used from the history view was throwing an error in this situation, when it should have just accepted that the translation was not currently valid.
Another similar point of potential failure is also patched, pre-emptively.
> Avoid throwing errors in editor

- translate/src/utils/message/getSyntaxType.test.js
- translate/src/utils/message/getSyntaxType.ts
Fixes #2703 by adding a limit (15) to the number of fields that may be shown either in the original source or the rich editor view.
> Add limit (15) for fields in rich editor

- pontoon/base/templatetags/helpers.py
- pontoon/base/tests/test_helpers.py
- pontoon/pretranslation/pretranslate.py
Fix #2710.
This patch aligns the return value of `get_reconstructed_message` with frontend - the generated messages is returned as ASP and needs to be serialized with the default serializer settings before being used for pretranslated messages coming from TM.
> Properly serialize FTL messages coming from TM

- pontoon/pretranslation/pretranslate.py
Fixes #2690
I think the same approach can be applied to prevent attribute translation as well.
> Only machine translate the part that follows Id in fluent string

- pontoon/pretranslation/tasks.py
The QuerySet to select locales to perform pretranslation for a specific project on selects all locales that have pretranslation enabled for at least one project. This patch fixes that to only select locales that have pretranslation enabled for the given project.
> Fix Pretranslation Locale QuerySet

- translate/src/utils/message/getSimplePreview.test.js
- translate/src/utils/message/getSimplePreview.ts
> Never include empty literals in simple editor view

- translate/public/locale/en-US/translate.ftl
- translate/src/utils/message/getSyntaxType.test.js
- translate/src/utils/message/getSyntaxType.ts
- translate/src/utils/message/serialize.ts
Fixes #2742 
This does three things:
1. Force source view when the message contains an unsupported selector function like `PIATTAFORMA()`.
2. When serialising to Fluent, support all selector functions.
3. When serialisation fails, swallow the error rather than crashing.
It'll still be possible to save a message using `PIATTAFORMA()`, but to fix that we really ought to apply the validation in the backend.
I'll need to rebase #2720 on these changes.
> Do not crash when serialising & limit selector function names

- pontoon/teams/static/js/bugzilla.js
Possibly a regression form jQuery update: Bugs in the Bugs tab are not visible at the moment. This patch fixes that.
> Show bugs in the Bugs tab

- pontoon/base/models.py
- pontoon/base/tests/managers/test_user.py
- pontoon/base/tests/models/test_user.py
- pontoon/contributors/utils.py
- pontoon/contributors/views.py
- pontoon/teams/views.py
This PR returns system users to the Authors filters in translate view.
I've also added a couple of minor tweaks to user role handling.
> Only exclude system users from contributor dashboards and permissions selectors

- pontoon/contributors/templates/contributors/profile.html
On profile page, we have a regression, caused by #2770.
> Show contributor, not current user email

- pontoon/base/models.py
- pontoon/base/tests/managers/test_user.py
- pontoon/contributors/utils.py
- pontoon/contributors/views.py
The default output of `users_with_translations_counts()` is limited to 100 entries. That's because historically we've used this method on contributor dashboards only and didn't want to make the page (load) to big (slow).
Now that we use it in other places, including in pontoon-scripts, it doesn't make sense for the limit to be on by default.
> Default contributors limit

- pontoon/administration/templates/admin_project.html
- pontoon/administration/views.py
Fix #2787.
After you select locales for pretranslation, they are rightfully moved from Available to the Chosen column. After you reload the page, they appear in both columns.
> Exclude locales chosen for pretranslation from available

- translate/src/utils/message/getEmptyMessage.test.js
- translate/src/utils/message/getEmptyMessage.ts
- translate/src/utils/message/getPluralCategories.ts
Fixes #2780
Adds a wrapper around the `new Intl.PluralRules().resolvedOptions()` call that allows for special handling for individual locales, such as `tg`.
> Add special-case plural handling for some locales

- translate/src/index.tsx
Fixes #2764 
It looks like some update in tooling changed the ordering of CSS imports to be depth-first rather than breadth-first.
> Fix CSS import order in index.tsx to maintain expected rule priority

- translate/src/utils/message/getEmptyMessage.test.js
- translate/src/utils/message/getEmptyMessage.ts
- translate/src/utils/message/getPluralCategories.ts
These locales use `other` only for fractions.
> Fix empty message generation for be, pl, ru, uk

- pontoon/base/fluent.py
- pontoon/base/models.py
- pontoon/base/tests/test_fluent.py
- pontoon/pretranslation/pretranslate.py
- pontoon/pretranslation/tests/test_pretranslate.py
- pontoon/teams/templates/teams/team.html
Fix #2734.
For each plural expression, we change plural forms to match those of the target locale.
The code in `fluent.py` is inspired by the ([legacy](https://github.com/mozilla/pontoon/blob/26c5f709ce9ddec66ec214c4ec8db722196ea24c/translate/src/utils/message/getEmptyMessage.ts#L31)) frontend code.
> Pretranslate Fluent plural expression with target locale plural forms

- pontoon/pretranslation/tasks.py
- pontoon/pretranslation/tests/test_tasks.py
Fix #2691.
The patch keeps translations with failed checks stored as Errors in Warnings in Pontoon DB and treats them as such in stats and dashboards, but it doesn't send them to VCS. 
That way Errors and Warnings remain easy to spot, exposing potential further improvements to pretranslation logic, but at the same time no longer break products, which is the core issue we're solving in #2691.
> Do not mark Pretranslated strings with Errors and Warnings as needing sync

- .github/workflows/backend.yml
- .github/workflows/frontend.yml
- .github/workflows/tag-admin.yml
- requirements/default.in
- requirements/default.txt
- requirements/dev.in
- requirements/dev.txt
- requirements/lint.txt
- requirements/test.txt
Tested this locally, seems to work as intended. Did check that no local code appears to depend on `pytoml`, which is here replaced by `toml`.
The `pip-tools` update is necessary for pip 23.1 compatibility.
> Update to compare-locales 9.0.1, fluent-syntax 0.19.0, pip-tools 6.13.0

- pontoon/contributors/utils.py
This is not a final fix for #2289. It fixes a more recent performance regression which made an unnecessary DB request for each user listed in the Contributors panel.
I tested on stage with https://mozilla-pontoon-staging.herokuapp.com/fr/permissions/, which remains very slow, but at least loads now. It did not load in 3 out of 3 attempts before deploying the patch.
> Prefetch user profile data to speed up role detection

- pontoon/sync/core.py
- requirements/default.in
- requirements/default.txt
Fix #2809.
Updating hg.mozilla.org repos is relativelly slow due to network latency. It is particularly slow for projects that use per-locale repos (e.g. Firefox), because there's plenty of them.
To mitigate that, we use Mercurial API to quickly collect latest commit hashes, which allows us to detect repos that needs syncing without actually updating them.
However, this optimization is performed on all hg.mozilla.org repositories, including the single-locale one used by Thunderbird and Seamonkey. That causes all locales to be falsely detected as changed. We should refactor the optimization logic, but for now this patch limits it to multi-locale repositories.
This patch also upgrades the `mercurial` package, which should resolve the `pickle` errors and hopefully a few other things (i.e. …
> Optimize Thunderbird and Seamonkey sync

- docs/admin/deployment.rst
- pontoon/settings/base.py
- pontoon/teams/views.py
We have a `DEFAULT_FROM_EMAIL` variable, but we use a different setting for the FROM email address when requesting locales to be added to projects. There's no need for two different values, really.
Additionally, this patch changes the `noreply` part of the `DEFAULT_FROM_EMAIL` because such addresses canot be verified and because that's [apparently a bad idea in general](https://mailchimp.com/what-to-know-about-using-no-reply-email/).
> Replace LOCALE_REQUEST_FROM_EMAIL with DEFAULT_FROM_EMAIL

- pontoon/base/models.py
- pontoon/contributors/templates/contributors/widgets/contributor_selector_list.html
- pontoon/teams/templates/teams/includes/permissions.html
- pontoon/teams/tests/test_views.py
- pontoon/teams/views.py
This is the first part of fixing the permissions page performance issue tracked in #2289. It removes the ability to assign permissions to any user (not just locale contributors).
It's rarely used feature, but still required. We're dropping it temporarily only, in order to prevent page load timeouts immediately. In the followup patch, we'll restore the feature by loading all users on request rather than on page load.
> Speed up permission page by removing the ability to select among all users

- pontoon/sync/core.py
This patch fixes a bug introduced in #2830, which used logical AND instead of OR:
We shouldn't fetch changed locales using repository API if the API is not configured OR the repository in not a multi-locale repository.
> Fix bad operator introduced in #2830

- translate/src/modules/comments/components/AddComment.css
- translate/src/modules/comments/components/AddComment.tsx
Fixes #2591 
We don't actually need the `/get-users/` data for the rendering of the `@mention`, but we do ultimately need the URL for comment submission. So let's just insert the mention right away, but block submission (with a `cursor: wait` indicator when hovering on the button) until we have the data.
This still doesn't fix the bad API, but it hides its effects further.
> Move contact person @mention delay to comment submission

- pontoon/localizations/templates/localizations/localization.html
- pontoon/localizations/views.py
- pontoon/projects/templates/projects/project.html
- pontoon/projects/views.py
Currently, the page load time of the Firefox dashboard is pretty bad.
In this patch, we speed that up by only loading _Tag count_ (needed in the Tag tab) on page load, rather than _all Tag data_.
The same logic is applied to the localization dashboard, where the impact is less visible.
PROD:
https://pontoon.mozilla.org/projects/firefox/
STAGE:
https://mozilla-pontoon-staging.herokuapp.com/projects/firefox/
> Speed up project dashboard

- pontoon/pretranslation/__init__.py
- pontoon/pretranslation/pretranslate.py
- pontoon/pretranslation/tasks.py
- pontoon/pretranslation/tests/test_tasks.py
Fix #2813.
Before this patch, we skipped pretranslation for strings that have had any kind of translation.
> Also pretranslate strings that only have rejected suggestions submitted by humans

- pontoon/localizations/views.py
- pontoon/projects/views.py
- pontoon/tags/templates/tags/widgets/tag_list.html
Fixes #2280 
This pull request addresses the issue identified with the sorting of tags on the dashboard. Previously, the tags on the dashboard were appearing in an arbitrary order, which made it challenging to quickly identify and address high-priority tags.
This update introduces a sorting mechanism that arranges tags according to their priority, with the highest priority (5-star) tags appearing at the top of the list. This change will allow users to quickly identify and focus on high-priority items.
> Sort tags on dashboard by priority

- pontoon/sync/vcs/repositories.py
Fixes #2306 
This pull request introduces specific handling for a common Git error that occurs during a push operation. The error message is "Updates were rejected because the remote contains work that you do not have locally...".
Previously, when this error occurred, it was difficult to understand the specific cause of the error and to take appropriate action to resolve it.
This change allows for more precise logging and error handling when this Git error occurs.
> Handle specific Git error during push operation 

- translate/public/locale/en-US/translate.ftl
- translate/src/modules/editor/components/EditorSettings.test.js
- translate/src/modules/editor/components/EditorSettings.tsx
Fixes #2848 
This pull request addresses issue #2848, where the "Make Suggestions" setting was visible in the editor menu for contributors, even though it was hidden in their profile settings. 
With this change, the "Make Suggestions" button will only be rendered if the user has translator permissions. If the user does not have translator permissions, the button will not appear.
This ensures a more consistent and less confusing user experience, as the visibility of the "Make Suggestions" setting now correctly reflects the user's permissions.
> Hide "Make Suggestions" for Non-Translators

- pontoon/base/models.py
- pontoon/contributors/templates/contributors/widgets/notifications_menu.html
Addresses #2726 
Previously, the redirection was dependent on whether the 'new string' was present in the user's custom homepage. This check was implemented in both the template and the models. However, this was found to be redundant and led to incorrect redirections because the [translate_locale_agnostic](https://github.com/mozilla/pontoon/blob/master/pontoon/base/views.py#L57) function already handles the redirection based on the user's custom homepage.
This change simplifies the code and ensures that users are correctly redirected when they click on a notification about a new string.
> Correct Redirection for New String Notifications

- docker/Dockerfile
- docker/server_run.sh
I got annoyed always waiting for the 10 second timeout when stopping the dev server. Two things were going wrong, both fixed here:
1. Docker was sending the process its default `SIGTERM` signal, but Django expects `SIGINT`.
2. The `server_run.sh` script was not replacing its process with Django, and not passing on to it any signals.
> Speed up server stop in development

- pontoon/base/static/css/boilerplate.css
- pontoon/base/templates/500.html
We don't need to accommodate ancient browsers, esp. as these cause the following console warning:
> This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.
> Drop `zoom: 1` from CSS clearfix

- pontoon/base/static/css/fonts.css
This is a workaround for google/fonts#6221, which shows up for us in some failed-checks warnings.
I'm tracking the upstream issue and will update the font files once it's properly fixed.
> Workaround for zero-width italic backticks

- pontoon/base/utils.py
- pontoon/sync/formats/xliff.py
- pontoon/sync/tests/formats/test_xliff.py
Fixes #2239 
This Pull Request addresses the issue of missing strings in downloaded XLIFF files.
The problem surfaced when a new string was added to the reference file and subsequently translated. Despite the string being present in the Pontoon interface, it was missing in the downloaded XLIFF file.
This PR fixes the issue by ensuring that all new strings and their corresponding translations are correctly parsed and written into the downloaded XLIFF file. Now, when a user adds a new string to the reference file, translates it, and downloads the translated file, they will find the new string and its translation present as expected.
Details of main changes:
* Rewrote the `XLIFFEntity` and `XLIFFResource` classes
* Adjusted the writing logic in the `save` function to ensure all translations …
> Fix Missing Strings in Downloaded XLIFF Files

- pontoon/base/placeables.py
- pontoon/base/tests/test_placeables.py
- pontoon/machinery/utils.py
- pontoon/pretranslation/pretranslate.py
- pontoon/pretranslation/tasks.py
- pontoon/pretranslation/tests/test_transformer.py
- pontoon/pretranslation/transformer.py
Fixes #2181.
This patch prevents placeables modifications by machine translation. Any placeable found in the input string is stored in the glossary with equivalent translations for all locales supported by Google Translate.
~I [tried to](https://github.com/mozilla/pontoon/pull/2873/commits/8b03a884ca551102e3d92b2643900daca3c2c522) use the glossary only on strings containing errors and warnings, but I [reverted](https://github.com/mozilla/pontoon/pull/2873/commits/1ff9dce6ca4eba7ef4d5b98137c1eb127763b7bd) the commit, because the code looks ugly. A bigger refactor will be needed should we want to proceed with that.~
~Which means, at least for now, any string containing placeables is translated using the glossary. Placeables are detected using the most common parsers taken from …
> Use Glossary to prevent placeables modifications by machine translation

- package-lock.json
- translate/package.json
- translate/src/modules/translationform/components/EditField.tsx
- translate/src/modules/translationform/utils/editFieldExtensions.ts
- translate/src/modules/translationform/utils/editFieldModes.ts
Fixes part of #2180
These use a a CodeMirror 5-style [stream parser](https://codemirror.net/docs/ref/#language.StreamParser) or tokenizer, as that seemed like the easiest solution for the level of complexity we need. As these have a slightly different shape than our other parsers, and as our current regexps are somewhat suboptimal as identified in mozilla/react-content-marker#23, I wrote new ones for use here. Fluent patterns are handled specially, while all others are parsed for printf and Python-style variables. HTML-ish tags are identified in both.
Happy to take instruction on the CSS styles used by the highlighter.
Some examples:
> Add syntax highlighting for placeholders and tags

- pontoon/machinery/static/js/machinery.js
- translate/src/context/MachineryTranslations.tsx
Fixes #2899.
As of yesterday, Microsoft Terminology API seems to be shut down:
https://slator.com/microsoft-kills-off-beloved-language-portal/
Filed #2901 to investigate if we can build a replacement service.
Deployed to stage for testing:
https://mozilla-pontoon-staging.herokuapp.com/machinery/
> Disable Microsoft Terminology service in Machinery

- pontoon/teams/views.py
Views like https://pontoon.mozilla.org/sl/ are broken if the user is not logged in.
> Fix broken team dashboard for non-authenticated users

- requirements/default.in
- requirements/default.txt
This PR updates parsimonious from 0.8.1 to 0.10 that is compatible with Python 3.11.
> Update parsimonious to v0.10

- translate/src/api/entity.ts
- translate/src/context/MachineryTranslations.tsx
Fixes #2823
This was apparently missed out in the original PR #1866. Machinery depends on the `machinery_original` value, which was correctly sent from the backend, but "fixed" to use a key `machineryOriginal` instead.
> Do not enforce camel case on sibling entity object keys

- translate/src/modules/translationform/utils/editFieldExtensions.test.ts
- translate/src/modules/translationform/utils/editFieldExtensions.ts
With the new editor and its syntax highlighting, we can limit the spellcheck to just the literal translatable content of a message, rather than needing to apply it to all of it.
This allows us to e.g. not have a fluent placeholder `{ $tabCount }` get marked as a spelling error by the browser.
This isn't a workaround for [Firefox bug 1837268](https://bugzilla.mozilla.org/show_bug.cgi?id=1837268), though tbf seeing if it were was a part of the reason why I implemented this.
> Only spellcheck string content, not placeholders or html tags

- pontoon/insights/static/js/insights_tab.js
Tooltip labels are missing in the Translation activity (Completion) and Pretranslation quality (Approval rate) charts.
This patch fixes that.
> Restore values in Review activity and Pretranslation quality tooltips

- pontoon/teams/views.py
This patch removes the requirement that only projects that can be requested to be enabled can be requested to be pretranslated. The requirement was included because the code was copied from the project request form.
> Drop can_be_requested flag from the pretranslation project request

- translate/src/utils/message/parseFlatFluent.test.js
- translate/src/utils/message/parseFlatFluent.ts
Fixes #2954
The `parseFlatFuent()` Fluent visitor was not handling terms right, as they're not matched by `visitMessage()`, and need a separate `visitTerm()` method.
> In parseFlatFluent(), also flatten terms

- .github/workflows/backend.yml
- .github/workflows/frontend.yml
- .github/workflows/heroku.yml
- .github/workflows/js-lint.yml
- .github/workflows/py-lint.yml
- .github/workflows/tag-admin.yml
- CONTRIBUTING.rst
- README.md
- docs/admin/deployment.rst
- docs/dev/first-contribution.rst
Closes #2943
When this is merged, the GitHub default branch should also be updated via [settings](https://github.com/mozilla/pontoon/settings); that'll take care of the rest, and prompt later visitors to the repo with update instructions for their clients.
> Update `master` branch references to `main`

- app.json
Fix #2662.
This patch unifies the PostgreSQL version used in deployment with the [Deploy with Heroku button](https://github.com/mozilla/pontoon#installing-pontoon) with the one used in production and stage environment.
> Upgrade Postgres to version 15 in the app.json file

- docs/admin/deployment.rst
- pontoon/settings/base.py
> Update Firefox Accounts references to Mozilla Accounts

- translate/src/modules/translationform/components/EditField.test.tsx
- translate/src/modules/translationform/utils/editFieldExtensions.ts
- translate/src/modules/translationform/utils/editFieldModes.ts
Fixes #2987
Fixes #2988
Pre-empts #2990
The space issue was due to using an incorrect CSS `white-space: pre-line` value for plain text, which was collapsing whitespace and thereby messing up everything: the right value here is `pre-wrap`. I could replicate this locally, but it doesn't show up in tests (which are finally added here for EditField) as that browser feature is not emulated by JSDOM.
The odd editing experience when removing one of the `""` in a tag property value is fixed by making property values also `pre-wrap`, and bailing out of literals on `}` and `>`.
The printf regexp is updated as discussed in the issue.
I also included some improvements here for how paired syntax characters like `{}` and `""` are handled. The matching pair highlighting is dropped, as that's a bit too …
> Editor fixes: preserve whitespace, exclude ` ` as a printf conversion flag, match brackets better

- pontoon/translations/forms.py
Fix #2991.
We use CharFields for validating original strings and translations when translations are being saved.
By default, CharField [strips the value of the leading and trailing whitespace](https://docs.djangoproject.com/en/4.2/ref/forms/fields/#django.forms.CharField).
Until now, we've been only bypassing this default for translations. 
From now on, we also do that for original strings.
Deployed to stage for testing:
https://mozilla-pontoon-staging.herokuapp.com/fi/all-projects/all-resources/?string=192448
> Fix validation of strings with leading and trailing newlines

- translate/src/modules/user/components/UserMenu.css
Forgot to push this commit in #2997.
Hence the borders in the Theme Toggle in the Translate View are currently missing:
https://mozilla-pontoon-staging.herokuapp.com/sl/firefox/all-resources/
> Sync theme toggle CSS between /translate and /pontoon

- pontoon/base/static/js/theme-switcher.js
- pontoon/base/templates/base.html
- pontoon/base/templatetags/helpers.py
- translate/public/translate.html
- translate/src/context/Theme.tsx
- translate/src/hooks/useTheme.ts
When system theme is selected, we apply the right theme in the client, because system settings can only be accessed from the client. That results in FOUT (flash of unstyled text) when navigating between pages if the system theme is Light, because Pontoon defaults to the dark theme and then immediatelly changes it to light when the JS executed.
This patch prevents that by storing the system theme setting in a cookie. Cookie is read by the server, so we set the theme accordingly already in a template.
Deployed to https://mozilla-pontoon-staging.herokuapp.com/.
> Prevent FOUT when using System Theme

- pontoon/insights/static/js/insights.js
Touch #2981.
With this improvement, the tooltip changes position based on the mouse position, so it can be made visible for all data points. It's still not always visible, though.
> Improve position of the tooltip of the charts on the /insights page

- pontoon/base/templates/robots.txt
- pontoon/insights/admin.py
- pontoon/insights/utils.py
- pontoon/insights/views.py
Several Insights pages improvements are included in this PR:
* Fix #2980: Prevent bots from checking the /insights page
* Optimize ProjectLocaleInsightsSnapshot Admin view/editing page 
* Refactor data gathering for the /insights page:
1. Fix https://github.com/mozilla/pontoon/issues/2979: Optimize /insights page. To render the charts on the Insights pages, we use periodically gathered ProjectLocaleInsightsSnapshot data. That works fine on Project, Locale and ProjectLocale pages, but not on the /insights page which shows data across the entire app. The amount of data requested from the DB quickly becomes big and the request starts timing out. In this patch, we gather data directly from the ActionLog as hinted at in https://github.com/mozilla/pontoon/issues/2938.
2. Fix …
> Optimize and fix the /insights page

- pontoon/checks/libraries/compare_locales.py
- pontoon/checks/tests/test_compare_locales.py
- pontoon/sync/formats/__init__.py
- pontoon/sync/formats/compare_locales.py
- pontoon/sync/formats/xml.py
- pontoon/sync/tests/formats/test_formats.py
- pontoon/sync/tests/formats/test_xml.py
- pontoon/sync/utils.py
Fix #2212 using the approach identified in https://github.com/mozilla/pontoon/issues/2212#issuecomment-918455079: straight apostrophes in strings.xml files are escaped on export serialization and unescaped on import parsing.
In return, users can now submit strings with straight apostrophes without the need to manually escape them. They are stored in the DB and displayed in the UI without any escaping.
We should unescape straight apostrophes in existing translations and TM entries.
I've also added an example string to our test project:
https://github.com/mozilla-l10n/pontoon-test/blob/master/en-US/strings.xml#L9
> Escape straight apostrophes in strings.xml files

- translate/src/modules/notification/components/NotificationPanel.tsx
Fix #3011.
During the development of the light theme, I needed the notification popup to be shown for a longer period than just 2 seconds. And I committed that change by mistake. 🤦 
https://github.com/mozilla/pontoon/commit/b97cbb7fc2cec6731680476f880ec643ab4831ec#diff-c0aa89be6ec58edea23eb616736c9bdf130d5ce3063749733db72e24c020e8c0R28
> Restore notification panel delay back to 2 seconds

- pontoon/base/models.py
- pontoon/base/tests/models/test_user.py
Fix #3035.
Fix locale_role logic to check if the user is a manager or translator before checking if it's an admin.
> List Admins that are also Locale Managers or Translators as members of these groups in the Locale Contributors page

- translate/src/modules/entitieslist/components/EntitiesList.tsx
Fix #3053.
Always use Hooks at the top level of your React function:
https://legacy.reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level
> Fix broken translate view when filters result in no matches

- translate/src/modules/entitydetails/components/Helpers.tsx
Fix #3050.
[Factoring out](https://github.com/mozilla/pontoon/commit/2f613fa74df1b04eda90bead914a2cf77faf5a0e#diff-8450f0b6e89e6e5f13e7d05d29af46988b50a0afdd034b548075dc6f8209f7a7) the `TeamComments` component broke the ability to insert the contact person via Request Context button.
> Fix Request Context button Contact person mention

- translate/src/App.css
Fix #3052.
It turns out the CSS property removed in cc7d3503db342958d225029e5521c2e847986eed was not so unused afterall.
> Restore Translate view full height

- pontoon/localizations/tests/test_views.py
- pontoon/localizations/views.py
Fixes #2338 
This PR addresses an inconsistency in our AJAX views regarding the checks for the existence and visibility of `Locale` and `Project`, as well as the existence of `ProjectLocale`. Previously, `ajax_resources` and `ajax_tags` only checked for the `Locale` and `Project`, while `ajax_contributors` and `ajax_insights` checked for the `ProjectLocale`. This update ensures that all these views consistently perform both sets of checks.
> Uniform Checks for Locale, Project, and ProjectLocale in AJAX Views

- pontoon/pretranslation/tasks.py
Fix #3073.
We currently retrieve pretranslations for each locale separately, and store them all at once with a single DB query (for all locales). That makes our DB performance a little bit better, but risks the need for additional retrieval of already retrieved pretranslations in case of an error during processing of one of the locales.
Since retrieving pretranslations is significantly slower than writing them to the DB, we should write to DB for each locale separately, right after pretranslations are retrieved.
> Store pretranslations for each locale separately

- pontoon/pretranslation/pretranslate.py
- pontoon/pretranslation/tests/test_pretranslate.py
After Fluent pretranslations are created, we need to parse and serialize them again in order to make sure they are stored in the canonical form (e.g. with spaces within curly braces).
Fix #3072.
> Properly serialize Fluent placeables generated by Pretranslation

- pontoon/contributors/tests/test_views.py
- pontoon/contributors/urls.py
- pontoon/localizations/urls.py
- pontoon/projects/tests/test_views.py
- pontoon/projects/urls.py
- pontoon/settings/base.py
- pontoon/teams/tests/test_views.py
- pontoon/teams/urls.py
This patch caches all Contributors views for a period of 1 day:
- /contributors
- /LOCALE/contributors
- /projects/PROJECT/contributors
- /PROJECT/LOCALE/contributors
It mostly fixes #3082, but I'll keep the issue open until I check if there's something we can do to speed up the Authors and Time Range filters.
If this works well, we should cache the Insights views.
The patch is deployed to stage.
> Cache contributors views

- pontoon/insights/urls.py
- pontoon/localizations/urls.py
- pontoon/projects/urls.py
- pontoon/teams/urls.py
Fix #3094.
This is very similar to https://github.com/mozilla/pontoon/pull/3091, but for Insights rather than Contributors views.
> Cache insights views

- pontoon/administration/views.py
- pontoon/base/models.py
- pontoon/projects/views.py
- pontoon/teams/views.py
Fix #3102.
Prefetch `latest_translation__approved_user` to speed up dashboards by retrieving Latest Activity data with less DB requests.
> Prefetch latest_translation__approved_user

- pontoon/dev/utils.py
Fix #3114.
This is an old script for quick SQL performance debugging:
https://github.com/mozilla-l10n/pontoon-scripts/blob/main/dev/debug_sql_performance.py
It's easier to use when integrated into Pontoon directly.
> Introduce dev utils, add debug_sql()

- pontoon/tags/tests/test_views.py
- pontoon/tags/utils.py
> 404 if tags don't have resources assigned

- .eslintrc.js
- pontoon/administration/static/js/admin_project.js
- pontoon/base/static/js/double_list_selector.js
- pontoon/base/static/js/main.js
- pontoon/base/static/js/progress-chart.js
- pontoon/base/static/js/table.js
- pontoon/base/static/js/tabs.js
- pontoon/base/static/js/theme-switcher.js
- pontoon/contributors/static/js/notifications.js
- pontoon/contributors/static/js/profile.js
- pontoon/contributors/static/js/settings.js
- pontoon/insights/static/js/insights.js
- pontoon/insights/static/js/insights_charts.js
- pontoon/insights/static/js/insights_tab.js
- pontoon/machinery/static/js/machinery.js
- pontoon/projects/static/js/manual_notifications.js
- pontoon/teams/static/js/bugzilla.js
- pontoon/teams/static/js/info.js
- pontoon/teams/static/js/multiple_team_selector.js
- pontoon/teams/static/js/permissions.js
- pontoon/teams/static/js/request.js
Fix https://github.com/mozilla/pontoon/issues/2931.
Introduces two new ESLint rules (with their default options supplied) to be enforced when linting:
- `no-var`
- `prefer-const`
Additionally, fixes the ~230 issues raised by these two new rules when linting against the "pontoon/" subdirectory when running the `make eslint` command.
> Fix #2931 - New ESLint Rules & Fixes

- pontoon/contributors/tests/test_views.py
- pontoon/contributors/urls.py
- pontoon/contributors/views.py
- pontoon/insights/urls.py
- pontoon/insights/views.py
- pontoon/localizations/urls.py
- pontoon/projects/tests/test_views.py
- pontoon/projects/urls.py
- pontoon/teams/tests/test_views.py
- pontoon/teams/urls.py
> Avoid caching page headers

- pontoon/base/models.py
- pontoon/base/views.py
Currently, the main DB query to load entities in the entity list is executed twice if the `string` parameter is provided in the URL. That's particularly bad, because that query is often very slow (see #2965).
This patch drops that redundant DB query and reorganizes the code to prefetch data.
> Only make one DB query when string param provided in URL

- pontoon/base/models.py
PEP-257 describes how you can use docstrings for attributes. They come *after* the attribute: https://stackoverflow.com/questions/3051241/how-to-document-class-attributes-in-python/69754746#69754746
> Fix Resource.order docstring

- pontoon/base/forms.py
- pontoon/base/models.py
- pontoon/base/tests/views/test_entity.py
- pontoon/base/views.py
- translate/src/api/entity.ts
- translate/src/modules/entities/actions.ts
- translate/src/modules/entities/reducer.ts
- translate/src/modules/entitieslist/components/EntitiesList.test.js
- translate/src/modules/entitieslist/components/EntitiesList.tsx
Fix #2522.
We currently use a weird way of paginating entities - in each request we include a list of already loaded entities, which we exclude from the matching entities in Django and then return the first page of the remaining entities.
This is a relic of the react-infinite-scroller library which we no longer use.
We should implement proper paging, i.e. drop exclude_entities and only return the relevant page.
That should also speed up loading of entities, because NOT IN DB queries tend to be slow and because less data will be transferred.
> Use proper paging for entities

- .readthedocs.yaml
Fix #3137.
Just adding a default configuration file, which is now required for the docs build to succeed:
https://docs.readthedocs.io/en/stable/config-file/v2.html#id1
I've uncommented the python reqs.
> Add .readthedocs.yaml configuration file

- docs/index.rst
Per discussion in https://github.com/mozilla/pontoon/issues/2135#issuecomment-1910356465, make it clearer that there are actually two different external subsites containing pontoon documentation. This wasn't clear to me from the docs.
Relates to #2214
> Update index.rst to explicitly link to the mozilla-l10n sites

- pontoon/base/models.py
- pontoon/contributors/static/js/notifications.js
- pontoon/contributors/templates/contributors/includes/notifications_remaining.html
- pontoon/contributors/templates/contributors/notifications.html
- pontoon/contributors/urls.py
- pontoon/contributors/views.py
Fix #2278.
The patch comes in 2 parts:
Part 1 improves performance by significantly reducing the number of DB calls through prefetching related data.
Part 2 improves perceived performance by only loading the first 100 notifications initially. Any remaining notifications are loaded afterwards via AJAX. That makes the page usable much faster, and by the time the user scrolls to the bottom of the page, the remaining notifications are likely to be loaded already.
> Speed up /notifications page

- pontoon/machinery/views.py
[This test](https://github.com/mozilla/pontoon/blob/0c7943f7afe8f86d16a5d4313276958aff71e6ec/pontoon/machinery/tests/test_views.py#L379) consistently fails on my machine, as the returned project_names array is `['Project B', 'Project A']` rather than the expected `['Project A', 'Project B']`.
Adding the "name" column as the third sorting criterion makes the results consistent.
> Include "name" column in concordance search result sorting order

- pontoon/base/migrations/0058_remove_tr_tr_collation.py
Fixes #3165 
This is a prerequisite to being able to simplify our dev env postgres container.
Because we currently include a
```sql
CREATE COLLATION tr_tr (LOCALE = 'tr_TR.utf8');
```
command in our database initialization, it means that the results of a `pg_dump` or `pg_upgrade` will include that as well, and that means that any environment where the data is restored is expected to include a `tr_TR.utf8` locale, which is itself non-standard. In other words, migrating dev environment data to a not-custom postgres instance is a pain.
So let's drop the collation, and wherever it's used, switch to `tr-x-icu` instead.
This also needs to be a SQL migration, because it's touching stuff that's not accessible via Django.
> Drop the custom tr_tr collation

- docs/admin/deployment.rst
- pontoon/base/management/commands/warmup_cache.py
Fix #3155.
We cache data for some of the views (e.g. Contributors) for a day. Some of them don't get a lot of visits, not even one per day, meaning that the visitors of these pages often hit the cold cache.
This command refreshes data in the cache every day, because it changes often. The command is designed to run daily.
_Deployed to stage._
> Keep cache warm

- docker-compose.yml
- docker/postgres/Dockerfile
- docker/postgres/docker-entrypoint-initdb.d/collations.sql
This drops the custom postgres dev container build originally introduced in #866 in favour of using the upstream `postgres` image directly. While at it, let's also update to v15.
This change should not be applied until #3169 has landed, and anyone who cares has had an opportunity to apply its migration, so that the `pg_upgrade` or `pg_dump`/`pg_restore` this PR necessitates applies cleanly.
> Use postgres:15 instead of custom postgres:13.4 build for dev env

- pontoon/base/templates/tracker.html
- pontoon/settings/base.py
Fix #3080.
Upgrade tracker code for Google Analytics 4. Also update corresponding [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) settings.
> Upgrade tracker code for Google Analytics 4

- pontoon/settings/base.py
@ayanaar I missed this one, because it's async and the error appears with a delay.
> Fix CSP due to Google Analytics upgrade

- pontoon/localizations/urls.py
- pontoon/localizations/views.py
- pontoon/projects/urls.py
- pontoon/projects/views.py
- pontoon/teams/urls.py
- pontoon/teams/views.py
By using low-level cache API we makes it explicit what exactly is cached and what cache key is used.
> Replace cache_page with low-level cache API calls

- pontoon/translate/views.py
- translate/public/translate.html
- translate/src/context/MachineryTranslations.tsx
Translate view makes requests to Google Translate and Microsoft Translator backend code even if API keys are not set. While the requests to external services are not made in this case, we should still prevent the redundant call to Pontoon backend.
> Do not make requests to non-configured Machinery services

- pontoon/sync/tests/test_vcs.py
- pontoon/sync/vcs/repositories.py
Fixes #3178 
Tested manually by setting the data to be invalid in a local install:
```sql
update base_repository set last_synced_revisions = '{"single_locale": "foobar"}' where id = ...;
```
> During sync, fall back to reporting all files as changed if the hg/git/svn cli command fails

- docker-compose.yml
This removes the following warning on `make run`:
> WARN[0000] ~/pontoon/docker-compose.yml: `version` is obsolete
> Drop version from docker-compose.yml, because it is obsolete

- pontoon/localizations/tests/test_views.py
As I'm running Pontoon locally on my M1 Macbook without Docker, it appears that the paths `has/stats.po` and `has/stats2.po` are sorted differently than they are in the test environments, and so end up in a different order in the GET results.
Let's use `has/stats1.po` and `has/stats2.po`, as they're more predictably ordered.
> Use more dependable file names in pontoon.localizations test

- translate/src/modules/comments/components/Comment.css
Fix #2400
Added the CSS changes proposed by @safaalfulaij (thank you!) to comments in Pontoon. In particular, directionality for comments is set to "plaintext" to treat it as simple text. Directionality for mentions is separated from the rest of the comment content, ensuring that Arabic and Hebrew nicknames maintain their directionality. To improve comment readability, the proposed change to move all comment content to a newline after the author's name was added.
**To reproduce results**: Populate your database as in [step 3 here](https://mozilla-pontoon.readthedocs.io/en/latest/dev/first-contribution.html). Create a superuser account, and set the nickname to be in either Arabic or Hebrew. Create a mock translation for one of the strings in a locale. Create another superuser account, and …
> Fixed commenting bug for right-to-left languages

- pontoon/localizations/templates/localizations/includes/tags.html
- pontoon/projects/templates/projects/includes/tags.html
Fix #3105
Added a search field for Tags in both the Localization and Project dashboards. Reused same component structure and styling as the search field in the Resources/Teams tab located in the Localization/Project dashboards respectively.
**To reproduce results:** First, you will need to download a database dump that includes the "Firefox" and "Mozilla.org" projects. Load the database dump as described [here](https://mozilla-pontoon.readthedocs.io/en/latest/dev/contributing.html#database). Next, create a new superuser account using `make setup`. Run the webapp and locate either the "Firefox" or "Mozilla.org" projects in either the Teams>Language>Projects tab or directly through the Projects tab at the top of the Pontoon website header. Finally, click on the Tags tab to view the new …
> Added Tags search field to both Project and Localization dashboards

- translate/public/locale/en-US/translate.ftl
- translate/src/modules/interactivetour/components/InteractiveTour.tsx
Fix #3223.
@bcolsson Could you please test on [stage](https://mozilla-pontoon-staging.herokuapp.com/projects/tutorial/playground/) if everything works as expected? I changed the wording slightly to match the /settings.
> Add new tour card for email communications

- translate/src/modules/editor/hooks/useSendTranslation.ts
- translate/src/modules/machinery/components/MachineryTranslation.tsx
**Fixes #3228 and #3204**
**Issue #3228:**
This PR addresses the problem where machinery sources were not being attributed correctly for any Fluent (FTL) strings. Previously, no sources were identified, leading to incorrect attribution. With this fix, sources are now accurately identified and attributed for Fluent files, ensuring correct tracking and reporting of translation sources.
**Issue #3204:**
This PR also fixes the issue where LLM translations (`gpt-transform`) were incorrectly attributed to Google Translate. This has been corrected, ensuring that LLM translations are now properly attributed as a machinery source, allowing for accurate logging and monitoring of this feature's usage.
> Fix attribution issues for Fluent sources and LLM translations

- translate/src/modules/comments/components/AddComment.tsx
Fix #2840 
Fixed styling bug for comments, in which there was no automatic space appended after mentioning a user using `@[name]`. The bug was resolved by explicitly setting the cursor to the end of the editor's content, thereby ensuring that the space was added in the correct location within the editor.
To reproduce results: After starting up the server, navigate to any translated string within any team/project. Then, click the "COMMENT" button on that string, and type "@[any letter]" to bring up a list of users to mention in your comment. Choose any user using either your cursor or the arrow keys + tab, then type the rest of your comment. There should be a space automatically added after the mention, before the content of your comment.
> Fixed spacing bug after mentions in comments

- pontoon/base/views.py
- translate/src/api/user.ts
- translate/src/modules/comments/components/AddComment.tsx
Fix #2625 
Added functionality for mentioning users by typing their username instead of only by display name. This feature was achieved by modifying the `/get-users/` API to return the usernames of all UserProfile objects in addition to the preexisting fields. The suggestedUsers filter function was modified to first check for a matching username (if it exists), then checking for a matching display name.
**To reproduce results**: After starting up the server, navigate to any team/project. Select any string that has an existing translation. Click the "COMMENT" button, and then inside the text editor field, type `@[any string of letters]` to display a list of users whose display name or username contains that string of letters. If you know a specific user's username, try typing their full …
> Added capability to mention users by username

- pontoon/administration/views.py
- pontoon/base/migrations/0065_fix_projectlocale_permissions.py
> Revert using bulk_create for new projectlocales

- translate/public/locale/en-US/translate.ftl
- translate/src/modules/history/components/HistoryTranslation.tsx
Fix #2763 
Added a `reviewedDate` field to the tooltip when hovering over rejected or approved strings.
**To reproduce results**: After starting the server, navigate to any team/project (e.g. `http://localhost:8000/sq/facebook-container/messages.json/?string=196694` ). Hover over the User Avatar or Username to show the tooltip. The tooltip should now display `[Approved/Rejected] by { $user } on { $reviewedDate }` or `[Approved/Rejected] on { $reviewedDate }`
> Add reviewed time information to reviewed strings tooltip

- pontoon/base/static/css/check-box.css
- pontoon/base/static/css/style.css
- pontoon/base/static/js/main.js
- pontoon/contributors/static/css/settings.css
- pontoon/messaging/forms.py
- pontoon/messaging/static/css/messaging.css
- pontoon/messaging/static/js/messaging.js
- pontoon/messaging/templates/messaging/messaging.html
- pontoon/messaging/urls.py
- pontoon/messaging/utils.py
- pontoon/messaging/views.py
- pontoon/settings/base.py
- requirements/default.in
- requirements/default.txt
Fix #3243.
Fix #2072.
This is the first part of the implementation of the Messaging Center. It allows for sending emails and in-app notifications from `/messaging/`. Locally emails are sent to stdout.
Note that until we implement recipient filters (#3244), the recipient of the messages is the sender.
While the development is in progress, the page is not linked from the UI.
Also included:
- Factor out check-box CSS
- Make .notification selectors in style.css and main.js more specific
> Add ability to send emails and notifications from the Messaging Center

- translate/src/modules/machinery/components/MachineryTranslation.tsx
- translate/src/modules/machinery/components/source/GoogleTranslation.tsx
Fix #3269 
Updated user action logging by adding locale name and locale code when an LLM translation is copied. Additionally, updated the logging for dropdown selections to record the locale code instead of the locale name for the selected option.
> Enhance user action logging

- pontoon/insights/static/js/insights.js
- pontoon/insights/utils.py
Fixes #3276 
Fixed the bug on the [Insights page](https://pontoon.mozilla.org/insights/) where the graph shown was not a [function](https://en.wikipedia.org/wiki/Vertical_line_test) (i.e. line graph would jump back and forth horizontally). 
The issue seemed to be that the dates being passed through `chart.data('dates')` were not chronologically ordered by default.
Before:
After:
> Sorted date labels for insights chart

- .gitignore
- docker/config/server.env.template
- docs/admin/deployment.rst
- pontoon/settings/base.py
Fix #3192 
- Added rotating file handlers for Django and Pontoon loggers
- Console logging now uses verbose format in DEBUG mode
- Improved log formatting for clarity and consistency
- added *.log  in .gitignore to prevent log files from being pushed
> Update logging configuration for better debug and error tracking

- pontoon/contributors/tests/test_utils.py
- pontoon/contributors/utils.py
This PR fixes the existing bug with `test_get_contribution_timeline_data_with_actions` that occurs on the first day of the month (e.g. August 1st, September 1st, etc).
The `test_get_contribution_timeline_data_with_actions` test case inside of `contributors/tests/test_utils.py` was failing on the first of the first day of each month since actions are grouped by the month they are created in. The `yesterdays_action_user_a` variable was setting the `action.created_at` to be the last day of the previous month, so the contribution timeline data was returning an empty object.
I've also manually set the start date of the query to be midnight, to ensure that all actions within a month are captured, regardless of the time they were created.
> Fix failing test case in contributors/tests/test_utils.py

- pontoon/base/templates/tracker.html
This change should increase the Observatory score from 85 to 105.
https://developer.mozilla.org/en-US/observatory/analyze?host=pontoon.mozilla.org
https://developer.mozilla.org/en-US/observatory/analyze?host=mozilla-pontoon-staging.herokuapp.com
> Add Subresource Integrity (SRI) to an external script

- pontoon/machinery/openai_service.py
Fixes #3232 
This pull request enhances the translation process by explicitly instructing the LLM to preserve all HTML tags in the translated text. The following changes were made:
- Added a guideline to preserve all HTML tags in the system message prompts for "informal," "formal," and "rephrased" translation styles.
These changes will help maintain the integrity of the original HTML structure in the translated output, addressing issues where tags like `<small>` and `<p>` were sometimes lost.
- Verified that HTML tags are now consistently retained in translations across different characteristics ("informal," "formal," "rephrased").
- Try these strings as an example for testing: [String 1](https://pontoon.mozilla.org/it/thunderbirdnet/LC_MESSAGES/messages.po/?string=281728) and [String …
> Ensure Preservation of HTML Tags in LLM-Generated Translations

- translate/src/context/TranslationContext.tsx
- translate/src/modules/machinery/components/MachineryTranslation.tsx
- translate/src/modules/machinery/components/source/GoogleTranslation.tsx
- translate/src/modules/translationform/utils/editFieldShortcuts.ts
Fully fixes #3204 
This PR includes the following changes:
- **Refactored the LLM hook**: The LLM hook (`useLLMTranslation`) was refactored to return a function that is called outside of the callback. This change was made to address issues with the `useHandleCtrlShiftArrow` function, which previously caused the keyboard shortcut to stop functioning correctly after an LLM translation was generated. 
- **Added UX logging**: Implemented UX logging for when LLM translations are copied into the editor using the keyboard shortcut. This helps track the adoption and usage of the LLM translation feature.
- The keyboard shortcut now works as expected for LLM translations and other translations, including when an LLM translation is selected from the dropdown.
As discussed with @eemeli, there is a …
> Implement UX Logging and Fix LLM Translation Shortcut Functionality

- pontoon/actionlog/admin.py
- pontoon/base/admin.py
- pontoon/checks/admin.py
- pontoon/sync/admin.py
- pontoon/terminology/admin.py
Speed up Django Admin New and Edit pages by introducing `autocomplete_fields` for fields with a lot of entries. 
All `raw_id_fields` are also replaced with `autocomplete_fields` for an improved usability.
Deployed to stage. You can compare for example the loading times of the following URLs:
https://mozilla-pontoon-staging.herokuapp.com/a/actionlog/actionlog/4742759/change/
https://pontoon.mozilla.org/a/actionlog/actionlog/4742759/change/
> Speed up Django Admin Edit and New and views

- pontoon/contributors/tests/test_utils.py
The timeline test is failing again:
https://github.com/mozilla/pontoon/actions/runs/10656042532/job/29534242752
See #3294 for the original attempt to fix it.
Sorry for not noticing this during the code review!
> Properly fix failing timeline test

- docs/admin/deployment.rst
- pontoon/base/middleware.py
- pontoon/settings/base.py
IP Ranges can be defined with the CIDR notation (e.g. 192.168.1.0/24).
Fixes #3304
> Allow IP ranges in BLOCKED_IPS setting

- pontoon/base/forms.py
- pontoon/base/models/entity.py
- pontoon/base/views.py
- translate/src/api/entity.ts
- translate/src/context/Location.tsx
- translate/src/modules/search/components/SearchBox.tsx
- translate/src/modules/search/constants.ts
Fix #3226 
Added a filter to expand a user's search to include rejected translations. Currently, by default, rejected translations are included in the QuerySet returned after a search. This feature will remove that default behaviour to only search in approved translations, and if the filter is set, then rejected translations are included in the QuerySet as well.
**To reproduce results**: 
Head to any string within the translate view upon running the server. Ensure that the string has an approved translation, as well as a rejected translation. Find the difference between the two strings, then enter that within the Search Box input. The left side column will show no results, as long as the searched string does not appear in any other **approved** translation.
Then, click on the magnifying …
> Implement filter for searching in rejected translations

- pontoon/base/forms.py
- pontoon/base/models/entity.py
- pontoon/base/views.py
- translate/src/api/entity.ts
- translate/src/context/Location.tsx
- translate/src/modules/placeable/components/Highlight.tsx
- translate/src/modules/search/components/SearchBox.tsx
- translate/src/modules/search/components/SearchPanel.tsx
- translate/src/modules/search/constants.ts
Fix #3224 
Added a search filter for matching exact casing. Currently, by default, searches are case insensitive (e.g. `Foo` and `foo` would both appear when searching for `Foo`). This feature retains the default behaviour, but adds the option to strictly match casing between the search term and matches.
**To reproduce results**:
Head to any string within the translate view upon running the server. Ensure that the string appears at least twice in the string list (left-side column), once with an uppercase letter and once with all lowercase letters.
Then, click on the magnifying glass icon on the right side of the search box. Click on the `Match case` option to toggle the filter, then click the APPLY SEARCH OPTIONS button. The results shown on the left column will now only include instances …
> Implement search filter for matching case

- pontoon/base/models/entity.py
- translate/src/modules/search/components/SearchPanel.css
Currently in production, if both `Match case` and `Translations only` are active Search Options, then no results will be displayed, no matter what the search term is
Before: https://pontoon.mozilla.org/fr/facebook-container/messages.json/?search=Facebook&search_translations_only=true&search_match_case=true
After: http://localhost:8000/fr/facebook-container/messages.json/?search=Facebook&search_translations_only=true&search_match_case=true
This PR fixes that bug, and also adjusts the placement of the Search Options panel to display under the magnifying glass icon.
The bug was fixed by removing the second parameter (`locale.db_collation`) from the query when `search_match_case` is set to true.
> Fix bug when Match Case and Translations Only filter were active

- pontoon/base/models/entity.py
Fix #3321
Simplifying the query creation seemed to cause an issue with the casing Search Option. 
To fix the issue, I simply added a bracket around the conditional query in `translation_filters`, which corrects the variable scope and produces the correct QuerySet.
Before:
After (Note: the three unhighlighted results are from #3284):
> Fixed variable scoping in Match case query

- pontoon/base/forms.py
- pontoon/base/models/entity.py
- pontoon/base/views.py
- translate/src/api/entity.ts
- translate/src/context/Location.tsx
- translate/src/modules/placeable/components/Highlight.tsx
- translate/src/modules/search/components/SearchBox.tsx
- translate/src/modules/search/constants.ts
Fix #3225 
Added a filter to only return search results that are an exact match to the search term (case insensitive). Currently, searing for "cookie" would also return results that contain "cookies". Now, if the filter is activated, only results that exactly match "cookie".
**To reproduce results:**
Head to any string within the translate view upon running the server. Ensure the string has both a singular and plural version present in the resource (e.g. cookie and cookies). Search for the singular version using the search box on the left side, and observe how both the singular and plural versions appear in the string list (left side column).
Then, click on the magnifying glass icon on the right side of the search box. Click on the `Match whole words` option to toggle the filter, then …
> Implement filter for matching whole words

- translate/src/modules/placeable/components/Highlight.test.js
- translate/src/modules/placeable/components/Highlight.tsx
fixes #3327 
[i18next](https://www.i18next.com/) uses `{{var}}` for it's [interpolations](https://www.i18next.com/translation-function/interpolation). The placeholder matching wasn't recognizing the 2nd closing bracket.
This has been fixed by adjusting the curly regex to `{(?:(?:"[^"]*")|[^}])*}}?` (as discussed in the chat)
<sub>https://regex101.com/r/ttFTUE/2</sub>
Additionally I've added test cases to cover this for the future
> Double curly-brackets placeholders

- translate/src/modules/search/components/SearchPanel.css
The search panel could get cut-off on the left side on screen narrower than ~1400 px.
> Make search panel visible on all screen widths

- pontoon/base/static/css/check-box.css
- pontoon/base/static/css/style.css
- pontoon/contributors/static/css/settings.css
- pontoon/messaging/forms.py
- pontoon/messaging/static/css/messaging.css
- pontoon/messaging/static/js/messaging.js
- pontoon/messaging/templates/messaging/messaging.html
- pontoon/messaging/views.py
Fix #3244.
This is a continuation of what was started in #3314. It implements the remaining bits of the Compose screen in the Messaging Center, namely Activity filters. As mentioned in #l10n-team last Friday, Activity filters are always visible, which is not what the spec says, but it’s simpler from the UX and codebase point of view.
The diff looks bigger than the changes actually are because of a dedent in [Remove redundand condition](https://github.com/mozilla/pontoon/commit/0c6c645750a936719e6aeea3c2b2d0918137f369) and formatting of the HTML file in [Update check-box and messaging styling](https://github.com/mozilla/pontoon/commit/1203f69feaaf03bf2033434f4109e502d9a78ade). Hence, I suggest reviewing commit by commit. …
> Add ability to filter message recipients by activity

- pontoon/base/models/entity.py
- translate/src/modules/search/components/SearchPanel.css
- translate/src/modules/search/constants.ts
Fix #3284 
This PR adds additional regex to the `entity_filters` and `translation_filters` objects to solve the `.ftl` bug stemming from how Fluent translations are stored in the backend. As such, the `exclude_identifiers` filter has been re-enabled (See #3221).
**To reproduce results**: observe how for any fluent file, the Entity.string has the format of `{key} = {value}`. 
Now, [this query](http://localhost:8000/it/firefox/browser/branding/official/brand.ftl/?search=brand) will produce no results, since "brand" is only contained within the key of each Entity. Once the `exclude_identifiers` [filter is set](http://localhost:8000/it/firefox/browser/branding/official/brand.ftl/?search=brand&search_identifiers=true&string=192265), then all the keys containing "brand" will be displayed.
> Add regex to solve .ftl search bug

- pontoon/base/models/entity.py
Fix #3333 
Currently, Pontoon search fails if any search term contains a special character that's used in a regex pattern.
This PR surrounds all search terms with `re.escape`, which makes sure that any combination of special characters are included in the search term rather than affecting the preexisting regex pattern.
For example, this query will now work as intended: http://localhost:8000/it/sumo/all-resources/?search=%24moco_link&search_rejected_translations=true&string=222592
Additionally, the server error previously caused by this query is now fixed: http://localhost:8000/it/sumo/all-resources/?search=%28moco_link&string=222592
> Fix Pontoon search for terms with special characters

- translate/src/modules/translationform/utils/editFieldExtensions.test.ts
- translate/src/modules/translationform/utils/editFieldModes.ts
I've added highlighting support for the i18next interpolation format to the `common` mode of editFieldModes.
~~It's a quite extensive regex as there is quite some stuff you can do inside a i18next interpolation:~~
<sub>Thank you @eemeli for simplifying it</sub>
```
/{{.*?}}/
```
https://regex101.com/r/gokJ09/1
> Add i18next format support to editFieldModes

- pontoon/base/models/entity.py
Fix #3344 
This PR adds the `search_identifers` query to `translation_filters`, effectively allowing users to search for keys regardless of if they include source strings in their search.
Before, toggling the `Search in translations only` filter would only search within the `Translation.string` field, meaning that a user could not exclude source strings and still search within both the `key` and `Translation.string` fields.
From the filed issue, these two queries now produce the same results, as intended:
http://localhost:8000//it/firefox-for-android/all-resources/?search=mozac_browser_errorpages_redirect_loop_message&search_identifiers=true&string=196837
http://localhost:8000/it/firefox-for-android/all-resources/?search=mozac_browser_errorpages_redirect_loop_message&search_identifiers=tru …
> Add ability to search for keys within translations only

- pontoon/base/forms.py
- pontoon/base/models/entity.py
- pontoon/base/views.py
- translate/src/api/entity.ts
- translate/src/context/Location.tsx
- translate/src/modules/entitieslist/components/Entity.tsx
- translate/src/modules/search/components/SearchBox.tsx
- translate/src/modules/search/components/SearchPanel.css
- translate/src/modules/search/components/SearchPanel.tsx
- translate/src/modules/search/constants.ts
Fix #3345 
As per the discussion in the related issue, this PR renames the following in `translate/src/modules/search/constants.ts`:
- `search_translations_only` --> `search_exclude_source_strings`
- `Search in translations only` --> `Exclude source strings`
- `Search in string identifiers` --> `Include string identifiers`
- `Search in rejected translations` --> `Include rejected translations`
Renaming the variables was done to improve clarity and more accurately reflect how the query changes in the backend. Additionally, I've added visual separation between the 'Match' and 'Include/Exclude' filters, reflecting the difference in their behaviours.
> Tweaked search panel design

- translate/src/modules/search/components/SearchBox.test.js
- translate/src/modules/search/components/SearchBox.tsx
- translate/src/modules/search/components/SearchPanel.tsx
Fix #3354 and #3355 
This PR addresses the current bugs that relate to preserving state when the search panel is discarded and search terms are typed into the search bar. 
Previously, discarding the panel with a search option toggled on will toggle off that option. Also, if a search term was entered into the search bar and the Enter/Return key is not clicked, but the `APPLY SEARCH OPTIONS` button was clicked, then the term inside the search bar will not be included in the query.
This PR fixes the first issue by introducing a new state to track which options are selected, and syncing those with searchOptions whenever the panel is visible. The second issue is addressed by moving the `search` variable outside of the spread operator in `SearchBox.tsx`.
> Fixed bugs regarding state preservation

- .eslintignore
- .github/workflows/backend.yml
- .github/workflows/py-lint.yml
- .gitignore
- CONTRIBUTING.rst
- Makefile
- docker/Dockerfile
- docker/compile_requirements.sh
- docs/dev/setup-virtualenv.rst
- requirements/dev.in
- requirements/dev.txt
As discussed, this needs to be tested on stage to make sure that the post compile step works as expected on Heroku.
> Replace pip and pip-tools with uv

- requirements/default.in
- requirements/default.txt
This probably needs some testing on stage.
A bit surprising that the [changelog](https://github.com/googleapis/google-cloud-python/blob/main/packages/google-cloud-translate/CHANGELOG.md) indicates 3.10 as the version compatible with Python 3.11, and we still have version 3.8 of the package.
> Update google-cloud-translate package to 3.16.0

- requirements/default.in
- requirements/default.txt
Stumbled upon #2766. Looks like the [project](https://github.com/agronholm/apscheduler) is actively maintained, they're even working on a 4.0 release, so maybe we should close that issue?
> Update APScheduler to 3.10.4

- .github/workflows/backend.yml
This should fix #2240 
`makemigrations --check` [doesn't create new migration files since 4.2](https://docs.djangoproject.com/en/5.1/releases/4.2/#miscellaneous), and returns 1 when there's a migration pending.
> Check for missing Django migrations in backend test

- package-lock.json
- translate/package.json
The important bit here is the removal of (the outdated version of) `lodash.pick`.
Deployed to stage.
> Update reactour to latest version

- .coveragerc
Using specific coverage file instead of setup.cfg, fixed warning in `make pytest` (`CoverageWarning: --include is ignored because --source is set (include-ignored)`).
> Update Python coverage config file, fix warning

- CONTRIBUTING.rst
- docs/admin/deployment.rst
- docs/dev/setup.rst
Docker Toolbox is deprecated (and so are Windows 7–8): https://github.com/docker-archive/toolbox
> Fix broken links in docs, remove Windows Home section for docker

- pontoon/api/README.md
- pontoon/api/tests/test_schema.py
- pontoon/api/tests/test_urls.py
- pontoon/api/urls.py
Both of these URLs for:
https://mozilla-pontoon-staging.herokuapp.com/graphql?query=%7Bprojects%7Bname,missingStrings,approvedStrings%7D%7D
https://mozilla-pontoon-staging.herokuapp.com/graphql/?query=%7Bprojects%7Bname,missingStrings,approvedStrings%7D%7D
> Add trailing slash to the graphql URLs

- CONTRIBUTING.rst
- Makefile
- docs/dev/setup.rst
Currently, `make shell` spins up a brand-new container, which is not particularly useful. Also added a `make shell-root` option to connect as root.
> Improve `make shell`, add instructions for SSH in Docker

- pontoon/base/middleware.py
- pontoon/base/models/user.py
Change IP throttling to never block legitimate users (identified by having at least 1 approved translation).
For blocked IPs we now also log the username if the request is coming from an authenticated user.
Log message is also changed a little so it's easier to search for all IPs with excessive requests (blocked and legitimate).
> Do not throttle IPs of legitimate users

- pontoon/administration/static/css/admin_project.css
- pontoon/base/models/comment.py
- pontoon/base/models/user.py
- pontoon/base/static/css/dark-theme.css
- pontoon/base/static/css/light-theme.css
- pontoon/base/tests/models/test_comment.py
- pontoon/base/tests/models/test_user.py
- pontoon/base/views.py
- pontoon/contributors/static/css/profile.css
- pontoon/contributors/templates/contributors/profile.html
- pontoon/contributors/templates/contributors/settings.html
- pontoon/teams/views.py
- pontoon/test/fixtures/base.py
- specs/0119-gamification-badges.md
- translate/src/api/user.ts
- translate/src/hooks/useTranslator.test.js
- translate/src/hooks/useTranslator.ts
- translate/src/hooks/useUserStatus.test.js
- translate/src/hooks/useUserStatus.ts
- translate/src/modules/comments/components/AddComment.tsx
- translate/src/modules/editor/components/EditorSettings.test.js
- translate/src/modules/editor/components/FailedChecks.test.js
- translate/src/modules/entitieslist/components/EntitiesList.test.js
- translate/src/modules/teamcomments/components/TeamComments.tsx
- translate/src/modules/user/components/UserAvatar.css
- translate/src/modules/user/components/UserAvatar.tsx
- translate/src/modules/user/components/UserMenu.test.js
- translate/src/modules/user/components/UserMenu.tsx
- translate/src/modules/user/reducer.ts
- translate/src/test/store.jsx
This adds a banner for users defined as "Project Manager" within a project. To reduce the space for confusion, I changed the tooltip of MNGR from "Manager" to "Team Manager".
This also makes the priority of roles consistent between front-end and back-end:
- If a user as a role within the locale (translator, manager), we use that for the banner.
- If a user is set as PM, we use that even if the user is an Admin.
Finally, this adds CSS variables for users, instead of reusing the ones for translation status.
Fixes #3418 
Fixes #3425
TODO:
> Add banner for project managers, give priority to roles within locale

- pontoon/base/models/entity.py
Entities explicitly requested using `string` or `list` URL parameters might not be enabled for localization for the given locale. 
If the project is given in the URL, the 404 page shows up:
https://pontoon.mozilla.org/es/facebook-container/all-resources/?string=196694
If the All Projects view is used, we hit the IndexError here, because the `projectlocale` list is empty:
https://pontoon.mozilla.org/es/all-projects/all-resources/?string=196694
Instead of the broken translate page, we should skip the entity from the list.
> Do not fail on entities not enabled for the locale

- pontoon/base/templates/header.html
- pontoon/messaging/forms.py
- pontoon/messaging/static/css/messaging.css
- pontoon/messaging/static/js/messaging.js
- pontoon/messaging/templates/messaging/includes/compose.html
- pontoon/messaging/urls.py
- pontoon/messaging/views.py
Fix #3162.
This is the final step of functional changes to the Messaging center before we can start using it in production:
* Messaging link is added to the main menu, visible only to users that can actually access the page
* As soon as you hit the Review page, contributors start getting fetched, as indicated in the button in the bottom right part of the screen. 
* Once fetching is complete, the button to send the messages is made available with the recipient count written over it. 
* While messages are being sent or if the recipient count is 0, the Send button is disabled. 
* If fetching contributors fails, the button turns red and offers you the ability to retry fetching.
Note that you can only send notifications on stage, sending emails will fail. Also note that neither fetching nor …
> Release Messaging center

- pontoon/base/static/css/dark-theme.css
- pontoon/base/static/css/light-theme.css
- pontoon/base/static/css/style.css
- pontoon/teams/static/js/translation_memory.js
- pontoon/teams/templates/teams/includes/translation_memory.html
- pontoon/teams/templates/teams/team.html
- pontoon/teams/views.py
Fix #3444.
It is now possible to link to a particular view in a TM tab, reflecting any search parameters and the number of pages to load: https://mozilla-pontoon-staging.herokuapp.com/sl/translation-memory/?search=Open&pages=3.
Also included are the following changes:
* [Make TM tab available to Translators, not just Managers](https://github.com/mozilla/pontoon/commit/149c4e42cbb35193fa14f9e237b700a5b0f6da7e)
* [Add more contrast to the search fields](https://github.com/mozilla/pontoon/commit/1b646e94d0496a6c811cc006ce9df33512e38744)
* [Bugfix: Narrow down event targets](https://github.com/mozilla/pontoon/commit/4018936090bc86634d6729f99badc1ebe0c59de1)
> Reflect search and pagination in TM tab

- pytest.ini
There's a file in `amo` that matches the default test file pattern:
`media/projects/amo/git@github.com:mozilla/olympia.git/conftest.py`.
This avoids matching that when running pytest.
> Include media/ in pytest norecursedirs

- pontoon/teams/static/css/translation_memory.css
- pontoon/teams/static/js/translation_memory.js
- pontoon/teams/templates/teams/includes/translation_memory.html
- pontoon/teams/templates/teams/widgets/translation_memory_entries.html
- pontoon/teams/urls.py
- pontoon/teams/views.py
Fix https://github.com/mozilla/pontoon/issues/2031.
This is the final step towards Translation Memory Management ([spec](https://github.com/mozilla/pontoon/blob/main/specs/0121-translation-memory-management.md)), which adds the ability for team managers and translators to upload .TMX files to their locale's TM. The PR is deployed to [stage](https://mozilla-pontoon-staging.herokuapp.com/sl/translation-memory/) for testing.
Also included is the [minor change](https://github.com/mozilla/pontoon/pull/3452/commits/91cbd86cb81b1d8df47cead08ba0fe5d62129fe8) in how error messages are presented (as errors, rather than regular messages).
TODO:
> Add ability to upload personal translation memory

- pontoon/teams/static/css/translation_memory.css
- pontoon/teams/static/js/translation_memory.js
- pontoon/teams/templates/teams/includes/translation_memory.html
Shows a legal notice when uploading a .TMX file. I also tried with a popup instead of an inline notice, but it felt weird with two popups (one for a notice, and another for the file picker).
https://mozilla-pontoon-staging.herokuapp.com/sl/translation-memory/
> Show upload .TMX terms

- pontoon/api/urls.py
- pontoon/api/views.py
- pontoon/urls.py
Introduce an API endpoint to retrieve User action data on a given date for a given project:
`/api/v1/user-actions/YYYY-MM-DD/project/PROJECT-SLUG/`
Example:
[/api/v1/user-actions/2024-01-07/project/thunderbird/](https://mozilla-pontoon-staging.herokuapp.com/api/v1/user-actions/2024-01-07/project/thunderbird/)
The following actions are tracked:
* Translation created
* Translation deleted
* Translation approved
* Translation unapproved
* Translation rejected
* Translation unrejected
Notes:
* Authentication is required.
* The links above point to the stage server, which only has data until 2024-11-20. 
* Performance should be a bit better on the production instance.
> Add an API endpoint to retrieve User action data

- pontoon/base/fluent.py
- pontoon/base/tests/test_fluent.py
- pontoon/pretranslation/tests/test_pretranslate.py
- pontoon/pretranslation/transformer.py
Fix #3461.
The code that extracts access key candidates [expects](https://github.com/mozilla/pontoon/blob/e23b7dbdf857a0f2e931937d5c6dd6db17ceb3e0/pontoon/pretranslation/transformer.py#L109-L111) that if the _source_ attribute is a `SelectExpression`, its variant keys must have a `name` property. That's not the case for variant keys of type `NumberLiteral` ([example](https://pontoon.mozilla.org/sv-SE/firefox/all-resources/?string=313552)).
This is the code to reproduce the error:
```python
from pontoon.base.models import *
from pontoon.pretranslation.pretranslate import get_pretranslations
entity = Entity.objects.get(pk=313552)
locale = Locale.objects.get(code="sv-SE")
get_pretranslations(entity, locale, False)
File "<console>", line 1, in <module>
File …
```
> Support variant keys of type NumberLiteral in Pretranslation of access keys

- translate/src/modules/editor/components/NewContributorTooltip.css
Fix #3465.
Preview (unless you've made contributions to `ab`):
https://mozilla-pontoon-staging.herokuapp.com/ab/all-projects/all-resources/?string=311950
> Make NewContributorTooltip visible again

- pontoon/messaging/templates/messaging/emails/notification_digest.html
This PR fixes a regression introduced by https://github.com/mozilla/pontoon/pull/3456/commits/0d518e6cea8f7c726c3ed4fa101d8682fbc73718, which draws too many borders:
Before:
After:
> Remove unnecessary border from notification emails

- docs/admin/deployment.rst
- pontoon/messaging/management/commands/send_notification_emails.py
- pontoon/settings/base.py
Let's not hardcode the day on which to send weekly notification digest emails. That way we can also make sure it includes the (weekly) suggestion notifications, for which the sending day can also be configured.
> Configurable day to send weekly notification digest emails on

- pontoon/base/models/user.py
- pontoon/translations/tests/test_views.py
- pontoon/translations/views.py
Fix #3476.
I've added a test that checks whether the new contributor notification is sent.
I've also excluded the notification to be sent when project manager makes the contribution to the locale.
> Fix new contributor detection logic

- specs/0120-transactional-emails.md
Minor copy updates and fixes in Onboarding and Inactive account emails.
Please see the updated text in the designs of all transactional emails below. Note that the http://localhost:8000/ URLs will be replaced with https://pontoon.mozilla.org/ in production.
Onboarding 1:
Onboarding 2:
Onboarding 3:
Inactive contributor: 
Inactive translator: 
Inactive manager:
> Update Transactional emails spec

- pontoon/messaging/views.py
That should have been done as part of #3493.
> Call send_manual_emails() task asynchronously

- translate/public/locale/en-US/translate.ftl
- translate/src/modules/search/components/SearchPanel.css
- translate/src/modules/search/components/SearchPanel.tsx
For `fa-w`, see #3507 
The console is full or React errors when opening the panel. The edit removed a bunch of trailing whitespaces, which I think it's useful to remove anyway.
> Fix advanced search options (missing Fluent strings, CSS)

- translate/src/modules/search/components/SearchBox.css
- translate/src/modules/search/components/SearchPanel.css
- translate/src/modules/search/components/SearchPanel.tsx
> Make advanced search options more discoverable

- README.md
- contribute.json
- docs/dev/first-contribution.rst
- pontoon/base/templates/django/base.html
- pontoon/base/templates/header.html
- pontoon/homepage/templates/homepage_content.html
- translate/src/modules/user/components/UserMenu.tsx
Before deployment, we should "lock" https://discourse.mozilla.org/c/pontoon/258 and pin a post pointing to GitHub Discussions.
After deployment, we should update references in the Homepage and Transaction email content, which are stored in the DB.
> Replace Discourse with GitHub Discussions

- translate/src/modules/search/components/SearchPanel.tsx
This was fixed in #3508, but lost in the rebase of #3509
> Restore fix for Fluent references in advanced search options

- pontoon/sync/core/translations_from_repo.py
- pontoon/sync/tests/test_translations_from_repo.py
Fixes #2120 
Fixes #3518
This should not have any significant impact on sync, as the comparison is only done when there's at least some difference. A couple of stylistic fly-by fixes are included to satisfy Mypy.
> Use Fluent BaseNode.equals() to match DB & repo translations

- pontoon/sync/core/translations_from_repo.py
The `region.properties` files were previously ignored, and with no change to the source resource, normal sync hasn't noticed that they should be added.
A forced sync should be run for `seamonkey` to expose the files.
> Account for missing resource from previous sync implementation

- pontoon/api/tests/test_schema.py
In some environments ([example](https://github.com/mathjazz/pontoon/actions/runs/12984741173/job/36208205822)) some of the [TM search API tests](https://github.com/mozilla/pontoon/pull/3540) are failing.
> Order lists of dicts in TM search API tests

- pontoon/administration/templates/admin.html
- pontoon/administration/views.py
- pontoon/api/schema.py
- pontoon/base/aggregated_stats.py
- pontoon/base/models/locale.py
- pontoon/base/models/project.py
- pontoon/base/models/project_locale.py
- pontoon/base/models/translated_resource.py
- pontoon/base/templates/widgets/progress_chart.html
- pontoon/insights/tasks.py
- pontoon/localizations/templates/localizations/widgets/resource_list.html
- pontoon/localizations/tests/test_views.py
- pontoon/localizations/views.py
- pontoon/projects/templates/projects/includes/teams.html
- pontoon/projects/templates/projects/projects.html
- pontoon/projects/templates/projects/widgets/project_list.html
- pontoon/projects/views.py
- pontoon/tags/tests/test_utils.py
- pontoon/tags/utils.py
- pontoon/teams/templates/teams/includes/projects.html
- pontoon/teams/templates/teams/teams.html
- pontoon/teams/views.py
Touches #3545
Refactors the data access for aggregated stats on listings of projects and teams.
The `Project.get_charts()`, `ProjectLocale.get_charts()` and `Locale.get_charts()` methods are dropped, and their functionality is now provided by `ProjectQuerySet.stats_data()` and `LocaleQuerySet.stats_data()`.
Derived percentage and completeness data for stats is now calculated in Jinja templates, as necessary.
After these changes, the GraphQL endpoint is perhaps the only remaining actual user of the AggregatedStats fields.
> Use fewer queries for translation progress stats on dashboards

- pontoon/sync/core/translations_from_repo.py
- pontoon/sync/utils.py
Code that's specifically and only for manualy file imports should not be in the sync internals.
This PR also fixes a bug introduced in #3522, as the type hint for `update_db_translations()` was not updated, and the early return was also not updated:
https://github.com/mozilla/pontoon/blob/1278167d98ac9810eccaf98698718988a23f2038/pontoon/sync/core/translations_from_repo.py#L81-L83
https://github.com/mozilla/pontoon/blob/1278167d98ac9810eccaf98698718988a23f2038/pontoon/sync/core/translations_from_repo.py#L295-L302
> Move badge notification code out of update_db_translations()

- pontoon/base/models/locale.py
- pontoon/base/models/project.py
- pontoon/base/models/project_locale.py
- pontoon/base/models/user.py
- pontoon/base/tests/models/test_locale.py
- pontoon/base/tests/models/test_project.py
- pontoon/base/tests/models/test_project_locale.py
- pontoon/base/tests/test_utils.py
- pontoon/base/utils.py
- pontoon/contributors/templates/contributors/settings.html
- pontoon/projects/templates/projects/includes/teams.html
- pontoon/projects/templates/projects/widgets/project_list.html
- pontoon/projects/views.py
- pontoon/teams/templates/teams/includes/projects.html
- pontoon/teams/views.py
Fixes #3545 
This should speed things up a bit. Two related changes are included to resolve the identified inefficiencies, and a couple of the `Locale` methods are dropped/simplified to match current usage. The `ProjectLocale.get_latest_activity()` function is split into two separate implementations on `Locale` and `Project`, as they are now rather different, and the `get_object_or_none()` utility is dropped as obsolete.
> Reduce database queries on dashboards

- pontoon/sync/core/translations_from_repo.py
- pontoon/sync/tests/test_translations_from_repo.py
Fixes #3516 
I've only validated this via the test suite, but checking with real-ish syncs as well would be good (CC @flodolo).
> Reject translations removed from repo

- .gitattributes
- requirements/dev.in
- requirements/dev.txt
Adds `django-stubs` for better type hints and marks vendored JS files as "binary" so they're skipped by default in `git grep` and similar output.
> Minor quality-of-life improvements

- pontoon/base/tests/models/test_comment.py
- pontoon/base/tests/views/test_comment.py
- pontoon/base/views.py
- pontoon/test/fixtures/base.py
Fix #3597.
While frontend prevents non-PMs to pin or unpin comments, the backend allows any authenticated user to do so.
> Only PMs should be able to pin and unpin comments

- docs/admin/deployment.rst
- pontoon/settings/base.py
Hey, I am deploying the app behind a reverse proxy, which deals with this redirect. If I don't disable it I get an infinite redirect loop. This env var allows me to fix this issue.
> add the SECURE_SSL_REDIRECT env var

- pontoon/sync/core/translations_to_repo.py
- pontoon/sync/tests/test_e2e.py
In some manual testing I noticed that [mozilla-l10n/mozilla-vpn-extension-l10n@8998785](https://github.com/mozilla-l10n/mozilla-vpn-extension-l10n/commit/8998785057cee071b1f47b5c0ab7674f12eac2a3) had dropped the `"placeholders"` objects from its serializations, as a regression from #3587.
This is due to `pontoon.sync.core.translations_to_repo.set_translation()` setting the entry value to a string (rather than a properly parsed moz.l10n `Message`), which drops the declarations representing said `"placeholders"` from the output.
To fix this, we need to do a minimal parse of the webextension message so that we end up with the right serialization. Once #3611 updates moz.l10n to 0.7.0, its `webext_parse_message()` could replace the code inlined here.
The `mozilla-vpn-extension` project will …
> Fix messages.json serialization for messages with $placeholders$

- pontoon/contributors/static/css/profile.css
I was reviewing disabled profile users ([example](https://pontoon.mozilla.org/contributors/Dnlau96/)), and the warning is barely visible even knowing where it is. I think it makes sense to show it in red, as other administrator related content.
> Make user disabled message more visible

- mypy.ini
This should've been included in #3586 to make full use of `django-stubs`.
> Add mypy.ini

- CONTRIBUTING.rst
This PR replaces the invalid command to start postgresql container with a working one:
* `up` starts the service as defined in `docker-compose.yml`
* `-d` means "detached" mode (runs in the background)
* `postgresql` is the name of the service
> Update command to start just the postgresql container

- pontoon/sync/views.py
This fixes #3544 by changing the view associated with querying Syncs, excluding Syncs that have the "In-Progress" status.
> Bug Fix #3544: Remove In-Progress Syncs from Sync Error Page

- CONTRIBUTING.rst
- docs/dev/setup-virtualenv.rst
- docs/dev/setup.rst
Fix: #3633
According to https://nodejs.org/en/blog/release/v16.6.0, the `array.at` feature was introduced in `node v16.6.0`
Changed this in the docs.
> Fix: Changed min node version from 14 to 16.6.0

- pontoon/base/migrations/0077_fix_android_newlines.py
- pontoon/sync/core/translations_to_repo.py
- pontoon/sync/formats/xml.py
- pontoon/sync/tests/test_e2e.py
Fixes two related regressions from #3611, as literal `"` quotes are now showing up as `\\\"` double-escaped, and escaped newlines `\n` are showing up as `\\n`.
Also normalises the presentation of escaped newlines to always be followed by a literal newline, and drops any whitespace immediately after an escaped newline when serialising.
> Fix escaped quotes and newlines for Android strings

- pontoon/base/migrations/0079_trim_android.py
- pontoon/sync/formats/xml.py
- pontoon/sync/tests/formats/test_xml.py
- requirements/default.in
- requirements/default.txt
Three main changes here for Android string handling:
1. The `\u` escapes use hexadecimal rather than decimal values.
2. Leading and trailing whitespace is trimmed.
3. HTML-ish content is serialised with a `<![CDATA[...]]>` wrapper.
Note that an `lxml` workaround for https://bugs.launchpad.net/lxml/+bug/2111509 requires capping its version range to max at its current version (5.4.0), as the workaround will need to be removed once the bug is fixed.
> Use moz.l10n 0.7.4, with fixed Android string resource handling

- pontoon/insights/models.py
- pontoon/insights/tests/test_models.py
Fix #3659 by restoring the `InsightsSnapshot.missing_strings` property removed in https://github.com/mozilla/pontoon/pull/3536.
> Fix missing string count in Monthly activity summary

- README.md
> Fix URL for Deploy to Heroku button in README

- pontoon/urls.py
Without this fix, deploying Pontoon to prod fails, because `debug_toolbar` isn't installed there.
> Only conditionally include Django Debug Toolbar URLs

- pontoon/base/models/locale.py
- pontoon/base/models/project.py
- pontoon/projects/views.py
- pontoon/teams/views.py
stats_data now returns a LocaleQuerySet, which is required for our REST API implementation, while stats_data_as_dict retains the old behavior of returning a dictionary, which is used in the /teams page as well as an ajax render.
> Added stats_data_as_dict and changed stats_data

- bin/post_compile
I think there's still value in being able to debug performance on stage with DDT and such, so I'm keeping the ability to install dev requirements through the same variable (`DJANGO_DEV`) that is also used to enable them in settings.
> Install DEV requirements on stage if DJANGO_DEV is True

- pontoon/api/views.py
Resolves #3698.
It is important to note that the new api follows the implementation of the /teams page, which excludes the locales "en-US", "en", "bn-IN" and "bn-BD". The reason is that added these locales changes the missing_strings, total_strings fields in /locales to incorrect inflated values.
> Return correct results with distinct locales in /locales

- CONTRIBUTING.rst
- docs/conf.py
- pontoon/base/models/locale.py
- pontoon/base/models/project.py
- pontoon/base/templates/base.html
- pontoon/base/templates/django/base.html
- translate/tsconfig.json
Not exactly important, but it bothers me every time I stumble upon one 🦉
> Fix spelling of JavaScript across docs and comments

- pontoon/api/urls.py
- pontoon/api/views.py
This PR resolves #3680.
It creates a new endpoint at `/api/v2/user-actions/<str:date>/project/<slug:slug>/`, which lists out user actions on the specified day related to a specified project.
It mirrors the behavior of `/api/v1/user-actions/<str:date>/project/<slug:slug>/`. It requires the user to be signed in in order to be able to access the data.
Future action is needed to clean up the old endpoint `/api/v2/user-actions/<str:date>/project/<slug:slug>/`.
> Api/V2/: User-actions Endpoint

- pontoon/checks/libraries/__init__.py
- pontoon/checks/tests/test_libraries.py
- pontoon/checks/tests/test_translate_toolkit.py
Fixes #3750 
Rather than skipping all of the translate-toolkit checks as suggested in https://github.com/mozilla/pontoon/issues/3750#issuecomment-3151228293, let's run them separately for each of the patterns, as was done previously.
This uses the plural pattern of the source for all variants except for `one`.
> Run translate-toolkit checks separately for each gettext plural pattern, rather than the message as a whole

- pontoon/insights/migrations/0018_fix_locale_insights.py
- pontoon/insights/tasks.py
- pontoon/insights/tests/test_tasks.py
Fixes #3794
The attached migration took about 90 seconds to run for me locally. The `unreviewed_suggestions_lifespan` values that it sets are for the time when the migration is run, as generating the historical data would be quite cumbersome.
> Ensure LocaleInsightsSnapshot.unreviewed_suggestions_lifespan is never null
