README.md
=> Fixed "based on on" typo

pontoon/base/migrations/0006_auto_20150602_0616.py, pontoon/base/migrations/0007_auto_20150710_0944.py, pontoon/base/migrations/0008_auto_20150710_0946.py
=> Fix conflicting migrations.

pontoon/administration/management/commands/commit_projects.py, pontoon/administration/management/commands/update_projects.py
From https://github.com/mozilla/pontoon/pull/43#discussion_r34347338.
@mathjazz r?
=> Remove redundant timestamp from mgmt command logs.

requirements.txt
@mathjazz r?
This is deployed to https://mozilla-pontoon-staging.herokuapp.com/ so a quick spot check there for functionality would be appreciated. :D
=> Upgrade to Django 1.8.3.

pontoon/base/views.py
Handle the case where the subpages don't have any resources.
=> Bug 1186090

pontoon/administration/files.py
=> Bugfix: locale PO files and in PO, not POT

pontoon/administration/files.py, pontoon/administration/management/commands/sync_projects.py, pontoon/administration/vcs.py, pontoon/base/__init__.py, pontoon/base/formats/__init__.py, pontoon/base/formats/base.py, pontoon/base/formats/lang.py, pontoon/base/migrations/0009_auto_20150721_1511.py, pontoon/base/migrations/0010_translation_extra.py, pontoon/base/models.py, pontoon/base/utils.py, pontoon/base/vcs_models.py, pontoon/base/views.py, requirements.txt
Adds a new management command called `sync_projects` that simultaneously pulls updates from VCS to update the database and commits changes from the database to VCS.
More details to follow, and this is still slightly incomplete, but I figured putting it up now for some pre-reviewing would be helpful. Don't merge for now.
@mathjazz Comments, criticism, and questions are welcome. :D
=> Bug 1178874: Add new sync_projects command.

bin/sync_projects.sh
=> Add ability to pass arguments to sync_projects.sh.

pontoon/base/migrations/0011_auto_20150803_1524.py, pontoon/base/models.py, pontoon/base/templates/locale_selector.html
=> Fix locale ordering again, order_by returns a new queryset

pontoon/base/models.py, pontoon/base/static/js/main.js, pontoon/base/static/js/search.js, pontoon/base/static/js/translate_old.js, pontoon/base/templates/search.html, pontoon/base/templates/translate.html, pontoon/base/templates/user.html, pontoon/base/views.py, pontoon/settings/base.py
This fixes bugs 1190566, 1190796 and 1190953 and also adds dir and lang attributes on Terminology Search and Contributor pages.
@amire80, r?
@Osmose, r?
=> Dir & lang attributes

pontoon/base/formats/lang.py
=> Remove {ok} tag when translation doesn't match source.

pontoon/base/templates/translate.html
=> Bug 1183011: Swap resource and locale positions

pontoon/base/static/css/translate.css, pontoon/base/static/js/translate_old.js, pontoon/base/templates/translate.html
=> Bug 1184444: add unchanged strings filter

pontoon/administration/management/commands/sync_projects.py, pontoon/base/models.py
@mathjazz Does this look any better?
=> Update stats on sync when resource exists or is asymmetric.

pontoon/base/static/js/main.js, pontoon/base/static/js/translate_old.js
=> Restore advertised and mistakenly removed keyboard shortcuts

pontoon/base/static/css/project.css, pontoon/base/static/css/style.css
Make project column wider to avoid text overflow.
=> Make project column wider

pontoon/base/models.py, pontoon/base/views.py
Loads translate view up to 80% faster. Uses dicts and hashes to minimize DB queries.
@Osmose, r?
=> Significant entities loading optimization

requirements.txt
=> Fix bug 1195912 - Django 1.8.4 security update

pontoon/base/models.py, pontoon/base/tests/directory_detection_test/real_resources/templates/test.po, pontoon/base/tests/directory_detection_test/templates/not_a_resource.py, pontoon/base/tests/test_models.py
=> Ignore possible source directories with no resources.

pontoon/base/views.py
In both, contributor profile and top contributors page we no longer
count unchanged translations.
This is a quick fix for, but more improvements are needed to the top contributors page:
https://bugzilla.mozilla.org/show_bug.cgi?id=1196140
@Osmose, r?
=> Exclude unchanged translations from stats

pontoon/base/templates/translate.html
=> Bug 1193771: Remove Download ZIP from the menu

pontoon/base/views.py
=> Make subpages, that aren't linked to resources, work again

pontoon/base/migrations/0019_auto_20150820_1345.py, pontoon/base/models.py, pontoon/base/views.py
=> Rename resource to resources (ManyToManyField)

pontoon/base/models.py, pontoon/base/templates/translate.html, pontoon/base/templates/user.html, pontoon/base/templates/users.html, pontoon/base/views.py
=> Move gravatar_url() to User moder

pontoon/settings/base.py
Fixes a slightly annoying warning.
@mathjazz r?
=> Remove TEMPLATE_* settings as they're deprecated.

pontoon/administration/management/commands/sync_projects.py, pontoon/administration/tests/fake-checkout/inactive-locale/main.lang, pontoon/administration/tests/fake-checkout/inactive-locale/other.lang, pontoon/administration/tests/test_sync_projects.py
=> Fix bug 1198106: Update all stats during sync.

pontoon/base/views.py
This is a regression caused by #122.
@Osmose r?
=> Only show resource menu if project uses > 1 resource

.travis.yml, pontoon/settings/base.py
Probably going to have to modify this to get the tests running.
=> Add .travis.yml file for automated tests.

pontoon/base/formats/lang.py
=> Fix bug 1199195: Remove BOM in langfiles if present.

pontoon/base/tests/test_views.py
See #128 for more details.
@Osmose r?
=> Add tests for update part code in translate view

requirements.txt
=> Add missing requirements for tests

pontoon/base/views.py
=> Order contributor timeline by day

pontoon/base/static/js/translate_old.js
To avoid leaving the false impression work is complete.
@Osmose r?
=> Only count approved translations when calculating progress

pontoon/base/static/js/translate_old.js, pontoon/base/views.py
@Osmose I'm merging this because Affiliates, Firefox Updater and Firefox Tiles are confusing people.
=> Hotifx hide single parts

pontoon/base/static/js/translate_old.js, pontoon/base/views.py
=> Do not die if subpage set

pontoon/base/static/js/pontoon.js
=> Also detect L10nJs using data-l10n-ids

pontoon/sites/static/snippets/css/aboutHome.css
@jotes r?
This is the final one, I promise. Successfully deployed to staging:
https://mozilla-pontoon-staging.herokuapp.com/sites/snippets/
https://mozilla-pontoon-staging.herokuapp.com/sites/tiles/
=> Fix broken snippets site CSS references

pontoon/base/models.py, pontoon/base/static/js/pontoon.js, pontoon/base/static/js/translate_old.js
Store empty translations as '' and untranslated strings as null.
@Osmose, r?
=> Bug 1198610: Allow saving empty translations in place

pontoon/base/static/js/translate_old.js
Also fix string length calculation for plural forms.
=> Render translations as '' instead of null in DOM

pontoon/base/static/js/translate_old.js
=> Do not request new locale by mistake

pontoon/base/static/js/translate_old.js
=> Exclude unapproved translations from percentage in resource menu

pontoon/base/static/js/translate_old.js
=> Fix pluralized string length calculation

pontoon/base/models.py
=> Also get translations is specified plural form is 0

pontoon/sites/views.py
Fixed xframes header. @mathjazz could you review?
=> Fixed xframe header for sites pages.

pontoon/base/static/js/pontoon.js
=> Avoid some tags when detecting hooks

pontoon/base/formats/lang.py, pontoon/base/tests/formats/test_lang.py
=> Fix bug 1204331: Preserve hashes in comments.

pontoon/administration/static/css/admin_project.css, pontoon/administration/views.py, pontoon/base/migrations/0023_auto_20150916_0642.py, pontoon/base/models.py, pontoon/base/static/css/locales.css, pontoon/base/static/css/project.css, pontoon/base/static/css/search.css, pontoon/base/static/css/style.css, pontoon/base/static/css/translate.css, pontoon/base/static/js/main.js, pontoon/base/templates/latest_activity.html, pontoon/base/templates/locale_selector.html, pontoon/base/templates/project_selector.html, pontoon/base/templatetags/helpers.py, pontoon/base/tests/test_models.py, pontoon/base/views.py, pontoon/settings/base.py
This is #165 with squashed commits.
=> Add latest activity column

pontoon/base/formats/po.py
=> Log what PO file trigerred IOError

pontoon/base/migrations/0024_locale_team_description.py, pontoon/base/models.py, pontoon/base/static/css/style.css, pontoon/base/templates/locale.html
hi @mathjazz could you review if that's enough for now? thx.
=> Bug 1200191. Added field for team description

pontoon/base/models.py, pontoon/base/static/css/style.css, pontoon/base/templates/users.html, pontoon/base/tests/__init__.py, pontoon/base/tests/test_models.py, pontoon/base/tests/test_views.py, pontoon/base/views.py, requirements.txt
@mathjazz Hi, could you review?
=> Bug 1196140. Added possibility to see top contributors aggregated by last 12|6|3 months.

pontoon/base/formats/silme.py, pontoon/base/tests/__init__.py, pontoon/base/tests/formats/__init__.py, pontoon/base/tests/formats/test_silme.py
=> Fix bug 1208013: Allow Silme to load missing files if source exists.

pontoon/administration/files.py
@mathjazz r?
It gets past the error mentioned in the bug but it fails for me locally because I don't have permission to commit to hg. Help with testing is greatly appreciated. :D
=> Fix bug 1208064: Use correct path for updating.

pontoon/administration/files.py
=> Bug 1208064: Another outdated path fix

bin/mozilla-en-US.py
This extends the script to also support Mozilla Beta repositories, which we can use for adding Firefox Beta etc. to Pontoon.
Appears to be working fine:
http://hg.mozilla.org/users/m_owca.info
@Osmose r?
=> Add support for Mozilla Beta repositories

pontoon/base/formats/__init__.py, pontoon/base/formats/silme.py, pontoon/base/tests/formats/test_silme.py, requirements.txt
=> Bug 1178874: Add .inc support to sync_projects.

pontoon/base/models.py, pontoon/base/templates/project_selector.html, pontoon/base/tests/__init__.py, pontoon/base/tests/test_models.py, pontoon/base/views.py
=> Add stats to subpages in the parts menu

pontoon/base/models.py, pontoon/base/tests/test_models.py, pontoon/base/views.py
To actually make it usable on production. This cuts DB requests in half.
I tested it with prod DB and the translate view loads even faster than
current production instance. By 20-30%.
@Osmose r?
--
I wanted to fix this, not so much because subpage stats are an important feature, but because it also partially blocks bug 1178880.
In any case it will be interesting to observe how this scales. We might need to consider loading project and locale data only and using AJAX to get resources, pages and stats. We could probably also load all these data for the requested and localizers' locale.
=> Optimize locales_parts_stats()

bin/sync_projects.sh, docs/admin/deployment.rst, docs/conf.py, docs/dev/sync.rst, docs/dev/workflow.rst, docs/index.rst, docs/requirements.txt
=> Bug 1212415: Document new sync process.

pontoon/base/models.py, pontoon/base/static/css/style.css, pontoon/base/templates/locale.html, pontoon/base/templates/locale_contributors.html, pontoon/base/templates/project.html, pontoon/base/templates/project_contributors.html, pontoon/base/templates/users.html, pontoon/base/templates/widgets/contributors.html, pontoon/base/templates/widgets/menu.html, pontoon/base/tests/__init__.py, pontoon/base/tests/test_models.py, pontoon/base/tests/test_views.py, pontoon/base/urls.py, pontoon/base/views.py
@Osmose @mathjazz Hi, could you review?
I've removed validation if locale contains projects -> i'm not sure if that's really required.
=> Bug 1206779 - added contributors subpages to project and locale views.

pontoon/base/static/css/project.css, pontoon/base/static/css/style.css, pontoon/base/static/js/project.js, pontoon/base/templates/locale.html, pontoon/base/templates/locale_contributors.html, pontoon/base/templates/locales.html, pontoon/base/templates/project.html, pontoon/base/templates/project_contributors.html, pontoon/base/templates/projects.html, pontoon/base/templates/search.html, pontoon/base/templates/users.html, pontoon/base/templates/widgets/contributors.html, pontoon/base/urls.py, pontoon/base/views.py
This is branched off #201, so please only look at this commit:
https://github.com/mozilla/pontoon/commit/1d28fa6c8bf23523fbc9d4683256ee41df5e2e3f
I'll reuse more tabs code when implementing tabs for locale requests. And redesigning it again. It could look much better, but it's good enough for release.
=> Bug 1206779: Fix locale/project contributors design

pontoon/base/static/js/main.js
=> Fix bug 1214847: Sort by text contents, not HTML markup

docs/admin/deployment.rst
Not sure about the first deploy though.
@Osmose r?
=> No need to run migrations when depoying (anymore)

pontoon/base/static/css/style.css, pontoon/base/static/css/users.css
=> Fix overflow issue in lists

pontoon/base/models.py
=> Hotfix for stats calculation

pontoon/settings/base.py
=> Simplify Celery settings

pontoon/base/static/css/style.css, pontoon/base/static/css/users.css
This changes everything. Again.
@Osmose r?
=> Properly align tabs

.gitignore, pontoon/base/templates/robots.txt, pontoon/urls.py
Tested locally, using sslserver (https://github.com/teddziuba/django-sslserver) module in local.py, works.
=> Bug 1215562: robots.txt file

pontoon/base/static/css/translate.css, pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html
Which means we no longer need More details button.
=> Show all metadata by default, below original string

pontoon/base/models.py, pontoon/base/static/js/translate.js
Note before merging: This is branced from #228.
=> Search by key

pontoon/administration/management/commands/import_verbatim.py
@jotes @Osmose another quick r?
=> Use timezone aware dates on Verbatim import

pontoon/base/static/js/main.js, pontoon/base/templates/translate.html, pontoon/base/templates/user.html, pontoon/base/templates/widgets/contributors.html
Also replaces "Needs work" with "Need work".
@Osmose @jotes?
=> Fix bug 1208393: Rename Unapproved to Suggested

pontoon/base/templates/user.html
=> Rename permissions to resemble word 'suggestions'

pontoon/base/models.py, pontoon/base/static/js/translate.js, pontoon/base/tests/test_models.py
@Osmose r?
I deloyed a hotfix (https://github.com/mozilla/pontoon/commit/4aeaba65b06ea0aeafb35a373eae75346f1cdec7) earlier and I wanted to do it without touching too much code. This is now a more proper fix.
=> Cleaner fix for bug 1217753

pontoon/urls.py
=> Fix bug 1216988: Redirect pt to pt-PT and ga to ga-IE

pontoon/sync/changeset.py, pontoon/sync/tests/test_changeset.py, pontoon/sync/tests/test_core.py
@mathjazz @Osmose  Hi, could you review?
=> Bug fix 1214722. Passes authors correctly to the commit message.

pontoon/sync/core.py, pontoon/sync/tests/test_core.py
=> Bug fix 1221508. Removes duplicated contributors from commit message.

pontoon/administration/templates/commit_message.jinja, pontoon/sync/tests/test_core.py
=> Bug 1221508: Fix test

pontoon/base/errors.py, pontoon/base/migrations/0040_auto_20151017_0005.py, pontoon/base/migrations/0041_create_locale_permissions.py, pontoon/base/migrations/0042_locale_groups.py, pontoon/base/migrations/0043_create_locale_groups.py, pontoon/base/migrations/0044_locale_translators.py, pontoon/base/models.py, pontoon/base/signals.py, pontoon/base/templates/translate.html, pontoon/base/templates/user.html, pontoon/base/tests/test_models.py, pontoon/base/tests/test_views.py, pontoon/base/utils.py, pontoon/base/views.py, pontoon/settings/base.py, pontoon/sync/management/commands/import_pootle.py, requirements.txt
@Osmose @mathjazz Hi,
I would say it's an alpha version of migrations. There's a lot to discuss because i wasn't sure about some things. Hopefully every change should be relatively easy.
My questions and doubts:
- i'm assigning groups to locale because it's a lot easier to assign users. I think it will benefit in future, however i don't want to over-engineer anything.
- i'm not sure if goods idea to have signals which create these permission groups associated with locale. I mean, i don't now how often locale are added, maybe it's a rare case so this isn't so important feat. I could add separate bootstrap function for locale groups. It would speedup tests and object creation.
- I've added some tests for models, i'm not sure if views require them as they use has_perm functions.
=> Fix bug 952488 - Added locale managers

.buildpacks, docs/admin/deployment.rst
=> Remove multi-buildpack and document how to configure buildpacks.

pontoon/administration/views.py, pontoon/base/views.py
This should help with the IntegrityError in https://app.raygun.io/crashreporting/cqwxbq/errors/935498833, although it won't help with [bug 1220286](https://bugzilla.mozilla.org/show_bug.cgi?id=1220286).
@mathjazz r?
=> Use per-view transactions when modifying the database.

pontoon/base/tasks.py
=> Get a proper traceback object for celery errors.

pontoon/sync/core.py
=> Properly handle unicode entity keys when logging.

pontoon/base/migrations/0045_remove_can_localize.py, pontoon/base/models.py, pontoon/base/signals.py, pontoon/base/static/css/user.css, pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html, pontoon/base/templates/user.html, pontoon/base/templatetags/helpers.py
Also check if user has translator permission on each project load (potential locale change).
And also remove the old can_localize permission.
=> Display what locales does the translator have permissions for

pontoon/base/models.py, pontoon/base/static/css/translate.css, pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html, pontoon/base/tests/test_models.py, pontoon/base/views.py
Adding probably the most wanted missing filter, listing all entities that contain suggestions. Suggested filter only lists strings which don't have approved translations.
=> Fix bug 1225021: Add Has suggestions filter

pontoon/base/static/css/translate.css, pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html
=> Remove Cancel button, one (Back) is enough

pontoon/base/static/css/translate.css, pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html
=> Add Untranslated filter

pontoon/base/static/css/translate.css, pontoon/base/static/js/main.js, pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html, pontoon/base/templates/user.html, pontoon/base/templates/widgets/contributors.html
* Approved -> Translated
* Untranslated -> Missing
* Needs work -> Fuzzy
Also renamed View profile to My profile and Contains suggestions to Containing Suggestions (to be number independant). And also use capital letters in menus.
=> Unify copy with other Mozilla l10n tools

pontoon/base/static/js/main.js, pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html
=> Show keyboard shortcuts in tooltips

pontoon/base/urls.py, pontoon/base/utils.py, pontoon/base/views.py
* Removed template as attribute
* Moved data dict into render() params
* Removed log.debug(), which was used nowhere
* Use HttpResponseBadRequest if request not AJAX
* Use @require_POST decorator to detect non-POST requests
* Removed traces of Transifex
=> Base view cleanup

pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html
Forgot to open this one yesterday.
=> Use currently selected filter in search placeholder

pontoon/base/views.py
No more email addres spoofing.
=> Fix bug 1225087: Add user email address into Reply-To instead of From

requirements.txt
Upgrade to the just released security release:
https://www.djangoproject.com/weblog/2015/nov/24/security-releases-issued/
Didn't notice anything unusual.
=> Django security update

pontoon/base/static/js/translate.js, pontoon/base/views.py
=> Optimize suggestions from other locales

requirements.txt
=> Fix bug 1228815. Updated sha256 sum for the django-browser-id.

pontoon/base/templates/base.html, pontoon/settings/base.py
=> Use local jQuery, Google CDN is slow in China

pontoon/sync/tasks.py
=> Fix sync overwriting project changes

pontoon/base/static/css/translate.css, pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html, pontoon/base/tests/test_views.py, pontoon/base/views.py
Makes the translation contents purely readonly for non authenticated users.
=> Fix Bug 1223770: Do not allow edits/suggests to non-authenticated users

pontoon/base/static/js/translate.js
Hello! @mathjazz could you look at this? thx!
=> Fix bug 1232378. Show projects only if search is empty or name matches.

pontoon/base/views.py, pylama.ini
I decided to split this big refactoring into smaller steps. @Osmose @mathjazz could you review this again?
=> Using JsonResponse for all json-like responses

pontoon/sync/static/css/sync_logs.css, pontoon/sync/templates/sync/log_list.html, pontoon/sync/views.py
=> Bug 1208171: Paginate sync log listing.

pontoon/sync/changeset.py, pontoon/sync/tests/test_changeset.py
@Osmose r?
This should resolve issues we have with stats sometimes not counting fuzzies properly.
=> Fix bug 1218980: Unfuzzy existing fuzzy translations

pontoon/base/static/js/main.js, pontoon/base/templates/user.html
=> Fix bug 1234501: Make profile toggles work

pontoon/sync/tests/test_vcs_models.py, pontoon/sync/utils.py, pontoon/sync/vcs_models.py
=> Bug 1220290: Don't parse files from hidden paths.

pontoon/sync/management/commands/sync_projects.py, pontoon/sync/tests/test_sync_projects.py
=> Bug 1211789: invalid slugs display error warning during synchronization.

pontoon/sync/management/commands/sync_projects.py
Hi, i'm sorry that i've discovered this so late. Could you review @mathjazz?
=> Bug 1211789: synchronization of all projects shouldn't display warning.

pontoon/administration/static/css/admin_project.css, pontoon/administration/static/js/admin_project.js, pontoon/administration/templates/admin_project.html, pontoon/administration/urls.py, pontoon/administration/views.py
@jotes r?
I granted superuser status to a few more people and this looked like a good idea. ;)
Also added a comment to #207.
=> Remove the ability to delete projects from the admin UI

pontoon/base/templates/404.html
=> Allow signing in on 404/403 pages

pontoon/base/models.py, pontoon/base/templates/latest_activity.html, pontoon/base/templates/translate.html, pontoon/base/templates/user.html, pontoon/base/templates/widgets/contributors.html, pontoon/base/views.py, pontoon/sync/formats/po.py, pontoon/sync/templates/sync/commit_message.jinja, pontoon/sync/tests/test_core.py, pontoon/sync/vcs/repositories.py
We present users differently in different places. I thought it would be nice to have a centralized place to generate all these display names.
@jotes r?
=> Centralize user name and email presentation

pontoon/base/templates/landing.html, pontoon/base/templates/latest_activity.html, pontoon/base/templates/translate.html, pontoon/base/templates/user.html, pontoon/base/templates/widgets/contributors.html, pontoon/base/templatetags/helpers.py
=> Prevent spam by using HTML entities in emails

pontoon/base/static/css/style.css, pontoon/base/static/css/terms.css, pontoon/base/templates/500.html, pontoon/base/templates/landing.html, pontoon/base/templates/terms.html, pontoon/base/templates/translate.html, pontoon/base/urls.py, pontoon/urls.py
=> Add Terms page

pontoon/sync/formats/silme.py
=> Fix bug 1236281: temporary hardcode special case for zh-CN

pontoon/base/static/js/translate.js, pontoon/base/views.py
=> Fix bug: enable approving in suggest mode

pontoon/sync/changeset.py, pontoon/sync/tests/test_changeset.py
Hi @mathjazz, could you review?
=> Bug 1211028: commiting only changed resources.

pontoon/base/models.py, pontoon/sync/formats/__init__.py, pontoon/sync/formats/l20n.py, pontoon/sync/formats/lang.py, pontoon/sync/formats/po.py, pontoon/sync/formats/silme.py, pontoon/sync/formats/xliff.py, pontoon/sync/tests/formats/__init__.py, pontoon/sync/tests/formats/test_l20n.py, pontoon/sync/vcs/models.py
Hi, i decided to split work into smaller reviewable parts. @mathjazz  Could you look at this? It's still in initial stage, i'll try to finish the rest asap.
=> Bug 1236109: Synchronization of l20n files.

pontoon/base/static/js/main.js
Hi @mathjazz could you review?
=> Fix bug 1214719: sort suggestions by stress and source

pontoon/base/static/js/main.js, pontoon/base/views.py
r=me.
Not escaping Transvision source text causes interesting things.
Also a bit of a cleanup.
=> Escape Transvision source text

pontoon/base/models.py, pontoon/base/views.py, requirements.txt
=> Update django pylibmc and don't prefetch latest activity for team and teams pages

pontoon/base/static/js/translate.js
Hi @mathjazz! Could you review?
=> Fix bug 1226759. A click on placeable replaces selected text.

pontoon/base/static/js/locale_project.js
Hi @mathjazz, I guess this is urgent issue.
=> Fix bug 1249990: Fixed the search query input.

pontoon/base/middleware.py, pontoon/base/tests/test_views.py, pontoon/base/views.py, pontoon/settings/base.py
=> Block IP addresses via settings variable BLOCKED_IPS

pontoon/base/static/js/main.js, pontoon/base/tests/test_views.py, pontoon/base/views.py
=> Fix machinery errors

docs/admin/deployment.rst, docs/dev/install.rst, pontoon/settings/base.py
=> Remove HMAC_KEY from the docs

pontoon/base/static/css/translate.css, pontoon/base/static/js/main.js, pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html
Parse comments for image links and present them in translation editor
@jotes r?
=> Display screenshots in translation editor

pontoon/base/static/js/pontoon.js
hi @mathjazz, could you look at this patch?
=> Fix bug 1225827. Set the lang and dir attributes on editable elements.

pontoon/base/static/js/main.js, pontoon/base/templates/base.html, pontoon/settings/base.py
@jotes r?
I had to switch to Persona API, because django_browserid API was hit by popup blocker (and I didn't investigate further).
=> Asynchronously load Persona to avoid blocking JS execution

pontoon/base/utils.py
=> Allow download if asymmetric file doesn't exist

pontoon/base/static/js/main.js, pontoon/base/static/js/translate.js
=> Fix bug 1252507: on menu open apply search input

pontoon/base/static/css/style.css, pontoon/base/static/js/main.js
hi! @mathjazz Could you check if this patch fixed problems mentioned by @MikkCZ ?
=> Fix bug 1255341. Fixed sorting of the results in the machinery.

pontoon/base/forms.py, pontoon/base/static/js/user.js, pontoon/base/templatetags/helpers.py, pontoon/base/views.py
hi @mathjazz could you review?
=> Fix bug 1258774 Sanitize first_name.

pontoon/settings/base.py, pontoon/sync/changeset.py, pontoon/sync/core.py, pontoon/sync/tasks.py, pontoon/sync/tests/test_changeset.py, pontoon/sync/tests/test_tasks.py
Hi @mathjazz, could you review?
=> Fix bug 1201431. Remove the obsolete resources.

pontoon/base/forms.py, pontoon/base/models.py, pontoon/base/static/css/style.css, pontoon/base/static/css/translate.css, pontoon/base/static/js/main.js, pontoon/base/static/js/pontoon.js, pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html, pontoon/base/templates/widgets/button.html, pontoon/base/urls.py, pontoon/base/views.py
This is not ready for a review yet.
=> Bug 983096: Batch operations

pontoon/sync/formats/xliff.py, requirements.txt
=> Bug 1257812 xliff output

pontoon/base/templates/translate.html
First time I opened this function, I was a little confused about to what strings the actions would apply (if the square works as a button for opening the action menu (because it's "pop" effect steals your focus), or a checkbox.
=> Better info about what translation actions do

pontoon/base/models.py
=> Fix bug 1264012: Search only translations for current locale

pontoon/base/static/css/style.css
=> Fix bug 1229079: dynamic search input padding

pontoon/sync/management/commands/sync_projects.py, pontoon/sync/tasks.py, pontoon/sync/tests/test_sync_projects.py
=> Bug 1214411: Add ability to sync specified locales only

pontoon/base/static/css/style.css, pontoon/base/static/css/translate.css, pontoon/base/static/js/main.js, pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html, pontoon/base/templates/widgets/keyboard_shortcut.html
=> Fix bug 1233979: Make keyboard shortcuts more visible

pontoon/base/tests/test_views.py
hi @mathjazz, could you review? This PR fixes errors on the master branch.
=> Fixed test_last_activity.

pontoon/base/static/js/translate.js
=> Fix bug 1267554: Prevent simultaneous getEntities() requests

pontoon/administration/static/css/admin_project.css, pontoon/base/static/css/search.css, pontoon/base/static/css/translate.css
r=me
Tried to keep the general CSS file (`style.css`) unchanged to avoid unexpected surprises.
=> Fix broken menus when scrollbars are displayed

pontoon/base/static/css/style.css, pontoon/base/templates/widgets/progress_chart.html
=> Fix bug 1271331: Do not overflow progress chart

pontoon/base/static/js/translate.js, pontoon/base/views.py
@jotes r? This can totally wait before we merge #382.
=> Fix bug 1272958: Go to next entity if same translation exists

pontoon/base/models.py, pontoon/sync/formats/__init__.py, pontoon/sync/formats/ftl.py, pontoon/sync/tests/formats/test_l20n.py, requirements.txt
@zbraniecki r?
I'm leaving the original L20n file format support in the codebase for now. We should remove it eventually.
=> Add support for the L20n's FTL format

pontoon/base/admin.py, pontoon/sync/admin.py
A step towards switching to Django admin
r=me
=> Admin optimization

pontoon/base/static/js/main.js, pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html
=> Update keyboard shortcuts

pontoon/sync/tasks.py, pontoon/sync/vcs/models.py
=> Update stats when entities or resources become obsolete

pontoon/base/models.py, pontoon/sync/utils.py, pontoon/sync/vcs/models.py
=> Add locales to repository if not yet available

docs/dev/install.rst
I'm setting up Pontoon right now and I think it would be helpful to list all dependencies explicitly in a form of a `apt install` one-liner for people using Ubuntu.  Let's keep this PR open in case I find more things that I'd like to add.
=> Update docs with a apt one-liner

docs/admin/deployment.rst, docs/dev/install.rst, pontoon/settings/__init__.py, pontoon/settings/dev.py, requirements-dev.txt, requirements.txt
Hi @mathjazz,
Could you look at these tools?
Django debug toolbar will be helpful during tracking possible performance issues and django extensions have a pretty neat set of commands like shell_plus (loads all models automatically).
=> Small tools that are helpful during the development.

pontoon/sync/formats/ftl.py
=> FTL: Parse entire entities, including traits

pontoon/sync/core.py, pontoon/sync/tasks.py, pontoon/sync/tests/test_tasks.py, pontoon/sync/vcs/models.py
Properly import newly added asymmetric files.
Sadly most of the code is about passing the list of newly added files around.
@jotes r?
=> Create TranslatedResource for newly added asymmetric file

pontoon/base/views.py
=> Fix deleting

pontoon/base/static/js/translate.js
=> Prevent double translation submissions which break stats

pontoon/base/models.py
hi @mathjazz,
I discovered this issue after I tried to create new migrations. Could you apply this patch and check if you can create migration?h
=> Fixed Manager that broke Django migrations.

pontoon/sync/vcs/models.py
This is an improvement over #408, which introduced adding locales to
projects, even if they their respective folders weren't present in the
repository.
While #408 made this possible, it broke sync if locale that wasn't
enabled in the repository was added to the project and a new source
file was added to the project.
@jotes r?
=> Do not break sync if file added and not all locales in repo

requirements.txt
=> Fix bug 1287575: Django security update

pontoon/base/models.py, pontoon/base/views.py
=> Add more details to project request email

pontoon/sync/vcs/models.py
Detecting which on the list of changed files since the last sync is
an actual resource file and which locale does it belong to could take
minutes, now it should take seconds.
@jotes r?
This is a quite significant improvement. Due to this bottleneck, sync sometimes runs significantly faster with the `--force` flag (which syncs all resources)!
=> Optimize detecting relevant changed files

pontoon/base/models.py, pontoon/sync/models.py, pontoon/sync/tasks.py, pontoon/sync/vcs/models.py
While working on #440, I also noticed a few nits to make code slighlty more readable.
@jotes r?
=> Refactor changed locale files detection

pontoon/base/static/js/pontoon.js, pontoon/base/static/js/translate.js
@jotes r? I know this is tedious review, so if you don't feel comfortable doing it, just let me know.
It's a few bugfixes, code cleanups and most of all - live updating in-context translations as you change them in the editor. Sadly there's now good way of detecting changes to translation `textarea`, so we have to make a number of function calls.
=> Live update in context

requirements.txt
=> Properly serialize strings with quotes in DTD files

pontoon/base/utils.py
=> Fix bug 1292889: Mark {{variables}} as placebles

pontoon/sync/utils.py, pontoon/sync/vcs/models.py
=> Use appropriate locale separator when creating folders

pontoon/base/templates/translate.html
As described in https://github.com/mozilla/pontoon/pull/449#issuecomment-239624613
=> Add helper tabs tooltips.

pontoon/base/tests/test_models.py
=> Test missing filter for partially translated pluralized strings

pontoon/base/static/css/translate.css, pontoon/base/static/js/jquery.mark.js, pontoon/base/static/js/translate.js, pontoon/settings/base.py, pontoon/sync/tasks.py
Hi @mathjazz,
Could you look at this?
=> Bug 1243118. Added highlight of search results.

pontoon/base/models.py, pontoon/base/static/css/translate.css, pontoon/base/static/css/users.css, pontoon/base/static/js/main.js, pontoon/base/static/js/translate.js, pontoon/base/templates/500.html, pontoon/base/templates/landing.html, pontoon/base/templates/translate.html, pontoon/base/templates/user_settings.html, pontoon/base/templates/widgets/contributors.html, pontoon/base/urls.py, pontoon/base/views.py
Changes:
Use user id in JS.
Use roles instead of emails contributors' lists.
Additionaly: fixed links on MDN
=> Fix bug 1299084 - Use email only if user didn't specify their name

pontoon/base/static/js/pontoon.js
Hardcode jQuery path and check trusted origins on postMessage.
=> Fix bug 1302583

pontoon/base/models.py, pontoon/base/static/css/translate.css, pontoon/base/static/css/users.css, pontoon/base/static/js/translate.js, pontoon/base/templates/widgets/contributors.html, pontoon/base/views.py
=> Bug 1299084: fix performance regression in contributor roles

requirements.txt
=> Fix bug 1305559: Django security update

pontoon/base/migrations/0067_migrate_old_django_browserid.py
=> Make from_django_browserid migration reversible

pontoon/base/models.py
@jotes r?
What is this?
Currently, if a project has subpages defined, we only list those pages in locale-project pages and in the parts menu. If new resources are added to repository, we don't list them, but we show their strings when "All Resources" is selected. So much for the consistency.
With this patch, we also list all other resources available for locale, that are not bound to any subpage. This helps us when new resources are added to project without a notice to update the project setup.
=> List resources not bound to subpages

pontoon/base/adapter.py
@mathjazz Hi, could you look at this patch? This should solve an issue mentioned by flod but it needs testing the rest of scenarios.
=> Fixed merging of accounts.

pontoon/base/static/js/main.js
=> Encode Transvision URL component to avoid self-XSS

requirements.txt
=> Replace django-allauth with a fork

docs/dev/install.rst
=> fix bug 1310510 - make install instructions more user-friendly

pontoon/base/models.py
=> Add help text to plural-related Locale fields

pontoon/base/models.py
@mathjazz I fixed [this issue](https://github.com/mozilla/pontoon/pull/463#issuecomment-257048719). Also make `authored_by` and `between_time_interval` to return Qs.
I don't know why but time range filter requires to apply first, in this way your combination works fine.
r?
=> Fix bug 1243115 - fixed issue with suggested & time-range filter

pontoon/base/static/js/translate.js
=> Fix bug 1313870 - Update number when deleting a history entity

pontoon/base/static/css/style.css, pontoon/base/tests/test_adapter.py, pontoon/settings/base.py, pontoon/settings/dev.py
=> Remove Persona remains

pontoon/base/models.py, pontoon/sync/formats/__init__.py, pontoon/sync/vcs/models.py
An Alternative .xliff file extension
@jotes r?
=> Add support for .xlf

pontoon/administration/static/css/admin_project.css, pontoon/administration/static/js/admin_project.js, pontoon/administration/templates/admin_project.html, pontoon/base/urls.py, pontoon/base/views.py, pontoon/settings/base.py
@jotes r?
This functionality allows admins to e.g. set projects up on staging server and see if they sync.
=> Manually trigger sync from project administration

.travis.yml, README.md, app.json, bin/heroku_postdeploy, docs/admin/deployment.rst, pontoon/allauth_urls.py, pontoon/base/middleware.py, pontoon/base/static/css/style.css, pontoon/base/templates/django/base.html, pontoon/base/templates/js/pontoon.js, pontoon/base/templates/landing.html, pontoon/base/templates/registration/login.html, pontoon/base/templates/translate.html, pontoon/base/templatetags/helpers.py, pontoon/base/tests/__init__.py, pontoon/base/tests/test_views.py, pontoon/base/urls.py, pontoon/base/views.py, pontoon/settings/base.py, pontoon/settings/dev.py, pontoon/urls.py
I accidentally force pushed my master branch.
This is a continuation of https://github.com/mozilla/pontoon/pull/446 .
Ref. bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1316171
=> Heroku app json

bin/heroku_postdeploy
Hi @mathjazz!
I successfully tested this PR on a couple of installations, could you look if this helps in your case?
=> Wait for memcached during a build on Heroku.

docs/admin/deployment.rst
@mathjazz Hi, could  you look at this?
=> Fix bug 1286062: Added dmathieu's buildpack to docs.

pontoon/base/models.py, pontoon/base/static/css/translate.css, pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html, pontoon/base/tests/test_models.py, pontoon/base/tests/test_views.py, pontoon/base/utils.py, pontoon/base/views.py
Hi, I decided to help and provide some small refactorings and solve problems with combined filters.
=> Bug 1243115 revival

pontoon/sync/tasks.py
It's a regression introduced by 19c0f089e0b11237c1c15c6ce65173a9222d0e43
r=me
=> Fix error in sync_translations_error()

pontoon/administration/templates/admin_project.html, pontoon/administration/views.py
=> Fix server error when adding a project without download prefix

pontoon/base/templates/user.html
@mathjazz This should solve the situation on production. I'll try to add more tests for this future to be sure that won't happen in the future!
=> Bug 1225109: fixed timeline reference url.

pontoon/base/tests/test_views.py, pontoon/base/urls.py, pontoon/base/views.py
@mathjazz couple of tests related to the implementation of new timeline.
=> Bug 1225109: added test for contributors profile page.

pontoon/base/static/js/request_projects.js
Thanks @deimidis for reporting!
r=me
=> Prevent openning project page from the request panel

pontoon/base/static/js/translate.js
=> Allow copying text from helpers suggestions

pontoon/base/views.py
Thanks @ibrahimasarr for reporting!
=> Fix uploading files, 1c24429 regression

pontoon/base/templates/js/pontoon.js, pontoon/settings/base.py
@mathjazz could you look at this?
=> Added integrity hash for a remote jQuery library.

pontoon/base/models.py, pontoon/base/static/css/manage_permissions.css, pontoon/base/static/js/manage_permissions.js, pontoon/base/templates/locale_permissions.html, pontoon/base/templates/widgets/multiple_choice.html, pontoon/base/views.py
4 smaller improvements to the permissions page. Details in commit messages.
@jotes r?
=> Permissions frontent improvements

pontoon/base/static/css/style.css, pontoon/base/static/js/main.js, pontoon/base/static/js/translate.js
=> Fix bug 1333659: Restore &nbsp; highlights

pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html
We keep the permission checking code on both sides, server and client
(for performance reasons). We only updated server side code in previous
commit.
@jotes r?
=> Fix bug 1331710: Update canTranslate() in JS

package.json
Also update babel to latest version.
@jotes r?
=> Fix bug 1336984: Update to latest LTS node.js

pontoon/base/migrations/0044_locale_translators.py, pontoon/base/models.py, pontoon/base/tests/test_models.py
Hi @mathjazz, could you review?
This is a quick hotfix against issue reported by @davida
=> Bug 1342613 fix createsuperuser.

pontoon/localizations/views.py
=> 404 instead of 500 if ProjectLocale doesn't exist

pontoon/base/templates/widgets/heading_info.html
=> Fix translate links on localization dashboard

pontoon/base/static/css/style.css, pontoon/base/static/js/table.js
=> Fix arrow direction and color in tables

pontoon/base/static/js/translate.js, pontoon/base/utils.py, pontoon/base/views.py
@mathjazz Hi, could you look at this?
=> Fix bug 1344322: respect DATA_UPLOAD_MAX_NUMBER_FIELDS in the batch editor.

pontoon/base/static/css/style.css, pontoon/base/static/css/translate.css, pontoon/base/static/js/main.js, pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html, pontoon/teams/static/js/request_projects.js
3 frontend fixes in the translate view, related to the dashboard redesign.
Separate commit for each fix. See commit messages for details.
Especially the first one is very annoying and should land rather soon.
@jotes r?
=> Translate frontend bugfixes

docs/dev/install.rst, pontoon/base/migrations/0044_locale_translators.py, pontoon/base/models.py, pontoon/sync/management/commands/sync_projects.py, pontoon/sync/tests/test_sync_projects.py
=> Fix management command

pontoon/sync/management/commands/sync_projects.py
=> Fix sync of all projects.

pontoon/administration/static/css/admin_project.css, pontoon/administration/static/js/admin_project.js, pontoon/administration/templates/admin_project.html, pontoon/administration/views.py
Adding ability to copy enabled locales from one project to another.
Split into two commits for easier review.
@jotes r?
=> Copy locales from another projects

pontoon/contributors/static/js/contributor.js
@mathjazz Hey, could you look at this?
=> Fix bug 1348577 - Update css selector for user name input.

pontoon/administration/forms.py, pontoon/base/admin.py, pontoon/localizations/templates/localizations/localization.html, pontoon/projects/templates/projects/project.html
And fix the ability to add project contact through Pontoon Admin.
=> Show project contact in dashboards

pontoon/base/admin.py, pontoon/base/middleware.py, pontoon/settings/base.py
Automatically logs in the user with username `ADMIN_EMAIL` and password
`ADMIN_PASSWORD` if `AUTO_LOGIN` enabled. Useful in demo environment.
@jotes r?
=> Add ability to automatically log in a user

pontoon/base/static/js/translate.js, pontoon/base/tests/test_views.py, pontoon/base/views.py
Hi @mathjazz 
I take a small break from Terminology, I'll do a few small bugs and then resume working on Terminology (this weekend)
Could you look at this?
=> Fix bug 1350695 Suggest button posts suggestions between different browser tabs.

requirements.txt
=> Fix bug 1353419: Upgrade Django to 1.10.7

bin/mozilla-en-US.py
=> Update en-US repo script to include central

pontoon/base/static/css/translate.css, pontoon/base/static/js/main.js, pontoon/machinery/static/js/machinery.js, pontoon/machinery/templates/machinery/machinery.html
A few bug fixes I discovered while working on #575.
@jotes r?
=> A few frontend bugfixes

pontoon/urls.py
=> Redirect legacy Aurora projects

requirements.txt
=> Fix bug 1357425: Upgrade to latest Mercurial

bin/make-langpacks.py
=> Update langpack script to use mozilla-central

pontoon/base/models.py
=> Fix missing string search regression

pontoon/base/forms.py
This is really just a trivial copy and paste.
@jotes r?
=> Mode related form code blocks together

pontoon/base/models.py, pontoon/base/static/css/style.css, pontoon/base/static/css/translate.css, pontoon/base/static/js/main.js, pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html, pontoon/base/views.py, pontoon/contributors/static/css/profile.css, pontoon/contributors/templates/contributors/includes/timeline.html
@jotes r?
Outcome already approved in the bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1357919#c6
=> RTL fixes (+ Locales tab sorting)

pontoon/base/models.py, pontoon/base/static/css/style.css, pontoon/base/static/css/translate.css, pontoon/base/static/js/main.js, pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html, pontoon/base/views.py, pontoon/contributors/static/css/profile.css, pontoon/contributors/templates/contributors/includes/timeline.html
=> Revert "RTL fixes (+ Locales tab sorting)"

pontoon/base/models.py, pontoon/base/static/css/style.css, pontoon/base/static/css/translate.css, pontoon/base/static/js/main.js, pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html, pontoon/base/views.py, pontoon/contributors/static/css/profile.css, pontoon/contributors/templates/contributors/includes/timeline.html
r=me
This is a fix for mistakenly squashed #585.
=> Rtl fixes 2

pontoon/sync/tasks.py
=> Log repo pull start and end

pontoon/base/static/js/table.js
Hi @mathjazz 
I'm not sure if latest-activity should behave in the same way -> I can restore previous behaviour if you want.
=> Change sorting for deadlines/last activity.

docs/dev/install.rst
=> Update docs with MANUAL_SYNC

pontoon/base/static/js/main.js
Markup diff between the original string and the TM source string
@jotes r?
=> Fix bug 1354223: Show diff in Machinery

pontoon/base/static/js/translate.js
=> Fix bug 1324936. Add link to resource in the translation tab.

pontoon/base/static/js/fluent_interface.js, pontoon/base/static/js/translate.js
=> Fix FTL regressions

pontoon/base/models.py, pontoon/base/views.py
Store Translation Memory on batch editing actions (approve and search & replace).
@jotes r?
Note: This is branched off #601.
=> Translation Memory fix

pontoon/base/static/js/translate.js
=> Fix bug 1355850: check unsaved changes when entering batch editing

pontoon/base/static/js/tabs.js, pontoon/teams/static/js/bugzilla.js
Fixes Turkish contributors tab.
And another bug I found along the way (JS error if bug list empty for a locale).
@jotes r?
=> Fix bug 1363320: Properly compose tab URLs

pontoon/base/static/js/translate.js
=> Fix bug 1366164: Prevent too long translations on approval

pontoon/base/views.py
=> Prevent AttributeError when batch approving approved translations

pontoon/sync/changeset.py, pontoon/sync/tasks.py, pontoon/sync/tests/test_changeset.py
@jotes r?
See more details in commit messages.
=> Bug 1361017 do not remove obsolete from vcs

pontoon/base/models.py, pontoon/projects/templates/projects/includes/teams.html, pontoon/projects/views.py, pontoon/teams/templates/teams/includes/projects.html, pontoon/teams/views.py
It should speed up Project and Team dashboard default tabs by some 20 %.
@jotes r?
=> Use prefetched ProjectLocales on team/project dashboards

pontoon/sync/models.py
This is a temporary fix for bug 1310668. We recalculate any broken stats when the sync task completes.
@jotes r?
=> Bug 1310668: Recalculate stats when sync completes

pontoon/base/static/js/main.js, pontoon/base/static/js/translate.js
The current implementation makes `django-pipeline` throw an error on compression.
@jotes r?
=> Bug 1377830: Remove duplicates from array without using ES6

pontoon/base/models.py, pontoon/base/tests/test_models.py, pontoon/base/views.py
@jotes r?
Fixing bug reported by @jordis.
=> On translation delete, remove corresponding TM entry

docs/dev/fluent.rst, docs/index.rst, pontoon/base/static/js/fluent_interface.js, pontoon/base/static/js/lib/fluent-syntax.js, pontoon/sync/formats/ftl.py, requirements.txt
@mathjazz @stasm could you look if everything is okay? I tested that manually and results are visible here:
https://github.com/jotes/pontoon-intro/commit/2c283146a365e088a27f528f3caa8ed42aa95a4b
I'm not sure if that's an expected result of serialization.
=> Bug 1237667 - bumped python-fluent to 0.4.1

.dockerignore, .gitignore, Makefile, docker-compose.yml, docker/Dockerfile, docker/Dockerfile.base, docker/config/webapp.env, docker/entrypoint.sh, docker/run_tests_in_docker.sh, docker/run_webapp.sh, docker/set_up_ubuntu.sh, docker/set_up_webapp.sh, docs/dev/install-docker.rst, docs/dev/workflow.rst, docs/index.rst, docs/requirements.txt, requirements.txt
This is not fully ready yet, as I think it is missing some important features. Those are:
=> Fixes bug 1376813 - THIS... IS... DOCKER!

docker/Dockerfile, docs/dev/install-docker.rst
=> Bug 1384491 - Add note on Docker doc about git submodules

pontoon/projects/templates/projects/widgets/project_list.html, pontoon/teams/static/css/team.css, pontoon/teams/static/js/request_projects.js, pontoon/teams/templates/teams/includes/projects.html
* Ask for confirmation (plenty of emails sent without wanting to)
* Add explanation note on how the process works
=> Improve new projects request

pontoon/machinery/templates/machinery/microsoft_terminology.jinja, pontoon/machinery/views.py, pontoon/settings/base.py, requirements.txt
Suds library is deprecated and will not support python 3
=> use requests and jinja2 template instead of external suds library (deprecated)

pontoon/base/static/js/fluent_interface.js, pontoon/base/static/js/translate.js
Details in commit messages.
@jotes r?
=> Fixes for a few FTL bugs

requirements.txt
@mathjazz I'm not too sure how to test this. Unit tests pass, but I'm afraid the ``oauthlib`` update might break stuff.
=> Fix bug 1386632 - Update python packages rsa and oauthlib.

pontoon/settings/base.py, pontoon/teams/static/css/team.css, pontoon/teams/static/js/info.js, pontoon/teams/templates/teams/includes/info.html, pontoon/teams/urls.py, pontoon/teams/views.py, requirements.txt
Fix bug 1343804 - Edit team info
=> Bug 1343804: Add ability to save and edit team information

pontoon/base/models.py, pontoon/base/static/css/style.css, pontoon/base/static/css/translate.css, pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html, pontoon/base/tests/test_models.py, pontoon/base/tests/test_views.py
Let's make it easier to find rejected suggestions.
=> Fix bug 1389084: Add Rejected Suggestions filter

pontoon/base/static/css/translate.css
=> Fix bug 1389933: Make rejected opaque on hover

pontoon/base/static/css/translate.css
=> Fix bug 1383483: Set #source iframe background to white

pontoon/machinery/views.py
=> Properly validate Microsoft Translator and Terminology locales

pontoon/base/views.py, pontoon/machinery/views.py
=> Fix bug 1390047: Exclude rejected and unreviewed from TM

pontoon/administration/forms.py
=> Make project info field optional again

pontoon/sync/changeset.py
If an existing translation is made fuzzy in the VCS, we mark it as
fuzzy in the DB on next sync, but don't unapprove it. That is because
two separate instances of the same translation are passed to
bulk_update - the first one sets the fuzzy flag and the second one
unsets the approved flag. bulk_update only executes the first instance,
so now we properly set all flags on it and don't pass the second one.
Note: this only applies to translations that are made fuzzy in the
locale file. Most of the time a new source strings is created when
existing translation are made fuzzy on msgmerge. This case already
behaves properly.
@jotes r?
=> Bug 1381852: Unapprove fuzzy translations on import

pontoon/base/utils.py, pontoon/sync/changeset.py, pontoon/sync/tests/test_changeset.py
@jotes r?
This is actually easier than it looks - please check out the 2nd commit. The first commit is just code cleanup that makes things a little easier to understand.
=> Bug 1391049 reject approved vcs

README.md
...just to make them more discoverable.
=> README: also link to existing bugs

pontoon/base/static/js/translate.js
=> Fix bug 1396080: Encode non-encoded querystring

requirements.txt
Tests are passing. I tested locally with the most common views, tasks and a little bit of sync.
=> Upgrade to latest Django

pontoon/contributors/static/js/settings.js
Without this fix, user's hompage changes everytime you pick preferred locale.
=> Bug 1398683: Narower homepage selector

pontoon/machinery/static/js/machinery.js, pontoon/teams/static/js/team_selector.js, pontoon/teams/templates/teams/widgets/team_selector.html
We need to pass locale codes for Microsoft Terminology and Microsoft
Translator, as well as Transvision flag for the locale to the template,
so JS can read it and use it.
=> Fix bug 1399431: Fix JS error on Machinery

pontoon/base/models.py
I haven't solved anything, but at least this piece of code should be more readable now.
=> No bug - Rewrite the filter_* methods into a function.

pontoon/base/forms.py, pontoon/base/models.py, pontoon/base/static/js/translate.js, pontoon/base/tests/test_models.py, pontoon/base/tests/test_views.py, pontoon/base/views.py
@mathjazz I was reading through this code to make sure I actually understand it well, in order to make sense of our optimization goal, and thought that I could make some things slightly better. One thing leading to another, I ended up with this not-so-small refactoring of the ``entities`` view. 
I do not know what to make of this. Maybe it isn't valuable to merge it, as surely it introduces risk (I'm not confident the current code coverage protects well enough against regression in a code that is that complex). I'm also not sure it's even that much better than the current code. I do like the use of a ``Form`` in that view, but I'm not fond of the separation in functions. I guess what I would really want to do is to split this view into 3 or 4 independent views, instead of having one view …
=> Refactor the entities view into smaller functions.

Makefile
=> Fix bug 1399037 - Fix building docker containers on Mac OS.

pontoon/base/templates/base.html, pontoon/base/templates/translate.html
=> Fix bug 1402673: fix title tag base

pontoon/settings/base.py
I've successfully tested this on stage. 
@stasm r?
=> Bug 1302053 - Fix CORS access for the API.

.travis.yml, pontoon/allauth_urls.py, pontoon/base/admin.py, pontoon/base/celeryapp.py, pontoon/base/models.py, pontoon/base/signals.py, pontoon/base/templatetags/helpers.py, pontoon/base/tests/__init__.py, pontoon/base/tests/test_models.py, pontoon/base/tests/test_views.py, pontoon/base/utils.py, pontoon/urls.py, pontoon/wsgi.py, pylama.ini
It's a brave new world! 
Note: I need to verify if we run pylama on builds in travis. @jotes @mathjazz do you know if we do?
=> Fixes bug 1384139 - Fix all remaining PEP8 violations in Pontoon.

pontoon/base/utils.py, pontoon/sync/changeset.py, pontoon/sync/tests/test_changeset.py
@adngdb or @jotes r?
See [bug 1406974](https://bugzilla.mozilla.org/show_bug.cgi?id=1406974) for more details.
=> Fix bug 1406974: Fix file upload

pontoon/base/models.py, pontoon/base/tests/test_models.py, pontoon/base/tests/test_views.py
There is one last test that is failing, and it's a mocking issue. I'll finish this next week, but that shouldn't have any impact on the actual code, so @mathjazz if you want to review this now, feel free! 
Note that I also haven't tested this with the Search across all projects feature yet.
=> Fix bug 1377099 - Speed up status filters

pontoon/base/static/js/fluent_interface.js
Add dir, and lang attributes to l20n inputs https://bugzilla.mozilla.org/show_bug.cgi?id=1387972 .
=> Fix Bug1387972 Set lang and dir attributes on l20n inputs

Makefile
=> Add dockerdebug make target to allow pdb debugging

.codecov.yml, .travis.yml, requirements-test.txt, requirements.txt, setup.cfg
its really helpful to see what code is/not tested in PRs, to see what is currently not tested, and to monitor over time.
=> Fixes #1416269 Add coverage to Pontoon

nltk.txt, requirements.txt
=> Fix bug 1418270 Bump Caighdean requirement to fix Heroku

pontoon/api/schema.py, pontoon/api/tests/test_schema.py, requirements.txt
https://bugzilla.mozilla.org/show_bug.cgi?id=1411955
=> Bug 1411955 - Upgrade to Graphene 2.0

bin/post_compile, docker/run_webapp.sh
@jotes @mathjazz r? 
I haven't tested it on heroku yet, because I don't want to mess with our stage server now. So I'm counting on your knowledge of heroku to confirm that this is the right way to implement that feature. :)
=> Fix bug 1421317 - Expose current git revision sha in web app.

tests/base/fixtures.py, tests/env.py, tests/fixtures/factory.py, tests/fixtures/locales.py, tests/fixtures/project_locales.py, tests/fixtures/projects.py, tests/fixtures/resources.py, tests/fixtures/site.py, tests/fixtures/translated_resources.py
Adds:
- some further fixtures for base models
- a `factories` fixtures for easier accessing of fixtures
- a `site_matrix` fixture that loads a load of related projects/locales/project_locales/resources/translated_resources etc
=> Touch bug #1417530 Add more fixtures

pontoon/base/static/css/translate.css, pontoon/base/static/js/fluent_interface.js, pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html
SInce we found bugs in the original FTL patch, I'm reverting both of them until they're fixed, making it possible to deploy other changes we landed this week.
=> Revert FTL changes

bin/post_compile
=> Fix bug 1421317 - Fix writing current revision sha during heroku deployment.

pontoon/base/static/css/translate.css, pontoon/base/static/js/fluent_interface.js, pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html
In this PR I'll fix bugs that forced us to revert the source view patches.
The 1st commit (f3380a4) makes reverting the reverts possible and the 4th (b263770) applies what the 1st commit reverted.
So only the commits following the 4th one are in need of a review.
=> Source view 2nd attempt

pontoon/base/static/css/translate.css, pontoon/base/static/js/fluent_interface.js, pontoon/base/static/js/translate.js
NOTE: This is branched off #777. Only https://github.com/mozilla/pontoon/commit/1337f165b32da3bbfa3a92bddbbbe5b9e6618d22 should be reviewed.
=> Fix bug 1382348: Mark placeables

README.md
[Docs] - README.md -> minor spelling tweaks
=> [Docs] - README.md -> minor spelling tweaks

CONTRIBUTING.rst
[Docs] - Contributing - minor spelling tweaks
=> [Docs] - Contributing - minor spelling tweaks

pontoon/base/static/js/fluent_interface.js
@adngdb or @Pike or @jotes If anyone is still around to have a look at this, I'd appreciate it.
=> Fix bug 1426835: Do not render HTML in FTL strings

pontoon/base/static/js/fluent_interface.js, pontoon/base/static/js/translate.js
=> Fix bug 1427048: Fix tab shortcut regression

tests/base/fixtures.py, tests/fixtures/factory.py, tests/fixtures/site.py, tests/fixtures/translated_resources.py
this will also ease the landing of #766
=> Touch bug 1417530: Add more fixtures

pontoon/base/static/js/fluent_interface.js
I've added a test case here:
https://github.com/mathjazz/pontoon-ftl/blob/master/en-US/demo.ftl#L19
=> Fix bug 1430941: Support strings with value and attributes

docker/Dockerfile, docker/entrypoint.sh, docker/run_webapp.sh, docker/set_up_env.sh, docker/set_up_ubuntu.sh, docker/set_up_webapp.sh
turns out that its better to have this in image build, as @adngdb suggested (apologies)
~~as it stands this creates nvm in roots env, so  this needs a bit of work~~
this also ensures that ~~all app stuff is done as~~ the nvm/npm env is created for the app user
=> Docker fixes

.eslintignore, .eslintrc.js, .travis.yml, package.json, tests/js/foo.js
Adds jest and enzyme testing to the test env, and eslint, altho its set to not fail for now
=> Touch Bug 1243129: Js testing and linting

.travis.yml, package.json, tests/js/__setup__/index.js
Some updates to test env to enable js testing and improve travis efficiency
=> Touch bug #1416256: Some test updates

tests/fixtures/factory.py, tests/fixtures/tags.py
This provides fixtures for #766 - mostly to separate the test logic from the implementation for easier review.
~~It (will) also provides a glob to regex function that is needed in above PR~~
=> Touch #1416256 String tiers - add tag test fixtures

package.json, pontoon/static/js/utils/ajax.js, pontoon/static/js/utils/strip.js, pontoon/static/js/widgets/columns.js, tests/js/utils.js, tests/js/widgets.js
Add some basic react widgets (...and tests!)
=> Touch Bug 1243129: React utils and widgets

pontoon/base/forms.py
@MikkCZ r?
This is currently deployed to [stage](https://mozilla-pontoon-staging.herokuapp.com/settings/).
Note to self: we should announce the ability to change email on the mailing list.
=> Bug 1335331: Rename first_name to name

.gitignore, docs/dev/install.rst, package-lock.json
A collection of dev install updates, related to webpack.
Note on `package-lock.json`:
https://stackoverflow.com/a/44210813
=> Bug 1243129: Webpack updates

pontoon/base/views.py, tests/base/views/ajax.py
This adds some base "class-based-views" for handling ajax requests.
It always returns JSON, and defers to the form.
Its required for the view used in #823 
...just adding some tests...
=> Touch #1416256:  Add base ajax form class based views

pontoon/base/models.py, pontoon/teams/templates/teams/includes/permissions.html, pontoon/teams/views.py, tests/teams/views.py
Hey, @mathjazz 
I know there're missing tests, however I decided to push it to check if you agree with how this should look like.
TODO:
=> [WIP] Fix bug 1432179 - Sort contributors by email

README.md
@mathjazz in the light of all those students who are turning their eyes on Pontoon for GSoC, I'd like to generally improve our documentation. This is a first step. What do you think?
=> No bug - Rework readme file to make it easier for new contributors.

.eslintrc.js, .travis.yml, pontoon/administration/static/js/admin_project.js, pontoon/base/static/js/fluent_interface.js, pontoon/base/static/js/main.js, pontoon/base/static/js/multiple_locale_selector.js, pontoon/base/static/js/progress-chart.js, pontoon/base/static/js/table.js, pontoon/base/static/js/tabs.js, pontoon/base/static/js/translate.js, pontoon/contributors/static/js/notifications.js, pontoon/projects/static/js/manual_notifications.js, pontoon/teams/static/js/permissions.js, pontoon/teams/static/js/request_projects.js
cleanup failing eslint javascript - this might catch a couple of bugs, reduces noise, and means we can prevent the problem getting worse
=> Fix Bug 1437273: Cleanup failing eslint

pontoon/base/static/js/translate.js
fixes bug found by @mathjazz created in c96bbe5698be0da31bb0cfa10d0d306d6533c675
=> Fix for bug created eslinting

pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html
Fixed removal of .selected class even though it is selected which
gets removed due to updation each time filter option is clicked.
=> Fix bug 1389724: Fixed author select filter UI

pontoon/settings/base.py
@mathjazz @phlax any idea how I can test that? I pushed the change to stage and nothing broke, but I do not know how to verify that the connection is using SSL.
=> Fix bug 1435010 - Require SSL for connecting to PostgreSQL.

pontoon/static/js/errors/index.js, pontoon/static/js/utils/datetime.js, tests/js/utils/ajax.js, tests/js/utils/datetime.js, tests/js/utils/strip.js, tests/js/widgets/checkbox.js, tests/js/widgets/columns.js, tests/js/widgets/errors.js
this 
- fixes a js test error
- separates out some of the js tests 
- adds a `NotImplementedError`
- adds an l10n Datetime formatter
- ~adds `Humanize` lib for l10n numbers etc~
=> Touch Bug 1243129: Mixed bag of JS cleanups/updates

pontoon/base/static/js/main.js
=> Fix bug 1439543: Add rel="noopener noreferrer" to JS links

.travis.yml
add collations into travis env
(...so that we can...) add some tests to ensure collation lookups work correctly with db
=> Touch Bug 1440940: Add tr locale in travis env

.travis.yml, tests/env.py
- add collation in the pytest env
- remove collation from travis setup as this did not seem to work for the test db
=> Touch Bug 1440940: Collation test env

pontoon/static/js/widgets/tables/checkbox.js, pontoon/static/js/widgets/tables/index.js, tests/js/widgets/tables/checkbox.js
Adds a react checkbox table, where you can de/select all and it can submit the visibly selected
=> Touch Bug #1416256: React checkbox table widget

tests/base/managers/entity.py
I have added the required tests for checking collations. @phlax thanks a lot!
=> Fix bug 1440940:Add tests to prevent regression in collation lookups.

pontoon/base/templates/terms.html
See [bug 1443584](https://bugzilla.mozilla.org/show_bug.cgi?id=1443584) for more details.
=> Fix bug 1443584: Link to Mozilla Community Participation Guidelines

pontoon/tags/exceptions.py, pontoon/tags/utils/__init__.py, pontoon/tags/utils/resources.py, tests/tags/utils/resources.py
Adds a Resources util for adding/removing resources from tags according to project and project set up
it does the following
- search for linked resources
- search for not linked resources
- un/link resources
=> Touch Bug #1416256: String tiers resources util

docker/run_tests.sh, docker/run_tests_in_docker.sh
This commit adds a new run_tests file that runs all our current linters and tests, and puts the docker environment to parity with travis. This way we can easily run the entire test suite locally.
=> No bug - Run all tests and linters during make dockertest.

pontoon/tags/admin/forms.py, tests/tags/forms.py
Adds an admin form for un/linking resources to/from tags
~~just tidying tests...~~
used in #802
=> Touch Bug #1416256: String tiers admin form

pontoon/static/js/tags/admin/button.js, pontoon/static/js/tags/admin/manager.js, pontoon/static/js/tags/admin/search.js, pontoon/static/js/tags/admin/table.js, pontoon/static/js/tags/admin/tag-resources.css, pontoon/static/js/widgets/tables/checkbox.js, pontoon/static/js/widgets/tables/index.js, tests/js/tags/admin.js, tests/js/widgets/tables/checkbox.js
Just the react admin widget and tests for adding/removing resources from tags
also some cleanup/fixes for checkbox widget
Broken out from #815 
Used in #802
=> Touch #1416256: String tiers admin widget

pontoon/administration/urls.py, pontoon/base/utils.py, pontoon/base/views.py, pontoon/tags/admin/views.py, requirements.txt, tests/base/views/ajax.py, tests/env.py, tests/fixtures/user.py, tests/tags/views.py
Adds a view that can be accessed by the resources widget
=> Touch #1416256: String tiers admin view

pontoon/base/models.py, pontoon/base/static/js/translate.js, tests/base/managers/entity.py, tests/fixtures/entities.py
This PR is regarding the bug : https://bugzilla.mozilla.org/show_bug.cgi?id=1219908.
Right now I have added the split lookup and search according to this : https://pastebin.mozilla.org/9079558
The sql query for the the most recent commit looks like: https://pastebin.com/1UCFFjug
=> Fix bug 1219908: Add split search query for translation search.

pontoon/base/static/css/table.css, pontoon/base/templates/widgets/heading_info.html, pontoon/projects/templates/projects/includes/tags.html, pontoon/projects/urls.py, pontoon/projects/views.py, pontoon/tags/templates/tags/tag.html, pontoon/tags/templates/tags/widgets/tag_list.html, pontoon/tags/urls.py, pontoon/tags/utils/chart.py, pontoon/tags/utils/latest_activity.py, pontoon/tags/utils/tagged.py, pontoon/tags/views.py, pontoon/urls.py, tests/tags/utils/tagged.py, tests/tags/views.py
Implementation of the string tiers project views using django/jinja
=> String tiers django-based views

pontoon/base/views.py, tests/base/views/locale_agnostic.py
Allow query params to be passed through when redirecting to lang translate view
=> Add query params in lang agnostic redirect

pontoon/base/forms.py, pontoon/base/models.py, pontoon/base/static/css/translate.css, pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html, pontoon/base/templates/widgets/progress_chart.html, pontoon/base/views.py, pontoon/projects/templates/projects/includes/tags.html, pontoon/projects/templates/projects/includes/teams.html, pontoon/tags/templates/tags/widgets/tag_list.html, pontoon/tags/views.py, pontoon/teams/templates/teams/widgets/team_list.html, tests/base/models/entity.py
Adds tag filters to translate filtering dropdown
=> String tiers translate filter

pontoon/base/views.py
This makes such links redirect instead of 404:
http://pontoon.mozilla.org/projects/all-projects/all-resources/
=> Add support for locale-agnostic links for All Projects views

pontoon/base/models.py, pontoon/base/views.py
using the contribs code path in translate dropdown
=> Fix Bug 1450863: Use User.with_translation_counts for getting contribs in translate dd

pontoon/base/static/js/main.js, pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html
=> Bug 1453139: Prevent DoesNotExist for non-managers

pontoon/base/static/js/translate.js
The solution is simple: we need to select the string before the request
is made and not wait until it completes.
=> Fix bug 1454351: Update the right string in string list

pontoon/administration/tests/test_views.py, pontoon/administration/views.py
This computes the number of entities in a resource whenever that number changes, and calculates all stats accordingly. It fixes the issue that dashboards were showing incorrect numbers after new strings had been added, or strings had been removed.
=> Fix bug 1436889 - Update total strings and stats after adding entities.

pontoon/base/static/js/translate.js, pontoon/batch/forms.py
Hey @mathjazz, could you look at this?
=> Fix bug 1438575: Mass replace works on non-breakable spaces.

pontoon/base/migrations/0120_bug_1423679_update_plurals_20180417_1135.py
By re-implementing the Model methods in the migration and using frozen models instead of actual ones.
@jotes r?
=> Bug bug 1459583: Fix failing migration

pontoon/base/views.py
Download TM is now enabled for All Projects.
=> Fix bug 1459601: Enable download TM for All Projects

pontoon/base/static/js/fluent_interface.js, pontoon/base/static/js/main.js, pontoon/base/static/js/translate.js, pontoon/machinery/static/js/machinery.js
Test case:
https://mozilla-pontoon-staging.herokuapp.com/de/common-voice/all-resources/?string=178208
=> Fix bug 1455191: [FTL] Convert TM strings to simple strings

pontoon/base/static/js/translate.js
This is a regression from [bug 1453879](https://bugzilla.mozilla.org/show_bug.cgi?id=1453879).
=> Fix bug 1462419: Restore text selection in helpers

pontoon/base/templates/translate.html, pontoon/base/templates/widgets/button.html, pontoon/contributors/templates/contributors/profile.html
=> Rename refresh icon to sync (Font Awesome 5)

pontoon/base/static/js/translate.js, pontoon/sync/formats/json_extensions.py, pontoon/sync/tests/formats/test_json_extensions.py, pontoon/sync/vcs/models.py
https://mozilla-pontoon-staging.herokuapp.com/projects/http-dns-mozilla-l10n/
=> Fix bug 1426676: Fix JSON file format bugs

pontoon/teams/static/css/team.css
@MikkCZ r?
I'll deploy to stage in a bit.
=> Fix bug 1470648: Hide Bulb column on Project Request

pontoon/base/management/commands/calculate_stats.py
=> Fix bug 1470337: De-optimize calculate_stats

pontoon/base/static/css/translate.css, pontoon/base/static/js/fluent_interface.js
Details in the bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1455099
=> Fix bug 1455099: [FTL] Make selectors with siblings more readable using indentation

pontoon/base/static/css/translate.css, pontoon/base/static/js/translate.js
1st commit removes the unused code.
2nd commit fixes the regression.
=> Fix bug 1471534: Truncate missing strings with suggestions

pontoon/base/static/js/translate.js
This is fix for a regression introduced in #993.
=> Fix bug 1472436: Convert toggleClass param to Boolean

pontoon/checks/libraries/pontoon.py, pontoon/checks/tests/test_pontoon.py
For more details, please see the bug description:
https://bugzilla.mozilla.org/show_bug.cgi?id=1472793
=> Fix bug 1472793: Error on non-localizable entries

pontoon/base/static/js/translate.js
For steps to reproduce, see:
https://bugzilla.mozilla.org/show_bug.cgi?id=1473575#c0
I'll deploy to stage in a bit.
=> Fix bug 1473575: Fix tags detection for all-projects

.gitignore, CONTRIBUTING.rst, README.md, docs/dev/setup-virtualenv.rst, docs/dev/setup.rst, docs/index.rst
=> Fix bug 1473372: Make Docker setup default in developer docs

pontoon/checks/__init__.py
@mathjazz hey, could you look at this? I discovered this a moment ago.
=> Bug 1458345 [hotfix] Save errors/warnings for .lang and .properties files

pontoon/base/static/js/main.js
=> Fix bug 1477026: data.translation is not always present

pontoon/base/utils.py
@mathjazz As promised -> this is a hotfix with a new feature, tests for this function will land in a separate PR.
=> Bug 1463999 Check uploaded translations

pontoon/base/static/js/main.js
Details:
https://bugzilla.mozilla.org/show_bug.cgi?id=1476945#c7
=> Fix bug 1476945: [FTL] Query TM with simple strings

pontoon/base/utils.py
The `projects` parameter can also be a QuerySet.
=> Fix batch actions

pontoon/base/static/css/translate.css, pontoon/base/static/js/translate.js
=> Fix bug 1471354: Make review icons visible to unauthenticated users and contributors

pontoon/base/static/js/translate.js
Fixes a regression introduced in https://github.com/mozilla/pontoon/pull/997.
=> Fix bug 1479030: Use correct URL param when filtering by tags

pontoon/administration/tests/test_views.py, pontoon/administration/views.py, pontoon/base/tests/models/test_entity.py, pontoon/tags/tests/conftest.py, pontoon/test/factories.py, pontoon/test/fixtures/base.py
I took this opportunity to move this test file to pytest, hope you don't mind. I've isolated the pytest changes as much as I could to make the review easier.
=> Fix bug 1481197 - Enforce order for database projects strings. 

pontoon/base/models.py, pontoon/base/static/css/translate.css, pontoon/base/static/js/translate.js, pontoon/base/tests/models/test_entity.py, pontoon/settings/base.py
Note: this is based on #1064. See only https://github.com/mozilla/pontoon/commit/9e572121d31d56ea8d560471cbe8351c76a92a4b.
=> Fix bug 1485611: Mark errors and warnings in string list

frontend/README.md, frontend/package.json, frontend/src/App.css, frontend/src/App.js, frontend/src/index.css, frontend/src/index.js, frontend/src/modules/entitieslist/actions.js, frontend/src/modules/entitieslist/components/EntitiesList.css, frontend/src/modules/entitieslist/components/EntitiesList.js, frontend/src/modules/entitieslist/components/EntitiesList.test.js, frontend/src/modules/entitieslist/reducer.js, frontend/src/modules/entitydetails/components/Editor.css, frontend/yarn.lock
This makes sure that the screen always takes 100% of the screen, and that scrolling is handled in panels, notably in the EntitiesList component. It also adds an infinite scroller so that next entities are loaded when a user goes near the bottom of the list (by default, within 250px from the bottom).
=> Fix bug 1486516 - Continuous loading of entities. 

pontoon/base/models.py, pontoon/base/static/css/translate.css, pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html, pontoon/base/tests/managers/test_entity.py, pontoon/test/factories.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1486605
=> Fix bug 1486605: Add errors and warnings filters

pontoon/base/static/js/translate.js, pontoon/base/templates/translate.html
This PR fixes two bugs found by @MikkCZ during testing on stage. For details, see commit messages.
=> Fix display of string Warnings/Errors

pontoon/base/static/js/fluent_interface.js
=> Fix bug 1492755: Do not break if only source string has value

frontend/src/modules/entitieslist/components/EntitiesList.js, frontend/src/modules/entitieslist/components/EntitiesList.test.js, frontend/src/modules/entitieslist/components/EntitiesLoader.css, frontend/src/modules/entitieslist/components/EntitiesLoader.js, frontend/src/modules/entitieslist/reducer.js
Hi,
I decided to start with the smallest possible component to get familliar with the code.
@mathjazz @adngdb could you review?
=> Bug 1489054 - Add entity list loader

frontend/src/App.js, frontend/src/core/api/base.js, frontend/src/core/api/index.js, frontend/src/core/api/user.js, frontend/src/core/lightbox/actions.js, frontend/src/core/user/actions.js, frontend/src/core/user/components/UserAutoUpdater.js, frontend/src/core/user/components/UserAutoUpdater.test.js, frontend/src/core/user/index.js, frontend/src/core/user/reducer.js, frontend/src/rootReducer.js, pontoon/base/urls.py, pontoon/base/views.py
This data will be used later on by other modules to give access to actions, show special data, and display the name and avatar of the user.
=> Fix bug 1490349 - Add current user data to Translate app. 

pontoon/base/static/js/translate.js
=> Fix bug 1494373: If no suggestions present, don't try to focus them

pontoon/base/static/css/style.css, pontoon/base/static/js/main.js
That allows us to group MT results with other services
=> Add percent match number to MT services

pontoon/teams/static/css/request.css
We should reconsider the UX for requesting new locales in order to meet
requirements from the PM team.
=> Bug 1468997: Disable Request Locale, r=me

pontoon/contributors/templates/contributors/profile.html
This is available on stage for testing:
https://mozilla-pontoon-staging.herokuapp.com/contributors/24SF1A7jby9lhuuirruQS4xRN3w/
=> Fix bug 1516165: Hide email address from profile page for unauthenticated users

docs/dev/browser-support.rst, frontend/package.json, frontend/src/App.css, frontend/src/App.js, frontend/src/core/locales/selectors.js, frontend/src/core/navigation/components/Navigation.css, frontend/src/core/navigation/components/Navigation.js, frontend/src/core/navigation/index.js, frontend/src/core/navigation/selectors.js, frontend/src/core/navigation/selectors.test.js, frontend/src/modules/entitieslist/components/EntitiesList.js, frontend/src/modules/entitieslist/selectors.js, frontend/src/modules/entitydetails/components/EntityDetails.js, frontend/src/modules/entitydetails/selectors.js, frontend/src/modules/history/components/History.js, frontend/src/modules/search/components/SearchBox.js, frontend/yarn.lock
This adds a very simple navigation element at the top. It's a breadcrumb that allows to go back to the home page, to the team page, or to the project dashboard for the current team. Note that this PR doesn't close the bug, as I guess this is insufficient for our users.
=> Bug 1486504 - Navigation for Translate.Next

requirements.txt
=> Update to Django 1.11.18

pontoon/base/static/js/fluent_interface.js, pontoon/base/static/js/lib/fluent-syntax.js, pontoon/base/templatetags/helpers.py, requirements.txt
=> Fix bug 1509079: Update fluent libraries to support fluent syntax 0.8

pontoon/base/static/js/main.js
=> Fix bug 1522088: Do not duplicate machinery percentage

frontend/public/static/locale/en-US/translate.ftl, frontend/public/static/locale/es/translate.ftl, frontend/public/static/locale/fr/translate.ftl, frontend/src/core/api/translation.js, frontend/src/core/api/user.js, frontend/src/core/user/actions.js, frontend/src/core/user/index.js, frontend/src/core/user/reducer.js, frontend/src/modules/editor/components/Editor.css, frontend/src/modules/editor/components/Editor.js, frontend/src/modules/editor/components/Editor.test.js, frontend/src/modules/editor/components/EditorSettings.css, frontend/src/modules/editor/components/EditorSettings.js, frontend/src/modules/entitydetails/actions.js, frontend/src/modules/entitydetails/components/EntityDetails.js, frontend/src/modules/entitydetails/components/EntityDetails.test.js, pontoon/base/views.py
This adds settings to the Editor, and makes use of them to show the "Save" or "Suggest" button as well as when sending translations. It also now moves on to the next entity after a translation has been sent.
=> Fix bug 1519898 - Add user settings in the Editor. 

frontend/public/index.html, frontend/src/App.css, frontend/src/modules/search/components/SearchBox.css
- fix main background color
- set header background color
- set header border
- fix search icons position
r=me
=> No bug: CSS fixes

frontend/src/App.css
This fixes a regression in setting a header background.
=> More CSS fixes

pontoon/base/static/css/translate.css
=> Prevent overflow in the project menu

requirements.txt
=> Upgrade to Django 1.11.20

.travis.yml, frontend/src/App.js, frontend/src/core/l10n/components/AppLocalizationProvider.test.js, frontend/src/core/loaders/components/WaveLoader.js
Note: this is failing on master, so I'm letting this fail to verify it does work. I'll fix the failure afterwards.
=> No bug - Run Flow in travis.

pontoon/base/tests/managers/test_user.py, pontoon/contributors/utils.py
We need this for easier handling of PM requests, one of which just hit my mailbox. :)
=> Fix bug 1529905: Expose rejected count

frontend/package.json, frontend/public/static/locale/en-US/translate.ftl, frontend/public/static/locale/fr/translate.ftl, frontend/src/core/diff/components/TranslationDiff.css, frontend/src/core/diff/components/TranslationDiff.js, frontend/src/core/diff/components/TranslationDiff.test.js, frontend/src/core/diff/index.js, frontend/src/modules/entitydetails/components/Metadata.css, frontend/src/modules/history/components/History.js, frontend/src/modules/history/components/Translation.css, frontend/src/modules/history/components/Translation.js, frontend/src/modules/history/components/Translation.test.js, frontend/src/modules/machinery/components/Machinery.js, frontend/src/modules/otherlocales/components/Locales.js, frontend/yarn.lock
=> Fix bug 1490343: Show/hide diff

frontend/public/static/locale/en-US/translate.ftl, frontend/public/static/locale/fr/translate.ftl, frontend/src/App.css, frontend/src/App.js, frontend/src/core/api/base.js, frontend/src/core/api/user.js, frontend/src/core/user/actions.js, frontend/src/core/user/components/AppSwitcher.css, frontend/src/core/user/components/AppSwitcher.js, frontend/src/core/user/components/SignIn.css, frontend/src/core/user/components/SignIn.js, frontend/src/core/user/components/SignInLink.js, frontend/src/core/user/components/SignOut.css, frontend/src/core/user/components/SignOut.js, frontend/src/core/user/components/UserAutoUpdater.js, frontend/src/core/user/components/UserAutoUpdater.test.js, frontend/src/core/user/components/UserControls.js, frontend/src/core/user/components/UserControls.test.js, frontend/src/core/user/index.js, frontend/src/core/user/reducer.js, frontend/src/modules/editor/components/Editor.js, pontoon/base/views.py
This also does a bunch of refactoring, putting all user-related components into the user module and exposing a single, catch-all UserControls component for simplicity of use.
=> Fix bug 1528177 - Add links to Sign in and out in Translate.Next.

requirements.txt
Testing on stage with `DJANGO_STAGE = False` succeeded.
=> Fix bug 1527507: Add requirements.txt file

frontend/src/modules/entitydetails/components/EntityDetails.js, frontend/src/modules/entitydetails/components/EntityDetails.test.js
Let's remove this unstyled block of text for good.
=> Remove Select an entity note

pontoon/api/tests/test_urls.py, pontoon/base/management/commands/heroku_deploy_setup.py, pontoon/base/middleware.py, pontoon/base/tests/models/test_entity.py, pontoon/base/utils.py, pontoon/base/views.py, pontoon/batch/forms.py, pontoon/checks/libraries/__init__.py, pontoon/checks/libraries/compare_locales.py, pontoon/checks/libraries/pontoon.py, pontoon/checks/management/commands/run_checks.py, pontoon/db/__init__.py, pontoon/localizations/views.py, pontoon/machinery/tests/test_views.py, pontoon/sync/core.py, pontoon/sync/formats/lang.py, pontoon/sync/tests/test_sync_projects.py, pontoon/sync/vcs/models.py, requirements/default.txt
Hey,
I updated `six` to 1.12.0 and replaced all missing methods with their equivalents.
@adngdb do you have a moment to look at this?
=> Fix bug 1536670 - Update six to 1.12.0

pontoon/checks/libraries/compare_locales.py
=> Fix bug 1541576: Support unicode characters in XML checks

frontend/src/core/api/machinery.js, frontend/src/modules/entitydetails/components/EntityDetails.js, frontend/src/modules/entitydetails/components/Tools.js, frontend/src/modules/machinery/actions.js, frontend/src/modules/machinery/components/Machinery.js, frontend/src/modules/machinery/components/Translation.js, frontend/src/modules/machinery/reducer.js, pontoon/machinery/tests/test_views.py, pontoon/machinery/views.py
This gets the job done. (With the exception of changing the source string in machinery diff, which I'm not sure how to take care of yet.)
Before I dig into it, I wonder if I should refactor the machinery API, because I'm using a couple of ugly hacks to make this patch work. See the question below.
=> Fix bug 1524549: Add support for custom search in Machinery

docker/Dockerfile.base
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1542027 using the Jarek's suggested patch.
=> Bug 1542027: Multiple tries to download GPG keys in docker image

frontend/src/modules/editor/actions.js, frontend/src/modules/editor/components/Editor.js, frontend/src/modules/editor/components/EditorProxy.js, frontend/src/modules/editor/components/FluentEditor.js, frontend/src/modules/editor/components/FluentEditor.test.js, frontend/src/modules/editor/components/GenericEditor.js, frontend/src/modules/editor/components/GenericEditor.test.js, frontend/src/modules/editor/reducer.js, frontend/src/modules/entitydetails/components/EntityDetails.js
Also make sure that the cursor is at the beginning of the Editor when it loads.
=> Fix bug 1542611 - Always put focus on Editor.

frontend/src/core/api/translation.js
See https://bugzilla.mozilla.org/show_bug.cgi?id=1545714#c0.
=> Fix bug 1545714: Pass correct pass value for All Resources

.eslintrc.js, frontend/public/index.html, frontend/public/static/locale/en-US/translate.ftl, frontend/public/static/locale/fr/translate.ftl, frontend/src/App.js, frontend/src/core/notification/actions.js, frontend/src/core/notification/components/NotificationPanel.css, frontend/src/core/notification/components/NotificationPanel.js, frontend/src/core/notification/components/NotificationPanel.test.js, frontend/src/core/notification/index.js, frontend/src/core/notification/messages.js, frontend/src/core/notification/reducer.js, frontend/src/core/user/actions.js, frontend/src/modules/editor/actions.js, frontend/src/modules/editor/components/Editor.js, frontend/src/modules/editor/components/FailedChecks.js, frontend/src/modules/editor/components/GenericEditor.js, frontend/src/modules/entitydetails/components/EntityDetails.js, frontend/src/modules/entitydetails/components/Helpers.js, frontend/src/modules/history/actions.js, frontend/src/modules/history/components/History.js, frontend/src/modules/history/components/Translation.js, frontend/src/modules/history/index.js, frontend/src/rootReducer.js, pontoon/base/static/js/main.js, pontoon/contributors/views.py, pontoon/settings/base.py, pontoon/translate/views.py
@mathjazz this is an early look, but the feature "works", and I wanted to have your opinion on the way I handle animations. You can test it by sending an already existing translation.
=> Fix bug 1500871 - Add support for status notifications.

pontoon/base/views.py
This fixes a regression introduced by bug 1518820.
=> Bug 1518820: Fix reference before assignment error

.travis.yml
'tis a work in progress, I am clueless about this error so I'm trying things. Don't mind me.
=> No bug - Fix build issue with pip in travis.

frontend/src/core/navigation/components/Navigation.js, frontend/src/core/navigation/components/Navigation.test.js
This also fixes the broken link to the project dashboard when all projects are selected. Now it leads to the locale dashboard.
=> Fix bug 1554709 - Show project name in navigation.

frontend/src/core/api/index.js, frontend/src/modules/entitydetails/components/EntityDetails.js, frontend/src/modules/entitydetails/components/Helpers.js, frontend/src/modules/machinery/actions.js, frontend/src/modules/machinery/components/Translation.js, frontend/src/modules/machinery/reducer.js, frontend/src/modules/otherlocales/actions.js, frontend/src/modules/otherlocales/components/OtherLocales.js, frontend/src/modules/otherlocales/reducer.js, frontend/src/modules/otherlocales/selectors.js
@mathjazz Let's do this first.
=> No bug - Correctly import types from API.

pontoon/base/models.py, pontoon/base/tests/views/test_translation.py
=> Fix bug 1556680: Create instead of delete a TM entry on approve

frontend/src/modules/entitydetails/components/Metadata.css
=> Fix bug 1556410: Do not cross select Metadata elements on double click

docs/admin/deployment.rst, docs/dev/setup-virtualenv.rst
Also, document the following optional settings:
- GOOGLE_ANALYTICS_KEY
- GOOGLE_TRANSLATE_API_KEY
- MICROSOFT_TRANSLATOR_API_KEY
- MANUAL_SYNC
@VishalCR7 r?
=> Fix bug 1555828: Document DJANGO_LOGIN in deployemnt docs

frontend/src/App.css, frontend/src/modules/editor/components/Editor.css, frontend/src/modules/editor/components/Editor.js, frontend/src/modules/editor/components/KeyboardShortcuts.css, frontend/src/modules/entitydetails/components/Helpers.css, frontend/src/modules/entitydetails/components/Metadata.css, frontend/src/modules/entitydetails/components/Metadata.js
Entity details panel will now break less on narrow mobile screens.
The patch includes some other CSS improvements in `EntityDetails`.
=> Fix bug 1555924: Improve layout on mobile

frontend/src/modules/entitydetails/components/Helpers.css, frontend/src/modules/history/components/Translation.js, frontend/src/modules/machinery/components/Translation.js, frontend/src/modules/otherlocales/components/Translation.js
Also: Fix ugly outline appearing on click on active Helpers tab
=> Fix bug 1554997: Text selection in helpers

frontend/package.json, frontend/src/core/navigation/components/Navigation.js, frontend/src/core/navigation/components/Navigation.test.js, frontend/yarn.lock
This also means we have one less dependency, which is always a good thing (even though that one is really small).
=> No bug - Refactor Navigation component to use existing selector.

pontoon/base/static/css/style.css, pontoon/base/templates/widgets/menu.html, pontoon/localizations/templates/localizations/localization.html, pontoon/projects/templates/projects/project.html, pontoon/teams/templates/teams/team.html
Hey @mathjazz, I heard you disliked icons so I put icons in your Pontoon so you can hate icons while you Pontoon. :smirk:
=> No bug - Add icons to tabs in dashboards.

frontend/package.json, frontend/src/core/placeable/parsers/leadingSpace.js, frontend/src/core/placeable/parsers/leadingSpace.test.js, frontend/src/core/placeable/parsers/unusualSpace.js, frontend/src/core/placeable/parsers/unusualSpace.test.js, frontend/yarn.lock
I've added a failing test to confirm the bug.
=> Fix bug 1555001: Unusual space false positive

frontend/public/index.html, frontend/src/modules/navbar/components/Navigation.js, pontoon/batch/tests/test_views.py, pontoon/translate/tests/test_views.py
This should have been two separate PRs, but since they are small and the 2nd depends on the 1st, I'm squeezing them together. Will avoid doing that in the future.
=> Fix bugs 1574889 (<title>) and 1574922 (update navbar on project change)

pontoon/machinery/views.py
The first commit is a bugfix, the 2nd one improve the code readability slightly.
=> Fix bug 1578155: Fix TM ordering by quality

pontoon/translate/tests/test_views.py, pontoon/translate/views.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1579145
=> Fix bug 1579145: Validate Locale, Project, ProjectLocale in Translate.Next URLs

frontend/src/core/editor/components/connectedEditor.js, frontend/src/modules/fluenteditor/components/Editor.js, frontend/src/modules/fluenteditor/components/RichEditor.js, frontend/src/modules/fluenteditor/components/RichTranslationForm.js, frontend/src/modules/fluenteditor/components/SourceTranslationForm.js, frontend/src/modules/fluentoriginal/components/RichString.js, frontend/src/modules/genericeditor/components/Editor.js, frontend/src/modules/genericeditor/components/GenericTranslationForm.js, frontend/src/modules/search/actions.js, frontend/src/modules/search/components/SearchBox.js, frontend/src/modules/search/components/SearchBox.test.js, frontend/src/modules/search/index.js, frontend/src/modules/search/reducer.js
@mathjazz I randomly tried this to see what it would do, and, well, it kinda seems to work? Lucky me I guess! :D
=> Fix bug 1557922 - Keep focus on search input after a request.

frontend/src/modules/batchactions/components/BatchActions.js
This patch fixes the bug with replacing (non-breaking) spaces.
=> Fix bug 1580632: Encode find/replace fields

.eslintrc.js, frontend/src/store.js
This is deployed to stage, and it works. :-)
=> Fix bug 1583527 - Show redux logs only in development.

frontend/src/modules/fluenteditor/components/Editor.js, frontend/src/modules/fluenteditor/components/Editor.test.js
The best way to test this is to submit a simple, rich and complex translation for the same string.
=> Fix bug 1566477: Detect Fluent Editor mode when copying translation into editor

frontend/src/modules/fluenteditor/components/Editor.js
As I mentioned in the bug, there are two problems which I thought root from the same source.
They are separate, hence separate commits.
=> Fix bug 1584164: Do not convert complex strings to complex

frontend/src/core/l10n/index.js, l10n.toml
=> Fix bug 1584489: Remove fr and es from supported languages

frontend/src/modules/search/components/SearchBox.css, frontend/src/modules/search/index.js, pontoon/base/models.py
This fix adds a new filter in the "Extra filters" category that will search for empty strings.
=> Fixed Bug 1243137 - Implement empty string filter

pontoon/contributors/static/css/contributors.css, pontoon/contributors/templates/contributors/widgets/contributor_list.html
Remove rank from contributors.css and contributor_list.html [1587924](https://bugzilla.mozilla.org/show_bug.cgi?id=1587924)
=> Fix bug 1587924 - Remove Rank column from the Contributors table

frontend/public/static/locale/en-US/translate.ftl, frontend/src/modules/search/components/FiltersPanel.js
Localize search panel statuses and filters
=> Fix bug 1586233 - Localize search panel statuses and filters

frontend/src/core/user/components/UserMenu.css, frontend/src/modules/history/components/Translation.css, frontend/src/modules/history/components/Translation.js, frontend/src/modules/history/components/Translation.test.js, frontend/src/modules/history/reducer.js, frontend/src/modules/search/components/FiltersPanel.css, pontoon/base/static/css/style.css, pontoon/base/views.py
=> Fix bug 1586829 - Show avatars in translations

Makefile, pontoon/base/models.py, pontoon/base/tests/__init__.py, pontoon/batch/tests/test_views.py, pontoon/sync/changeset.py, pontoon/sync/formats/compare_locales.py, pontoon/sync/formats/silme.py, pontoon/sync/tests/formats/__init__.py, pontoon/sync/tests/formats/test_compare_locales.py, pontoon/tags/tests/test_views.py, pontoon/teams/tests/test_views.py, pontoon/translate/tests/test_views.py
This is a follow-up on https://github.com/mozilla/pontoon/pull/1419.
I'll implement all comments from the previous PR today and notify Pike to take a look [again] :-)
=> Bug 1585251 Fix some failing tests 

frontend/public/static/locale/en-US/translate.ftl, frontend/public/static/locale/fr/translate.ftl, frontend/src/modules/entitieslist/components/EntitiesList.css, frontend/src/modules/entitydetails/components/Helpers.css, frontend/src/modules/machinery/components/Machinery.css, frontend/src/modules/machinery/components/Machinery.js, frontend/src/modules/search/components/FiltersPanel.css, frontend/src/modules/search/components/SearchBox.css
Redesign search boxes to look more like input fields
=> Fix bug 1586827 - Redesign search boxes to look more like input fields

frontend/src/modules/search/components/SearchBox.js
Quick follow-up from #1434 to avoid having an unconventional code pattern.
=> No bug - Making code more consistent.

pontoon/teams/static/css/team.css, pontoon/teams/static/js/bugzilla.js
Updated the bugzilla.js file by adding Assignee and Status fields to the list of bugs. Closed the previous PR since I couldn't resolve update issue on time.
=> Fix bug 1423854: Adds status and assignee to the list of bugs and allows sorting

pontoon/settings/dev.py
=> bug 1591492, fix settings/dev.py to exclude graphene from jinja

frontend/src/modules/search/components/FiltersPanel.js
Wrong priority star rating is displayed in Translate View menu
=> Fix bug 1589874

pontoon/base/models.py, pontoon/base/templates/django/base.html
Fix regression introduced in https://github.com/mozilla/pontoon/commit/ff4f1d2158278b95b55f338fb0d0ae4e7a883a90#diff-91c36325f8496b8a88e5688322739387.
=> No bug: Fix Django login avatar regression

pontoon/teams/static/css/team.css, pontoon/teams/static/js/bugzilla.js
**What does this PR do?**
This pull request fixes the issue [1591336](https://bugzilla.mozilla.org/show_bug.cgi?id=1591336). It adds a sort function to the bug table to make it sortable.
**How can this be tested**
- Go to the bug list page.
- Click on any of the headers to sort the table row.
=> Fix bug 1591336 Make colums in bug list sortable

pontoon/base/models.py, pontoon/contributors/utils.py, pontoon/contributors/views.py, pontoon/teams/views.py
Add parameter all_users to users_with_translations_counts for have possibility to display user Imported.
Add user Imported based on AnonimousUser entry
[Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1564841)
=> Bug 1564841: Add ability to filter Imported strings

frontend/README.md, pontoon/base/templates/translate.html, pontoon/base/tests/views/test_translation.py, pontoon/base/views.py, pontoon/settings/base.py, pontoon/translate/tests/test_views.py, pontoon/translate/views.py, requirements/default.txt
And remove waffle entirely, as it was not being used by anything anymore.
=> Fix bug 1587341 - Remove waffle flag for Translate.Next.

docker/run_tests.sh, pontoon/base/tests/test_utils.py, pontoon/base/utils.py, pontoon/tags/tests/fixtures/tags.py
=> Fix bug 1591498 - Translate glob patterns into regexes with compare-locales Patterns

frontend/public/static/locale/en-US/translate.ftl, frontend/public/static/locale/fr/translate.ftl, frontend/src/App.css, frontend/src/core/editor/components/connectedEditor.css, frontend/src/modules/entitieslist/components/Entity.css, frontend/src/modules/entitydetails/components/EntityDetails.css, frontend/src/modules/entitydetails/components/EntityDetails.js, frontend/src/modules/entitydetails/components/Helpers.css, frontend/src/modules/entitydetails/components/Helpers.js, frontend/src/modules/entitydetails/components/Metadata.css, frontend/src/modules/history/components/History.css, frontend/src/modules/history/components/Translation.css, frontend/src/modules/machinery/components/Translation.css, frontend/src/modules/otherlocales/components/Translation.css
The gist of the patch is in the first two commits.
The rest is a couple of related CSS improvements.
=> Fix bug 1586820: 3-column layout

frontend/src/modules/interactivetour/components/InteractiveTour.css
The patch is deployed to stage:
https://mozilla-pontoon-staging.herokuapp.com/sl/tutorial/playground/?string=189477
@jotes r?
=> Fix bug 1595956: Fix font color in interactive tour

docs/admin/deployment.rst, pontoon/base/management/commands/update_auth_providers.py, pontoon/base/templatetags/helpers.py, pontoon/settings/base.py
Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1597284
So straightforward thanks to the groundwork in https://github.com/mozilla/pontoon/pull/1442 to generalize the socialapp setup h/t @abowler2
=> Fix bug 1597284 - Add support for authenticating with Google

frontend/src/modules/history/components/Translation.css
See https://discourse.mozilla.org/t/change-the-view-order-of-suggestions/49226/7
=> Fix bad fuzzy CSS selector

pontoon/sync/formats/xliff.py, pontoon/sync/tests/test_vcs.py, pontoon/sync/vcs/repositories.py, requirements/default.txt
@jotes mind giving this a quick look too, please?
=> Bug 1585252 - Fix string encoding errors for sync with Python 3.

Makefile, pontoon/base/tests/test_utils.py, pontoon/base/utils.py, pontoon/static/js/tags/admin/manager.js, pontoon/tags/admin/forms.py, pontoon/tags/tests/fixtures/tags.py, pontoon/tags/tests/test_forms.py, pontoon/tags/tests/utils/test_resources.py, pontoon/tags/tests/utils/test_stats.py, pontoon/tags/tests/utils/test_tags.py, pontoon/tags/tests/utils/test_translations.py, pontoon/tags/utils/base.py, pontoon/tags/utils/resources.py, pontoon/tags/utils/tags.py, tests/js/tags/admin.js
TODO:
This is still in progressm I may ask you for your feedback/help at IRC tomorrow.
=> Fix bug 1600278 remove glob patterns

Makefile, docs/dev/first-contribution.rst, docs/dev/setup.rst
Can someone verify that this doesn't break anything for Linux and macOS? 
I plan to verify this also on WIndows Professional later this week, where it's possible to use the official Docker installer.
=> Update Docker makefile and documentation for Windows

pontoon/base/admin.py
=> Fix bug 1459156: Enable adding users via Django Admin

pontoon/administration/templates/admin_project.html
Deployed to stage for testing:
https://mozilla-pontoon-staging.herokuapp.com/admin/projects/firefox/
=> Fix bug 1619650: Add Issue tracking to autocomplete list of External Resources

pontoon/base/tests/managers/test_entity.py
=> Remove redundand test decorators and params

frontend/src/core/comments/components/AddComment.css
Align with avatar and prevent jumping on resize
=> Fix add comment form position

pontoon/administration/static/css/admin_project.css, pontoon/administration/templates/admin_project.html
=> Consistently style checkboxes in Project Admin

frontend/src/modules/history/actions.js, frontend/src/modules/machinery/components/Count.js, frontend/src/modules/machinery/index.js, frontend/src/modules/otherlocales/components/Count.js, frontend/src/modules/teamcomments/actions.js, frontend/src/modules/teamcomments/components/CommentCount.js, frontend/src/modules/teamcomments/components/Count.js, frontend/src/modules/teamcomments/components/TeamComments.js, frontend/src/modules/teamcomments/index.js, frontend/src/modules/teamcomments/reducer.js
Contents:
* Do not set count to 0 or render No comments message during fetching
* Rename CommentCount to Count
* Make MachineryCount and OtherLocalesCount a functional component
* Explain why request() not called as part of get()
Most of the diff is a result of deindentation.
=> Unify Count components

pontoon/settings/base.py
This is causing `make build` to fail among other things.
=> Fix bad merge from #1580

frontend/package.json, frontend/yarn.lock
=> [WIP] Update react-scripts

pontoon/base/utils.py
Seems like this has been biting us since the Python3 upgrade.
I tried to write some unit tests, but gave up. :/
=> Fix bug 1628446: Fix download of ZIP files

pontoon/translations/forms.py, pontoon/translations/tests/test_forms.py
Looks like we hit a regression here.
=> Fix bug 1631116: Allow submitting empty translations

frontend/src/core/term/components/Term.js
=> Do not show usage title if no usage

pontoon/base/views.py
@SafaAlfulaij Could you please review this?
=> Fix bug 1640296: Fix adding team comments to system projects

pontoon/settings/base.py
=> Fix bug 1639492: Fix Sync timeout conversion

docs/user/localizing-your-projects.rst
@mathjazz Hey, I'm not sure if that's enough. Should I extend this section and explain the visibility settings in depth?
=> No bug - update the docs about private projects

docs/user/localizing-your-projects.rst
=> No bug - Fix the lists in the "Localizing your projects" document.

app.json
change cr-free (before raygun:free)
=> Update app.json - bug 1657587

frontend/package.json, frontend/public/static/locale/en-US/translate.ftl, frontend/src/modules/search/components/FiltersPanel.js, frontend/src/modules/search/components/SearchBox.css, frontend/src/modules/search/components/SearchBox.js, frontend/src/modules/search/components/SearchBox.test.js
Deployed to stage for user feedback:
https://mozilla-pontoon-staging.herokuapp.com/projects/firefox/all-resources/
=> Fix bug 1659491: Trigger string list search with Enter

frontend/src/modules/entitieslist/components/Entity.css, frontend/src/modules/resourceprogress/components/ProgressChart.js, frontend/src/modules/resourceprogress/components/ResourceProgress.css, frontend/src/modules/search/components/SearchBox.css, pontoon/base/static/css/style.css, pontoon/base/static/css/table.css
Three Changes Made to implement new colour for missing strings
1)Entity.css
Added- .entity.missing .status:before with new colour ie #5F7285
2)ResourceProgress.css
Changed-.progress-chart .menu .details div.missing border colour to #5F7285
3)style.css
Added- .missing .status.fa:before with new colour ie #5F7285
=>  Fix Bug 1598313 change checkbox colour for missing strings

pontoon/base/static/css/download_selector.css, pontoon/base/templates/widgets/heading_info.html, pontoon/localizations/templates/localizations/localization.html, pontoon/settings/base.py, pontoon/teams/templates/teams/team.html
Fix Bug 1662510 Add ability to download TBX and TMX files from dashboards
1)Added a macro named download_button to heading_info.html
2)Added a new file named download_selector.css in the staic/css folder
3)Included the newly created css file download_selector.css in pontoon/settings/base.py
for both localization and teams.
4)Echoed the macro download_button in the localization.html
5)Echoed the macro download_button in the team.html
=> Fix Bug 1662510 Add ability to download TBX and TMX files from dashboard

frontend/yarn.lock
=> Update frontend dependencies

pontoon/base/views.py
Notify:
- authors of existing translations across all locales
- reviewers of existing translations across all locales
Send separate notification for each locale the user has contributed to.
Each notification is then linked to corresponding translate view.
=> Bug 1611510: Send Pin Comment notifications

frontend/src/modules/search/components/FiltersPanel.js
Addressing Bug 1658867 Tag priority. Fix for tags in the filter panel to put in order of highest priority to lowest, Changes tested by flow.
=> Fix Bug 1658867: Fix for tags in the filter panel 

requirements/default.txt
The new version supports Django 3.1.
=> Bug 1627655: Update django-jinja

.travis.yml
Updated PostgreSQL 9.4 to PostgreSQL 11.5 in travis
=> Fix Bug 1607158 Upgrade PostgreSQL database version used in travis

specs/0106-concordance-search.md
Addressing comments by @flodolo in https://github.com/mozilla/pontoon/pull/1656#discussion_r527713782.
=> Bug 1651105: Concordance search spec: Followup

.git-blame-ignore-revs
Added the Prettier commits and some comments to the git blame ignore file
=> Ignore Prettier formatting commits on blame

frontend/src/modules/entitydetails/components/EntityDetails.js
Fixed the initial machinery state by added in function to optimize the FTL files
=> FIx Bug 1676750: [FTL] Unable to get back to the initial Machinery state after search

docs/admin/deployment.rst, pontoon/actionlog/models.py, pontoon/base/models.py, pontoon/base/utils.py, pontoon/checks/management/commands/run_checks.py, pontoon/insights/management/commands/collect_insights.py, pontoon/insights/tasks.py, pontoon/projects/management/commands/send_deadline_notifications.py
This is [Step 2/4](https://wiki.mozilla.org/L10n:Pontoon_Roadmap#Community_Health_Dashboard) of the [Community Health Dashboard](https://github.com/mozilla/pontoon/blob/fddf18f45546cb3c9d59285437e18c72de7ed577/specs/0108-community-health-dashboard.md) implementation.
It adds a scheduled job, which will populate the data model introduced in f2258ed4aba57731983b5e126cc8b3b10e351c29 every day. The job takes around 15 seconds to run on stage. Historic data for the past year needed to plot over-the-time charts before enough data is collected using this job will be added as part of [bug 1680055](https://bugzilla.mozilla.org/show_bug.cgi?id=1680055).
Deployment docs have been updated to cover the new scheduled job and the not yet documented `send_deadline_notifications`. A few smaller fixes …
=> Fix bug 1680054: Regularly collect data needed for community health dashboard

pontoon/insights/tasks.py
We've been passing wrong params. 🤭
=> Bug 1680054: Fix active reviewers and contributors calculation

pontoon/insights/tasks.py
Making some changes to what data is presented in the Insights charts.
In a followup I'll be updating the spec with detailed description of what data is being collected.
=> Bug 1680054: Improve insights calculations

pontoon/insights/static/js/insights.js
Using two Y axes with different scale and the same unit is deceiving.
=> Bug 1680056: Join Y-Axis of the Review activity chart

pontoon/insights/static/css/insights.css, pontoon/insights/static/js/insights.js
* More space between a bullet and text in the legend items
* Bigger area to fill with gradient under line charts
=> Minor styling improvements on Insights charts

.gitignore, .vscode/settings.json, pontoon/machinery/tests/test_views.py, pontoon/machinery/utils.py, pontoon/machinery/views.py
=> Bug 1679710 - Remove duplicates from Concordance search results.

pontoon/machinery/utils.py
@mathjazz Hey,
I realized that we can simplify the code even more.
=> Bug 1679710 the last dab

pontoon/administration/forms.py, pontoon/administration/templates/admin_project.html
fixed the problem where you couldn't save a project with read-only locales in the admin project
=> Fix Bug 1633150  Add ability to enable projects with read-only locales only

pontoon/administration/views.py
I noticed this while reviewing #1796.
@Mitch4sho Could you review please?
=> Fix bug 1684693: Exclude selected Read-only locales from Available locales

CONTRIBUTING.rst, Makefile
I tried to make the command run using `${DC}` instead of `${DOCKER}`, but I failed.
=> Add make dumpdb command

frontend/public/static/locale/en-US/translate.ftl, frontend/src/core/editor/actions.js, frontend/src/core/editor/components/KeyboardShortcuts.css, frontend/src/core/editor/components/KeyboardShortcuts.js, frontend/src/core/editor/hooks/useAddTextToTranslation.js, frontend/src/core/editor/hooks/useCopyMachineryTranslation.js, frontend/src/core/editor/hooks/useHandleShortcuts.js, frontend/src/core/editor/index.js, frontend/src/core/editor/reducer.js, frontend/src/modules/entitydetails/components/EntityDetails.js, frontend/src/modules/entitydetails/components/Helpers.js, frontend/src/modules/machinery/components/Machinery.js, frontend/src/modules/machinery/components/Translation.css, frontend/src/modules/machinery/components/Translation.js, frontend/src/modules/machinery/components/Translation.test.js
* Reimplements the tab shortcut
* Brings back the keyboard shortcuts panel entry
=> Fix Bug 1543344: Implement Tab shortcut in editor

frontend/src/modules/machinery/components/Translation.js
=> Fix bug 1686370: scroll selected helper item into view

frontend/src/core/editor/hooks/useHandleShortcuts.js
Sorry I had this change stashed for the last PR but failed to update the commit accordingly.
=> No bug - Adjust code comment to reflect actual 'Tab' behavior

pontoon/homepage/static/css/fullpage.css, pontoon/homepage/static/js/homepage.js, pontoon/homepage/static/js/lib/fullpage.js
The version we are downgrading two was released 2 months before the GPL3 version we've been using.
=> Switch to a MIT-licensed version of fullpage.js

pontoon/machinery/tests/test_views.py, pontoon/machinery/utils.py
=> No bug - Fix the concordance search results

frontend/src/modules/entitieslist/components/EntitiesList.js
Added the new method scrollIntoView and remove some redundant code
=>  Bug 1686569 Use Element.scrollIntoView() to scroll to the selected entity

frontend/src/modules/entitieslist/components/EntitiesList.js
Another PR with the If statement back in the code.
=> Bug 1686569 Use Element.scrollIntoView() to scroll to the selected entity 

frontend/src/core/project/components/ProjectItem.css, frontend/src/core/project/components/ProjectItem.js
Similar thing as we did in #1791.
=> Bug 1684086: Prevent project menu overflow and unify line height

frontend/src/core/user/components/UserMenu.js, frontend/src/core/user/components/UserMenu.test.js
=> Bug 1688571: fix negative performance side-effects of `UserMenu`

frontend/src/modules/search/components/FiltersPanel.css, frontend/src/modules/search/components/FiltersPanel.js, frontend/src/modules/search/components/FiltersPanel.test.js
This now only listens for `click` events when the menu is visible by the means of leveraging the `useOnDiscard` hook
=> Bug 1688571: fix negative performance side-effects of `FiltersPanel`

frontend/package.json, frontend/yarn.lock
=> Bug 1688571: remove unused react-onclickoutside dependency

frontend/src/modules/entitydetails/components/EntityDetails.js, frontend/src/modules/machinery/actions.js, pontoon/base/static/js/main.js, pontoon/machinery/templates/machinery/machinery.html, pontoon/machinery/tests/test_views.py, pontoon/machinery/views.py
Deployed to stage for testing:
https://mozilla-pontoon-staging.herokuapp.com/projects/firefox/all-resources/
https://mozilla-pontoon-staging.herokuapp.com/machinery/
=> Fix bug 1690336: Only make requests to paid Machinery services if user authenticated

frontend/src/core/editor/hooks/useHandleShortcuts.js, frontend/src/modules/entitydetails/components/EntityNavigation.js
Please note the cleanup commit is to avoid things like this from happening in the future.
=> Fix bug 1691180: avoid native shortcut when pressing ctrl+shift+c

frontend/src/modules/machinery/actions.js, pontoon/machinery/tests/test_views.py, pontoon/machinery/views.py
We're getting lots of 400 errors:
https://bugzilla.mozilla.org/show_bug.cgi?id=1691805
=> Fix bug 1691805: Do not make requests to MT services if locale not supported

frontend/src/core/api/machinery.js, frontend/src/modules/machinery/actions.js, pontoon/machinery/tests/test_views.py, pontoon/machinery/views.py, requirements/default.in, requirements/default.txt, requirements/dev.txt, requirements/test.txt
Better to have such small (but important) piece of code integrated than relying on an external dependency.
=> Fix bug 1692888: Drop caighdean

frontend/src/core/term/components/Term.css, frontend/src/modules/entitieslist/components/Entity.css, frontend/src/modules/history/components/Translation.css, frontend/src/modules/machinery/components/Translation.css, frontend/src/modules/otherlocales/components/OtherLocales.css, frontend/src/modules/otherlocales/components/Translation.css
Changed Background to : #272a2f
=> Fix Bug 1692539: Implementing dark background on hover for all panels

requirements/default.in, requirements/default.txt, requirements/dev.txt, requirements/test.txt
Also: reflect django-dotenv update in the rest of the requirements files.
@flozz Could you please review?
=> Fix bug 1699655: Update to Django 3.1.7

.eslintrc.js, frontend/src/core/api/base.js, frontend/src/core/api/entity.js, frontend/src/core/api/l10n.js, frontend/src/core/api/translation.js, frontend/src/core/api/user.js, frontend/src/core/entities/actions.js, frontend/src/core/lightbox/components/Lightbox.js, frontend/src/core/loaders/components/SkeletonLoader.js, frontend/src/core/plural/actions.js
* Prepare for typescript in core/api/base
=> Prepare for typescript while still in flow

pontoon/homepage/templates/homepage_content.html
=> Fix Github/GitHub case

frontend/src/App.css, frontend/src/core/user/components/UserControls.css, frontend/src/modules/batchactions/components/BatchActions.css, frontend/src/modules/batchactions/components/BatchActions.js, frontend/src/modules/batchactions/components/BatchActions.test.js
By preventing a class name clash.
=> Fix bug 1710384: Prevent batch editor layout breakage

runtime.txt
https://www.python.org/downloads/release/python-397/
=> Update to python 3.9.7

frontend/package.json, frontend/src/index.tsx, frontend/yarn.lock
Replace old addLocale() alias, which is not supported by TypeScript.
=> Closes #2325 - Update to latest javascript-time-ago

pontoon/insights/templates/insights/widgets/insights.html, specs/0108-community-health-dashboard.md
This is a fix for the "change existing chart" part of #2262.
@flodolo could you please review, since it also changes the wording from the spec you wrote?
The implementation of the new chart will follow in a separate patch.
=> New copy for the Unreviewed suggestions insights chart

pontoon/urls.py
See #2378 for more information.
=> Fix #2378 - Remove legacy redirect for en-US locale

frontend/public/static/locale/en-US/translate.ftl, frontend/src/core/api/entity.ts, frontend/src/core/api/index.ts, frontend/src/core/api/types.ts, frontend/src/core/entities/actions.ts, frontend/src/core/entities/reducer.ts, frontend/src/modules/entitieslist/components/EntitiesList.tsx, frontend/src/modules/entitieslist/components/Entity.css, frontend/src/modules/entitieslist/components/Entity.test.js, frontend/src/modules/entitieslist/components/Entity.tsx, pontoon/base/models.py, pontoon/base/tests/models/test_entity.py, pontoon/base/urls.py, pontoon/base/views.py
=> Add ability to reveal adjacent strings 

pontoon/urls.py
=> Remove legacy Aurora redirects

frontend/src/modules/search/components/FiltersPanel.tsx, frontend/src/modules/search/components/SearchBox.tsx
Selecting the same filter will refresh the list.
=> Add ability to Re-apply existing filter

pontoon/administration/templates/tag_inline_formset.html, translate/public/translate.html
Fixes #2478, see discussion there.
=> Add `translate="no"` attributes to React root elements

pontoon/administration/templates/admin_project.html
Missed that when fixing #2434.
=> Rename Deadline to Target Date in Project Admin

translate/src/modules/entitydetails/components/EntityDetails.test.js, translate/src/modules/entitydetails/components/EntityDetails.tsx
Built on #2518, will be rebased once that's merged; only the last commit is actually meant for this PR.
As discussed in https://github.com/mozilla/pontoon/pull/2437#discussion_r815229774, some of the tests needed to be skipped due to refactoring changes. Here, EntityDetails and its tests are refactored, allowing the last skipped tests to be un-skipped.
=> Drop EntityDetailsBase wrapper; un-skip all tests

translate/src/modules/fluenteditor/components/RichTranslationForm.tsx
This is a side effect of chasing windmills while working on #2549. The previous code structure used a rather imperative style that's replaced here with something more React-ish and hopefully easier to understand and reason about.
=> Refactor RichForm internals as components rather than inner functions

translate/src/core/editor/components/TranslationLength.test.js, translate/src/core/editor/components/TranslationLength.tsx
=> Use correct source length for FTL strings

translate/src/context/Editor.tsx, translate/src/core/editor/hooks/useHandleShortcuts.ts, translate/src/modules/machinery/components/Translation.test.js, translate/src/modules/machinery/components/Translation.tsx, translate/src/modules/otherlocales/components/Translation.test.js, translate/src/modules/otherlocales/components/Translation.tsx, translate/src/test/utils.js
Fixes #2567
Filed as a draft for now as no tests are provided for `modules/otherlocales/components/Translation.tsx`.
=> Copy only contents of FTL string from other-locales view

translate/src/App.tsx, translate/src/modules/entitydetails/components/Entity.tsx
=> Move EntityViewProvider from Entity to App to allow its use in UserMenu

translate/src/context/HistoryData.tsx, translate/src/core/entities/hooks.ts
=> Force-refresh history after submitting a translation with no next string

pontoon/base/middleware.py, pontoon/settings/base.py
This is an old feature used on some test instances for demo purposes. It's no longer required and ugly.
=> Remove ability to auto login users

.eslintignore, .prettierignore
Fix #2468.
This should speed up relevant make commands significantly.
=> Run Prettier and ESLint in relevant folders only

pontoon/terminology/models.py
=> Obsolete entities when mass deleting terms

pontoon/base/templatetags/helpers.py, pontoon/base/tests/test_helpers.py, pontoon/pretranslation/pretranslate.py
Fix #2697 
If the code looks good, I will add some test cases for the new helper function.
=> Convert fluent strings with single input to simple message before pretranslation

pontoon/base/models.py, pontoon/contributors/templates/contributors/widgets/notifications_menu.html
=> Include Pretranslated strings in new string notification link

docs/dev/first-contribution.rst
Remove optional fields from the instructions.
=> Update URL of pontoon-test repo

pontoon/base/static/js/table.js, pontoon/contributors/static/js/profile.js, pontoon/teams/static/js/bugzilla.js
=> Fix date format in latest activity tooltip inconsistency with the rest of the app

translate/src/context/Editor.tsx, translate/src/modules/translationform/components/EditAccesskey.tsx, translate/src/modules/translationform/components/EditField.tsx, translate/src/modules/translationform/components/TranslationForm.tsx
=> Set refs correctly in EditAccesskey

translate/src/context/Editor.tsx
Fixes #2757 by adding missing source view special-casing to EditorActions.
Tests ought to get added as a part of #2760.
=> Fix copying content into FTL source view

pontoon/contributors/templates/contributors/profile.html, pontoon/contributors/views.py
=> Show "All contributions" by default when accessing own profile

pontoon/base/models.py, pontoon/contributors/templates/contributors/profile.html, pontoon/teams/views.py
=> CC requester to the email sent when requesting a new project

pontoon/contributors/tests/test_views.py, pontoon/contributors/urls.py
=> Drop support for email addresses in contributor URLs

pontoon/machinery/utils.py, pontoon/pretranslation/pretranslate.py, pontoon/pretranslation/tasks.py, pontoon/pretranslation/tests/test_pretranslate.py, pontoon/pretranslation/tests/test_tasks.py, pontoon/sync/tasks.py, pontoon/sync/tests/test_tasks.py
A set of smaller changes split into even smaller commits done as part of a fix for #2733.
Let's deploy this without the actual fix to lower the risk of regressions slightly.
=> Preparation work for text-only pretranslation of Fluent strings

pontoon/base/static/css/style.css, pontoon/machinery/static/js/machinery.js
=> Fix NaN on /machinery page

pontoon/base/models.py, pontoon/base/utils.py, pontoon/batch/utils.py, pontoon/batch/views.py, pontoon/pretranslation/tasks.py
=> Factor out bulk ChangedEntityLocale creation

pontoon/base/models.py, pontoon/base/tests/models/test_entity.py
=> Move mark_changed() model method from Entity to Translation model

pontoon/administration/templates/admin_project.html
=> SYNC button should be disabled when a project is disabled

translate/src/core/user/components/UserMenu.test.js, translate/src/core/user/components/UserMenu.tsx
=> Admin · Current Project link broken in All Projects view

translate/src/core/placeable/components/Highlight.test.js, translate/src/core/placeable/components/Highlight.tsx
=> Use correct match for highlighted terms

pontoon/base/views.py, translate/public/locale/en-US/translate.ftl, translate/src/api/translation.ts, translate/src/modules/history/components/HistoryTranslation.test.js, translate/src/modules/history/components/HistoryTranslation.tsx
=> Tooltip on rejected string authors says "Not reviewed yet"

pontoon/projects/views.py
The form for sending manual notifications to project contributors can get slow quickly due to the way past notifications are retrieved.
This patch fixes that by reducing the number of DB calls.
=> Speed up project notifications tab

pontoon/base/models.py
We'll add tests one day!
(As part of fixing #2040 if not earlier.)
=> Exclude obsolete entities when aggregating locale stats

specs/0113-pretranslation-opt-in.md
=> Add specs for Pretranslation opt-in UI

pontoon/translate/views.py
Restore access to the currently broken [All Projects Translate view](https://pontoon.mozilla.org/sl/all-projects/all-resources/) by restoring dedentation.
=> Restore access to the All Projects Translate view

translate/src/api/utils/base.ts, translate/src/context/MachineryTranslations.tsx, translate/src/modules/entitydetails/components/EntityDetails.test.js, translate/src/modules/entitydetails/components/EntityDetails.tsx
Fixes #2874
Also improves the errors logged for 404 errors.
=> Do not load team comments or other locales if there is no entity

translate/src/modules/translationform/utils/editFieldExtensions.ts
Fixes an issue identified on the Pontoon Matrix channel:
> Somehow Firefox does now not apply spellchecking to some parts of the contenteditable div anymore.
> https://share.cleanshot.com/x0ZQ4k9P
> If I rightclick on the last part of the edited string, you don't see the menu items related to spellchecking anymore, right clicking on the start of the string shows the entries related to the spellchecker.
> It seems, that Firefox stops spellchecking at the beginning of the <a> tag.
The spellcheck decorations were not being updated when the editable content updated.
=> Update spellcheck decorations on content updates

pontoon/teams/views.py
This reverts commit c963b7fdadd6f781e6f9d04cd3ac1d23d8e8a561.
The patch is deployed to stage.
=> Revert "Temporarily disable the ability to Request Pretranslation"

pontoon/base/models.py
=> Do not allow empty translations in strings.xml files

translate/src/modules/comments/components/AddComment.tsx
=> Do not grab focus for AddComment edit field if active element is an editor

requirements/default.in, requirements/default.txt
'nuff said.
The patch is deployed to stage.
=> Update to compare-locales 9.0.2

pontoon/base/admin.py
https://mozilla-pontoon-staging.herokuapp.com/a/
In Comment Admin, searches by Comment.content.
In Entity Admin, searches by Entity.string and Entity.string_plural.
In Translation Admin, searches by Translation.string.
=> Enable search in Comment, Entity and Translation Admins

translate/src/modules/placeable/components/Highlight.test.js, translate/src/modules/placeable/components/Highlight.tsx
=> Fix search terms for `"` and `""`

pontoon/base/management/commands/heroku_deploy_setup.py
Fix #2460.
Remove reference to Project.url field which was removed in #2862.
=> Fix deployment using Deploy to Heroku button

docs/admin/deployment.rst, docs/admin/maintenance.rst, pontoon/settings/base.py
=> Document DDoS mitigation

requirements/default.in, requirements/default.txt, requirements/dev.txt
Fix #3099.
Also update django-jinja to the latest version.
=> Update Django to the latest dot version

pontoon/localizations/templates/localizations/includes/resources.html, pontoon/localizations/templates/localizations/widgets/resource_list.html, pontoon/localizations/tests/test_views.py, pontoon/localizations/views.py
=> Optimize logic to retrieve Resources in the Localization dashboard

pontoon/checks/libraries/pontoon_db.py, pontoon/checks/tests/test_pontoon_db.py
=> Add warning for _any_ empty Fluent entries

docs/admin/deployment.rst
See #3135. This is just a docs update, it doesn't actually fix the issue.
=> Document clearing the session store

pontoon/translations/forms.py, pontoon/translations/tests/test_forms.py
Prevent possible AttributeError when Entity or Locale validation fails.
=> Fix validation message on translation creation

pontoon/administration/static/js/admin_project.js, pontoon/administration/templates/admin_project.html, pontoon/administration/urls.py, pontoon/administration/views.py, pontoon/base/models.py, pontoon/contributors/templates/contributors/widgets/notifications_menu.html
Fix #3083.
The main change here is to [Retrieve project locales asynchronously to speed up loading of the page](https://github.com/mozilla/pontoon/commit/f43e01863abbf36dcdbf0bdabe88899b7879bee4).
_Updated: deployed to stage._
=> Project Admin page optimization

pontoon/base/management/commands/warmup_cache.py
Since the cache timeout is the same as the frequency of the warmup task, it's possible that we hit the warm cache when making the request to warmup cache.
To make sure cache data is refreshed, we delete it before making a request which will populate it again.
=> Make sure cache data is refreshed by deleting it before making a request which will populate it again

pontoon/base/models/entity.py
=> Do not search in comments

.github/workflows/backend.yml, .github/workflows/frontend.yml, .github/workflows/tag-admin.yml
=> Automation: Use token for Codecov

pontoon/messaging/static/css/email_consent.css
=> Add equal weight to the No, thanks button on the Email consent page

requirements/default.in, requirements/default.txt
Improve placeable checks for Android projects.
=> Update compare-locales to 9.0.4

pontoon/base/static/css/style.css, pontoon/base/static/js/lib/jquery.timeago.js, pontoon/base/static/js/main.js, pontoon/contributors/templates/contributors/widgets/notifications_menu.html
Fix #3281.
Fix for notifications time display in django template
=> Django notifications time display

pontoon/messaging/utils.py, requirements/default.in, requirements/default.txt
=> Replace html2text with BeautifulSoup

docs/dev/setup-virtualenv.rst
Not sure if this should be removed, but the doc is currently wildly outdated.
=> Update doc for virtualenv

.github/workflows/backend.yml
=> Collect coverage in Backend workflow (Python)

translate/jest.config.js
=> Collect coverage for npm test in /translate

docker-compose.yml, pontoon/settings/base.py, pontoon/wsgi.py, requirements/default.in, requirements/default.txt
One more. :)
Deployed to stage. Also tested locally.
=> Replace unmaintained wsgi-sslify with Django settings

.codecov.yml
I'd rather do this than exclude the file from prettier.
=> Run prettier on the new .codecov.yml file

pontoon/settings/dev.py, requirements/default.in, requirements/default.txt
=> Fix graphql on DEV server, update django-graphene to 3.2.2

pontoon/base/views.py
Noticed this while reviewing #3400.
=> Reduce the number of DB queries when retrieving translation history

pontoon/base/models/comment.py, pontoon/base/tests/models/test_comment.py, pontoon/test/factories.py
History panel is currently broken is it contains translations with comments.
=> Fix user status in translation comments

.codecov.yml
1. Don't add a comment if the PR is making things better.
2. Include fewer sections in the comment; the header should include a link to the full report.
=> Less and smaller codecov comments

translate/src/modules/search/components/FiltersPanel.css
Similar to https://github.com/mozilla/pontoon/pull/3411.
=> Make priority starts visible in the Filter Panel on hover

docs/admin/deployment.rst
=> Added documentation for new badge env variables

translate/src/api/user.ts, translate/src/modules/user/reducer.ts
Minor inconsistency between backend and a couple of places on frontend found while working on #3422.
=> Clean up user data api

pontoon/contributors/templates/contributors/settings.html
=> Show contact email address in settings if set

pontoon/base/models/locale.py, pontoon/base/models/translated_resource.py
Fix #3447
Fix #2608
See https://github.com/mozilla/pontoon/issues/3447#issuecomment-2485498811 for more details.
=> Do not special-case Public projects for Locale stats calculation

specs/0120-transactional-emails.md
Minor updates for more consistent styling.
=> Formatting updates for the Transaction Emails spec

pontoon/base/static/css/style.css, pontoon/messaging/static/css/messaging.css, translate/src/modules/user/components/UserNotification.css
Found these two minor inconsistencies while sending the TM tab announcement message.
=> Messaging css fixes

requirements/default.in, requirements/default.txt, requirements/dev.txt
=> Update to Django 4.2.17

pontoon/messaging/emails.py, pontoon/messaging/templates/messaging/emails/manual.html, pontoon/messaging/views.py
Also: Factor out `send_manual_emails()` and move it to `pontoon.messaging.emails`.
=> Use Base email template for emails sent from the Messaging Center

pontoon/base/views.py
Fix #3469 
This PR factors out the logic for sending comment notifications for both team and translation comments to locale managers and translators.
**To reproduce results**: Upon starting the server, go to any locale and add yourself as a manager/translator within that locale (using the `/permissions/` page). Then, create a new superuser in a new terminal. Open a new container tab/browser session, and log in to the local session of Pontoon using the new superuser you created. Go to any string in the same locale that the first account is now a manager/translator for, and add a team comment and translation comment. The first account should receive a notification in both cases.
TODO:
- Update [notification documentation](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/n …
=> Send translation comment notifications to managers and translators

pontoon/api/schema.py, pontoon/api/tests/test_schema.py
Fix #3531.
Adds a GraphQL API call support for simple case-insensitive search of Translation Memory source and target strings for a given locale.
Example:
```graphql
query {
tmSearch(search: "Firefox", locale: "sl") {
source,
target,
project {
name,
},
}
```
Response:
```json
{
"data": {
"tmSearch": [
{
"source": "Update your Firefox",
"target": "Posodobi Firefox",
"project": {
"name": "Mozilla.org"
}
},
]
}
}
```
=> Add ability to search TM via API

pontoon/teams/views.py
=> Revert project_stats QuerySet which breaks stats

pontoon/teams/views.py
=> Show latest activity for project-locale, not project, in /[locale]/

docs/admin/deployment.rst, pontoon/settings/base.py
Unfortunately, for my custom setup, I need to disable the `sslmode`. This change gives me the option to do that.
=> add the DATABASE_SSLMODE env var

pontoon/sync/core/translations_to_repo.py, pontoon/sync/tests/test_translations_to_repo.py
=> Create missing folders in path before writing translated file

pontoon/base/management/commands/calculate_stats.py
=> Calculate stats only on enabled projects by default, add `-all` option

pontoon/sync/core/translations_to_repo.py
=> Do not commit pretranslations with warnings

pontoon/base/models/project.py, pontoon/sync/core/checkout.py, pontoon/sync/core/entities.py
=> Create TranslatedResources for all DB (rather than VCS) locales

pontoon/administration/static/css/admin.css, pontoon/administration/static/js/admin.js, pontoon/administration/templates/admin.html, pontoon/administration/views.py, pontoon/settings/base.py
addresses #3543 
Sample video of how the toggle disable/enable projects in the admin page looks like:
https://github.com/user-attachments/assets/0afdb02f-a29a-469f-a680-c0f761c17504
=> Feature: Toggle between enabled and disabled project

pontoon/sync/formats/xml.py
Oops, include missing parentheses.
=> Fix Android strings regexp

pontoon/localizations/templates/localizations/widgets/resource_list.html, pontoon/tags/templates/tags/widgets/tag_list.html
Fix #3657.
This strictly fixes #3657 (i.e. the symptom), but not the underlying problem with stats calculation).
=> Prevent ZeroDivisionError on resource and tag list

pontoon/administration/views.py
Regression from:
https://github.com/mozilla/pontoon/commit/2e7d8db594ecd1d662818b13b58a5fb0e41bc7f4
=> Fix stats_data() call in Admin

pontoon/api/serializers.py
Possible naive, but attempting to fix #3706
=> API v2: exclude disabled and system projects

pontoon/api/serializers.py, pontoon/api/views.py
=> Exclude disabled and system projects in API

pontoon/base/migrations/0093_delete_more_empty_gettext_plurals.py
Remove values missed out in #3722.
=> Delete additional empty Translation & TranslationMemoryEntry plural gettext values

pontoon/api/schema.py, pontoon/base/middleware.py, pontoon/settings/base.py
This PR resolves #3747.
Need clarification on if more warning is needed.
=> Add Deprecation Warning for GraphQL requests

pontoon/base/migrations/0099_add_trailing_fluent_newlines.py, translate/src/context/Editor.tsx
=> Ensure all Fluent strings end in a newline

pontoon/contributors/tests/test_views.py, pontoon/contributors/views.py, translate/src/hooks/useTranslator.test.js
This PR addresses [https://bugzilla.mozilla.org/show_bug.cgi?id=1987028](url).
=> add permission check to token deletion
