mozilla/pontoon

- pontoon/base/static/js/translate.js
The link to a contributor profile in the History tab links to a non-existing users/ page. 
It should probably go to the contributor's profile instead.
> Fix contributor profile link from the History tab

- .buildpacks
- Aptfile
- docker-compose.yml
- pontoon/administration/vcs.py
- pontoon/settings/base.py
This removes some of the git-specific auth code I added and instead configures Docker to use the SSH keys of the system it runs on and Heroku to load an SSH key from the environment. This also adds a buildpack to install Subversion and Mercurial onto the Heroku dynos since they don't come with it pre-installed.
Testing the Heroku SVN/HG bits is blocked by [bug 1166010](https://bugzilla.mozilla.org/show_bug.cgi?id=1166010), but while we're waiting this could use a second pair of eyes.
> Use SSH Keys for VCS auth on Heroku/Docker

- docs/admin/deployment.rst
- pontoon/settings/base.py
On Heroku, we'll have to provide a relative path to the binary since the app directory moves around during the Python build process.
This has been tested on the staging server and appears to work with the properly set environment variable.
> Re-enable minification via yuglify.

- pontoon/base/models.py
This is a fix for overriden CommaSeparatedIntegerField validator:
https://github.com/mathjazz/pontoon/commit/2680745895d86270b4c8699502cba807b674c157#commitcomment-12129310
@Osmose, r?
> Fix field validator

- pontoon/base/static/js/pontoon.js
- pontoon/base/static/js/translate_old.js
- pontoon/base/views.py
This PR does two things:
1. If no resource or subpage is requested in URL, it selects the first one available **for locale**.
2. In translate view, if selected locale doesn't support selected resource or subpage, fallback to the first option available.
Also removes "unreachable code after return statement" JS warning (should be a separate branch).
@Osmose, r?
> Properly select default resources and subpages

- pontoon/base/templates/project_selector.html
If project was created but not imported, it was impossible to open it from the admin project list, because it wasn't linked to. Because we relied on stats to check if we should create the link or not.
@Osmose, r?
> Fix project admin links for non-imported projects

- bin/mozilla-en-US.py
- pontoon/administration/files.py
- pontoon/administration/vcs.py
Mozilla product localization involves Firefox, Firefox for Android, Thunderbird, Lightning and Mozilla Suite. Instead of having 5 different repositories with l10n resources like all other projects do, we are dealing with just 2 repositories, one for Firefox and Firefox for Android, and one for Thunderbird, Lightning and Mozilla Suite. Both of these epositories are huge, because they contain the entire codebase of these products.
That means we have to move folders around to create fake per-project repositories, because this is what Pontoon expects. Depending on how long will it take to clone 2,5 GB of repositories on each sync cycle on staging, we might need to adapt sync to do it only every 2 hours for these projects.
@Osmose, r? It was convenient to simply add 3 blocks of code to …
> Enable Mozilla product localization

- bin/post_compile
- docs/admin/deployment.rst
- pontoon/settings/base.py
Since collectstatic has trouble building the assets during the normal build, we build them during post_compile, when the path issues that cause collectstatic to fail don't exist anymore.
This commit also reverts the previous removal of the translate app as that was a temporary fix.
This has been tested on staging and seems to work fine. Before deploying to production we'll want to set the `DISABLE_COLLECTSTATIC` environment variable on prod to get rid of annoying non-error messages during the build.
@mathjazz r?
> Fix bug 1188929: Build assets in post_compile.

- pontoon/settings/base.py
- requirements.txt
Re-enables Raygun and temporarily uses my fork of raygun4py with a fix
for our unicode issues. Once the fix gets merged we should switch back
to the official library.
@mathjazz r?
> Bug 1179963: Re-enable raygun and use fork.

- .buildpacks
- docs/admin/deployment.rst
Pins our buildpacks to specific commits that we know work for deploying Pontoon. Also documents the process of pinning the multi-buildpack that combines them together.
This has been tested and works on staging, including pinning the multi-buildpack.
@mathjazz r?
> Pin buildpacks

- pontoon/base/static/js/main.js
- pontoon/base/templates/locale_selector.html
- pontoon/base/templates/project_selector.html
- pontoon/base/templatetags/helpers.py
* If two projects/locales have equal share of approved strings, we sort them by comparing unapproved.
* In locale selector, sort locales by alphabetic order.
* Remove project.details from project selector when data not available.
> Fix sorting

- pontoon/settings/base.py
@Osmose, quick r?
This enables EXCLUDES list again, which removes me from the top contributors list. I've been using Pontoon since day 1 and it's not fair I'm on that list.
While this fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1179956, I'm leaving it open in case we want to explore solutions for reading lists from environment variables. Which is less urgent than removing my name from the list.
> Set EXCLUDES setting via environment

- pontoon/base/models.py
This fixes an issue with deletion where approved translations for other locales would cause Entity.has_changed to return False when no approved translations exist for the given locale.
@mathjazz r?
> Filter by locale when checking if translation changed.

- pontoon/base/migrations/0012_auto_20150804_0859.py
We have way more locales enabled than there are localization teams at
Mozilla, so things like he-IL vs he confuse people. This migration
removes unused locales and we'll and new ones if requested.
@Osmose, r?
> Remove unused locales

- pontoon/base/static/js/translate_old.js
Show Sign in warning to non-authenticated users right after projects get selected. Make it persistent.
https://bugzilla.mozilla.org/show_bug.cgi?id=1183013
@Osmose, r?
> Bug 1183013: Make Sign in warning more visible

- pontoon/base/views.py
Do not allow newlines in .lang files translations:
https://bugzilla.mozilla.org/show_bug.cgi?id=1190754
@Osmose, r?
> Bug 1190754: Do not allow newlines in .lang files translations

- pontoon/base/migrations/0013_add_en_US.py
Both are source locales and shouldn't have been removed.
@mathjazz r?
> Add en and en-US locales back to locale list.

- pontoon/base/templates/locale_selector.html
This makes tooltips re-appear on the project landing page.
> Fix project page chart: convert to json

- pontoon/administration/management/commands/sync_projects.py
When constructing a unique key for entities during sync, if Entity.key is blank,
we should use Entity.string as the key value instead.
@mathjazz r? Found this while testing Mozilla.org sync locally. sync_projects used to do this but it got lost during some refactoring, so we need it again.
Without this fix, the langfile parser will create VCSEntities that have a key set to their string value, while database Entities will have a blank key. The code that matches up VCSEntities and database Entities for comparison will not match them up correctly since they will have different keys.
> Bug 1178874: Fall back to string when entity key is empty.

- pontoon/base/models.py
- pontoon/base/vcs_models.py
A subtle bug in the path methods on the Project model caused paths to be
incorrect for projects that do not have locale directories at the root of their
repo. We fix this bug and also simplify the path methods based on how they're
used.
@mathjazz r? This is the bug that was causing issues with the Firefox 3.6 Start project on staging, since it has all it's locales underneath a top-level directory named `locale`.
> Bug 1178874: Handle paths properly in Project path methods.

- pontoon/administration/management/commands/sync_projects.py
This resolves issues like this:
http://viewvc.svn.mozilla.org/vc?view=revision&sortby=date&revision=144394
@Osmose, r?
> Sync: Fallback commit author should be pontoon, not the first admin

- pontoon/administration/files.py
- pontoon/base/models.py
This is a relic from the past, which we no longer use at Mozilla. We treat en-GB as a separate locale we localize into.
@Osmose, r?
> Remove en-GB as possible source locale directory

- pontoon/base/static/js/main.js
We returned 0 instead of dict with values set to 0 if data wasn't
available. It didn't break on other landing pages but project page,
because data is always available.
@Osmose, r?
> Fix sorting on project landing page

- pontoon/administration/management/commands/sync_projects.py
- pontoon/administration/templates/commit_message.jinja
This lets us put some slightly more complex logic in the commit message
template, like hiding the list of authors if none are available.
@mathjazz r?
> Use jinja to render commit messages.

- docs/admin/deployment.rst
- pontoon/settings/base.py
- requirements.txt
This adds the ability to use a shared cache between all the dynos in the app. I've provisioned a 250mb cache for staging and deployed this and since then I haven't been able to replicate the login failure issues, which I suspect are related to the cache given that session-csrf stores anonymous CSRF tokens in the cache.
Plus it's just a good idea for us to use a shared cache anyway.
@mathjazz r?
> Bug 1191133: Support using Memcached as a cache backend.

- bin/dump-verbatim.py
- pontoon/administration/management/commands/import_verbatim.py
I'm using these to scripts to dump data from Verbatim that's not stored in VCS, like attributions and translations submission dates.
@Osmose, please review the import_verbatim.py part.
> Verbatim migration

- pontoon/administration/management/commands/sync_projects.py
- pontoon/base/migrations/0014_auto_20150806_0948.py
- pontoon/base/migrations/0015_remove_project_last_synced.py
- pontoon/base/models.py
Instead of querying for translations every time we need to see if an entity has
changed for a particular locale, we instead store whether the entity has changed
in the database whenever translations are saved. This significantly speeds up
sync_projects by removing a ton of unnecessary database queries.
@mathjazz r?
> Track Entity.has_changed status in the database.

- pontoon/base/models.py
- pontoon/base/static/js/main.js
- pontoon/base/static/js/search.js
- pontoon/base/static/js/translate_old.js
- pontoon/base/templates/search.html
- pontoon/base/templates/translate.html
- pontoon/base/templates/user.html
- pontoon/base/views.py
- pontoon/settings/base.py
That means we no longer need to keep information which locales are RTL and which LTR.
@Osmose, r?
> Use dir="auto" on all elements holding translations

- pontoon/base/models.py
We set stats to 0 after repository is updated and than reset them during
extract. But we never reset them for files that use assymetric file
format and aren't in the locale repository yet. Since we also rely on
stats when picking files to dump and commit, these files never ended
up in the repository. This is a regression and should land asap.
I tested this with Firefox for Android Aurora locally and works as expected.
@Osmose, r? This is quite a serious one.
> Also commit files that aren't in the repository yet

- pontoon/administration/management/commands/sync_projects.py
- pontoon/base/formats/lang.py
- pontoon/base/models.py
- pontoon/base/vcs_models.py
- requirements.txt
Uses django-dirtyfields to determine if an Entity or Translation has actually
changed, so that we only update the database in cases where changes are
necessary rather than blindly updating all the time.
My local sync test case went from 34 seconds to 20 seconds with this change. Progress!
@mathjazz r?
> Bug 1191718: Only update DB during sync when necessary.

- pontoon/administration/management/commands/sync_projects.py
Stats weren't actually being updated due to the bulk actions in `sync_projects`, now they're updated once all the action has happened for each project. Yay!
@mathjazz r?
> Update stats after sync.

- pontoon/base/models.py
Which can mean 10 seconds when loading projects with big resource files
> This makes get_translations() ~50% faster

- pontoon/base/static/js/main.js
- pontoon/base/static/js/translate_old.js
This fix unifies the way we display translations, original strings and
comments across the entire app. E.g. `&hellip;` and `<br />` now always
show up as is instead of being rendered sometimes.
It also unifies the way we insert these escaped strings into textarea when
e.g. copying them from suggestions or pasting placeables. We simply use
jQuery's .text() method.
> Bug 1190843: Fix escaping HTML

- pontoon/administration/files.py
- pontoon/base/models.py
Instead of checking if project contains at least one resource of any asymmetric format, we now check if all project formats are asymmetric.
Use Resource object's is_asymmetric property.
@Osmose, r?
> Proper asymmetric projects detection

- pontoon/administration/files.py
Only remove *child* empty directories when processing asymmetric formats to avoid deleting locale directory itself.
> Only remove *child* empty directories

- pontoon/administration/management/commands/sync_projects.py
- pontoon/administration/tests/test_sync_projects.py
- pontoon/base/formats/__init__.py
- pontoon/base/formats/base.py
- pontoon/base/formats/lang.py
- pontoon/base/formats/po.py
- pontoon/base/migrations/0017_entity_source_jsonfield.py
- pontoon/base/models.py
- pontoon/base/static/js/translate_old.js
- pontoon/base/tests/__init__.py
- pontoon/base/tests/formats/test_po.py
- pontoon/base/tests/test_models.py
- pontoon/base/vcs_models.py
This PR adds support for the po/pot formats to sync_projects. It also updates sync_projects to support plural strings and sources for formats that require them.
Because I had to modify sync_projects a bit, I based this PR off the existing #105 PR. That should be merged before this, and I can rebase once it lands. In the meantime, you can view individual commits to see the three extra commits this adds.
This also adds tests for the pofile parser. They're designed to be generic enough that any format can use them as long as they provide the proper input and output files for each test, but I haven't yet actually done the work yet to make them generic. I figure the PR for xliff can support that so we can have a common set of "requirements" that each format supports, with opt-ins to optional …
> POFile support for sync_projects

- pontoon/administration/management/commands/sync_projects.py
When string is imported, we always set `approved` and `approved_date`
attributes. Which shouldn't happen, if string is fuzzy.
> Fuzzy strings must not be imported as approved.

- pontoon/base/static/css/translate.css
- pontoon/base/templates/translate.html
Also replaces "Unchanged" filter icon (thumb up) with bars (equivalency),
because the new "No results" icons was too similar and might apply relation.
@Osmose, r?
> Fix bug 1193359: Replace unsafe glyph with FA icon

- pontoon/base/migrations/0018_auto_20150820_0925.py
For more details, see:
http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#zh
http://localization-guide.readthedocs.org/en/latest/l10n/pluralforms.html#f2
This PR resets Chinese plurals configuration and removes Chinese translations in plural forms.
@Osmose, r?
> Contrary to our configuration, Chinese doesn't use plurals

- pontoon/base/formats/__init__.py
- pontoon/base/formats/xliff.py
- pontoon/base/tests/formats/__init__.py
- pontoon/base/tests/formats/test_po.py
- pontoon/base/tests/formats/test_xliff.py
Also refactors the pontoon.base.formats tests to be reusable between formats.
@mathjazz r?
> Bug 1178874: Add xliff support to sync_projects.

- requirements.txt
When I tried installing the requirements via peep I got an error with the Django hash not match. I've updated it to the has that works for me.
@mathjazz Can you confirm if this hash works for you? If not, then maybe there's something wrong on my end?
> Fix Django SHA in requirements.txt.

- pontoon/base/templates/500.html
- pontoon/base/templates/landing.html
- pontoon/base/urls.py
Rename both, the title and the URL from Search to Terminology. Search can mean many things and Terminology is much more specific. Also keep the legacy /search URL and redirect it to /terminology. Also update links on static 500 page.
@Osmose r?
> Search2terminology

- pontoon/base/tests/__init__.py
- pontoon/base/tests/test_views.py
- pontoon/base/views.py
Specifically, if a resource has no stats for a given locale, but it has
stats for other locales, viewing strings for that locale in translate
causes an IndexError due to the view code only filtering out unimportant
locales _after_ checking the existence of stats for the resource.
@mathjazz r?
> Fix IndexError when resource has no stats in translate view.

- pontoon/base/static/js/translate_old.js
This is a regression caused by removal of the <base> tag.
@Osmose r?
> When building Go and Sign out URLs, make them absolute

- pontoon/settings/base.py
- requirements.txt
The new commit contains fixes for raygun4py where it was printing errors to
stderr instead of logging them properly, causing extra output during test runs
and other situations.
https://github.com/Osmose/raygun4py/commit/52489dfe17e27119940f0a640e80a6a7577b0606 is the commit being added on top of our existing changes in the fork. Still waiting on Raygun to release a new version with our old fixes as well.
I also added a logging filter for raygun4py logging so we don't see "No API Key aaaaahhh" errors every time a test triggers the middleware.
@mathjazz r?
> Update raygun4py fork commit.

- pontoon/base/static/js/pontoon.js
If we had multiple occurences of the same string in the DOM, we only
matched the last one.
Merging this one too to ship Donations form. Today is the day to break the rules I guess.
@Osmose
> Match source strings with all occurences in the DOM

- pontoon/base/static/css/style.css
When hovering progress charts on project or team or admin page, tooltip
flickers if you hover over the handle (arrow). This solution clips the
arrow, so that hovering over it is not possible, which means flickering
is gone. To achieve this, I use CSS clip property (deprecated, but
needed for Firefox), -webkit-clip-path (needed for WebKit) and clip-path
(standard).
@Osmose r?
> Fix tooltip flickering

- pontoon/base/static/css/style.css
- pontoon/base/static/css/translate.css
- pontoon/base/static/js/main.js
- pontoon/base/templates/locale_selector.html
- pontoon/base/templates/project_selector.html
Sometimes it's hard to distinguish if progress chart is at 99.99% or 100%.
Percentage allows localizers to quickly see if there's work to do or not.
For that reason, we also use floor as rounding function, because showing
100% when 9999/10000 strings are translated is a red herring.
@Osmose r?
> On dashboards, also show progress as percentage

- pontoon/base/templates/translate.html
We currently use the `fa-thumbs-down` for "No results", this gesture is not a friendly gesture.
I think the `fa-exclamation-circle` is a good choice.
Do I need to write a bug for the tiny patch?
> Make a better icon for "No results"

- pontoon/base/tests/formats/bom.lang
- pontoon/base/tests/formats/test_lang.py
@mathjazz r?
The langfile has the BOM, but you'll need a hex editor to see it.
> Add test for leading UTF-8 BOM in langfiles.

- pontoon/sites/static/tiles/css/newTab.css
- pontoon/sites/static/tiles/css/newTabSkin.css
They prevent Pontoon from building in production by raising
whitenoise.django.MissingFileError.
@jotes r?
> Remove chrome:// URLs from tiles CSS

- docs/admin/deployment.rst
- pontoon/administration/files.py
- pontoon/administration/management/commands/sync_projects.py
- pontoon/administration/tests/test_sync_projects.py
- pontoon/base/formats/po.py
- pontoon/base/models.py
- pontoon/base/tests/formats/test_po.py
- pontoon/base/utils.py
- pontoon/base/views.py
- pontoon/settings/base.py
This will require a config change to the Heroku apps before deploying them, namely setting the `TZ` environment variable to `UTC`.
I believe this will also fix bug 1199763.
@mathjazz r?
> Bug 1179950: Enable timezone support.

- pontoon/base/templates/translate.html
We might have projects with both, subpages with page_urls and resource
files without in-place localization.
@Osmose r?
> Properly detect in-place localization mode

- pontoon/administration/files.py
- pontoon/base/__init__.py
- pontoon/base/formats/__init__.py
- pontoon/base/formats/lang.py
- pontoon/base/formats/po.py
- pontoon/base/formats/silme.py
- pontoon/base/formats/xliff.py
- pontoon/base/tests/formats/__init__.py
- pontoon/base/tests/formats/test_po.py
- pontoon/base/tests/formats/test_silme.py
- pontoon/base/tests/formats/test_xliff.py
- pontoon/base/vcs_models.py
- requirements.txt
Adds support for ini, dtd, and properties files, including more format tests for them. This also switches us to using the silme fork at https://github.com/Osmose/silme/ instead of the HG-hosted version.
This also changes how we build entities in vcs_models; in order to support both asymmetric and symmetric formats, we first build entities based on the source resource files, and then load translations from each translated resource. 
I did manual testing for DTD files, but haven't yet manually tested ini and properties files. Suggestions on good projects to use for testing those are welcome, otherwise we can just test on staging before merging.
@mathjazz r?
> Bug 1178874: Add support for silme formats to sync_projects.

- pontoon/base/models.py
If we wanted to match subpage against specific resource(s), its name
had to be exactly the same as the path to the resource file. Which is
lame. This is no loner required. As a consequence, we can now have
several different subpages matched agains the same resource.
@Osmose r?
> Subpage names don't need to match resource paths anymore

- pontoon/base/migrations/0020_auto_20150904_0857.py
- pontoon/base/migrations/0021_auto_20150904_1007.py
- pontoon/base/migrations/0022_remove_locale_nplurals.py
- pontoon/base/models.py
- pontoon/base/static/css/translate.css
- pontoon/base/static/js/translate_old.js
- pontoon/base/templates/translate.html
- pontoon/base/tests/formats/__init__.py
This changes a few things related to plurals:
1. Plural forms are displayed as CLDR values now (one, two, many...) with supscripted example number, calculated from plural rule.
2. For that to work, I had to add missing plural data for all locales. I also removed two unused (duplicate) locales and nplurals field, which can be calculated from the CLDR plurals list length.
@Osmose r?
> Improve plurals

- pontoon/administration/management/commands/sync_projects.py
- pontoon/administration/tests/test_sync_projects.py
- pontoon/base/formats/po.py
- pontoon/base/tests/formats/__init__.py
- pontoon/base/tests/formats/test_po.py
- pontoon/base/tests/formats/test_silme.py
Our pofile sync code had an issue where it would remove the fuzzy flag for an entity if it was fuzzy in VCS, because we weren't checking that the entity was marked as not fuzzy before removing the flag.
To help debug this issue I also added a `--no-pull` argument to `sync_projects` that skips updating from VCS during sync. This let me test syncing on a specific SVN commit, which is really useful for debugging.
@mathjazz r?
> Fix bug 1201212: Preserve fuzzy status for po entities.

- pontoon/base/formats/silme.py
- pontoon/base/tests/formats/__init__.py
- pontoon/base/tests/formats/test_silme.py
The problem is that blank translations would be exported as missing translations by the silme format plugin (meaning Entity.strings would be `{}` instead of `{None: ''}`). Thus, sync thought that VCS had no translation and unapproved all translations in the database, instead of identifying the empty translation as the correct one.
@mathjazz r?
> Fix bug 1203057: Allow blank translations in silme.

- requirements.txt
By adding silme version number to egg, which installs our patched
version of silme library.
@Osmose r?
> Fix bug 1204234: process empty strings on INI file

- pontoon/base/migrations/0002_initial_data.py
- pontoon/base/migrations/0016_auto_20150810_1301.py
@Osmose @mathjazz i wasn't sure how do you work  with database on existing production instances, so i decided to create separate migration instead of modyfing initial_data -> it will update all dev environments. It should resolve issue with 'tl' locale.
> Bug 1206176. From now on en-US is default locale for pontoon-intro

- .gitignore
- pontoon/administration/files.py
- pontoon/administration/forms.py
- pontoon/administration/management/commands/sync_projects.py
- pontoon/administration/static/css/admin_project.css
- pontoon/administration/static/js/admin_project.js
- pontoon/administration/templates/admin_project.html
- pontoon/administration/tests/test_sync_projects.py
- pontoon/administration/views.py
- pontoon/base/migrations/0025_add_repository.py
- pontoon/base/migrations/0026_migrate_repository_info.py
- pontoon/base/migrations/0027_auto_20150910_1735.py
- pontoon/base/migrations/0028_auto_20150915_0013.py
- pontoon/base/migrations/0029_repository_multi_locale.py
- pontoon/base/migrations/0030_repository_source_repo.py
- pontoon/base/models.py
- pontoon/base/tests/__init__.py
- pontoon/base/tests/test_models.py
- pontoon/base/vcs_models.py
Firefox and friends have multiple repos where strings are stored. The
old sync process used some magic code during sync to detect this and
download and commit strings to multiple repositories. This commit adds
support directly to Pontoon for multiple repos so that the new sync
process can support these special repos.
The old sync process still works by assuming that the first-found repo
is the singular repo that it expects.
While this adds UI to the admin interface, it's unpolished due to our
future plans of replacing the admin interface with the Django admin. In
addition, some code for supporting Transifex and File repos has been
removed due to those features also being slated for removal. Rather
than properly support these unused and about-to-die features, we do the
lazy thing and …
> Fix bug 1201707: Add support for multiple repos.

- docs/requirements.txt
- requirements.txt
This should fix docs @ readthedocs.org . You only need to set requirements file to 'requirements_docs.txt' in advanced settings.
Example build is available here: http://jotes-pontoon.readthedocs.org/en/latest/
@mathjazz @Osmose  could you review?
> Bug 1205445. Moved sphinx dependencies to separate file to fix builds

- pontoon/administration/management/commands/sync_projects.py
- pontoon/administration/tests/test_sync_projects.py
- pontoon/base/migrations/0031_changedentitylocale_when.py
- pontoon/base/models.py
When updating from VCS, only unapprove translations that existed before sync
started. This might cause multiple approved translations, so remove duplicate
approvals before committing the sync transaction.
@mathjazz r?
> Fix bug 1204047: Avoid race conditions from translations during sync.

- pontoon/base/static/css/translate.css
Marking placeables with red color is not the best idea, because we use
this color to mark untranslated strings. They also stand out in the
entity list.
Instead, we put them in rounded boxes now, to make them look more like
HTML tags. Boxes also allows us to display empty space placeables. And
we use neutral UI colors.
@Osmose r?
> Change placeables style

- pontoon/base/formats/lang.py
- pontoon/base/tests/formats/test_lang.py
- pontoon/base/tests/test_vcs_models.py
- pontoon/base/vcs_models.py
While I was messing with the langfile tests I also added the standard format tests that we added for all the other supported formats.
@mathjazz r?
> Fix bug 1201936: Handle invalid langfiles with blank translations.

- pontoon/base/tests/test_vcs_models.py
- pontoon/base/vcs_models.py
@mathjazz r?
Note that this isn't entirely correct, as it still uses the `repository_url` property, which defaults to the first repo defined in the database for the project. But it should function correctly for the repos as we currently have them and I've filed [bug 1209375](https://bugzilla.mozilla.org/show_bug.cgi?id=1209375) with what I think the proper long-term fix is.
> Fix bug 1207829: Filter region.properties properly.

- pontoon/base/tests/test_models.py
1) If only one resource defined, don't show it
2) Subpage names are now sorted alphabetically
@Osmose r?
> Fix project parts tests

- pontoon/base/tests/test_models.py
We cannot predict the PKs being assigned, but we do have access to what their values are supposed to be, so we can still assert them!
I don't think this calls for review so I'm skipping it, but leaving a PR here just to note the change.
> Test for actual pks instead of guessing what they are.

- pontoon/base/formats/silme.py
- pontoon/base/tests/__init__.py
- pontoon/base/tests/formats/test_silme.py
- pontoon/base/tests/test_vcs_models.py
- pontoon/base/vcs_models.py
When importing strings from VCS, only uncomment the entity when parsing
source resources. When exporting strings, only uncomment the entity if
Pontoon has a translation for it.
@mathjazz r?
> Fix bug 1209423: Correctly handle MOZ_LANGPACK_CONTRIBUTORS.

- pontoon/base/static/js/project.js
In /projects/SLUG/, if you click on Add to request new locales, activity and progress columns need to be hidden.
@Osmose r?
> Hide columns not needed in add locale view

- pontoon/base/static/css/translate.css
Untranslated icon looked like a prohibitive road sign, giving the
impression of "Don't come in here, you don't have a permission to enter".
It was also clashing with unchecked status of our custom checkbox (used
e.g. for enabling/disabling quality checks).
I dare to merge this.
> Fix bug 1190572: Replace untranslated icon

- pontoon/administration/management/commands/sync_projects.py
- pontoon/administration/tests/test_sync_projects.py
- pontoon/administration/tests/test_vcs.py
- pontoon/administration/vcs.py
- pontoon/base/migrations/0032_repository_last_synced_revisions.py
- pontoon/base/models.py
- pontoon/base/tests/test_models.py
Now we track the revision number/hash from the last time we synced, and
use that to determine if VCS has changed since the last sync. If not,
and there are no changes in the DB, we can skip syncing completely.
If things fail, sync should default to assuming changes exist, degrading gracefully to the old behavior.
@mathjazz r?
> Fix bug 1191718: Don't sync when there are no changes.

- pontoon/base/templates/locale_selector.html
After locale was added to the project and before it got imported, dashboards
with locale selector (namely project dashboard) failed with server error,
becuse we had no chart data an attempted to divide with None.
@Osmose r?
> Fix server error after locale added, but not imported

- pontoon/base/static/js/translate_old.js
Turns out my initial assessment in [bug 1212738](https://bugzilla.mozilla.org/show_bug.cgi?id=1212738) about the fix was wrong; the UI depends on `pluralForm` being `-1` for locales with `nplurals == 1`, regardless of what is stored in the database as the plural form of the string.
This fixes the issue on our current UI, but it's a bandaid. The hopeful future redesign/re-implementation will have to take a few things into consideration:
1. This was caused by a conflation of UI logic and app logic. Because we determined the plural form from which DOM elements were visible, the UI requirement of hiding the plural tabs for locales with `nplurals == 1` got conflated with our logic of what plural form to store in the database.
2. We don't currently have any good way to represent in the database …
> Fix bug 1212738: Send proper plural_form when updating translations.

- pontoon/base/apps.py
- pontoon/base/migrations/0036_project_has_changed.py
- pontoon/base/models.py
- pontoon/base/signals.py
- pontoon/base/tests/test_models.py
- pontoon/base/tests/test_signals.py
- pontoon/sync/core.py
- pontoon/sync/tests/test_core.py
By marking projects as changed when we update locales, we force sync to run even if there haven't been any new translations or changes in VCS.
This depends on #204 because I didn't want to handle the rebasing process after it gets merged. Feel free to comment just on the last commit, or wait until #204 lands. Probably the latter.
@mathjazz r?
> Fix bug 1211271: Mark projects as changed on locale add.

- pontoon/administration/templates/admin_project.html
- pontoon/base/models.py
- pontoon/base/static/css/locale_project.css
- pontoon/base/static/css/style.css
- pontoon/base/static/css/translate.css
- pontoon/base/static/css/user.css
- pontoon/base/static/js/locale_project.js
- pontoon/base/static/js/main.js
- pontoon/base/static/js/translate.js
- pontoon/base/templates/locale_project.html
- pontoon/base/templates/locale_selector.html
- pontoon/base/templates/part_selector.html
- pontoon/base/templates/project_selector.html
- pontoon/base/templates/translate.html
- pontoon/base/templates/user.html
- pontoon/base/tests/test_models.py
- pontoon/base/tests/test_views.py
- pontoon/base/urls.py
- pontoon/base/views.py
- pontoon/settings/base.py
This brings search across entire project, one of the most requested features by localizers. Full description is available as part of 3 commit messages. (I don't know how 9289678 ended up there, please ignore it before I remove it from this PR.)
@Osmose, I'd like to hear your feedback.
I decided to stick with my original plan of having joint Search and Resources/Subpages menu. Having separate menus is problematic, because it doesn't allow selecting resources when you're on the results page. I will however change the design to put resource selection and search in tabs.
For now it only searches original strings. I'd like to add options for searching translations, suggestions, comments, keys, and search case sensitive.
I'll add and update tests before asking for full code review.
> Bug 1178880 project locale dashboard with search

- pontoon/base/migrations/0037_entity_resource_related_names.py
- pontoon/base/models.py
- pontoon/base/templates/locale_selector.html
- pontoon/base/tests/test_models.py
- pontoon/base/views.py
- pontoon/sync/changeset.py
- pontoon/sync/core.py
Only fetch data for locales active in the project, and avoid
selecting all the project locales for each locale in the project.
Testing with django-debug-toolbar on a project with 3 locales, the project page with the locale listing went from 235 database queries to 18 and loads significantly faster.
This also has some query fixes I found while I was looking that don't particularly improve our performance, but improve our comprehensibility.
@mathjazz r?
> Add reverse FK names and optimize locale list.

- pontoon/base/migrations/0037_entity_resource_related_names.py
- pontoon/base/models.py
- pontoon/base/templates/locale_selector.html
- pontoon/base/tests/test_models.py
- pontoon/base/views.py
- pontoon/sync/changeset.py
- pontoon/sync/core.py
ae324e04bb27038bf6c5b4e841dec782791f53aa got pulled because it made the translate view slow. I've added an extra commit that removed a suspicious query from the prefetching for `locales_parts_stats` that was doing in `IN` query on a set of hundreds of ids. Locally, my translate view now loads roughly as fast as it does on the current master with this tweak, whereas without the extra commit it runs twice as slow.
The original "Add reverse FK names" commit should be identical to the one previously merged (different hash since it's rebased but it's the same changes otherwise).
@mathjazz r?
> Speed up locale list

- pontoon/base/static/css/translate.css
- pontoon/base/static/js/translate.js
- pontoon/base/templates/project_selector.html
- pontoon/base/urls.py
- pontoon/base/views.py
This changes the way we load project, locale, resource and stats data for the main menu. Instead of loading data as part of the main server request, we make separate AJAX requests for each project. Except for the currently translated project, so its resources/subpages/search are available immediately.
AJAX requests are triggered all at once, without any smart logic, letting the browser handle them within its limits. Requests are made after loading entities, which performs better than the other way around. Projects in the project menu are hidden until their AJAX request completes.
This is deployed on [staging](https://mozilla-pontoon-staging.herokuapp.com/) and is showing significant performance improvements:
- Main request: 12s vs 2s (> 80%)
- All requests: 18s vs 9s (> 80%)
- Full page …
> Use AJAX to fetch main menu data

- pontoon/administration/views.py
- pontoon/base/migrations/0038_add_latest_translation.py
- pontoon/base/migrations/0039_projectlocales_unique.py
- pontoon/base/models.py
- pontoon/base/signals.py
- pontoon/base/templates/locale_selector.html
- pontoon/base/templates/part_selector.html
- pontoon/base/templates/project_selector.html
- pontoon/base/tests/__init__.py
- pontoon/base/tests/test_models.py
- pontoon/base/tests/test_signals.py
- pontoon/base/tests/test_utils.py
- pontoon/base/tests/test_views.py
- pontoon/base/utils.py
- pontoon/base/views.py
This relies on #216, will rebase after that gets merged. Pay attention to the last commit only.
This denormalizes the latest activity such that Project, Resource, Locale, and ProjectLocale (which was previously an implicit through model for Project.locales) all have a `latest_translation` field that gets updated when translations are saved. The listings that show the latest activity now efficiently pull the `latest_translation` field when trying to figure out which translation qualifies as the latest activity, as opposed to doing a bunch of queries to find the latest activity.
Locally this led to a major drop in load time for the project, locale, and resource listings for me. It also reduced the number of database queries on each page by quite a bit.
@mathjazz r?
> Bug 1214392: Denormalize latest activity.

- pontoon/sync/changeset.py
- pontoon/sync/tests/test_changeset.py
Before this PR, we approved all DB translations with matching VCS counterparts, including the ones with fuzzy VCS counterparts.
Such translations were marked as both, approved and fuzzy in Pontoon, which means:
A. They were treated as approved in the translate view.
B. They were treated as fuzzy in sync (didn't get committed).
C. They were treated as both in stats, so stats were broken.
This PR fixes A. C will be fixed the next time sync will run for these projects. We can also do it manually.
@Osmose r?
> Fix bug 1201212: Do not approve translations with fuzzy VCS counterparts

- pontoon/base/models.py
- pontoon/sync/__init__.py
- pontoon/sync/formats/po.py
- pontoon/sync/tests/formats/test_po.py
- pontoon/sync/tests/formats/test_xliff.py
Some 70+ strings aren't even displayed in SUMO without this.
@Osmose r?
> Fix bug 1216452: Add support for msgctx in PO files

- bin/post_compile
- docs/admin/deployment.rst
Was trying to figure out performance stuff this morning and got tired of not knowing when deploys are happening while on New Relic.
The necessary environment variables are already on staging and prod. I tested on staging earlier and it seems to work fine: https://rpm.newrelic.com/accounts/263620/applications/8734596/deployments
@mathjazz r?
> Notify New Relic on deploy.

- pontoon/base/templates/contribute.json
- pontoon/urls.py
@Osmose What do you think about this?
If not else, it fixes the missing blank line above Robots.txt!
Ref:
https://bugzilla.mozilla.org/show_bug.cgi?id=1179796
> Expose contribute.json file on web root

- pontoon/administration/vcs.py
@Osmose r?
I wonder if this also fixes the funny fact that @stenox is marked as committer of pretty much all Pontoon commits on GitHub?
See:
https://github.com/mozilla-services/FindMyDevice-l10n/commits/master
https://github.com/mozilla/loop-client-l10n/commits/master
> Fix git user name and email

- pontoon/base/templates/translate.html
- pontoon/settings/base.py
This is half of a change to both the main site and pontoon-intro that reduces the number of static resource requests by doing better bundling on the intro and translate views.
The other half can be found at https://github.com/mozilla/pontoon-intro/pull/2.
Once this gets approved, I'll merge the change into pontoon-intro and rebase this change, including an update to the submodule, and then merge. 
@mathjazz r?
> Reduce static resource requests with more bundling.

- docs/admin/deployment.rst
- pontoon/settings/base.py
I've already had jp help set us up with a cloudfront CDN for prod (e.g. https://d183y7hobzemob.cloudfront.net/static/css/base.min.09ddf404e0aa.css). Once this hits prod we can set the `STATIC_HOST` environment variable and all of our static assets should be served through a CDN instead of directly through our site.
@mathjazz r?
> Add STATIC_HOST setting to support CDN use.

- bin/mozilla-en-US.py
- pontoon/administration/vcs.py
We need this pretty quickly, because the merge day just happenned today instead of Monday. I'm only implementing it for HG for now, which is also the only place we currently need it.
It works on the old Pontoon server (within the mozilla-en-US script):
http://hg.mozilla.org/users/m_owca.info/firefox-aurora/rev/72d219e997ef
I'll add tests once I extend it to other VCS types. Although I'm not exactly sure how to test these things.
> Bug 1201431: remove missing files & folders from HG

- pontoon/administration/vcs.py
I don't get the warning locally but commit totally still works and I believe this will get rid of the warning.
@mathjazz r?
> Bug 1214670: Explicitly push master when dealing with git.

- pontoon/base/static/css/style.css
- pontoon/base/static/js/main.js
I'm trying to make messaging around requesting new locale clearer. Because I'm getting many duplicate submissions. Which means UX sucks. I suppose for several reasons:
1) On project pages with longer locale list, confirmation is never visible.
-> Scrolling to top after request is made.
2) "Add" implies users can add locales themselves to projects.
-> Changing to "Request".
3) We never told anyone they will be notified when locale is enabled via email.
-> Adding that to the confirmation message.
> Make request locale UX more pleasant

- pontoon/base/signals.py
- pontoon/base/static/css/locale_admin.css
- pontoon/base/static/css/style.css
- pontoon/base/static/css/users.css
- pontoon/base/static/js/locale_admin.js
- pontoon/base/templates/locale.html
- pontoon/base/templates/locale_admin.html
- pontoon/base/templates/locale_contributors.html
- pontoon/base/templates/project.html
- pontoon/base/templates/widgets/contributors.html
- pontoon/base/templates/widgets/menu.html
- pontoon/base/tests/test_views.py
- pontoon/base/urls.py
- pontoon/base/views.py
- pontoon/settings/base.py
- pontoon/sync/tests/test_core.py
- pontoon/urls.py
Adding team admin page, available to locale managers, where they can select privileged users. This PR is branched from #219, so only check the last commit. I will rebase once #219 gets merged.
I'm especially interested in more elegant solution for exposing the "Admin" in Locale dashboard to locale managers only.
> Bug 952488 - Add locale managers UI

- pontoon/base/migrations/0044_locale_translators.py
Two changes:
1. Permission shouldn't be granted to users who didn't have old (can_localize) permissions. They could have approved translations, because someone else approved them for them.
2. Also, approved_translations__gte=1 is implicit with translation__approved=True.
@jotes r?
> Only grant new permissions to users with old can_localize permission

- docs/admin/deployment.rst
- pontoon/settings/base.py
- pontoon/sync/management/commands/sync_projects.py
- pontoon/sync/tasks.py
- pontoon/sync/tests/test_sync_projects.py
- pontoon/sync/tests/test_tasks.py
There's two commits here:
- Adds a `--force` parameter to `sync_projects` that bypasses the logic that skips repos with no changes. I needed this while attempting to profile the sync process so that I didn't have to keep making changes every time I ran sync.
- Adds the `CELERYD_MAX_TASKS_PER_CHILD` setting, which sets the number of tasks a celery worker can handle before being replaced by a new worker. The hope is that this will help rein in the amount of memory celery workers use (see the explanation and workaround sections from [this blog post](http://chase-seibert.github.io/blog/2013/08/03/diagnosing-memory-leaks-python.html) for my inspiration).
I'm still going to see if I can reduce our memory consumption but this may help get rid of the warnings, and we can configure the setting to …
> Cycle celery workers and add --force option to sync_projects.

- pontoon/base/models.py
- pontoon/base/static/css/translate.css
- pontoon/base/static/js/main.js
- pontoon/base/static/js/pontoon.js
- pontoon/base/static/js/translate.js
- pontoon/base/templates/locale_selector.html
- pontoon/base/templates/project_selector.html
- pontoon/base/templates/translate.html
- pontoon/base/tests/test_views.py
- pontoon/base/views.py
This is bringing *much* faster loading time of the translate view when loaded using the Go button in the main menu. Instead of reloading the entire page (and requesting a ton of project details), it uses AJAX to only load relevant content (mainly strings) and update other things like Project Info, Admin - Current project link etc.
It also manipulates history by changing URLs and making back/forward work smoothly. There are some other minor improvements, like using actual links (anchor tags) in the profile menu, instead of JS.
I need to fix a few bugs around pages with inplace support before this is ready for a review.
EDIT: We should consider preloading some data (especially project details) and making all pages AJAX-based.
> AJAX-based Go button

- pontoon/base/static/css/translate.css
- pontoon/base/static/js/translate.js
Project loader now overlaps everything *but* the header (where all the
menus are). It also uses lighter background colors, so menus are visible
if openned while projects are loading.
> Make translate view header always visible

- pontoon/sync/utils.py
Instead of returning the first directory with the name that matches
the locale code, we collect all directories with matching names and
return the first one that contains resources. If none of them contains
resources, we return the first one available (needed for asymmetric
formats).
@jotes r? @Osmose r?
> More accurate locale_directory_path detection

- pontoon/base/static/js/translate.js
We don't save translations from anonymous users. So the notification shouldn't ready "Translation saved/updated".
> Warn anonymous users their translations aren't saved

- pontoon/base/static/js/translate.js
It includes variable identifier, which matters to some locales. Showing
both variants, singular and plural might confuse some users to translate
both variants.
> Fix Bug 1224419: Show plural string to locales with a single plural form

- pontoon/base/migrations/0046_add_force_suggestions.py
- pontoon/base/models.py
- pontoon/base/static/css/translate.css
- pontoon/base/static/css/user.css
- pontoon/base/static/js/main.js
- pontoon/base/static/js/pontoon.js
- pontoon/base/static/js/translate.js
- pontoon/base/templates/translate.html
- pontoon/base/templates/user.html
- pontoon/base/templates/widgets/checkbox.html
- pontoon/base/urls.py
- pontoon/base/views.py
Uses different title (Suggest) and color (blue) for Save button if
user make suggestions (either because they don't have translator
privileges or because they explicitly force to make suggestions in
preferences).
Other minor fixes and improvements I *had* to make:
* Remove obsolete user profile fields
* Fix notification loader position on translate page
* Make entire plural tab area clickable
* Fix unsaved changes warning when adding suggestions
* Check for unsaved changed when clicking Go button
* Fix Safari error with onpopstate event, triggered on first page load
> Fix bug 1200184: Allow translators to make suggestions

- pontoon/base/static/js/translate.js
A small fix, does two things actually:
1) Updates has suggestions status (need for filtering) also when non-active translation gets deteled.
2) Moves update has suggestions status to a dedicated function.
> Update has suggestions status if non-active translation deleted

- docs/admin/deployment.rst
- pontoon/base/templatetags/helpers.py
- pontoon/base/tests/test_helpers.py
- pontoon/settings/base.py
- pontoon/sync/management/commands/clear_old_sync_logs.py
- pontoon/sync/management/commands/sync_projects.py
- pontoon/sync/migrations/0001_initial.py
- pontoon/sync/migrations/0002_auto_20151117_0029.py
- pontoon/sync/models.py
- pontoon/sync/static/css/sync_logs.css
- pontoon/sync/tasks.py
- pontoon/sync/templates/sync/log_details.html
- pontoon/sync/templates/sync/log_list.html
- pontoon/sync/tests/__init__.py
- pontoon/sync/tests/test_models.py
- pontoon/sync/tests/test_sync_projects.py
- pontoon/sync/tests/test_tasks.py
- pontoon/sync/urls.py
- pontoon/sync/views.py
- pontoon/urls.py
This is sort've in-progress but I think is sufficiently useful to merge now (plus I need to focus on different things for a while and thus won't really be able to improve this soon).
This adds some models for storing timing data about sync jobs in the database, and some views to view the data. The pages are public but not linked anywhere on the site, so we can use them and play around with them without bugging users. The data itself isn't sensitive so having the page public isn't an issue.
There are some known bugs that I haven't handled that I don't think are blockers:
- The big one, projects that are skipped due to a lack of changes have no timing data, which I think causes the entire run to not have an end time. This should be fixed with a followup PR soon, but I may not get to it for …
> Bug 1208171: Log sync timing to the database and display it.

- pontoon/sync/core.py
This will help with monitoring sync a lot.
> Log meaningful task name on RuntimeError

- pontoon/administration/vcs.py
I noticed several days ago that some projects sync constantly, even if
there are no changes neither on Pontoon nor on VCS side of things.
This is causing big problems because more and more projects are now
syncing perpetually, which makes sync in general and adding new locales
slow.
What went worng?
ChangedEntityLocales get rolled back on CommitToRepositoryException:
https://github.com/mozilla/pontoon/blob/master/pontoon/sync/tasks.py#L110
And CommitToRepositoryException is thrown if there's nothing to commit:
https://github.com/mozilla/pontoon/blob/master/pontoon/administration/vcs.py#L135
So we have a lot of ChangedEntityLocales instances that are already in
repository, and when we try to commit them, we remove them from the DB,
but than CommitToRepositoryException is …
> Fix perpetual sync

- pontoon/base/models.py
When saving or deleting translations, only mark entity as changed if
approved translation was added or deleted.
> Only mark approved strings as changed

- pontoon/administration/forms.py
- pontoon/administration/static/css/admin_project.css
- pontoon/administration/templates/admin_project.html
- pontoon/base/migrations/0047_repository_permalink_prefix.py
- pontoon/base/models.py
- pontoon/base/static/css/translate.css
- pontoon/base/static/js/pontoon.js
- pontoon/base/static/js/translate.js
- pontoon/base/templates/translate.html
- pontoon/base/utils.py
- pontoon/base/views.py
- pontoon/sync/changeset.py
- pontoon/sync/utils.py
- pontoon/sync/vcs_models.py
This is first part of Bug 1219212: re-enabling resource download. When translating a resource, you can now download it from the profile menu, by clicking on the "Download FORMAT" link, where FORMAT is PO or DTD etc.
Since we don't have storage, this is how it works:
1) Pull source repository.
2) Get source (en-US) file - works for all formats.
3) Update file from DB.
4) Pass it to the user for download.
I left the code in the view, because I found myself in the import loop when moving it to utils.py. When we agree where should we put it and if the basic direction of this PR is correct, I should write some tests for get_download_content().
I tried to reuse as much sync code as possible. I also had to modify it a bit, but nothing serious. Given that all tests pass, I think we should be …
> Bug 1219212: Add ability to download translated resources

- pontoon/base/forms.py
- pontoon/base/static/css/translate.css
- pontoon/base/static/js/translate.js
- pontoon/base/templates/translate.html
- pontoon/base/urls.py
- pontoon/base/utils.py
- pontoon/base/views.py
- pontoon/sync/changeset.py
This is based on #280, so look at 6853f0c only.
It adds the ability to upload translations for the currently translated resource (disabled on search and for non-translators).
To update translations in the DB, I reused the sync code. There shouldn't be any problems it upload is performed during sync, because it's same as if translations were manually submitted.
TODO (can wait until next release):
- I can't wait to get my hands dirty with drag & drop upload and fancy progress bars.
- Enable upload to anyone and add suggestions if user not translator or forces suggestions.
> Bug 1219212: Add ability to UPLOAD translated resources

- Procfile
- pontoon/settings/base.py
@mathjazz r?
The big thing here, I think, is `CELERY_SEND_EVENTS` and the process arguments, as those queues appear to be generating 1.2 messages per second according to the CloudAMQP board vs 0.2 messages per second for our actual task queues.
> Fix bug 1229067: Implement suggested celery settings for CloudAMQP.

- pontoon/sync/core.py
- pontoon/sync/exceptions.py
- pontoon/sync/formats/base.py
- pontoon/sync/formats/lang.py
- pontoon/sync/formats/po.py
- pontoon/sync/tests/formats/test_lang.py
- pontoon/sync/tests/test_core.py
- pontoon/sync/tests/test_vcs_models.py
- pontoon/sync/vcs_models.py
If we don't have both a VCS entity and a DB entity, we can't do anything useful to update the translations for the entity, so we just skip them.
This fixes an issue we were running into when testing the new MasterFirefoxOS translation files. Since there are source files that may not exist in certain locales, we get `None` back for `vcs_translation` and hit an error, when really we should be skipping those.
@mathjazz r?
> Skip updating translations for missing entities.

- pontoon/base/middleware.py
- pontoon/settings/base.py
If we still want notifications for excessive 404s we can configure a search in Papertrail.
@mathjazz r?
> Ignore non-failure exceptions like Http404 and Permission Denied.

- pontoon/base/tests/test_utils.py
- pontoon/base/utils.py
- pontoon/sync/migrations/0003_auto_20151204_2343.py
- pontoon/sync/models.py
- pontoon/sync/tasks.py
- pontoon/sync/templates/sync/log_details.html
- pontoon/sync/templatetags/helpers.py
- pontoon/sync/tests/test_models.py
- pontoon/sync/tests/test_tasks.py
Also logs end time for repo syncs that fail due to no locales being found within a repo.
This should fix most of the data issues with the sync logs. I'll hopefully come up with a separate PR implementing pagination.
@mathjazz r?
> Properly log project syncs that skip sync completely.

- pontoon/base/migrations/0048_translationmemoryentry.py
- pontoon/base/migrations/0049_create_translation_memory_entries.py
- pontoon/base/models.py
- pontoon/base/tests/__init__.py
- pontoon/base/tests/test_models.py
- pontoon/base/tests/test_views.py
- pontoon/base/views.py
- pontoon/sync/changeset.py
- pylama.ini
- requirements.txt
Hi @mathjazz @Osmose,
I've had very hard time with porting translation memory to elasticsearch. However, i can't say that anything was wrong with ES. I just don't know ES stack enough to make it work in reasonable time now. However, i'll definetely try again in future.
After first breakdown I decided to try with postgresql and in the end, it was a lot easier.
I've added new dependency which adds support pg_trgm. However, official version on Pypi can't support migrations in django 1.8.4. I've created PR to the upstream and i'm waiting for reaction of the owner of the package.
I would really like to hear your initial comments and suggestions.
> Initial version of translation memory.

- pontoon/base/utils.py
- pontoon/base/views.py
If project has mutiple resources, but less than 10, download all
files at once in a ZIP. Else, download separate files.
This wasn't tracked in bugzilla, it's a quick response to:
https://groups.google.com/forum/#!msg/mozilla.dev.l10n/aiJm4EH4s8w/V14iu-IUBwAJ
@jotes r?
> Download projects with few resources as ZIP

- pontoon/base/templatetags/helpers.py
Instead of listing all (100+) locales, simply put it as "all locales".
@jotes r?
> Simplify locales list for superusers

- pontoon/sync/formats/silme.py
- pontoon/sync/tests/formats/test_silme.py
Some DTD files require quotes to be escaped. This is my attempt to do so.
@jotes or @Osmose r?
The curly quotes (‘ and “) don't get escaped for some reason. Any idea why? I'll add tests.
> Fix bug 1193860: escape quotes in some DTD files

- pontoon/base/static/css/translate.css
- pontoon/base/static/js/translate.js
- pontoon/base/views.py
(Diff looks big because block alignment changed several times)
Do not automatically approve next translation when deleting the active
one. Not just when in suggest mode like the bug description suggests,
but in general.
Automatic approval is dangerous and from now on we require localizers
to explicitly approve one of the remaining suggestions. To avoid any
surprises.
@jotes r?
> Fix bug 1235893: Don't approve suggestions on delete

- pontoon/base/models.py
- pontoon/base/static/css/search.css
- pontoon/base/static/js/translate.js
- pontoon/base/templates/locale.html
- pontoon/base/templates/locale_selector.html
- pontoon/base/templates/project_selector.html
- pontoon/base/templates/translate.html
- pontoon/base/tests/test_models.py
- pontoon/base/tests/test_views.py
- pontoon/base/urls.py
- pontoon/base/views.py
It turns out #329 caused much longer translate page loads on stage for locales with many projects enabled. So instead of loading all projects, parts and stats data for locale, we now only load parts and stats for current project-locale combination.
That means changing selection in locale and project menu triggers AJAX request to get data for the part menu if not already available.
I've also made a step forward WRT code reuse.
@jotes r?
> Minimal main menu request

- pontoon/base/static/css/style.css
- pontoon/base/static/css/translate.css
- pontoon/base/static/js/main.js
- pontoon/base/static/js/translate.js
- pontoon/base/templates/translate.html
Loads all helper requests (history + machinery + locales) at once and displays a number of results in a tab.
@jotes r?
> Fix bug 1216516: Load all helper requests at once

- pontoon/base/models.py
- pontoon/base/tests/test_models.py
- pontoon/base/views.py
I realized `Project.objects.select_related('latest_translation')` is never used, because `p.get_latest_activity(locale)` actually ends up accessing `latest_translation` property of the `ProjectLocale` object (not `Project`).
So this PR collects the appropriate data and sends it to the template. It reduces DB requests by 40% on the locale page.
@Osmose @jotes Before I do something similar on the project page, I wonder if there's a more elegant way of doing this.
For more context, I noticed this while preparing for https://bugzilla.mozilla.org/show_bug.cgi?id=1214392.
> Optimize latest activity DB requests

- pontoon/settings/base.py
- requirements.txt
Hi, @mathjazz? Could you review this patch? This change definetely would require additional testing on your local environment before deployment on production.
> Removed support for django-sha2

- pontoon/base/models.py
- pontoon/base/templates/project_selector.html
- pontoon/sync/core.py
We have some issues with denormalized stats not being always in sync, see bug 1250303.
This fixes that and:
* Adds a little optimization to `update_resources()`.
* Displays projects in locale dashboard even if not imported yet.
@jotes r?
> Fix bug 1250303: Properly aggregate total strings

- pontoon/base/static/js/main.js
- pontoon/base/static/js/pontoon.js
- pontoon/base/static/js/translate.js
- pontoon/base/templates/translate.html
- pontoon/settings/base.py
* Remove 1 second setTimeout on .properties detection
* Preload iframe on homepage
* Do not wait for iframe to load before getting entities
* Optimize intro page (fix bug 1179017)
* Focus webpage when loaded
* Load translate.js code instantly, without waiting for page to load
@jotes r?
> Fix bug 1218801: Speedup homepage

- pontoon/base/static/js/translate.js
When approved button is clicked, we should only update the approved
icon once potential warning has been discarded.
@jotes r?
> Do not mark translation approved prematurely

- pontoon/base/models.py
- pontoon/base/static/js/translate.js
- pontoon/base/templates/part_selector.html
- pontoon/base/tests/test_models.py
- pontoon/base/tests/test_views.py
- pontoon/base/views.py
By renaming `resource__path` attribute (holding resource paths and subpage
names) to `title` and adding a new `resource__path` attribute holding
resource paths only.
@jotes r?
> Fix updating parts menu for subpages

- pontoon/base/models.py
- pontoon/sync/changeset.py
- pontoon/sync/core.py
- pontoon/sync/tasks.py
- pontoon/sync/tests/test_changeset.py
If translation is removed from the source file, we mark it as obsolete
in Pontoon. Now we also remove them from translated files in asymmetric
formats (they are removed on merge in symmetric ones), even if no other
changes have been made in those files (like translation added).
We do so by bringing a list of obsolete entities from the `sync_project`
task to `sync_project_repo` tasks and then marking `changed_resources` and
`locales_to_commit` properly so these files get updated and commited.
> Fix bug 1199489: delete obsolete translations

- pontoon/base/models.py
- pontoon/base/tests/test_models.py
Entity is untranslated if it doesn't have a single (approved, fuzzy or
suggested) translation. Previously, entity with expected_count of 1 and
2 suggestions was also treated as untranslated.
@jotes r?
> Fix untranslated filter

- pontoon/base/static/js/translate.js
- pontoon/base/templates/locale_selector.html
- pontoon/base/templates/part_selector.html
- pontoon/base/templates/project_selector.html
- pontoon/base/templates/translate.html
2. Add "All Projects" link to the Project menu, linking to /projects.
3. Remove Localization teams and Project Overview links from the Profile menu.
4. Add "Current Team" link to the Team menu, linking to /{team}.
5. Add "Current Project" link to the Project menu, linking to /{project}.
6. Add "Current Team - Project link to the Resources menu, linking to /{team}/{project}.
The label "Current Team - Project" looks strange, may be something like Project Overview?
> Bug 1228770: Translation Page Links

- pontoon/base/models.py
- pontoon/base/static/css/style.css
- pontoon/base/static/css/translate.css
- pontoon/base/static/js/main.js
- pontoon/base/static/js/translate.js
- pontoon/base/templates/translate.html
- pontoon/base/templates/widgets/progress_chart.html
- pontoon/base/tests/test_models.py
- pontoon/base/tests/test_views.py
- pontoon/base/views.py
This is a next iteration over #374, nicely crafted by @jotes.
**Fixed Bugs**
**New Features**
> Bug 1243086 direct links

- README.md
- contribute.json
- docs/admin/deployment.rst
Hi @mathjazz,
I'm not sure if you had a time to the latest mail from readthedocs but it looks like we have all links into .io just because of the security concerns.
> Fixed urls for readthedocs.

- pontoon/base/static/js/main.js
- pontoon/base/static/js/translate.js
We close menus on clicks outside. In theory. But in practice, we use
stopPropagation in many event handlers, preventing the event from
bubbling to the top of the DOM, where we catch clicks outside.
Yes, stopping event propagation can be dangerous:
https://css-tricks.com/dangers-stopping-event-propagation/
This patch removes all event.stopPropagation() calls, which prevented
menus from closing. In most cases simply removing the call was enough.
I only had to slightly refactor event handlers for helpers.
In addtion to that, I also replaced " with ' in modified event handler
selectors.
@jotes r?
> Always close menu on click outside the menu

- pontoon/sync/tasks.py
- pontoon/sync/vcs/models.py
I noticed the following sync messages in the logs:
"Synced translations for project firefox-aurora in locales ."
It occurs if repo changes, but none of the locale files is affected, e.g. if a readme file changes in the repo.
From now on, as soon as we detect there aren't any changes in translation files, we skip the repo sync.
@jotes r?
> Bug 1214411: Skip repo sync if locales have nothing to sync

- pontoon/settings/base.py
hi @mathjazz, I noticed that we don't use gzip for the django views.
More info at:
https://developers.google.com/speed/pagespeed/insights/?url=pontoon.mozilla.org
> Add gzip compression to django views.

- pontoon/sync/core.py
@jotes r?
This fixes the following scenario:
We merge new PO project strings, which means all files for all locales (`sl`, `fr`, `it`, `de`) are updated in the repo. We also have one new translation pending for file `file/path.po` in locale `fr` in Pontoon.
With the old code, `vcs_project.changed_files[file/path.po]` becomes `set([fr])` instead of `[sl, fr, it, de]`.
> Bug 1214411: Properly join dicts of VCS and DB changes

- pontoon/sync/core.py
- pontoon/sync/models.py
- pontoon/sync/tasks.py
If the previous project or repository sync hasn't completed yet, we
prevent next project or repository sync by raising RuntimeError.
From now on we also mark project as skipped in the sync log and
repository as finished (synced). We should probably add a special
status for this use case.
Until now, project and repository sync job that were prevented due to
RuntimeError always remained in-progress in the sync log.
Also, end_repo_sync() has been moved to RepositorySyncLog.end().
@jotes r?
> Log RuntimeErrors in Sync log

- pontoon/base/views.py
There are valid scenarios when `content` can be an empty string.  For instance,
this may happen when there hasn't been any translations made to the file that's
supposed to be downloaded.
@mathjazz r?
> Only raise Http404 when content is None

- pontoon/base/static/css/user.css
I see first part of this bug only in Webkit browsers. Commit fixes it.
Possible fix of second one:
1)consider such strings as untranslated, left span with class "translation-string" emply
2)add class for parent "half_translated", and assign "source-string" width 49% if parent has class "half_translated"
> Bug 1278826 - Text overflow in two places

- pontoon/base/models.py
- pontoon/base/static/css/translate.css
- pontoon/base/static/js/main.js
- pontoon/base/static/js/translate.js
- pontoon/base/templates/translate.html
- pontoon/base/views.py
@jotes r?
Authors are listed in the filter menu. Max height is set to fit 3 authors, then you need to scroll. If there aren't any translations submitted by Pontoon users, we don't show the filter. We update the authors list on translate page load, translation submission/deletion, batch operations and file upload.
I haven't found a much better UX solution for the authors selector. Filter menu is getting huge. Also, we'll be adding date/time (bug 1225305) and errors/checks (bug 1237667) filters, which will make it even bigger.
We should probably refactor filter UI as part of 1243115. We might also be able to merge it with the progress bar menu.
> Fix bug 1225302: Add filter by translation author

- pontoon/base/models.py
Hi @mathjazz,
Previous commit at master introduced a bug - registration of new users is impossible.
Django browser id throws following exception:
```
[17/Jun/2016 00:42:24] "GET /browserid/csrf/ HTTP/1.1" 200 32
[ERROR:django.request] 2016-06-17 00:42:26,464 Internal Server Error: /browserid/login/
File "/home/jot/.virtualenvs/pontoon/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
File "/home/jot/.virtualenvs/pontoon/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
File "/home/jot/.virtualenvs/pontoon/local/lib/python2.7/site-packages/django …
```
> Fixed User.objects.create_user

- pontoon/base/migrations/0002_initial_data.py
Hi @mathjazz, could you look at this? I remember that we talked @irc about this change quite a while ago.
I decided to modify a base migration because this won't change anything on your installation or production, but will affect only new contributors/fresh databases.
> Switched pontoon-intro into official mozilla repo.

- pontoon/base/static/js/translate.js
When modifying translation textarea programatically, move mouse cursor
to the beginning, because this is where users start reading from and
making changes.
@jotes r?
> Move move cursor to the beginning of textarea

- pontoon/sync/vcs/repositories.py
We shouldn't be requiring Git repository branch name to be called master. We should use the default branch. We just got a request to enable a project that uses "develop" branch as default and wants it to be used by Pontoon.
Later on we could add a new Repository model property to specify a branch name in addition to current type and URL.
@jotes r?
> Use default Git branch instead of master

- pontoon/base/static/img/logo.svg
This vector version is based on the logo.png file in the same folder. The file is derived from hand-crafted SVG source available pre request (because of its incompatibility with image editing programs).
> Vector version of Pontoon's logo

- pontoon/base/static/css/pontoon.css
- pontoon/base/static/css/translate.css
- pontoon/base/static/js/pontoon.js
- pontoon/base/static/js/translate.js
- pontoon/base/templates/translate.html
Translating on the page itself is insufficient for various reasons:
* Original string is not always fully seen (e.g. if containing markup)
* Additional string details like comments and context are not visible
* Suggestions from history, machinery and other locales are not available
* Only the first plural form can be translated
* Features like Copy from original or Move to next string are missing
In addition to that, when translating in the page itself using the
contentEditable attribute, we were sometimes unable to fully control the
[markup that was submitted](https://github.com/mozilla/donate.mozilla.org/issues/1596).
From now on, sidebar is always open and strings can only be translated
in there, while it's still possible to select them on the page. The
sidebar switch icon (hamburger) …
> Disable in-place editing

- pontoon/base/static/js/translate.js
- pontoon/base/views.py
If we unapprove a translation, that does not change the set of translation authors, so no need to update it.
@jotes r?
> No need to update authors on unapprove

- pontoon/base/static/css/style.css
- pontoon/base/static/js/translate.js
Mark Go button as active if main menu doesn't fully resemble locale, project, part combination currently being translated.
This is a minor improvement, but often requested by our localizers.
@jotes r?
> Resemble state in Go button

- pontoon/sync/core.py
- pontoon/sync/tasks.py
- pontoon/sync/tests/test_tasks.py
- pontoon/sync/vcs/models.py
If only source files change in repo (e.g. when new strings are merged), we skip syncing translations. Which is the right thing to do, but as part of this we also skip updating stats. Which we shouldn't.
@jotes r?
> Fix bug 1292890: Sync stats if only resources changed in monolingual files

- docs/dev/install.rst
Without installing contrib explicitly, I run into this stacktrace (Linux Mint 18):
> Applying base.0048_translationmemoryentry...Traceback (most recent call last):
>   File "manage.py", line 20, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/michal/repos/pontoon/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
>     utility.execute()
>   File "/home/michal/repos/pontoon/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/home/michal/repos/pontoon/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
>     self.execute(*args, **cmd_options)
> …
> Add postgresql-contrib to apted packages

- pontoon/sync/core.py
- pontoon/sync/tasks.py
- pontoon/sync/tests/test_core.py
This is even simpler than it looks: if we skip locale sync, but the resources have been changed, we need to update translated resources anyways to update the total_strings count.
Also remove unused argument from the `update_translated_resources()` function and update tests.
@jotes r?
> Update translated resources when skipping locales

- pontoon/base/models.py
- pontoon/base/static/js/translate.js
This fixes the missing filter to also include partially translated pluralized strings.
@jotes r?
> Fix bug 1278826: filter partially translated pluralized strings as missing

- pontoon/base/static/js/translate.js
While we disable the save button while request is in progress, users
can still submit multiple translation update requests with their
keyboards. That can lead to stats inconsistency due to DB latency
in production. With this patch, it is now actively prevented.
@jotes r?
> Prevent simultaneous save translation requests

- pontoon/base/models.py
- pontoon/base/static/js/translate.js
- pontoon/base/templates/widgets/contributors.html
- pontoon/base/templates/widgets/latest_activity.html
- pontoon/base/urls.py
- pontoon/base/views.py
We use email addresses as user identifiers in contributor URLs, which is a bad idea, at least due to poor privacy respect and spam protection, making e.g the [top contributors](https://pontoon.mozilla.org/contributors/) page very spam-bot friendly.
This patch replaces email addresses with usernames, while keeping the old email-based URLs alive (to avoid breaking links and to help with manual URL entering).
@jotes r?
> Use username instead of email as user identifier in URL

- docs/dev/sync.rst
- docs/index.rst
- pontoon/base/models.py
- pontoon/base/tests/test_models.py
- pontoon/sync/changeset.py
- pontoon/sync/core.py
- pontoon/sync/models.py
- pontoon/sync/tasks.py
- pontoon/sync/tests/test_changeset.py
- pontoon/sync/tests/test_core.py
- pontoon/sync/tests/test_models.py
- pontoon/sync/tests/test_tasks.py
- pontoon/sync/tests/test_vcs_models.py
- pontoon/sync/vcs/models.py
- pontoon/sync/vcs/repositories.py
This optimization affects all project repository types, fixes some bugs and hopefully makes code more readable. It's particularly noticeable on projects that use multiple repositories and when adding new locales or entire projects.
**Optimizations**
* When syncing resources, only check out source repositories (currently we check out all repositories twice: during resources and during translation sync). 3f939b2
* If no changes detected in source repository, skip syncing resources (currently we sync resources even if only translations need to be synced). 3f939b2
* Acknowledge changed files when syncing resources (currently if resources need to be synced, we sync all resources). 871cb88
* Optimize changed files detection by 90% using @cached_property. 3f83b32
* Do not detect all following …
> Bug 1298610: Optimize syncing new locales

- pontoon/sync/models.py
- pontoon/sync/tests/test_models.py
Loading /sync page is slow. This should speed it by ~80%.
The main trick is in not calling `SyncLog.finished` property.
@jotes r?
> Speed up sync log listing

- pontoon/base/templates/translate.html
@jotes r?
We forgot to update this sign-in link. It's simpler to directly link to Firefox Account and that's sufficient, given that we'll drop Persona support in a month from now.
> Fix Sign in link in translate view

- pontoon/base/adapter.py
If connecting existing Persona with a new Firefox Account that was already logged in previously, users get stuck on the migration page. This patch fixes the problem.
@jotes r?
Thanks for reporting, @goofy-bz!
> Fix Firefox Accounts migration bug spotted by @goofy-bz

- docs/dev/install.rst
- pontoon/settings/dev.py
1)We must modify django-debug-toolbar or add ajax.googleapis.com in CSP, because requirements-dev.txt contains django-debug-toolbar which needs access to ajax.googleapis.com
2)we need "data:" for base64 images. For example:
3)About Virtualenv
> Bug 1310510 - add virtualenv and fix CSP

- pontoon/administration/static/js/admin_project.js
- pontoon/administration/templates/admin_project.html
A patch to fix bug 1308983 (commit be16ccd) introduced a form element,
which prevented the Admin form to be submitted due to too general
form selector in JS.
r=me
> Fix admin form submission regression from be16ccd

- requirements.txt
The bug our fork fixes is now fixed upstream, let's move back to using the official branch.
@jotes r? Is there a reason why we were using a pretty old version - 0.25.2? Maybe because we started working on FxA support before 0.26.0 was release?
BTW, shall we also remove all social accounts with provider Persona?
> Switch back to latest upstream django-allauth

- pontoon/settings/base.py
It's causing JS error in local development randomly:
`TypeError: item.unmark is not a function  translate.js:3306:7`
@jotes r?
> Load jquery.mark.js lib before the script that uses it

- pontoon/base/utils.py
@jotes r?
There's no need to repalce space with `&nbsp;`. In fact, it's harmful:
https://bugzilla.mozilla.org/show_bug.cgi?id=1317243
> Bug 1317243: Do not replace space with &nbsp;

- pontoon/settings/base.py
@mathjazz I think this can be helpful on the production or even on the staging.
> Fix bug 1316171: JS_TRUSTED_ORIGINS can be loaded from ENV.

- pontoon/base/models.py
- pontoon/base/tests/test_models.py
@jotes r?
When All Resources are selected, we load entities by order within the
file, which means all entities that apear first in any of the project
files are loaded, followed by all "second" entities, etc.
From now on, we sort file path alphabetically like in the parts menu,
and then load entities from the first file, then second, etc.
> Order entities by file path, and then order within the path

- pontoon/base/models.py
- pontoon/sync/core.py
- pontoon/sync/models.py
- pontoon/sync/tasks.py
- pontoon/sync/tests/test_core.py
- pontoon/sync/tests/test_models.py
- pontoon/sync/tests/test_tasks.py
- pontoon/sync/vcs/models.py
- pontoon/sync/vcs/repositories.py
@jotes r?
This allows us to pull/push translations from/to different repositories per project. Currently we only support multiple repositories if one is used for source strings and the other for translations.
TODO:
> Fix bug 1311295: support multiple locale repositories

- pontoon/base/utils.py
Previously, if project had 4 .properties files and 1 .lang file, we
tried to download all files for all locales, even if the .lang file
was only enabled for a handful of them. Since the .lang file didn't
exist, download failed.
r=me
> Only download files we have translated resources for

- pontoon/base/middleware.py
@jotes r?
I noticed we weren't catching all IPs during a ddos attempt.
> Strip whitespace to catch all IPs

- docs/dev/install.rst
- pontoon/allauth_urls.py
- pontoon/base/templates/django/base.html
- pontoon/base/templates/landing.html
- pontoon/base/templates/translate.html
- pontoon/settings/base.py
@mathjazz I couldn't login via Fxa on my local/work machine. That's I decided to separate django login from the heroku demo.
> Separated django login from heroku_demo.

- pontoon/base/static/js/main.js
- pontoon/base/static/js/translate.js
@jotes r?
I implemented this with JS, because I think one day we should rewrite original string placeables (to avoid false positives) and move the code to frontend. Should be faster.
Having this code in JS should also help us with implementing diff view for suggestions:
https://bugzilla.mozilla.org/show_bug.cgi?id=1329003
> Fix bug 1215874: Markup &nbsp; and other special spaces

- pontoon/urls.py
While digging up how pontoon implements contribute.json, I found a copy-n-paste bug.
Easy enough?
> fix comment for contribute.json in urls.py

- pontoon/base/models.py
- pontoon/base/templates/translate.html
If the user doesn't have translator permission for the current project, she should not be able to turn Make suggestions toggle on/off from the translate view.
@jotes r?
> Fix bug 1331710: Only privileged can flip suggestions

- pontoon/base/static/css/style.css
- pontoon/base/static/css/translate.css
- pontoon/base/static/js/lib/diff.js
- pontoon/base/static/js/main.js
- pontoon/base/static/js/translate.js
@mathjazz Don't you think that comparing previous translations with next will look more logically?
Before:
After:
> Bug 1329003: improve diff experience

- pontoon/base/static/js/main.js
- pontoon/base/templates/django/base.html
- pontoon/base/templates/landing.html
- pontoon/base/templates/registration/login.html
- pontoon/base/templates/translate.html
* Rename label from email to username
* Load missing jQuery library
* Properly compose sign in URL
* Fix duplicate HTML IDs
* Use standalone login in translate view
> Standalone login fixes (was #528)

- pontoon/base/static/css/manage_permissions.css
- pontoon/base/static/js/manage_permissions.js
- pontoon/base/templates/locale_permissions.html
Steps to reproduce without the patch:
1. Go to /{locale}/permissions.
2. Add one project via project selector at the bottom.
3. Click on project selector again and start searching.
4. Clear search criteria.
5. Empty line appears in the project menu where selected project was displayed initially.
@jotes r?
> Prevent projects from disappearing on search in custom permissions selector

- pontoon/sync/vcs/models.py
The old code checked if changed paths in repository start with paths to locale directories without the trailing slash. If the changed path was `kab/mozorg/internet-health/privacy-security.lang`, it would match it with the Georgian locale directory `ka` and break.
The new code adds trailing slashes to locale directory paths, so it checks if the path starts with `ka/` (no match) and then continues all the way to `kab/` (match).
@jotes r?
@jotes I didn't add any tests yet, mostly because #405 is still open. Are you planning on continuing with that or is it too old to be useful now?
> Fix bug 1305233: Properly match changes in repository with enabled locales

- pontoon/base/utils.py
The XML placeables must be marked before variable placeables to avoid marking variables, but leaving out tags.
@jotes r?
> Fix bug 1334926: Properly mark variables withing XML attributes

- pontoon/base/static/js/translate.js
If missing string gets translated, show it as translated when selected.
@jotes r?
> Fix bug 1343631: Show translated string as translated

- pontoon/base/views.py
- pontoon/localizations/views.py
As part of the `pontoon.base` app split, we forgot to move the `from __future__ import division` to `pontoon.localizations` app.
This explains the difference in how division works without the import:
https://mail.python.org/pipermail/tutor/2008-March/060886.html
@jotes r?
> Fix chart calculations

- pontoon/base/admin.py
- pontoon/base/static/css/table.css
- pontoon/base/templates/widgets/heading_info.html
- pontoon/base/templates/widgets/latest_activity.html
- pontoon/projects/templates/projects/widgets/project_list.html
Red color implies errors, so we're replacing with "Pontoon green" in the latest activity column and removing the underline. "No activity yet" text has been replaced with &middot; to make it easier to distinguish from other entries. Also in the deadline column.
@MikkCZ @mastizada r?
Check it out on stage:
https://mozilla-pontoon-staging.herokuapp.com/projects/
> No more red in latest activity column

- pontoon/administration/static/css/admin_project.css
- pontoon/administration/static/js/admin_project.js
- pontoon/sync/vcs/repositories.py
Instead of removing the entire repository folder and running `hg clone` on each sync, we try to do something similar as `git reset --hard`:
* discard uncommitted changes,
* delete untracked files,
* discard local commits.
We need two HG extensions to make this work. They are enabled inside each repo's `.hg/hgrc file` on each sync. The code to do that would be more elegant if we could enable the extensions in the system/user `hgrc` file, but I'm not sure where to put it. I tried [several paths](https://www.selenic.com/mercurial/hgrc.5.html), but none them actually enabled the extensions. Mercurial is installed via pip.
We currently clone ~200 HG repositories during each sync cycle. Quick test showed that this patch reduces the average repo `pull()` time from 5 to 2 seconds (except afer …
> Faster HG pull()

- pontoon/teams/views.py
If a project cannot be requested by locales, we hide it from locales that have it enabled.
This patch fixes it.
> Show non-requestable projects on team pages

- pontoon/base/utils.py
- pontoon/base/views.py
- pontoon/localizations/views.py
- pontoon/machinery/views.py
- pontoon/teams/views.py
We currently allow case-insensitive locale codes in URLs, but only on server side (and without any redirects). Which means some of our pages are broken:
https://pontoon.mozilla.org/bn-bd/              
And some are more broken:
https://pontoon.mozilla.org/bn-bd/pontoon-intro/
OTOH, we require project slugs to be case-sensitive.
Let's make all URL parameters case-sensitive, which menas we'll simply 404 for the examples above.
@jotes r?
> Make URLs case-sensitive

- pontoon/base/static/js/translate.js
Fixes the `TypeError: localStorage is null` error when DOM storage is disabled (i.e. dom.storage.enabled is false).
> Fix TypeError when DOM storage is unavailable

- pontoon/base/static/css/style.css
- pontoon/base/static/css/translate.css
- pontoon/base/static/js/main.js
- pontoon/base/static/js/translate.js
- pontoon/base/views.py
- pontoon/contributors/static/css/profile.css
- pontoon/contributors/templates/contributors/includes/timeline.html
Just to make it more robust, we don't hardcode Arabic locale codes anymore.
@jotes r?
> Use script name in CSS selector instead of locale codes

- pontoon/base/static/js/translate.js
@jotes r?
I checked other keyboard shortcuts in Firefox with the `Tab` key and they are all combinations with `Ctrl`.
> Fix bug 1354812: Do not copy from helpers on Ctrl + Tab

- pontoon/base/models.py
- pontoon/base/static/css/translate.css
- pontoon/base/static/js/fluent_interface.js
- pontoon/base/static/js/lib/fluent-syntax.js
- pontoon/base/static/js/translate.js
- pontoon/base/templates/translate.html
- pontoon/base/views.py
- pontoon/settings/base.py
- pontoon/sync/changeset.py
- pontoon/sync/formats/ftl.py
- pontoon/sync/tests/test_vcs_models.py
- requirements.txt
This is the first attempt at implementing UI for the advanced L20n patterns.
**It brings:**
- More robust `FTL` file format parsing and serialization.
- Support for all patterns used in Test Pilot project, which is already enabled:
- Simple strings.
- Multiline strings.
- Attributes.
- Special interface for localizing access keys.
- Special interface for localizing plurals.
- Basic error handling of translations.
**TODO:**
**Not covered by this PR:**
- Selectors (remaining examples in the `demo.ftl` file).
- More advanced error handling, resembling http://l20n.github.io/tinker/.
> Bug 1280686: L20n UI for simple strings, multiline strings and traits

- pontoon/base/static/css/style.css
- pontoon/base/static/js/main.js
Move notifications bar to the bottom of the screen. On top of the page it covers the header and the main menu in the translate view, preventing it from being used while the notification is presented. It will be slightly less visible, but it covers big enough area to attract user's attention.
@jotes r?
> Show notifications at the bottom

- pontoon/base/static/js/fluent_interface.js
- pontoon/base/static/js/translate.js
They open in a separate tab/window, in order to keep consistent with
the Machinery link behaviour. Also, users would usually use the link
to suggest improvements for another language, so they would want to
keep their own translation view open.
@jotes r?
> Fix bug 1351579: Linkify suggestions from other locales

- pontoon/base/models.py
- pontoon/base/templates/widgets/latest_activity.html
- pontoon/base/utils.py
- pontoon/base/views.py
- pontoon/localizations/templates/localizations/widgets/resource_list.html
- pontoon/localizations/views.py
We don't set latest activity on batch editing actions and changes made via file upload.
We also don't show latest activity data for projects with subpages.
This patch fixes all of that.
@jotes r?
> Latest activity

- pontoon/contributors/static/css/profile.css
If the last child is positioned absolutely, the bottom of it can get cut off the viewport. That prevents the next batch of timeline items to load.
@jotes r?
> Fix bug 1362929: Fix contributor timeline loading

- pontoon/base/static/css/translate.css
- pontoon/base/static/js/main.js
- pontoon/base/static/js/translate.js
- pontoon/base/templates/translate.html
* Use string comments in .lang files to determine translation length limit
* If length limited, show character countdown
* If limit exceeded, prevent translation from being submitted
* Strip HTML tags when calculating string length
* Some code cleanups
@jotes r?
This fix is entirely frontend based, as we already mangle with comments in JS to present links and screenshots. We should file a bug to store this data in a more structured fashion on import.
> Fix bug 1349330: Prevent too long translation submissions

- pontoon/base/static/css/style.css
@jotes r?
Show diff doesn't show changes that contain regualr white space, e.g.:
https://pontoon.mozilla.org/fr/engagement/snippets/2017/jun2017.lang/?search=%23&string=165503
Markup is OK, it's a CSS bug.
> Mark whitespace in diffs

- pontoon/base/views.py
Fixes an issue reported by @StoyanDimitrov.
r=me
```
File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.50.0.39/newrelic/hooks/framework_django.py", line 499, in wrapper
return wrapped(*args, **kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
return view_func(request, *args, **kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/django/views/decorators/http.py", line 40, in inner
return func(request, *args, **kwargs)
File "/app/pontoon/base/utils.py", line 334, in wrap
return f(request, *args, **kwargs)
File …
```
> Fix UnboundLocalError on batch delete

- pontoon/machinery/static/css/machinery.css
- pontoon/settings/base.py
Fixes:
* JS Error that prevents Translation Memory suggestions from appearing
* Too general CSS selector that affects the main menu by mistake
r=me
> Fix machinery CSS and JS Error

- pontoon/base/static/js/main.js
@jotes r?
TODO: At some point we should also merge `pontoon.base.utils:mark_placeables()` logic (handling source string placeables) into `Pontoon.markPlaceables()` (handling translation placeables).
> Fix bug 1367005: Highlight more special characters in translations

- docs/dev/install.rst
As Ubuntu 17.04 use Postgresql 9.6, the previous command won't work so I added new and updated command.
> Add command for installation all the prerequisites if user is on Ubuntu 17.04.

- pontoon/base/static/css/translate.css
- pontoon/base/static/js/translate.js
- pontoon/base/templates/translate.html
- pontoon/base/urls.py
- pontoon/base/utils.py
- pontoon/base/views.py
Instead of updating a list of authors and the time range in the filter menu on any event that can change them, we do it when the filter menu is opened.
This has the biggest impact on saving and deleting translations. Together with 242de20c42663d8a0476cb1081deaae4df3b4312, those two tasks should be at least 80% faster.
It also speeds up loading of the translate page and entities.
@jotes r?
> Fix bug 1344658: optimize authors and time range

- pontoon/base/utils.py
[Without this change](https://docs.newrelic.com/docs/agents/python-agent/supported-features/python-tips-tricks#decorators_and_introspection), New Relic groups all functions using @require_AJAX decorator into a single transaction, which makes it impossible to see how each of them performs. Most if not all AJAX views use this decorator (17 at the moment).
> Adjust @require_AJAX decorator for New Relic use

- pontoon/base/static/js/translate.js
Previously, when selecting all entities for mass actions, we loaded PKs
of all entities that match the selected criteria for the string list.
We have to do this, because we use paging and not all entites are loaded
in the string list.
The problem with this approach is that some strings could have changed
state since they were loaded in the string list. For example, if only
missing strings were filtered, and we translated them, Select all would
not return such strings.
Now we concatenate those strings returned from the server with the
selected strings on the client side.
@jotes r?
> Fix bug 1377830: Fix selecting all entities

- pontoon/contributors/templates/contributors/profile.html
Just noticed while writing doc: click on the profile picture takes you on the http version, and they don't redirect you automatically.
> Link to https for Gravatar in profile page

- pontoon/base/static/js/fluent_interface.js
@jotes r?
Instead of using attribute names as element IDs in Fluent UI, prefix them with `ftl-id-` to prevent Pontoon CSS and JS code having impact.
Without this fix, Pontoon can easily look like this (`title` attribute sets the input element ID to `title`, which has a rule in CSS):
> Prefix element IDs in Fluent UI

- pontoon/base/static/js/fluent_interface.js
That's because we need to serialize translations consistently with the python-fluent serializer. Otherwise translations get re-imported.
@jotes r?
(That's one inconsistency between Pontoon FTL serializer [ui2ftl] and python-fluent serializer. The other one is related to comments and is coming in a separate commit.)
> Bug 1382538: Store FTL translations with trailing newline

- pontoon/base/static/js/fluent_interface.js
- pontoon/sync/formats/ftl.py
@jotes r?
b0e65a3 Previously we stored translation with a comment on sync, and without a comment on submit. We no longer store comments as part of the FTL translation in the DB.
5a52470 is less ugly than 55f1f70 and also more powerful - it takes care of whitespaces surrounding placeables for example.
> Bug 1382538 comments

- pontoon/base/static/js/translate.js
Turn keyboard shortcuts for moving between strings from a translation
editor to the entire translate page.
@jotes r?
> Fix bug 1382551: Extend keyboard navigation to entire translate view

- pontoon/sync/vcs/repositories.py
Unify the way we reference the latest revision in Mercurial repos:
1. When determining the repository's latest revision
2. When comparing with the last synced revision to determine what
changed since the last sync.
@Pike r?
> Fix bug 1383482: Replace tip with default

- pontoon/base/views.py
This is to prevent a possible `DoesNotExist` exception in `Locale.parts_stats`. Is there a better way to do this?
> Prevent DoesNotExist exception

- pontoon/sync/formats/ftl.py
We don't store translation comments in the DB, at least for now. The way we strip them from the translation is hideous. This patch fixes this.
All this should become easier when we'll be able to store AST in the DB instead of the serialized string.
> Bug 1382538: Properly remove comments in FTL translations

- pontoon/base/views.py
We should not have any duplicate translations for the same string and
the same locale. However, it's possible that we have them until we have
better DB constraints.
What's even better is that if there are duplicates, more duplicates
can be added. This patch fixes that.
r=jotes
> Prevent duplicate translation submissions

- pontoon/settings/base.py
- requirements.txt
Commonware is only used for monkey-patch of Django's HttpResponse object for secure cookies. Django's `SESSION_COOKIE_SECURE` and `CSRF_COOKIE_SECURE` should give same result.
> Replace commonware secure cookie patch with Django's built-in security

- pontoon/machinery/views.py
This patch fixes 2 issues that popped up in production after #639 was deployed:
1. `UnicodeDecodeError` when non-ASCII characters are used in the string.
2. `TypeError: object of type 'NoneType' has no len()` if the source string is empty.
@mastizada Since you're the author of the original patch, would you be willing to review this?
> MS Terminology fixes

- pontoon/base/static/js/translate.js
This worked for all formats except for FTL, because getSimplePreview()
returns the fallback value for them, which is passed as the second
argument.
For FTL strings we need to generate their presentation using their
source, which is passed as the first argument. Since the same argument
was passed for the base string and the translate string, the diff
was always empty.
@jotes r?
> Fix bug 1384846: Fix diff view for FTL strings

- pontoon/base/static/js/translate.js
@flodolo Do you feel comfortable reviewing this?
I'm working on FTL bugfixes and I thought this one was one of them, too. I fixed it by mistake.
> Fix bug 1382535: Keep translations on delete

- .pyup.yml
We want to have the pyup service regularly check our requirements files for security update. Adding this config file is the first step to setup this process.
> Bug 1384167 - Add a config file for pyup.

- pontoon/base/static/js/fluent_interface.js
- pontoon/base/static/js/translate.js
This patch brings several bugfixes related to working with FTL translations:
* Prevent submitting translations that produce parse errors.
* Prevent submitting translations that miss values and attributes if the exist in the source.
* Do not break the plurals UI if not all plural forms translated.
* Properly display placeables in attributes and main value.
@jotes r? It's not a big patch, but it still might be easier to review this on a commit-by-commit basis.
Note: I'm planning to rewrite most of this code as part of bug 1362072.
> Bug 1382773 and related Fluent UI bugfixes

- README.md
- pontoon/base/templates/django/base.html
- pontoon/base/templates/header.html
- pontoon/base/templates/translate.html
New docs should be in good enough shape to replace the MDN page.
> Link Help to new documentation on GitHub

- pontoon/teams/static/js/info.js
Event handlers for the recently introduced editing team info capability are too general. When saving team permissions, one of them gets fired by mistake, resulting in a CSRF error.
> Fix bug 1387374: CSRF error on permissions change

- pontoon/base/static/css/translate.css
- pontoon/base/static/js/main.js
- pontoon/base/static/js/translate.js
- pontoon/base/templates/translate.html
This PR is good for two reasons:
1. It removes more lines than adds.
2. It removes loading animations in the helper tabs (history, machinery, locales), including the horizontal progress bar (`self.NProgressUnbind()`), which makes Pontoon feel lighter while navigating between strings.
> Remove helper animations

- pontoon/contributors/templates/contributors/contributors.html
@jotes r?
Instead of latest activity, we're showing the first activity.
> Fix bug 1389882: Fix latest activity in Top Contributors

- pontoon/base/views.py
And only call the expensive calculate_stats() if neccessary - when translation changes status.
@jotes r?
> Mark entity as changed if fuzzy gets rejected

- pontoon/base/utils.py
@mathjazz Hi, could you look at this? This patch seems fix the issue with xml validators.
Previously I assumed that Entity.key can't contain any non-ascii characters and that broke tmx for sumo because sync adds \x04 signs here:
https://github.com/jotes/pontoon/blob/19984460dad55ccf65813009b80e0941a0041bcf/pontoon/sync/formats/po.py#L30
> Fix bug 1390149 Slugify parts of tuids in TMX files.

- pontoon/base/static/css/style.css
There's no reason to set fixed width of the `.language` and `.code` elements within the team selector menu. In fact, it makes longer language names break into multiple lines sometimes.
r=me
> Fix team selector width

- pontoon/base/models.py
- pontoon/base/tests/test_models.py
- pontoon/base/tests/test_views.py
Our model has two drawbacks that make it hard (slow) to filter and search strings:
1. Most filters need to identify an *active translation* (approved or latest suggestion) for the string, and there's no easy (fast) way of retrieving active translations from the model.
2. For projects using .po files we store translations for different plural forms as different Translation model instances, which makes it even harder to retrieve active translations: we need to retrieve one for each plural form supported for a locale. To circumvent that we use `with_status_counts` annotations, but that slows things down even further.
This PR solves the issue #2 for non-PO projects. That's currently 26 out of 33 projects enabled in Pontoon. The number also includes our biggest projects in terms of number of …
> Filters optimization for non-PO projects

- pontoon/base/admin.py
- pontoon/base/models.py
- pontoon/sync/core.py
- pontoon/sync/tasks.py
- pontoon/sync/tests/test_core.py
- pontoon/sync/tests/test_tasks.py
- pontoon/sync/vcs/models.py
This is 3 things and it's better to look at them commit by commit:
1. Purely cosmetic. But it helps a little with the following ones.
2. If `sync_projects` is ran with the `--locale` parameter, we only sync the specified locale, but we also pull repositories for all other locales within the project. And rely on that fact in a few places. This anomaly is now gone, which and helps with the final commit.
3. The actual bugfix. More info in commit description.
> Bug 1383252: Reduce the number of hg clone operations

- pontoon/sync/tasks.py
Without this change, updating stats for all locales is still [slow](https://pontoon.mozilla.org/sync/log/32546/), because changed_resources includes multiple copies for each resource and `update_translated_resources_no_files()` runs for all of them.
Also using this opportunity to:
* Log synced resource changes (we had a similar log before).
* Properly compare already synced locales and skip them.
> Add distinct() to changed_resources QuerySet

- pontoon/administration/views.py
- pontoon/base/models.py
- pontoon/base/utils.py
- pontoon/base/views.py
- pontoon/contributors/views.py
- pontoon/localizations/views.py
- pontoon/machinery/views.py
- pontoon/projects/views.py
- pontoon/teams/views.py
BTW, in some of the files we `import logging`, set `log = logging.getLogger(__name__)` and then never log anything.
I find this convenient, because I can easily log during development without setting up the logging first and then removing the setup once I'm done.
I wonder if anyone has objections to this.
> Always set logger name to module name

- pontoon/base/tests/test_views.py
We now only compare the count instead of the entire response, in which the selected source parameter can vary between different environments.
The error started showing on Travis after https://github.com/mozilla/pontoon/commit/393f618223437946c836f954560d68a88c754983#diff-d32c42d35421a86de5df6a6b90db1703 was merged.
@Pike is this the fix you had in mind?
> Fix failing Translation Memory count test

- pontoon/base/models.py
- pontoon/sync/core.py
- pontoon/sync/tasks.py
- pontoon/sync/vcs/models.py
When detecting changed resources, only take into account changes made before the sync job started. Otherwise we might end up trying to sync locales we didn't pull files for, which will lead to KeyError in VCSResource constructor's for locale in locales loop. This is a regression from bug 1383252.
That same error is also thrown when a new locale is enabled for a project during sync - after the "pull phase". We fix it by checking that all locales identified as needing sync have been pulled. This is an old bug we never fixed.
Note: None of these two bugs is causing destructive changes: they break the project sync which then completes on the next run. However, if new source strings are added and the error occures, we hit bug 1383271.
@Pike Let me know if I finally overflooded you with r? …
> Fix bug 1395490: fix KeyError on sync

- pontoon/base/models.py
- pontoon/base/static/css/style.css
- pontoon/base/static/js/main.js
- pontoon/contributors/static/css/notifications.css
- pontoon/contributors/templates/contributors/widgets/notifications_menu.html
- pontoon/settings/base.py
In notifications popup, always show the latest 7 notifications, including the unread. If there are more than 7 unread notifications, show all.
@jotes r?
> Fix bug 1363164: Show read notifications in popup

- pontoon/base/models.py
Is a logged in user with no contributions to any locales tries to load the home page, it raises a 500 error. That is a regression, and is fixed by this commit.
@mathjazz or @jotes r?
> Fixes bug 1396607 - Fix error when a user has no contributions yet.

- pontoon/base/static/js/table.js
- pontoon/projects/templates/projects/includes/teams.html
- pontoon/teams/templates/teams/teams.html
One should be able to search by locale (code), not just the language in places like https://pontoon.mozilla.org/teams/.
> Allow searching by locale code in team list

- pontoon/base/models.py
We join the entity table with the translation table in order to search, but that join is done for all the translations, where we only care about translations for the locale the user is looking at. This commit moves the filter on the locale up in the WHERE clause, allowing the database to optimize the join, leading to a faster search time.
> Bug 1377099 - Make search faster.

- pontoon/base/views.py
- pontoon/projects/templates/projects/widgets/project_selector.html
While looking at performance data of the search speedup, New Relic pointed me to a simple fix for improving page load time of the translate view.
It's a simple trick to cache a DB query in a variable insted of querying the DB with the same request in a loop.
Note that the translate view is also used as the homepage for users that are not authenticated or don't have any contributions, which makes it the most popular view.
```
translate view speedup: 40%
```
> Faster translate view

- pontoon/base/models.py
- pontoon/contributors/views.py
Another quick fix, with the same background as #703.
The average call to the /notifications page triggers 178 base_project select DB queries, which makes the page slow. With this fix, the number goes down to 2 and the page load is around 75% faster.
Note that the page is the 3rd most popular view (after translate view and team view) - possibly due to the [Pontoon Tools](https://addons.mozilla.org/sl/firefox/addon/pontoon-tools/?src=search) extension.
We use the same trick on the notifications menu. The impact is less obvious, because we usually only load the latest 7 notifications.
```
/notifications speedup: 60%
```
> Faster notifications page

- pontoon/base/models.py
- pontoon/projects/templates/projects/projects.html
- pontoon/teams/templates/teams/teams.html
This one was also discovered using the New Relic data.
We now use python to get top instances and aggregated data from projects and locales QuerySets. It's faster than querying the DB with order_by() and aggregate().
The 2nd commit also has a noticable performance impact. We now list all locales that have at least one project enabled, regardless if it's synced or not.
```
/teams speedup: 70%
/projects speedup: 40%
```
> Faster teams and projects pages

- pontoon/base/models.py
- pontoon/base/tests/test_models.py
- pontoon/contributors/static/css/contributors.css
- pontoon/contributors/templates/contributors/contributors.html
- pontoon/contributors/templates/contributors/widgets/contributor_list.html
- pontoon/localizations/views.py
- pontoon/projects/views.py
- pontoon/settings/base.py
- pontoon/teams/views.py
This brings around 80% speed up to the /contributors view, and up to 90% on more specific contributors pages (/sl/contributors, /projects/firefox/contributors, /sl/firefox/contributors).
On production the load time of these pages averages around 6 seconds, so this should bring us to around 1.5 seconds. I'm not sure we can achieve much more without changing the data model.
Please review each commit separately. I tried to be as verbose as possible in commit messsages. To further clarify the last commit (https://github.com/mozilla/pontoon/pull/706/commits/0f9ce46cc7a9d29d950a22c7e257017b74077023), I'm adding the before and after SQL query:
Before:
```sql
SELECT DISTINCT "auth_user"."id",
"auth_user"."password",
"auth_user"."last_login",
"auth_user"."is_superuser",
"auth_user"."username", …
```
> Bug 1357361: Speed up contributors list

- pontoon/base/static/js/translate.js
If a string contains a link to a JPG or PNG file in its comment, we
render the linked image as a thumbnail in the source panel. If the
subsequently openned string does not have a comment, we keep the
screenshot visible instead of removing it. This patch fixes that.
> Reset screenshot on string navigation

- pontoon/base/static/css/translate.css
Partially translated strings use a different CSS class than missing
strings, depite the fact that the status icon looks the same. That is
because we have translations to show for the partially translated
strings, so the source strings column can only occupy half the width.
Missing strings on the other hand don't have translations (d'oh), so
the original string can occupy the entire string list width.
> Fix status icon for partially translated strings

- requirements.txt
@mathjazz @stasm 
I tested that upgrade with my version of pontoon-intro. If you remember more suitable projects/edge-cases - feel free to point them out/review.
> Fix bug 1382538 - Bump python-fluent to 0.4.2

- bin/mozilla-en-US.py
Cross-channel repository is already limited to localizable files only, and it also includes files from the comm-* repositories.
> Fix bug 1399166: Use X-channel repo as source

- pontoon/api/schema.py
- pontoon/base/models.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1403861
The Suggested status is pending a refactor in bug 1377969 and until it's
fixed, it's confusing to use `translatedStrings` for Suggested.
The Fuzzy status might get folded into Unreviewed Strings as part of bug
1377969 too. Let's remove it for now and re-add if it stays around.
The Complete flag will now only be true if all strings are Approved.
Suggested and Fuzzy strings don't count towards this flag anymore.
> Bug 1403861 - Hide Suggested and Fuzzy statistics in the API

- pontoon/base/static/js/main.js
- pontoon/machinery/urls.py
- pontoon/machinery/views.py
Amagama is down due to an expired web server certificate. We don't have
a mechanism to simply turn it off. So we're removing it completely.
That is because:
* The content hasn't seen an update for years.
* New Relic shows it's the most time consuming transaction in Pontoon.
* We don't know when the server will be back up.
* The changeset is rather small so we should be able to revert it if needed.
> Fix bug 1411284: Disable amaGama

- pontoon/base/forms.py
- pontoon/base/tests/test_forms.py
I'm not confident this covers all the use cases from before, but logically it should (as it is now effectively doing the same thing than before my change to using a Form).
> Fix bug 1411225 - Accept white spaces in search for entities.

- pontoon/teams/static/js/team_selector.js
If the locale is selected on the preffered locales multi locale
selector, that same locale also gets selected as the homepage.
This patch fixes that.
@jotes r?
> Fix preferred locales and homepage selector interferance

- pontoon/base/static/js/translate.js
For each plural form of a locale, we calculate example number to use as a hint in the UI. Examples were not assigned to locales with 2 plural forms prior to this fix.
Compare plural tab content for [Slovenian](https://pontoon.mozilla.org/sl/amo-frontend/all-resources/?search=count&string=162963) (4 plural forms) and [German](https://pontoon.mozilla.org/de/amo-frontend/all-resources/?search=count&string=162963) (2 plural forms).
Note: This is the first step (codenamed "make it work as advertised") in moving this code to locale admin.
> Bug 1311053: Always assign plural examples

- Makefile
This prevents cleans up the container after running, and prevents
old containers from accumulating
> Add rm to make dockerrun

- .travis.yml
- requirements-test.txt
- setup.cfg
- tests/base/placeholder.py
- tests/conftest.py
- tests/fixtures/entities.py
- tests/fixtures/locales.py
- tests/fixtures/projects.py
- tests/fixtures/resources.py
Adds py.test setup and some basic fixtures
There are a couple of side effects of adding this:
- slows down test run
- by default py.tests coverage includes test files
re the first, i think we can live with that temporarily.
re including test files, i think that its useful to have coverage on tests/fixtures as sometimes its possible to assume a condition is being matched, or a loop contains some items, but coverage can indicate otherwise.
> Fixes #1417026 Add pytest

- docker/config/webapp.env.template
Running sync locally can be difficult, so allowing to do so from the admin interface is quite convenient for local development. This commit makes that the default behavior.
> No bug - Enable Sync button in admin for local development.

- pontoon/base/static/css/translate.css
- pontoon/base/static/js/fluent_interface.js
- pontoon/base/static/js/translate.js
- pontoon/base/templates/translate.html
Restore FTL button and enable switching between source and FTL editor:
- Fallback to source view for translations not supported in FTL editor.
- Same for source strings.
- Switching reflects changes in either editor.
- Prevent switching to rich editor if message not supported.
- Show translation length and Copy from source only for simple FTL strings and only in FTL editor.
- For untranslated strings not supported in rich editor, show source view if source string displayed as source.
Always use #translation textarea for source editor and #ftl-area for FTL editor (even for simple strings). Similarly, even simple source strings are displayed in #ftl-original. To make that possible, we keep entity and translation objects unchanged for non-complex FTL strings.
Other improvements:
- Bugfix: …
> Fix bug 1392255: Enable source view for FTL messages

- pontoon/base/static/css/translate.css
- pontoon/base/static/js/fluent_interface.js
- pontoon/base/static/js/translate.js
- pontoon/base/templates/translate.html
Use `<textarea>` elements instead of `<input type="text">` in rich FTL editor in order to make typing longer values easier. Input elements are limited to one line, textarea elements OTOH are resizeable.
> Fix bug 1382536: Replace input with textarea

- .travis.yml
- pontoon/base/templates/base.html
Adding the HiRes SVG favicon for nicer display in the Firefox's new tab.
For more details, see https://bugzilla.mozilla.org/show_bug.cgi?id=1421495.
We still need to use the old `.ico` favicon:
https://caniuse.com/#feat=link-icon-svg
> Fix bug 1421495: Add SVG favicon

- pontoon/base/templates/base.html
Without the type defined, Firefox uses the last defined favicon. See bug 1422289 for more details.
> Fix bug 1421495: Define favicon type

- pontoon/base/static/js/fluent_interface.js
@flodolo Thanks for noticing and filing the bug! Could you confirm that we also need to re-export all strings that are broken because of this bug?
> Fix bug 1423460: Do not hardcode plural selector

- requirements.txt
This fixes the travis breakage: https://travis-ci.org/mozilla/pontoon/builds/316385802?utm_source=github_status&utm_medium=notification
Seems to be working fine on stage.
> Update to latest psycopg2 to avoid breaking travis

- pontoon/base/static/js/translate.js
Previous code always set examples for the first two plural forms to 1 and 2.
@jotes r?
> Fix bug 1425420: Fix plural form example calculation

- pontoon/base/static/js/translate.js
- pontoon/batch/utils.py
To make search and replace work for FTL strings, we can't just use
Translation.string.replace(keyword, replacement) like for other file
formats, becuse we store the entire source code of the FTL Message in
Translation.string.
Instead, we need to:
1. Parse each string and get AST
2. Recursively traverse AST and run find & replace on text values only
3. Serialize updated AST.
> Fix bug 1393523: Search and replace text values only

- pontoon/base/templates/widgets/latest_activity.html
- pontoon/base/templatetags/helpers.py
- pontoon/base/tests/test_helpers.py
Same as #618, but server side. The idea is to show FTL translations as simple strings instead of source in the latest activity column tooltip on dashboards.
Not pretty, but still better IMHO.
Let me know if this makes sense and I can add some tests.
> Fix bug 1366259: beautify FTL strings in latest activity

- docker/Dockerfile
- docker/run_tests_in_docker.sh
I did not succeed in running tests with pytest in `make dockertest` for the moment, for a reason I don't understand. For now, this allows to manually run them with `make dockershell`, which is all I need.
> Bug 1417530 - Install test requirements in docker.

- pontoon/base/forms.py
- pontoon/contributors/static/css/contributor.css
- pontoon/contributors/static/css/settings.css
- pontoon/contributors/static/js/contributor.js
- pontoon/contributors/static/js/settings.js
- pontoon/contributors/templates/contributors/profile.html
- pontoon/contributors/templates/contributors/settings.html
- pontoon/contributors/tests.py
- pontoon/contributors/urls.py
- pontoon/contributors/views.py
Taking over from #631. This is exactly the same content, plus some changes I've made on top, and rebased against latest master. 
Lots of credits go to @karabellyj! Thanks again for your work! 
@mathjazz, mind making sure I haven't done anything stupid?
> Fix bug 1335331 - Enable users to change their email address

- pontoon/base/static/css/translate.css
- pontoon/base/static/js/fluent_interface.js
- pontoon/base/static/js/translate.js
A test case is described in the [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1429758), but it's simply reproducible with any simple FTL string that contains HTML markup, e.g.:
```
key = Value <span>with</span> markup
```
The second commit is unrelated stylistic improvement I noticed along the way.
> Bug 1429758 ftl fix copy

- pontoon/base/models.py
- pontoon/teams/views.py
@jotes r?
As mentioned in the [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1379149#c2), this is a simple optimization of the contributors query inspired by [bug 1357361](https://bugzilla.mozilla.org/show_bug.cgi?id=1357361).
I tested on stage and the entire /permissions page request gets around 60% shorter.
> Bug 1379149: Optimize Contributors query

- pontoon/base/utils.py
- tests/base/utils.py
Adds a util that uses python's fnmatch to convert a glob to a regex in a way that can then be used with django's `__regex` queryset selector.
> Touch bug #1416256: Glob to regex util

- setup.cfg
- tests/conftest.py
- tests/fixtures/doctest.py
The tag api is a little complex, so a doctest is useful to work through it, explain it, and as a form of integration test. This just adds doctest support in the env
> Touch bug #1416256: Doctest support

- bin/post_compile
- package.json
This PR
- increases the version of node used
- adds a webpack command to heroku deployment
The webpacked resources are not actually used yet, this is more to test/ensure that we can build resources properly on heroku
> Touch Bug 1243129: Heroku webpack support

- Makefile
- docker/run_tests_in_docker.sh
Adds a `dockerwebpack` command to the makefile to run webpack in the foreground
> Touch Bug 1243129: Add Dockerwebpack makefile target

- .eslintignore
- .eslintrc.js
- .travis.yml
- pontoon/static/js/placeholder/placeholder.js
- pontoon/static/js/widgets/checkbox.js
- tests/base/models/locale.py
- tests/js/foo.js
- tests/js/widgets.js
- sets up linting in more of the code base
- adds a checkbox widget that can have its `indeterminate` property set
> Touch Bug 1243129: linting, react env and a widget

- pontoon/base/static/js/fluent_interface.js
- pontoon/base/templatetags/helpers.py
- pontoon/base/tests/test_helpers.py
To make review easier, I've split the patch for bug [1431436](https://bugzilla.mozilla.org/show_bug.cgi?id=1431436) into two pieces, which can also be landed separately. This is the first piece that contains:
1. Simple preview updates, which all Pontoon to display virtually any valid FTL Message in the string list, latest activity column and other places where simplified preview is used.
2. Original string presentation updates to support any FTL Message that contains any combination of elements of type `TextElement`, `ExternalArgument`, `MessageReference` and `SelectExpression` in their value or attribute. That includes strings with plurals, PLATFORM() and strings that contain both - value and attribute.
The second piece will bring the editor support.
A …
> Bug 1431436: [FTL] Support PLATFORM()

- pontoon/base/static/css/table.css
- pontoon/projects/templates/projects/widgets/project_list.html
- pontoon/teams/static/css/team.css
Show total number of strings in the project request view of the team page,
so one can see how big the project is.
Here is the screenshot:
> Fix bug 1398852: Add all strings column in the project request view

- .eslintrc.js
- pontoon/static/js/widgets/columns.js
- pontoon/static/js/widgets/errors.js
- tests/js/widgets.js
Adds an error widget, converts the column widget to purecomponent, and sets the prefer-stateless flag for eslint
> Touch Bug 1243129: React errors widget

- pontoon/base/models.py
- pontoon/base/static/js/fluent_interface.js
- pontoon/base/static/js/translate.js
This is the continuation of #814, which brings support for editing (6ba9882) and saving (7d68a94) translations that contain selectors in values and attributes. If selectors are surrounded (with other selectors or simple strings), that's supported too.
A [pontoon-ftl](https://github.com/mozilla-l10n/pontoon-ftl/blob/master/en-US/demo.ftl) repository is available for testing and set up on stage. Feel free to deploy this patch to stage if needed.
> Bug 1431436: [FTL] Support PLATFORM() - 2nd half (editor & serializer)

- pontoon/base/static/js/fluent_interface.js
- pontoon/base/static/js/main.js
This is a next iteration of [bug 1382348](https://bugzilla.mozilla.org/show_bug.cgi?id=1382348).
Among other things, it will mark up DOM Overlays and make them easier to insert into the editor (using a mouse click).
> Fix bug 1434535: Mark XML tags as placeables

- pontoon/base/static/css/translate.css
I couldn't test it locally but this css addition tends to fix it using developer tools
Reference link : https://pontoon.mozilla.org/fr/fundraising/all-resources/?string=174187
Screenshots : 
Before:
After
> Fix bug 1418540: Fix overlay image cutoff in all-resources.

- pontoon/base/static/css/heading_info.css
I have changed the color to brightest possible shade of white i.e. #FFFFFF also the links gets underlined when someone hovers on the whole list(ref: https://pontoon.mozilla.org/projects/ ). Also added the same with right ones in one of the pages (ref: https://pontoon.mozilla.org/ach/activity-stream-new-tab/ )
Here is the screenshot and hovering effect as well
> Fix bug 1416528: Modified color of links in dashboard header

- pontoon/base/views.py
Earlier the user who hits the save button for a translation without making any changes is set as author for the translation if author is not set. I have removed the condition which sets the author for non changing translations
> Fix bug 1410569: Translation author not set to user if there are no changes

- pontoon/base/static/css/translate.css
@jotes Could you r, given that you're working on a related PR #836?
This also fixes the "newlines issue" in the diff view:
https://bugzilla.mozilla.org/show_bug.cgi?id=1389969#c1
> Fix bug 1435258: Keep dir-based alignement in diff view

- pontoon/base/models.py
- tests/fixtures/entities.py
afaict the qs.distinct is not required here, removing it speeds up  (EDIT: db timings in...) the entities view 3-4x in my testing
> Touch Bug 1436149: Entities perf hacks 2 - qs.distinct()

- pontoon/static/js/utils/ajax.js
- tests/js/utils.js
current code uses `URLSearchParameters` but it should be `URLSearchParams`
> Fix Bug 1437365: React ajax get fix

- pontoon/base/models.py
this might be required - im not sure - but in testijng the sql i always got the same results - and it took about 90% off of the query time. This method is used quite a lot i think
> Remove filter/distinct from Locale aggregate method 

- pontoon/base/static/js/fluent_interface.js
This fixes these kinds of bugs:
If the string is untranslated and we only translate one of the two
variants in the rich editor, the unsaved changes warning is not
displayed.
> Fix bug 1437989: Identify broken translations with error message

- pontoon/base/templates/base.html
- pontoon/base/templates/django/base.html
- pontoon/base/templates/tracker.html
- pontoon/settings/base.py
* Create a template for Google Analytics snippet and point to it in base templates
* Update the inline js snippet
* Update related CSP hashes and update CSP Rules
@mathjazz / @phlax Could you review and then push it to the staging to check if migrations works?
I tested it locally and analytics.js sends data to `https://www.google-analytics.com/collect?v=1&...` (it uses pixel tracking).
> Bug 1439650 - Migrate to analytics.js

- docker-compose.yml
- docker/postgres/Dockerfile
- docker/postgres/docker-entrypoint-initdb.d/collations.sql
Collations were fixed for turkish at least in previous bugs/PRS:
https://bugzilla.mozilla.org/show_bug.cgi?id=1346180
https://github.com/mozilla/pontoon/pull/554
This fix requires the collation set to be added/setup in the db env.
This PR adds that setup, which at least allows us to test against that bug in dev. It doesnt however fix it for any other locales, so we may wish to add (lots?) more locales, or see if we can do this without having to add a separate collation for each lang.
> Touch Bug 1440940: Docker postgres collations

- requirements.txt
Updated bleach to fix a security issue affecting versions from 2.1
to 2.1.2. In pontoon this is mitigated by CSP.
> Bug 1442745 upgrade bleach to 2.1.3

- .eslintrc.js
- pontoon/base/static/js/main.js
Changelog:
* Add start time to every ajax request.e
* Send event to Google Analytics with the overall time of request and requested url.
---
Hey @mathjazz and @Pike,
As we discussed during The Munich workweek, I prepared a small js-snippet that should track the overall time of all Ajax requests sent  from the Front-end to the Back-end.
I'm aware that We probably can't merge this until all non-technical concerns are resolved.
However, I would like to hear your opinions if this kind of metrics is useful and if e.g. We should add/remove some informations from events passed to GA.
To make it easier, I've ran my local instance and generated some events to in my personal GA account (Axel should still have access).
These  screen-shots should give you more context how this can look like in GA …
> Fix bug 1439650 - Track performance of all Ajax requests in Google Analytics

- pontoon/base/migrations/0117_bug_1405256_ftl_delete_duplicates.py
Delete TranslationMemoryEntry instances first, because the tms QuerySet gets empty after the Translation instances are deleted.
> Fix bug 1405256: Fix migration

- .travis.yml
This is a massive optimization for (cached) travis runs. Its pretty much as fast as we will get it without removing the old test suite, or speeding up tests themselves
- cache python dirs
- a workaround for travis' use of aufs which otherwise causes it to upload cache without change.
> Fix Bug 1442281: Cache python dirs in travis

- pontoon/base/static/css/heading_info.css
- pontoon/base/templates/widgets/heading_info.html
This fixes the bug as shown in the screenshot:
> Fix bug 1389820: Break resources into new lines if needed

- pontoon/tags/utils/__init__.py
- pontoon/tags/utils/latest_activity.py
- pontoon/tags/utils/stats.py
- pontoon/tags/utils/tag.py
- pontoon/tags/utils/tagged.py
- pontoon/tags/utils/tags.py
- tests/tags/utils/tag.py
- tests/tags/utils/tagged.py
- tests/tags/utils/tags.py
Adds a ~~model and~~ util for saving and fetching tags/tiers
The `TagsTool` provides the api for retrieving or saving information around tags. It has a number of associated tools that provide more specific apis.
Most simply you can call
```
tool = TagsTool()
```
this will provide you with an iterable object, the items of which will be of type `TagTool` (singular), which can provide further information/stats about a specific `tag`
you can filter the tool by passing kwargs - eg `projects`, `locales` (which should be lists)
you can create a clone of the tool, by calling it - this will carry any kwargs and you can add further - eg
```
filtered_tool = TagsTool(projects=['foo'])
more_filtered_tool = filtered_tool(locales=['en'])
```
You can filter the `tag` or `tags` that it provides …
> Touch #1416256 String tiers util

- .eslintrc.js
- package-lock.json
- package.json
- pontoon/static/js/utils/ajax.js
- pontoon/static/js/utils/csrf.js
- pontoon/static/js/utils/data.js
- pontoon/static/js/widgets/columns.js
- tests/js/utils/data.js
- tests/js/widgets/columns.js
Adds 
- ~~a data table component that fetches data and builds a reacttable component onMount~~
- ~~a table with checkboxes that can be selected and submitted~~
Adds a higher order component that wraps the wrapper component with a "manager" that retrieves/submits data from/to an api.
The wrapped component is passed `data`  and `errors` , and functions to `refreshData` and `handleSubmit` as props
~~blocked by #854~~
required for strings tiers project and admin views
> Touch Bug 1243129: React data manager

- pontoon/base/urls.py
- pontoon/base/views.py
- tests/base/views/locale_agnostic.py
This PR is for bug 1424845 on Bugzilla. I modified my code according to @jotes 's gist. Thanks a lot!
Per comment 9 (https://bugzilla.mozilla.org/show_bug.cgi?id=1424845#c9):
I'm not sure about hard-coding 'en-GB', but should we have something in case there is no accept-language locales?
Can I remove 'en-GB' from line 118 in views.py? I think it might be redundant since we are setting it as the locale in line 121.
Let me know if I need to change anything.
> Fix bug 1424845: Language-agnostic links to searches

- pontoon/base/static/js/fluent_interface.js
FTL editor uses a special [UI for localizing access keys](https://www.youtube.com/watch?v=hnJoWodS3F8). Candidates for access keys can be selected from a list that is generated from the input in surrounding fields. Currently the only such field is the first textarea element of the first attribute of the message.
After this patch, we generate access key candidates from all textarea elements belonging to the `label` attribute. If such attribute doesn't exist, we generate candidates from all textarea elements of the value.
See examples in the [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1445435) for test cases (which should all work now, because the patch is deployed to stage). 
Also included in the patch:
- Exclude space as a possible accesskey candidate
- Add more accurate current …
> Fix bug 1445435: Extend access key candidate generators

- pontoon/base/models.py
- pontoon/base/static/css/translate.css
- pontoon/base/static/js/translate.js
- pontoon/base/urls.py
- pontoon/base/views.py
- pontoon/localizations/templates/localizations/widgets/resource_selector.html
- pontoon/projects/templates/projects/widgets/project_selector.html
- pontoon/teams/templates/teams/team.html
- pontoon/teams/templates/teams/teams.html
- pontoon/teams/templates/teams/widgets/team_selector.html
- tests/base/models/entity.py
This patch adds the ability to load all strings across all projects for a selected locale in a translate view. That means localizers can also search and filter such strings, which simplifies tasks like:
* work on all untranslated strings for my locale
* review all suggestions for my locale or
* ensure consistency of a term translation across all projects in my locale
Translation of all locale projects can be requested from dashboards or by selecting "All Projects" in the project menu in the translate view. The part menu is hidden, because it contains too many items to be useful (for most locales). Time and author filters are disabled for performance reasons. A project name is now also listed in string metadata (under comment).
I tried to separate logic into multiple commits as I developed …
> Bug 1305281: Translate all locale projects

- bin/post_compile
- requirements-dev.txt
This allows the use of a @debug decorator that can be used to
print out the sql used in a method or function.
Also provides a contextmanager to do similar for a block of code.
Ideally, we add this to staging, and then we can check/share performance changes
> Fix Bug 1440895: Add dj.debug package to requirements-dev

- pontoon/base/static/css/translate.css
- pontoon/base/static/js/fluent_interface.js
This patch brings two fixes for the access key UI:
1. The list of candidates is now initialized properly - by extending the selector.
2. The access key textarea element no longer transforms text to uppercase.
@phlax Since you reviewed #899, which is related, I'd like to ask you to look at this one as well.
I deployed the patch to stage.
The bug on prod:
https://pontoon.mozilla.org/sl/firefox/browser/browser/preferences/preferences.ftl/?search=accessk&string=176239
The fix on stage:
https://mozilla-pontoon-staging.herokuapp.com/sl/test-fluent/preferences.ftl/?search=accessk&string=176235
> Bug 1447095: FTL access key UI fixes

- pontoon/base/static/js/fluent_interface.js
Fluent uses curly brackets to denote Placeables, which must not be used to generate access key candidates, because in in Pontoon UI they don't contain translateable text (but references to external arguments or other entities).
Bug on prod:
https://pontoon.mozilla.org/sl/firefox/browser/browser/preferences/preferences.ftl/?string=176239
Fixed on stage:
https://mozilla-pontoon-staging.herokuapp.com/sl/test-fluent/preferences.ftl/?string=176235
> Fix bug 1447103: Exclude placeables from access key candidates

- pontoon/base/static/js/fluent_interface.js
Exclude Placeables from generating access key candidates by building a
fake FTL Message from textarea contents, parsing it and only taking
TextElements into account.
Previous implementation used regex to try to do the same, which would
fail when curly brackets are escaped, e.g.:
```
key = Hello \{ and then { -brand-short-name} World
```
> Fix bug 1447103 more reliably

- tests/base/helpers.py
These were removed when shifting tests to pytests here #758
> Bring back as_simple_translation tests

- pontoon/base/models.py
- pontoon/projects/templates/projects/widgets/project_list.html
- pontoon/teams/views.py
I have replaced the earlier used `project.total_strings` with `chart.total_strings` which gives the correct number of strings in the project. This also addresses the discrepancy mentioned here : 
https://github.com/mozilla/pontoon/pull/827#issuecomment-372854230
> Fix bug 1442209: Replace total_string with avg_string_count in requestproject template.

- pontoon/base/static/js/fluent_interface.js
- pontoon/base/templatetags/helpers.py
- tests/base/helpers.py
We already have strings in the wild that use [Functions](projectfluent.org/fluent/guide/functions.html). Pontoon doesn't support Functions in the Rich FTL UI, so such strings are [displayed as source](https://pontoon.mozilla.org/cs/common-voice/messages.ftl/?search=DATE&string=175940).
This patch fixes that and treats Functions (AKA `CallExpressions`) as placeables (in the Pontoon definition of the word), meaning they are highlighted and be inserted into the editor with a click.
@adngdb Let me know if you can review this or do you want me to [refactor](https://bugzilla.mozilla.org/show_bug.cgi?id=1433499) first.
> Fix bug 1437857: Add support for Functions

- pontoon/base/templates/base.html
- pontoon/base/templates/django/base.html
This ~prevents/mitigates a fouc. Currently the body background is not set untill the css file is loaded - which means the browser paints the bg white initially - causing a fouc.
This doesnt entirely fix the problem but makes it much less noticable
> Set background colour at beginning of html load

- pontoon/base/static/js/main.js
- pontoon/base/templates/terms.html
@guerojeff Could you have a look at the English and legal in this patch?
> Fix bug 1448814: Add 3rd-party service copyright notice to Terms

- pontoon/tags/utils/latest_activity.py
- tests/tags/utils/tagged.py
Im not sure how this situation is created - but this fixes the issue for the tags view, and works the same as in other views
> Fix Bug 1450464: prevent tags view failing where latest translation is None

- pontoon/base/models.py
The Translation Time and Translation Authors sections of the filter menu in the translate view should only include translations of the project that is currenty being translated if "All Resources" is selected (i.e. `path` not specified).
Note that #922 will fix the issue for Translation Authors, but not for the Translation Time filter, which also depends on `for_locale_project_paths`.
> Fix bug 1450265: Filter Translators by project

- pontoon/base/static/js/fluent_interface.js
- pontoon/base/static/js/translate.js
A dozen or so fixes that should make `fluent_interface.js` easier to review and migrate to React. The refactor is limited to the plan outlined in [the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1433499#c3).
Diff is unreadable, so I strongly suggest looking into each commit diff message separately.
> Fix bug 1433499: Refactor fluent_interface.js

- pontoon/checks/libraries/__init__.py
- pontoon/checks/libraries/translate_toolkit.py
- tests/checks/libraries.py
Also disable KDE and Gnome specific checks.
@jotes r?
> Fix bug 1410619: Disable acronym checks

- pontoon/base/static/css/translate.css
- pontoon/base/static/js/fluent_interface.js
- pontoon/base/static/js/translate.js
- pontoon/base/urls.py
- pontoon/base/views.py
- pontoon/checks/libraries/__init__.py
- pontoon/checks/libraries/compare_locales.py
- pontoon/checks/libraries/pontoon.py
- pontoon/checks/libraries/translate_toolkit.py
- tests/checks/compare_locales.py
- tests/checks/libraries.py
- tests/checks/pontoon.py
The gist of this PR is what [bug 1458347](https://bugzilla.mozilla.org/show_bug.cgi?id=1458347) says: [removing](https://github.com/mozilla/pontoon/commit/b60aa5dfa1ae27cb306f302c8fe44ef237097520) the checks that are already included in compare-locales and [moving](https://github.com/mozilla/pontoon/commit/95ddc691c63d9653835dceb063b1bb9db3be05d0) the rest to `pontoon.checks.libraries.pontoon`. I also made a few other related enhancements along the way ([1](https://github.com/mozilla/pontoon/commit/50dd35ec510417bad14dd1d044729759e88f11d9), [2](https://github.com/mozilla/pontoon/commit/d936b66b3ba0ba81c6ad49eab68a071348eacf1e), [3](https://github.com/mozilla/pontoon/commit/bb0fe9b1f2d2ea608d9c2f71be1860906419282c)). This part if pretty straightforward.
A slightly more complex beast is …
> Bug 1458347: Move Fluent checks to backend

- pontoon/base/static/js/translate.js
In complex FTL strings, multiple fields are present, and we use Tab to
navigate between them, as this is the browser default shortcut. We also
use Tab to navigate between helper suggestions (history, machinery,
locales), as many other CAT tools do.
This patch re-enables Tab for navigating helper suggestions for complex
FTL strings when the focus is in the last field. After the suggestion
is copied, we keep the focus in the last field to make moving to next
suggestion with subsequent Tabs easier.
@jotes r?
> Fix bug 1450505: [FTL] Re-enable Tab to copy from helpers

- pontoon/base/static/js/translate.js
When Make Suggestions is turned on and you approve a suggestion that
returns warnings and click `Save anyway`, suggestions needs to get
approved. Previously, `Same translation already exists` message was
getting displayed.
> Fix bug 1459596: Fix approval in suggest mode

- .gitignore
- Makefile
- docker-compose.yml
- docker/Dockerfile
- docker/entrypoint_webapp.sh
- docker/run_tests.sh
- pontoon/settings/base.py
- webpack.config.js
This commit ensures that:
- the assets/ folder is always created
- dependencies (Python and node) do not pollute the user's repository. They are now installed in a different folder inside the container
- webpack takes resources from the right place, and puts bundles in the right folder
This looks like a small patch but it was actually fairly complex. The reason is that our Dockerfile is made for a production deployment, meaning that it builds all the resources it needs to run in place. That's fine. However, when we run locally for development, using docker-compose, we override the /app folder with the user's local folder. That means all resources built during `make build` are lost. This patch puts those resources in a different folder, and then links to that folder from the user's …
> Fix bug 1456846 - Fix docker dev environment.

- pontoon/checks/libraries/__init__.py
- pontoon/checks/libraries/compare_locales.py
- pontoon/checks/libraries/pontoon.py
- tests/checks/pontoon.py
- Change message to `Empty translations are not allowed`: better when
switching editors than `cannot be submitted`.
- Do not run FTL checks if translation empty to avoid similar messages
- Run internal Pontoon checks before compare-locales checks (no impact, just matching the order of messages as they are displayed)
> Fix bug 1460237: Do not error on empty FTL messages

- pontoon/base/static/js/fluent_interface.js
If we cannot switch from source to rich editor, because the message is
not supported, we should show this information in a notification bar
instead of presenting it as a failed check.
> Fix bug 1460238: Notification instead of failed check

- pontoon/checks/libraries/compare_locales.py
- pontoon/sync/formats/silme.py
- pontoon/sync/utils.py
Pontoon takes care of escaping quotes and apostrophes on serialization.
See: pontoon.sync.formats.silme.SilmeResource:escape_quotes()
@jotes r?
> Fix bug 1460073: Ignore Android DTD escaping checks

- pontoon/base/static/js/fluent_interface.js
- pontoon/base/templatetags/helpers.py
- tests/base/helpers.py
This is similar to [bug 1437857](https://bugzilla.mozilla.org/show_bug.cgi?id=1437857), where we added support for `CallExpressions`: https://github.com/mozilla/pontoon/pull/910/commits/2edbadd13d9f305b7cc80fd0901bdb83dc7f6a8f.
Now we're adding support for 4 remaining `*Expression` types.
> Fix bug 1453319: [FTL] Add support for missing expression types

- docs/admin/maintenance.rst
A queue [got stuck](https://pontoon.mozilla.org/sync/log/51004/) after a long time. I believe nobody has been fixing this except for me and @jotes.
So let's document it.
> Fix bug 1398339: Add Releasing the queue to docs

- pontoon/localizations/templates/localizations/includes/tags.html
- pontoon/localizations/templates/localizations/localization.html
- pontoon/localizations/urls.py
- pontoon/localizations/views.py
- pontoon/projects/templates/projects/includes/tags.html
- pontoon/projects/urls.py
- pontoon/projects/views.py
- pontoon/tags/templates/tags/widgets/tag_list.html
- pontoon/tags/views.py
In https://github.com/mozilla/pontoon/commit/5c4152d2a33be7a0c28d766b8da922a9d1fd35f6 we landed support for the _Tags_ tab in the [project dashboard](https://mozilla-pontoon-staging.herokuapp.com/projects/firefox/tags/), which contains a list of tags and their stats for the project. This patch bring the _Tags_ tab to the [localization dashboard](https://mozilla-pontoon-staging.herokuapp.com/sl/firefox/tags/), which contains a list of tags for the project and their stats for the localization (project-locale).
[First commit](https://github.com/mozilla/pontoon/commit/43fc906227d8442d533b736b7e786553a8c0cf60) sets the stage by generalizing the code for Tags tab on the Project dashboard. The [second one](https://github.com/mozilla/pontoon/commit/4aeaa0b538e7012689bc067ce4c779687b56124a) is an …
> Fix bug 1452647: Add Tags tab to the Localization dashboard

- pontoon/base/static/css/translate.css
- pontoon/base/templates/translate.html
- pontoon/base/templates/widgets/filter_item.html
This (alongside #969) is hopefully the last step before shipping Tags. You can test it on stage:
https://mozilla-pontoon-staging.herokuapp.com/sl/firefox/all-resources/?string=74127
@jotes r?
> Fix bug 1463073: Show tag priority in filter menu

- pontoon/administration/static/js/admin_project.js
Tag slug is only generated for the first tag. If you add more tags, it's not.
> Fix bug 1463364: Always generate tag slug

- pontoon/base/static/js/fluent_interface.js
@jotes r?
An example of a broken string in the wild:
https://pontoon.mozilla.org/fr/firefox/browser/browser/branding/sync-brand.ftl/?string=177742
Since the translation is not accessible via the UI, I'm providing it here:
```
-fxaccount-brand-name =
{
[lowercase] compte Firefox
*[uppercase] Compte Firefox
}
```
More on [Terms](https://projectfluent.org/fluent/guide/terms.html).
> Fix bug 1464852: [FTL] Support Term variants in rich editor

- pontoon/sync/formats/lang.py
- pontoon/sync/vcs/models.py
This fixes the first half of [bug 1465824](https://bugzilla.mozilla.org/show_bug.cgi?id=1465824):
_Make sure information about invalid files is properly logged._
For details, see commit messages.
@jotes r?
> Bug 1465824: Log invalid files

- pontoon/contributors/static/css/contributors.css
This fixes the following problem:
r=me
> Fix max length for contributors entries

- pontoon/base/static/js/translate.js
We introduced the removed line while fixing bug 1453879: https://github.com/mozilla/pontoon/pull/944.
After we fixed bug 1462419, the line is no longer needed: https://github.com/mozilla/pontoon/pull/967.
> Fix bug 1470742: Restore clickable contributor links in History tab

- pontoon/base/static/css/translate.css
This is a fix for a regression introduced in:
https://github.com/mozilla/pontoon/commit/46ffcb913bf945492b61787949f3199582ac1c23#diff-0c410b8223d3fa920e760f5f27612999R1172
> Fix bug 1471534: Do not truncate source string

- pontoon/base/static/js/fluent_interface.js
- pontoon/base/static/js/translate.js
This patch adds a special case for FTL messages with 1 simple attribute and no value to:
* source string panel
* editor
* serialization
A test case:
https://github.com/mozilla-l10n/pontoon-ftl/blob/master/en-US/demo.ftl#L10
Diff looks bigger than it could, due to change indentation. I suggest reviewing on a commit-by-commit basis.
> Fix bug 1447231: [FTL] Use simple string UI for messages with 1 simple attribute

- pontoon/base/static/css/translate.css
- pontoon/base/static/js/fluent_interface.js
- pontoon/base/templates/translate.html
Unlike regular Messages, Terms are allowed to contain custom attributes (i.e. attributes not present in source string).
This patch introduces the "Add attribute" button, together with the ability to remove custom attributes and edit their IDs.
To learn more about Terms and attributes, see:
https://projectfluent.org/fluent/guide/terms.html
The doc also contains a few examples, but you can also use the following file for testing:
https://github.com/mozilla-l10n/pontoon-ftl/blob/master/en-US/brand.ftl
> Fix bug 1454003: [FTL] Add ability to manage Term attributes

- pontoon/base/static/js/fluent_interface.js
It turns out we cannot use that trailing comma afterall 😩:
https://travis-ci.org/mozilla/pontoon/builds/397407562?utm_source=email&utm_medium=notification
```
The command "./node_modules/.bin/webpack" exited with 0.
14.53s$ python manage.py collectstatic -v0 --noinput
File "manage.py", line 20, in <module>
execute_from_command_line(sys.argv)
File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
utility.execute()
File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/ …
```
> Fix collectstatic by removing trailing comma

- pontoon/base/middleware.py
In [bug 1459939](https://bugzilla.mozilla.org/show_bug.cgi?id=1459939#c1) an exception was raised that contained a non-ASCII character. Which raised another exception, that prevented us to see the actual one.
This patch prevents that 2nd exception.
@jotes r?
Before:
```
Internal Server Error: /download/ 
Traceback (most recent call last): 
File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner 
response = get_response(request) 
File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response 
response = self._get_response(request) 
File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response 
response = …
```
> Bug 1465824: Encode non-Raygun exceptions as utf-8

- pontoon/base/static/js/translate.js
- pontoon/base/templates/translate.html
- pontoon/base/templates/widgets/filter_item.html
- pontoon/base/views.py
- pontoon/projects/templates/projects/widgets/project_selector.html
- pontoon/tags/models.py
- pontoon/tags/tests/test_models.py
Steps to reproduce:
1. Go to https://pontoon.mozilla.org/sl/firefox/all-resources/.
2. Open the filter menu.
3. Observe Tags.
4. Select AMO from the Project menu and click Go.
5. Open the filter menu.
6. Observe Tags.
Expected result: 
There are no tags in step 6.
Actual result:
Tags from step 3 (belonging to Firefox) are displayed in step 6 (when AMO is being translated).
> Fix bug 1472995: Dynamically update tags in the filters menu

- pontoon/settings/base.py
For details, see https://bugzilla.mozilla.org/show_bug.cgi?id=1473400.
> Fix bug 1473400: Remove contributor.js from /settings page

- pontoon/base/models.py
- pontoon/base/static/css/table.css
- pontoon/base/templates/widgets/deadline.html
- pontoon/base/templates/widgets/heading_info.html
- pontoon/base/templates/widgets/priority.html
- pontoon/localizations/templates/localizations/includes/resources.html
- pontoon/localizations/templates/localizations/widgets/resource_list.html
- pontoon/localizations/views.py
- pontoon/projects/templates/projects/widgets/project_list.html
- pontoon/tags/templates/tags/widgets/tag_list.html
This patch makes the most critical piece of information coming from the tags feature (priority) more visible, because ATM [not many people see it](https://bugzilla.mozilla.org/show_bug.cgi?id=1464802#c5).
It does that by introducing the priority column to the Resources tab (default) of the Localization dashboard. Note that the column only appears in at least one file is assigned to a tag (which sets the priority).
Since it's touching the same code and serving a similar purpose, we're also adding a deadline column to the localization dashboard. And, factoring out the deadline and priority field code, so that it can be reused easily.
Check out the behaviour on stage...
Priority only:
https://mozilla-pontoon-staging.herokuapp.com/sl/firefox/
Deadline only: …
> Fix bug 1464802: Show resource priority and deadline in localization dashboard

- pontoon/base/admin.py
- pontoon/base/models.py
- pontoon/base/templatetags/helpers.py
- pontoon/base/tests/test_helpers.py
- pontoon/localizations/views.py
This is a collection of fixes and improvements that were discovered as part of landing the file-level priority and deadline information.
https://github.com/mozilla/pontoon/commit/5607c65c20f687c2e650778f5481942c0bb103a6 just exposes Resource deadline in the Django admin and
https://github.com/mozilla/pontoon/commit/fe10de397d01b23f29446e8cbd97306d32b36566 removes the foo code to set the project deadline based on resource deadlines.
The interesting one is https://github.com/mozilla/pontoon/commit/7357daa8477b1b9e78394dab13da6c09a2f6732e, which prevents the `TypeError: datetime.date(2018, 2, 20) is not JSON serializable` triggered in here:
https://github.com/mozilla/pontoon/blob/7357daa8477b1b9e78394dab13da6c09a2f6732e/pontoon/projects/templates/projects/widgets/project_selector.html#L24
So …
> Bug 1464802: File priority & deadline followup

- pontoon/base/static/css/translate.css
We cannot reliably uppercase user names, because they may contain non-Latin characters, for which don't have a font support.
Since uppercase is used for cosmetic purposes at least here, I'm disabling it entirely for this use case.
> Fix bug 1475922: Do not uppercase user names

- bin/mozilla-en-US.py
Firefox, Firefox for Android, Thunderbird, Lightning and Seamonkey are special projects, because they store source strings in a single source repository (https://hg.mozilla.org/l10n/gecko-strings/). Pontoon doesn't support that [yet](https://bugzilla.mozilla.org/show_bug.cgi?id=1385834), so it needs to create its own per-project [*-central](https://hg.mozilla.org/users/m_owca.info) repositories.
The `mozilla-en-US.py` script does that job. It runs every 10 minutes, before each sync cycle.
Before this patch, if cloning of the source repository [failed](https://bugzilla.mozilla.org/show_bug.cgi?id=1475603#c0), all files were [removed](https://hg.mozilla.org/users/m_owca.info/firefox-for-android-central/rev/ab7cd3e0902a) from the per-project repositories. On next sync Pontoon then detected …
> Fix bug 1475603: If updating source repo fails, exit script

- pontoon/settings/base.py
- requirements.txt
Turns out `django-sslify` is no longer needed.
> Replace django-sslify with SECURE_SSL_REDIRECT

- pontoon/base/migrations/0100_bug_1390805_create_missing_tm_entries.py
- pontoon/base/utils.py
- pontoon/checks/libraries/compare_locales.py
- pontoon/checks/management/commands/run_checks.py
- pontoon/checks/tasks.py
- pontoon/checks/tests/test_models.py
- pontoon/checks/utils.py
- pontoon/sync/changeset.py
- pontoon/sync/tests/test_checks.py
Hey,
So this is the next PR for https://bugzilla.mozilla.org/show_bug.cgi?id=1458345
In this one, We finally run checks on translations during the sync process. 
TODO:
*Discussion/Questions* 
1. Do We want to ignore Translate Toolkit warnings here?
1. I wonder if the sync process should create TranslateMemory entries for the translations with errors?
1. Do we want to approve translations (from vcs) with errors? (I don't know if every VCS repo is protected with `compare-locales`)
> Bug 1458345 sync checks

- pontoon/base/models.py
- pontoon/base/views.py
Moving the `Prefetch` clause required for `map_entities` to `map_entities`, so that required data is always prefetched.
Fixes a bug which prevents string status from updating in the UI immediatelly after batch approval.
```
File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
response = self._get_response(request)
File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in …
```
> Make sure related entities data is always prefetched

- pontoon/base/views.py
In https://github.com/mozilla/pontoon/commit/b2f199d381d555055e38250ac49b4615182ec84d if requested entity not on the first page, we pass `entities` as a `list` instead of a `QuerySet` to `Entity.map_entities()`. Then we cannot prefetch.
```
File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
response = self._get_response(request)
File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", …
```
> Always pass entities as a QuerySet to map_entities()

- pontoon/sync/tasks.py
- pontoon/sync/tests/test_tasks.py
It should not be possible to make changes to read-only ProjectLocales through Pontoon, so Pontoon should never commit to these locales.
Still, it doesn't hurt to be extra cautious and add another check. And, it's necessary for cases like in [bug 1467978](https://bugzilla.mozilla.org/show_bug.cgi?id=1467978).
> Fix bug 1479771: Do not commit to read-only locales

- pontoon/sync/tests/formats/test_silme.py
- requirements.txt
We upgraded silme to fix its .inc parser to properly support empty translations.
> Fix bug 1480184: Upgrade to silme 0.9.4

- pontoon/base/static/js/tour.js
1. Added the locales tab slide which was missing.
2. Changed the content for history tab which was wrong and other content changes mentioned by flod.
3. Fixed the bouncing arrow at step 3 which was moving out of viewport.
4. Fixed the bug on using close button at step 3 and 5. (The menus were not disappearing even when clicked). Their afterStep events aren't fired upon using the Cross button.
> Bug 1473134: Tour content changes from flod's feedback and step 3/5 close button fix.

- pontoon/base/models.py
- pontoon/sync/core.py
- pontoon/sync/tasks.py
- pontoon/sync/tests/test_tasks.py
- pontoon/sync/vcs/models.py
Firefox source strings are first pushed to the so called `quarantine` repository, which is only used by 2 or 3 locales (e.g. Italian) that translate Firefox offline (without Pontoon). The purpose of `quarantine` is to test the quality of source strings and potentially back them out before they are exposed to all localizers in the `gecko-strings` repository used by Pontoon.
In https://github.com/mozilla/pontoon/commit/dd51a3db9ebc09c17c55fb7fe5600ec8bbffe107 we introduced read-only locales, which allow us to enable all locales in Pontoon. Including the ones working with the `quarantine` repository. However, when new source strings land in `gecko-strings`, Pontoon properly detects changed files and imports source strings, but it doesn't import [existing Italian …
> Bug 1372151: sync l10n files for which source changes, read-only and changed locales only

- pontoon/base/static/js/translate.js
Hey,
As We discussed, this should fix the possible XSS attack from anyone who's able to create new tags.
I decided to escape only  `slug` and `name` fields because they have `CharField` type.
//cc @mathjazz
> No bug - Fix possible XSS bug in the tags display

- pontoon/base/models.py
- pontoon/base/static/js/translate.js
- pontoon/batch/actions.py
- pontoon/batch/tests/test_views.py
- pontoon/batch/utils.py
- pontoon/batch/views.py
- pontoon/checks/tasks.py
- pontoon/checks/utils.py
- pontoon/sync/changeset.py
* How `find&replace` action should work? I thought about the following approaches:
* Allow to create suggestions with errors but don't mark them as approved
* Don't create suggestions at all if the change could create generate errors. This approach could require additional UI changes (to display errors etc.)
* Batch Approve should approve only translations without any errors (?)
* I think that batch reject operation doesn't require checks (feel free to correct me)
@mathjazz @pike hey, could you look at these discussion points?
Thanks in advance!
> Fix bug 1463173 - Run checks during batch actions

- pontoon/base/static/js/translate.js
- pontoon/base/views.py
_Note: this fixes a regression introduced by https://github.com/mozilla/pontoon/pull/1031/files._
Unauthenticated users can click the reject button for translations that are either fuzzy or unreviewed, and don't have an author assigned.
That is because we don't properly set the `own` class, which should only be set for authenticated users without permissions, in order to be able to reject their own translations.
I've also added the `login_required()` decorator, which is already used in similar functions.
> Fix bug 1486816: Always prevent reject actions for unauthenticated users

- pontoon/base/migrations/0133_calculate_strings_with_errors_warnings.py
- pontoon/base/models.py
We must use .distinct() in order to avoid counting translation twice.
> Fix errors and warnings stats calculation, r=me

- pontoon/base/models.py
- pontoon/base/static/js/progress-chart.js
- pontoon/base/static/js/translate.js
- pontoon/base/templates/widgets/progress_chart.html
- pontoon/localizations/templates/localizations/widgets/resource_list.html
- pontoon/localizations/tests.py
- pontoon/localizations/views.py
- pontoon/projects/templates/projects/widgets/project_list.html
- pontoon/projects/views.py
- pontoon/tags/tests/utils/test_tagged.py
- pontoon/tags/utils/chart.py
We're change the calculation of the completion percentage visible in progress charts on dashboards and the translate view.
**From:**
The number of Translated strings divided by the number of All strings [in %].
**To:**
The number of Translated strings and Strings with warnings divided by the number of All strings [in %].
That's because Warnings (unlike Errors) actually end up in product on build and are often false positives.
> Fix bug 1492829: Include warnings in completion percent

- pontoon/tags/tests/utils/test_tags.py
- pontoon/tags/utils/tags.py
- pontoon/test/fixtures/base.py
The lack of filtering on projects means that before this patch, finding the tag that was being concerned only took the slug into consideration. Thus, if two tags, under different projects, used the same slug, one of them would show up for all projects, leading to an incorrect listing of resources, and impossibility to manage that tag.
Note that I didn't add a test case for this, because of the amount of energy it took me to just find the one line where the fix was needed. I might reconsider next week, but by that time my understanding of this code might have faded away (I hope) so it's also possible that I'll never add that test case.
> Fix bug 1491027 - Filter on project when searching for tags.

- pontoon/base/static/js/translate.js
This string should not be marked as warning in the string list, because it's neither approved, nor fuzzy:
https://pontoon.mozilla.org/hr/firefox/browser/chrome/browser/pageInfo.properties/?string=175124
Check out how it works on stage, which runs this patch:
https://mozilla-pontoon-staging.herokuapp.com/hr/firefox/browser/chrome/browser/pageInfo.properties/?string=175124
> Fix bug 1494228: Consistenly identify Errors and Warnings in string list, and stats & filters

- pontoon/sync/models.py
total_strings mismatch in ProjectLocales of the same Project is
sometimes expected, because not all strings (files) need to be exposed
to all locales. So we shouldn't log every time we find such mismatch.
> Reduce fix_stats() log verbosity

- requirements.txt
Mercurial 4.6 introduces remote bundles, which should be much more performant.
> Update mercurial to 4.7.2

- pontoon/machinery/tests/conftest.py
- pontoon/machinery/tests/test_views.py
- pontoon/machinery/views.py
- pontoon/settings/base.py
Seems like v2 is deprecated.
This PR implements the basic support for v3 version of Microsoft translator.
I've just made a copy of `machine_translation` handler and adjusted it to
use the new v3 API, so now `machine_translation` is calling the `machine_translation_v3` if `MICROSOFT_TRANSLATOR_API_VERSION` equals to `3.0`.
> implement Microsoft translator API v3 support

- pontoon/base/models.py
This patch excludes strings from system projects (e.g. Tutorial) from filters and translate page stats when "All Projects" is selected as the Project.
Steps to reproduce:
1. Go to https://pontoon.mozilla.org/en-CA/.
2. Click on Missing (0).
3. Surprise! 🎉  There are (more than 0) strings in the string list!
> Fix bug 1500777: Exclude system projects from All Projects

- pontoon/base/static/css/translate.css
The source string panel collapses the new lines in FTL attributes, e.g.:
https://pontoon.mozilla.org/cy/firefox/all-resources/?string=191663
It should preserve them, same as it does for new lines in main values.
> Render new lines in FTL attributes in source string panel

- pontoon/base/static/css/style.css
- pontoon/base/static/js/main.js
If MT suggestion gets grouped with suggestions from other Machinery sources, and is returned first, it:
- causes the sources list to lack "percent match" at the beginning
- lacks a `&middot;` separating it from the other source titles
The bug is not easy to reproduce (at least not without `time.sleep()`), so I'm attaching a screenshot:
> Fix bug 1500854: Fix display of grouped Machinery results

- pontoon/base/migrations/0120_bug_1423679_update_plurals_20180417_1135.py
Hey,
It looks like the latest update of Fluent broke one of migrations.
I see the following error: https://gist.github.com/jotes/6c15a57a152d478a53131772e9eb8f5a
@mathjazz could you confirm the issue and review this patch?
> Fix migration 0120 for Fluent 0.7

- pontoon/base/static/js/fluent_interface.js
If source string contains custom (numeric) plural forms, list them as variants in untranslated, along with locale CLDR plurals.
Test case:
https://github.com/mozilla-l10n/pontoon-ftl/blob/master/en-US/demo.ftl#L30
> Fix bug 1443551: List custom plural forms

- frontend/.env
Doing that breaks our CSP rules, that explicitly reject inlined javascript code (inside a <script> tag). That is the default behavior of create-react-app 2 but it can be turned off with configuration, which is what this patch does.
> Fix bug 1505714 - Do not inline javascript during frontend build.

- pontoon/base/models.py
- pontoon/base/tests/managers/test_entity.py
- pontoon/base/tests/models/test_stats.py
- pontoon/batch/views.py
Howdy,
So, first of all -> I'm not good at naming things. Any suggestions are always welcome!
Main changes:
We don't make the full recalc of stats everytime a translaion is saved/approved/rejected and so on.
Instead of that, We create a small map with states of an entity before and after a translation.
Thanks to that, we're able to generate a diff and apply it to the all AggregatedStats objects. 
To give you more perspective, I've made some benchmarks: https://gist.github.com/jotes/c040baa84faab7ce68bbc7875590e9f4
If you have any additional questions/suggestions/metrics that could be useful -> feel free to suggest them.
Misc changes:
* removed missing variable from `calculate_stats` because it was unused.
TODO:
> Bug 1407016 - Remove calculate_stats() from Translation.save()

- requirements.txt
Notably, we're picking up the checker file pattern, and bug 1512709, to
keep namespace prefixes on Android documents.
https://github.com/Pike/compare-locales/compare/RELEASE_5_0_0...RELEASE_5_0_3
> Update compare-locales to pick up fixes for Android.

- pontoon/base/models.py
Each Unreviewed suggestion should be counted separately in stats. Until this patch, all Unreviewed suggestions of a pluralized entity for a given locale were counted as 1.
After landing this patch, we also need to `./manage.py calculate_stats` for all .po projects.
@jotes r? Details on IRC.
> No bug: Fix counting unreviewed pluralized strings in calculate_stats

- pontoon/checks/libraries/translate_toolkit.py
I've deployed this to stage as the first step to fixing bug 1514691.
Could you please have a look, @flodolo?
> Bug 1514691: Change wording of the empty translation warning

- pontoon/administration/views.py
This fixes the locales ordered by locale code. I have used `order_by('code')` function for this bug.
> Bug 1394194 - List of locales in Admin ordered by locale code

- pontoon/base/static/js/fluent_interface.js
- pontoon/sync/formats/ftl.py
This is how the non-imported strings from prod look on stage:
https://mozilla-pontoon-staging.herokuapp.com/ru/firefox/browser/browser/branding/sync-brand.ftl/
https://mozilla-pontoon-staging.herokuapp.com/uk/firefox/browser/browser/branding/sync-brand.ftl/
> Fix bug 1521523: [FTL] Hardcode - in front of Term keys

- pontoon/sync/formats/ftl.py
https://github.com/mozilla/pontoon/commit/d7d3d9af2d09703bff44b486910c876a65f9fe37 only fixes the problem with term keys on file import. This patch does the same for export.
> Fix bug 1521523: [FTL] Also hardcode - on serialization

- pontoon/base/views.py
- pontoon/batch/views.py
- pontoon/contributors/views.py
- pontoon/machinery/views.py
- pontoon/teams/views.py
Hello,
I noticed 5 Cross-Site Scripting [(XSS)](https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)) Vulnerabilities in the pontoon project. 
For each of the vulnerabilities please find a proposed fix in the corresponding commit. The commit messages include a Proof of Concept exploit to trigger the vulnerability. 
Fortunately, I couldn't bypass the CSP, so these vulnerabilities might not be easily exploitable. Some of them are additionally protected by CSRF-cookies, which makes exploiting them in a real-world scenario even harder. Nevertheless, each of them is still a major security risk, which someone more skilled than me might successfully exploit, so i would suggest fixing them. Please consider my patches, which should mitigate the vulnerabilities and not harm legit usages of …
> Fix several Cross-Site Scripting Vulnerabilities

- pontoon/base/static/css/style.css
- pontoon/base/templates/no_projects.html
- pontoon/homepage/views.py
- pontoon/projects/views.py
- pontoon/teams/views.py
Added a new template instead of 404ing when no projects are present as discussed on IRC.
This is how it looks:
PS:  Design subject to change :P
> Fix bug 1497572: Improve custom deployment experience 

- .dockerignore
- docker-compose.yml
- docker/Dockerfile.base
This requires the container to have git, and the local .git folder. With those, running tests with jest automatically only runs the tests that have changed since the last commit.
> No bug - Enable running only changed frontend tests.

- frontend/public/static/locale/en-US/translate.ftl
- frontend/public/static/locale/fr/translate.ftl
- frontend/src/core/api/index.js
- frontend/src/core/api/locale.js
- frontend/src/core/api/machinery.js
- frontend/src/core/api/types.js
- frontend/src/core/locales/actions.js
- frontend/src/modules/entitydetails/components/EntityDetails.js
- frontend/src/modules/entitydetails/components/MachineryCount.js
- frontend/src/modules/entitydetails/components/MachineryCount.test.js
- frontend/src/modules/entitydetails/components/Tools.css
- frontend/src/modules/entitydetails/components/Tools.js
- frontend/src/modules/machinery/actions.js
- frontend/src/modules/machinery/components/Machinery.css
- frontend/src/modules/machinery/components/Machinery.js
- frontend/src/modules/machinery/components/Machinery.test.js
- frontend/src/modules/machinery/components/Translation.css
- frontend/src/modules/machinery/components/Translation.js
- frontend/src/modules/machinery/components/Translation.test.js
- frontend/src/modules/machinery/index.js
- frontend/src/modules/machinery/reducer.js
- frontend/src/rootReducer.js
- pontoon/api/schema.py
This adds the Machinery tab and all its features. On load, fetches translations from various sources (Machine Translation, Translation Memory) and shows it as it arrives. Also allows searching for specific terms.
@mathjazz the commits in this branch are a bit erratic, so I'm not sure there's much value reviewing this one commit at a time. That is because I've been working weirdly on this, going back and forth as I understood more about the feature.
Note that the search bar does nothing for now, as this patch is already huge. I'll do that in follow-up [bug 1524549](https://bugzilla.mozilla.org/show_bug.cgi?id=1524549). The copy on click action will be covered in [bug 1490346](https://bugzilla.mozilla.org/show_bug.cgi?id=1490346).
> Fix bug 1486496 - Add a Machinery tab to Translate.Next. 

- frontend/public/static/locale/en-US/translate.ftl
- frontend/public/static/locale/es/translate.ftl
- frontend/public/static/locale/fr/translate.ftl
- frontend/src/core/api/translation.js
- frontend/src/modules/history/actions.js
- frontend/src/modules/history/components/History.js
- frontend/src/modules/history/components/Translation.css
- frontend/src/modules/history/components/Translation.js
- frontend/src/modules/history/components/Translation.test.js
- pontoon/base/views.py
This is a WIP patch which:
1. Shows the delete button when needed.
2. Deletes the translation on click.
This is the work that remains to be migrated:
https://github.com/mozilla/pontoon/blob/ba838fa88b787a9323f563987c35a4904fcab942/pontoon/base/static/js/translate.js#L2325-L2347
@adngdb I need some help:
1. How am I doing so far?
2. How do I reference the button to apply the `delete` class to it? Should I do that in `actions.js`?
3. How do I update count? Do I need to update `history.translations` first and then use length?
> Fix bug 1518828: [Translate.Next] Implement delete option in History tab

- docker/Dockerfile.base
While investigating a potential issue with our Dockerfile, I read that gosu's instruction for verifying the GPG key has changed a bit, so I took the time to update our build process.
See https://github.com/tianon/gosu/commit/74d8730b0bab611cbf204fd4419ef21ecb6df017 for reference.
Also, I guess we actually weren't verifying anything with that command of ours, for it missing the second argument of the `gpg` command... :disappointed:
> No bug - use --batch option to verify gosu gpg signature.

- pontoon/base/static/js/fluent_interface.js
This patch extends the ability to use multiline values wherever in a Fluent Message.
ATM, multiline values are only supported in simple messages, e.g.:
https://mozilla-pontoon-staging.herokuapp.com/de/fluent/demo.ftl/?string=195116
However, using them in select expressions and other more complex messages results in errors, e.g.:
https://mozilla-pontoon-staging.herokuapp.com/de/fluent/demo.ftl/?string=195048
To understand the problem better, you can try to save the translation below to the strings above on stage (which still runs the old code) and then test again locally with the patch applied:
```
This is a multiline
message.
```
> Fix bug 1525539: Support multiline everywhere

- frontend/public/static/locale/en-US/translate.ftl
- frontend/public/static/locale/fr/translate.ftl
- frontend/src/modules/editor/components/Editor.js
- frontend/src/modules/editor/components/Editor.test.js
- frontend/src/modules/editor/components/GenericEditor.js
- frontend/src/modules/entitydetails/components/EntityDetails.js
- frontend/src/modules/entitydetails/components/EntityDetails.test.js
- frontend/src/modules/entitydetails/components/Tools.js
- frontend/src/modules/history/components/History.js
- frontend/src/modules/history/components/History.test.js
- frontend/src/modules/history/components/Translation.css
- frontend/src/modules/history/components/Translation.js
- frontend/src/modules/machinery/components/Machinery.js
- frontend/src/modules/machinery/components/Machinery.test.js
- frontend/src/modules/machinery/components/Translation.css
- frontend/src/modules/machinery/components/Translation.js
- frontend/src/modules/otherlocales/components/Locales.css
- frontend/src/modules/otherlocales/components/Locales.js
- frontend/src/modules/otherlocales/components/Locales.test.js
- frontend/src/modules/otherlocales/components/Translation.css
- frontend/src/modules/otherlocales/components/Translation.js
This enables copying a translation in one of the helper tabs (History, Machinery, Locales) into the Editor when clicked. It involves refactoring some of those components to make the data flow the right way. It might not be the best way to do this, but it works and is satisfying for now. We might want to refactor this part of the code again later.
This also separates CSS rules for the various Translation components of the tabs, so that they do not impact each other.
> Fix bug 1490346 - Copy translations into the Editor on click.

- package.json
encountered the following error on **webpack-cli v2.1.5**:
```
webpack -p
/opt/pontoon/node_modules/webpack-cli/bin/config-yargs.js:89
describe: optionsSchema.definitions.output.properties.path.description,
^
TypeError: Cannot read property 'properties' of undefined
at module.exports (/opt/pontoon/node_modules/webpack-cli/bin/config-yargs.js:89:48)
at /opt/pontoon/node_modules/webpack-cli/bin/webpack.js:60:27
at Object.<anonymous> (/opt/pontoon/node_modules/webpack-cli/bin/webpack.js:515:3)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
```
looks almost …
> fix(webpack-cli): Cannot read property 'properties' of undefined

- frontend/public/static/locale/en-US/translate.ftl
- frontend/public/static/locale/fr/translate.ftl
- frontend/src/modules/editor/components/Editor.js
- frontend/src/modules/editor/components/EditorSettings.css
- frontend/src/modules/editor/components/EditorSettings.js
- frontend/src/modules/editor/components/KeyboardShortcuts.css
- frontend/src/modules/editor/components/KeyboardShortcuts.js
- frontend/src/modules/search/components/FiltersPanel.js
Note: the actual keyboard shortcuts are tracked in [bug 1525984](https://bugzilla.mozilla.org/show_bug.cgi?id=1525984).
> Fix bug 1519921: Add keyboard shortcut list

- CONTRIBUTING.rst
I'm not exactly sure how to talk about the 2 different frontend apps (Translate.Next and the code for tags). The documentation for Translate.Next is in its README, so I could point there maybe? Or I could not even talk about Translate.Next for now and wait until it's turned on? What do you think?
> No bug - Refresh our Contributing documentation file.

- .eslintrc.js
- frontend/src/lib/react-content-marker/createMarker.js
- frontend/src/lib/react-content-marker/createMarker.test.js
- frontend/src/lib/react-content-marker/index.js
- frontend/src/lib/react-content-marker/mark.js
- frontend/src/lib/react-content-marker/mark.test.js
- frontend/src/lib/react-content-marker/markRegExp.js
- frontend/src/lib/react-content-marker/markRegExp.test.js
- frontend/src/lib/react-content-marker/markTerm.js
- frontend/src/lib/react-content-marker/markTerm.test.js
This tool can be used to generate a React component that will apply a list of parsers to a string, and replace each matching pattern or term with a special marker. It currently supports RegExp and simple string terms. The markers can be anything, allowing us to define specific tags to use for each parser.
Note that this tool is in a `lib` folder because I intend to extract it to a library in the future.
Note: I'm asking review from all of you because this is a pretty generic problem and I'd like to get some feedback on my algorithms here.
> Bug 1492166 - Add a tool to mark patterns in a string.

- pontoon/base/views.py
This fixes the following error shown in the JS Console when a user tries to submit a translation to a read-only project:
```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```
While the error will be harder to trigger when [bug 1528273](https://bugzilla.mozilla.org/show_bug.cgi?id=1528273) gets fixed, we should still convert all AJAX responses to JSON, because that's what our new frontend expects. So this is just a first step. I'd be happy to make the next (and the final) one in a follow-up commit.
It shouldn't be too hard to keep compatibility with Translate.Current if we keep the status codes unchanged, because that's what our old frontend expects.
@adngdb Thoughts?
> Fix bug 1528293: Convert read-only AJAX responses to JSON

- pontoon/wsgi.py
- requirements.txt
Thanks to @adngdb for the hint! ([source](https://github.com/evansd/whitenoise/issues/53))
The patch is [deployed on stage for testing](https://mozilla-pontoon-staging.herokuapp.com/sl/firefox/browser/branding/official/brand.ftl/?string=175817).
> Fix bug 1529895: Serve static files with HSTS header

- pontoon/settings/base.py
- pontoon/wsgi.py
It turns out `sslify` takes care of `HSTS` for all requests, so we don't need to (and shouldn't) set it via the `SECURE_HSTS_SECONDS` setting. This patch addresses that.
It's deployed to stage:
https://mozilla-pontoon-staging.herokuapp.com/sl/firefox/
@psiinon r?
> Fix bug 1529895: Set Strict-Transport-Security header only once

- pontoon/base/templates/no_projects.html
@VishalCR7 r?
It doesn't make much sense to show the "Set up your first project" link to all users.
> Only show "Set up your first project" link to admins

- pontoon/tour/static/js/tour.js
This patch adds a link to the locale dashboard in the last step of the tour. The locale is the same as the one the tour has been taken in.
@MikkCZ r?
> Fix bug 1525863: In tour, add link to the team dashboard

- pontoon/homepage/templates/homepage_content.html
Now that the homepage content can be customized, we should make the default content generic and override it on pontoon.mozilla.org.
> Fix bug 1536897: Make homepage content generic

- frontend/src/core/loaders/components/CircleLoader.css
The loader at the end of the string list is always visible and spinning, which changes its height and the height of the entity list. In effect, that flashes the scrollbar.
By making the loader height fixed, scrollbar flashing stops.
> Fix bug 1527864: Prevent entity list scrollbar flashing

- frontend/src/modules/editor/components/Editor.js
- frontend/src/modules/editor/components/EditorProxy.js
- frontend/src/modules/editor/components/GenericEditor.js
- frontend/src/modules/editor/components/GenericEditor.test.js
This is part one of bug 1525984. It adds three shortcuts for the Editor: send translation on Enter, copy original on Ctrl + Shift + C and clear on Ctrl + Shift + Backspace.
@mathjazz, I'm going to do this in parts, because it will make it easier for you to review, and also those shortcuts aren't really tied to each others.
> Bug 1525984 - Add basic keyboard shortcuts for the Editor.

- frontend/public/static/locale/en-US/translate.ftl
- frontend/src/modules/editor/components/Editor.js
- frontend/src/modules/editor/components/Editor.test.js
- frontend/src/modules/editor/components/EditorProxy.js
- frontend/src/modules/editor/components/FluentEditor.js
- frontend/src/modules/editor/components/GenericEditor.js
- frontend/src/modules/entitydetails/components/EntityDetails.js
- frontend/src/modules/entitydetails/components/Metadata.js
- frontend/src/modules/entitydetails/components/Tools.js
- frontend/src/modules/entitydetails/selectors.js
- frontend/src/modules/entitydetails/selectors.test.js
- frontend/src/modules/history/components/History.js
- frontend/src/modules/history/components/Translation.js
- frontend/src/modules/history/components/Translation.test.js
- frontend/src/modules/machinery/components/Machinery.js
- frontend/src/modules/machinery/components/Translation.js
- frontend/src/modules/otherlocales/components/OtherLocales.js
- frontend/src/modules/otherlocales/components/Translation.js
In addition to supporting [read-only projects](https://bugzilla.mozilla.org/show_bug.cgi?id=1528273) as expected, this bug also extends support for [non-authenticated mode](https://bugzilla.mozilla.org/show_bug.cgi?id=1524602), by:
* making editor read-only
* disabling copying from helpers (tools)
* disabling copying from placeables
> Fix bug 1528273: Properly support read-only projects

- frontend/src/modules/machinery/components/Translation.js
- requirements/default.txt
Caighdean API endpoint [has moved](https://github.com/translate/python-caighdean/pull/2). Since the PR hasn't been merged upstream yet, we need to switch to a fork, which fixes the endpoint.
The patch is deployed to stage:
https://mozilla-pontoon-staging.herokuapp.com/ga-IE/firefox/browser/branding/official/brand.dtd/?string=74131
> Fix bug 1542575: Update Caighdean endpoint by using fork

- pontoon/contributors/urls.py
Created a username with a dot and it broke pontoon. Included a dot as a possible character for usernames on django urls configuration.
> Fix bug 1543193: Changed the url regexp for usernames to accept dots

- .pyup.yml
- .travis.yml
- CONTRIBUTING.rst
- docker/Dockerfile
- requirements.txt
- requirements/default.txt
- requirements/python2.txt
I moved `mercurial` to a separate requirements file and updated the version of `silme`.
However, it's still WIP.
TODO:
> Fix bug 1537613: Move Mercurial to a separate requirements file

- pontoon/machinery/tests/test_views.py
- pontoon/machinery/views.py
Caighdean MT takes `gd` translations as source and returns machine translation suggestions for `ga-IE`. We need to be more specific in determining the source string in order to prevent errors like this:
```
Message: str: get() returned more than one Translation -- it returned 2!
Traceback:
File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic/hooks/framework_django.py", line 544, in wrapper
return wrapped(*args, **kwargs)
File "/app/pontoon/machinery/views.py", line 239, in caighdean
text = entity.translation_set.get(locale__code='gd').string
File …
```
> Caighdean: Use approved translation of the right plural form as source

- requirements/constraints.txt
- requirements/default.txt
We switched to our own caighdean fork as part of bug 1542575. Since the
patch has been merged, we can now switch back to upstream caighdean.
@jotes One more r?
> Switch back to upstream caighdean

- frontend/src/modules/entitydetails/components/Metadata.css
If the source string is long or contains a longer description, we should allow scrolling to reveal all the information.
> Add overflow:auto to .metadata

- frontend/src/modules/editor/actions.js
- frontend/src/modules/editor/components/Editor.js
- frontend/src/modules/editor/components/Editor.test.js
- frontend/src/modules/editor/components/EditorProxy.js
- frontend/src/modules/editor/components/FluentEditor.js
- frontend/src/modules/editor/components/FluentEditor.test.js
- frontend/src/modules/editor/components/GenericEditor.js
- frontend/src/modules/editor/components/GenericEditor.test.js
- frontend/src/modules/editor/reducer.js
This removes the state buffer for the content of the various Editors. It was causing bugs when users were typing fast, because of our usage of debounce. It also turns out that not having that debounce is fine in terms of performance. Premature optimization it was! Bad developer!
> Fix bug 1542617 - Prevent character disappearance in Editor.

- frontend/src/modules/entitieslist/components/Entity.css
- frontend/src/modules/entitieslist/components/Entity.js
- frontend/src/modules/entitieslist/components/Entity.test.js
- frontend/src/modules/entitieslist/reducer.js
This fixes two things:
1. It takes into account all plural forms when determining entity status, not just the first one.
2. It adds support for `errors`, `warnings` and `partial` stati.
> Fix bug 1545450: Fix entity status icons

- frontend/public/static/locale/en-US/translate.ftl
- frontend/src/core/api/translation.js
- frontend/src/modules/editor/actions.js
- frontend/src/modules/editor/components/Editor.js
- frontend/src/modules/editor/components/EditorProxy.js
- frontend/src/modules/editor/components/EditorProxy.test.js
- frontend/src/modules/editor/components/FailedChecks.css
- frontend/src/modules/editor/components/FailedChecks.js
- frontend/src/modules/editor/components/FailedChecks.test.js
- frontend/src/modules/editor/components/FluentEditor.js
- frontend/src/modules/editor/components/FluentEditor.test.js
- frontend/src/modules/editor/components/GenericEditor.js
- frontend/src/modules/editor/components/GenericEditor.test.js
- frontend/src/modules/editor/reducer.js
- frontend/src/modules/entitieslist/reducer.js
- frontend/src/modules/entitydetails/components/EntityDetails.js
- frontend/src/modules/entitydetails/components/EntityDetails.test.js
- frontend/src/modules/history/actions.js
- pontoon/base/tests/views/test_translation.py
- pontoon/base/views.py
This is a WIP, see TODO for details. Due to the indent fix, it will be easier to review on a commit-by-commit basis.
TODO:
> Fix bug 1518820: Add errors and warnings

- frontend/src/modules/editor/components/Editor.css
- frontend/src/modules/editor/components/GenericEditor.js
- pontoon/base/static/css/translate.css
- pontoon/base/templates/translate.html
Changes:
* Added different styling to textarea for non-authenticated users. (translate.css)
* Changed placeholder text to clearly state what is required next. (translate.html)
The textarea in question already was already readonly and disabled focus, this pull request just adds in the formatting changes that were also requested when the bug report was created. 
Rather than removing the placeholder text, the placeholder text now also directs the user to sign in, in case the link below was overlooked.
Testing:
Viewed and interacted with textarea both as an authenticated and non-authenticated user.
> Bug 1429392 - Textarea More Explicitly Locked for Non-Auth Users

- frontend/src/modules/editor/components/Editor.js
- frontend/src/modules/editor/components/TranslationLength.css
- frontend/src/modules/editor/components/TranslationLength.js
- frontend/src/modules/editor/components/TranslationLength.test.js
This patch adds support for translation length information. For `LANG` strings with `MAX_LENGTH` provided in their comment, it shows countdown instead.
> Fix bug 1519931: Show string length and countdown

- frontend/src/core/utils/components/withActionsDisabled.js
- frontend/src/modules/editor/components/Editor.js
- frontend/src/modules/editor/components/Editor.test.js
- frontend/src/modules/editor/components/FailedChecks.js
- frontend/src/modules/editor/components/FailedChecks.test.js
- frontend/src/modules/editor/components/GenericEditor.js
- frontend/src/modules/editor/components/GenericEditor.test.js
- frontend/src/modules/entitydetails/components/EntityDetails.test.js
- frontend/src/modules/entitydetails/index.js
- frontend/src/modules/entitydetails/withActionsDisabled.js
- frontend/src/modules/history/components/Translation.js
- frontend/src/modules/history/components/Translation.test.js
This solution is inspired by: https://stackoverflow.com/a/49642037. I tried to avoid using `ref`.
I wonder if there's a better approach for preventing multiple in React world. If not, I'll add a similar solution for saving translations/suggestions.
> Fix bug 1543158: Prevent multiple review/delete requests

- frontend/README.md
- pontoon/base/templates/translate.html
- pontoon/base/views.py
- pontoon/translate/tests/test_views.py
- pontoon/translate/views.py
We do that by switching (pun not intended) from `waffle.switch` to `waffle.flag`.
> Fix bug 1550490: Allow activating Translate.Next for a subset of users

- frontend/public/static/locale/en-US/translate.ftl
- frontend/src/core/api/entity.js
- frontend/src/core/notification/messages.js
- frontend/src/modules/entitieslist/actions.js
- frontend/src/modules/entitieslist/components/EntitiesList.js
- frontend/src/modules/entitydetails/components/EntityDetails.js
- frontend/src/modules/entitydetails/components/EntityDetails.test.js
This patch loads entities that are not on the first page and scrolls the string list accordingly.
Also:
* If entity isn't found, the first entity is selected and a notification is sent.
* Fixes a bug that didn't populate the editor and update checks if entity specified via URL
> Fix bug 1539228: Load entities not on the first page

- frontend/package.json
- frontend/src/core/api/base.js
- frontend/src/core/api/entity.js
- frontend/src/core/api/machinery.js
- frontend/src/modules/history/actions.js
- frontend/src/modules/machinery/actions.js
- frontend/src/modules/otherlocales/actions.js
- frontend/yarn.lock
Whenever we fetch new content for the History, Machinery or Locales tabs, this cancels all previously running requests before starting new ones. This will reduce the load on the server and avoid mixed data issues in our tabs.
> Fix bug 1543162 - Cancel previously running requests when changing entity.

- frontend/src/modules/search/components/SearchBox.css
- frontend/src/modules/search/index.js
The current Approved filter not has a wrong name, it also doesn't filter anything.
> Fix bug 1553649: Rename Approved filter to Translated

- frontend/src/modules/history/actions.js
If approving a translation results in a failed check, we shouldn't display the notification on top of the page.
It doesn't add value and distracts the user from the actual focus, which should be in the failed checks popup.
> Fix bug 1553621: Don't show review action notifications on failed checks

- frontend/public/static/locale/en-US/translate.ftl
- frontend/src/core/api/index.js
- frontend/src/core/api/resource.js
- frontend/src/core/api/translation.js
- frontend/src/core/navigation/components/Navigation.css
- frontend/src/core/navigation/components/Navigation.js
- frontend/src/core/resource/actions.js
- frontend/src/core/resource/components/ResourceItem.css
- frontend/src/core/resource/components/ResourceItem.js
- frontend/src/core/resource/components/ResourceItem.test.js
- frontend/src/core/resource/components/ResourceMenu.css
- frontend/src/core/resource/components/ResourceMenu.js
- frontend/src/core/resource/components/ResourceMenu.test.js
- frontend/src/core/resource/components/ResourcePercent.css
- frontend/src/core/resource/components/ResourcePercent.js
- frontend/src/core/resource/components/ResourcePercent.test.js
- frontend/src/core/resource/index.js
- frontend/src/core/resource/reducer.js
- frontend/src/core/resource/reducer.test.js
- frontend/src/modules/editor/actions.js
- frontend/src/modules/editor/components/Editor.js
- frontend/src/modules/editor/components/Editor.test.js
- frontend/src/modules/entitieslist/reducer.js
- frontend/src/modules/entitydetails/components/EntityDetails.js
- frontend/src/modules/entitydetails/components/Metadata.js
- frontend/src/modules/entitydetails/components/Metadata.test.js
- frontend/src/modules/history/actions.js
- frontend/src/rootReducer.js
- pontoon/base/views.py
This patch exposes the name of the resource currently localized in the main navigation, and lists the entire batch of project resources with their completion percentages in the corresponding menu.
Selecting a resource in the menu hot-reloads the translate view. Before loading we check for any unsaved changes in the editor, which we now also do upon clicking on the resource path in the Metadata section.
--
I still need to implement search and write some tests, and then I believe navigation will be in a good enough state for Stage 2 testing. We'll still need to figure out what to do with "All Projects" afterwards, because right now that view hides the resource menu and makes it hard to switch to the regular locale - project - resource view.
@adngdb I'd appreciate your help with the "Can't …
> Fix bug 1519894: Add Resource menu

- pontoon/base/templates/js/pontoon.js
Really we should be using `{{settings.SITE_URL}}` here, but then we'd need to strip out the scheme.
> Use correct url for jquery

- frontend/src/core/plural/components/PluralSelector.css
- frontend/src/core/resource/reducer.js
- frontend/src/modules/editor/actions.js
- frontend/src/modules/editor/components/Editor.js
- frontend/src/modules/editor/components/Editor.test.js
- frontend/src/modules/entitydetails/components/EntityDetails.js
- frontend/src/modules/history/actions.js
Pass entity path, not resource parameter for updating stats in Resource menu. Without this fix, an error occurs in All Resources view every time you send or approve a translation.
A regression from https://bugzilla.mozilla.org/show_bug.cgi?id=1519894.
> All resources update

- frontend/src/core/utils/asLocaleString.js
- frontend/src/core/utils/index.js
- frontend/src/modules/resourceprogress/components/ResourceProgress.css
- frontend/src/modules/resourceprogress/components/ResourceProgress.js
- frontend/src/modules/search/components/FiltersPanel.js
I'm hardcoding `en-US` to make number formatting consistent with dashboards.
> Format numbers in resource progress and filters

- .pyup.yml
- CONTRIBUTING.rst
- requirements.txt
Hey,
The integration with Heroku isn't so thoroughly, and #1288 broke the requirements dedicated for Heroku.
This PR removes all remains of `requirements/python2.txt`.
@mathjazz @adngdb Could you look at this?
> Bug 1541252 - Fix deployment on Heroku

- frontend/src/core/user/components/UserNotification.js
- frontend/src/core/user/components/UserNotificationsMenu.test.js
- frontend/src/modules/history/components/Translation.js
- pontoon/base/models.py
- pontoon/base/views.py
The format of `date_iso` in notifications data returned by `/user-data/` endpoint is not valid. It contains duplicated timezone offset. The same is in `/get-history/`.
This should fix it and also avoid the [parsing magic](https://github.com/nmn/react-timeago/blob/v4.4.0/src/dateParser.js) which happens in _react-timeago_ [when `date` is a string](https://github.com/nmn/react-timeago/blob/v4.4.0/src/index.js#L187). They only [test with `Date` objects](https://github.com/nmn/react-timeago/blob/v4.4.0/__tests__/index.js), so let's use them too.
> Fix ISO date format for notifications data and translation history

- frontend/src/modules/editor/components/FluentEditor.js
- pontoon/settings/base.py
Without this patch, wrapped lines in the following string will appear indented:
```
update-setting-write-failure-message =
{-brand-short-name} encontró un error y no guardó este cambio. Tenga en cuenta que la configuración de esta preferencia de actualización requiere permiso para escribir en el archivo a continuación. Es posible que usted o un administrador del sistema puedan resolver el error otorgando al grupo de Usuarios el control total de este archivo.
```
Also: Show ACE editor icons by loosing CSP policy (it doesn't affect our [Observatory](https://observatory.mozilla.org/) score).
> Fix bug 1556947: Do not use indent in wrapped lines

- frontend/README.md
- frontend/package.json
- frontend/src/core/user/components/UserNotification.js
- frontend/src/index.js
- frontend/src/modules/history/components/Translation.js
- frontend/yarn.lock
The new library has the benefit of only updating every minute (not second) and supports more human readable outputs for edge cases (e.g. "Just now" vs. "1 second ago").
It also supports localizability, which we'll need in the future.
> Fix bug 1559298: Update TimeAgo library

- pontoon/base/static/css/heading_info.css
> Align team page heading details position with other dashboards

- frontend/public/index.html
- pontoon/base/templates/500.html
- pontoon/base/templates/base.html
- pontoon/base/templates/django/base.html
Let's use the same wording we use throughout the docs, GitHub, README, etc.
Let's also add Meta Description to Translate.Next.
It should improve our SEO.
> Unify Meta Description across templates

- .travis.yml
Hey,
This patch introduces a few small changes:
* TravisCI will run all back-end tests on Python 3 in a separate job
* Failures on Python 3 are allowed, ([demo](https://travis-ci.org/jotes/pontoon/builds/552472428)).
* Enables support for Python 3 in Mercurial.
@mathjazz @adngdb  can you look at this?
> Fix bug 1542084 - Add Python 3 to the testing matrix

- frontend/src/modules/entitydetails/components/EntityDetails.js
- frontend/src/modules/history/actions.js
- frontend/src/modules/history/reducer.js
- frontend/src/modules/machinery/actions.js
- frontend/src/modules/machinery/reducer.js
- frontend/src/modules/otherlocales/actions.js
- frontend/src/modules/otherlocales/reducer.js
I'd like to add a comment in comment in `componentDidUpdate` to explain why do we need the `selectedEntity !== prevProps.selectedEntity` check. But I forgot the answer. :) Could you please remind me?
Note that I've found some unused code and inconsistencies, which are addressed in followup commits.
> Fix bug 1555083: Prevent duplicate helpers requests

- pontoon/base/static/js/fluent_interface.js
Translating a string like this in the rich editor is not possible - it results in an `Expected literal` error upon saving:
```
number =
{ NUMBER($var, type: "ordinal") ->
[1] first
[one] { $var }st
*[other] { $var }nd
}
```
**What's going on?**
Pontoon doesn't show selectors (in this case `NUMBER($var, type: "ordinal")`) in the rich editor, but still stores them in DOM to help with serialization. Specifically, it naïvely puts them in `data-expression` attributes, without any escaping.
So when the selector contains quotes, like in our example, content gets stripped upon serialization, resulting in the above error. The serialized string looks like this:
```
number =
{ NUMBER($var, type:  ->
[1] first
[one] { $var }st
*[other] { $var }nd
}
```
A test case: …
> Fix bug 1563677: Escape selectors in data-expression attributes

- frontend/public/static/locale/en-US/translate.ftl
- frontend/public/static/locale/es/translate.ftl
- frontend/public/static/locale/fr/translate.ftl
- frontend/src/core/editor/components/EditorMenu.js
- frontend/src/core/editor/components/EditorMenu.test.js
- frontend/src/core/editor/components/EditorSettings.js
- frontend/src/core/editor/components/KeyboardShortcuts.js
- frontend/src/core/resource/components/ResourceMenu.js
- frontend/src/core/resource/components/ResourceMenu.test.js
- frontend/src/modules/entitydetails/components/EntityNavigation.js
- frontend/src/modules/entitydetails/components/Metadata.js
- frontend/src/modules/entitydetails/components/Metadata.test.js
- frontend/src/modules/history/components/History.js
- frontend/src/modules/history/components/History.test.js
- frontend/src/modules/history/components/Translation.js
- frontend/src/modules/machinery/components/Machinery.js
- frontend/src/modules/machinery/components/Machinery.test.js
- frontend/src/modules/machinery/components/Translation.js
- frontend/src/modules/otherlocales/components/Translation.js
This is a maintenance patch to:
1. sort the content of FTL files alphabetically;
2. harmonize our usage of l10n IDs to follow our convention everywhere;
3. add the missing French translations.
Each step is a separate commit, hopefully that's easy to review. :-)
> No bug - Reorganize FTL files

- frontend/public/static/locale/en-US/translate.ftl
- frontend/src/core/api/entity.js
- frontend/src/core/entities/actions.js
- frontend/src/core/navigation/actions.js
- frontend/src/core/navigation/selectors.js
- frontend/src/modules/batchactions/actions.js
- frontend/src/modules/batchactions/components/BatchActions.js
- frontend/src/modules/entitieslist/components/EntitiesList.js
- frontend/src/modules/search/components/FiltersPanel.css
- frontend/src/modules/search/components/FiltersPanel.js
- frontend/src/modules/search/components/FiltersPanel.test.js
- frontend/src/modules/search/components/SearchBox.css
- frontend/src/modules/search/components/SearchBox.js
- frontend/src/modules/search/components/SearchBox.test.js
- frontend/src/modules/search/index.js
In addition to fixing the bug, this patch also:
* Fixes the size of the Unreviewed checkbox (b1e79a5)
* Shows checkmark when hovering filter icons (f3e6a98)
* Brings some refactorings to better support multiple groups of filters (559c64c)
It also **drops the Untranslated filter** due to low usage compared to the code and UX complexity it comes with. The logs only show 10 hits per day, and it's impossible to tell how many of those are triggered by the Untranslated filter and how many are manual selections of the "Fuzzy, Errors, Missing" filters.
> Fix bug 1510185: Add extra filters

- pontoon/urls.py
I wonder if this is an opportunity to also drop "Redirect legacy Aurora projects".
This patch is deployed to stage:
https://mozilla-pontoon-staging.herokuapp.com/ga/
https://mozilla-pontoon-staging.herokuapp.com/pt/
You can compare that with production, which still redirects:
https://pontoon.mozilla.org/ga/
https://pontoon.mozilla.org/pt/
> Fix bug 1571039: Do not hardcode locale redirects

- frontend/src/core/utils/fluent/getReconstructedSimpleMessage.js
- frontend/src/core/utils/fluent/getReconstructedSimpleMessage.test.js
- frontend/src/core/utils/fluent/index.js
- frontend/src/core/utils/fluent/serializer.js
- frontend/src/modules/fluenteditor/components/Editor.test.js
- frontend/src/modules/fluenteditor/components/SimpleEditor.test.js
I'll probably go ahead and merge this to prevent any [DB inconsistencies](https://bugzilla.mozilla.org/show_bug.cgi?id=1573437#c0).
I'd still appreciate a review.
> Fix bug 1573437: Ensure strings are serialized with default Fluent serializer settings

- frontend/src/core/editor/reducer.js
- frontend/src/modules/genericeditor/components/GenericTranslationForm.js
- frontend/src/modules/unsavedchanges/actions.js
On long run, we might be able to survive without `initialTranslation`. For now, this is effectively a one liner that resets its value when it's not needed.
> Fix bug 1569863: Do not trigger unsaved changes warning when switching Fluent and non-Fluent strings

- frontend/src/modules/unsavedchanges/reducer.js
When a translation is saved or added, we set the "ignored" boolean to true in unsavedchanges to hide the check before moving to the next entity. However, that boolean was never reset, because that only happened when "hide" was called, and hide could only be called when the panel was displayed, and the panel was never displayed because ignored was true. This patch resets the "ignored" state to false every time the state is updated.
> Fix bug 1566869 - Reset ignored state on unsavedchanges update.

- pontoon/administration/tests/test_views.py
- pontoon/base/models.py
- requirements/default.txt
Hey,
The PR fixes unittests for the administration module.
Major changes :
* I've bumped up the version of `django-cookies-samesite` because of the missing Cookie module
* The `HTTPResponse.content`  returns a bytes object (on Python 3). The `contains` method raises an exception if you check a non-bytes object.
@adngdb @mathjazz r?
> Bug 1362323 - Fix tests for the administration app.

- frontend/src/modules/search/components/TimeRangeFilter.js
This PR was split out of #1363 to properly reference the bug it is addressing.
It establishes a state for the input fields that is separate from the chart boundaries. That allows us to display invalid inputs, mark them as errors (color: red) and prevent unpredictable behavior on input reported in the [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1377872).
> Fix bug 1377872: Validate manual time range input

- frontend/src/modules/search/components/TimeRangeFilter.js
This is a simplified solution to force a 4-digit YYYY until the fix
lands upstream. It also uses isValid() instead of parse().
> Bug 1377872: Simplify time range validation

- pontoon/base/models.py
- pontoon/base/tests/models/test_entity.py
- pontoon/base/tests/models/test_translation.py
- pontoon/test/fixtures/base.py
As of now, translation changes to invisible projects (e.g. system project like tutorial) do update the latest activity column shown on all teams dashboard. That's kind of confusing, since you cannot click through to that system project from any dashboards. As the name suggests, the project is invisible there.
This change omits updating `latest_translation` for a locale if the translation is being saved for a system project. Note, that `latest_translation` is still updated in all other tables, including `project_locale`, because the dashboard of an invisible project is still accessible via direct link or from its translation view and the latest activity should be displayed there.
I have written a small unit test for the behaviour. Also I have tested the patch manually in local setup. Exact …
> Fix Bug 1578057: update locale's latest_translation for visible projects only

- frontend/src/modules/fluentoriginal/components/RichString.js
Without this patch, this happens:
https://bugzilla.mozilla.org/show_bug.cgi?id=1579632
> Fix bug 1579632: Flatten Fluent messages in the Rich Editor

- frontend/src/modules/fluenteditor/components/RichTranslationForm.js
- frontend/src/modules/fluenteditor/components/RichTranslationForm.test.js
And add basic tests for `RichTranslationForm.js`.
> Fix bug 1579745: Set Locale-specific attributes in Fluent Rich Editor

- frontend/src/core/editor/components/connectedEditor.css
- frontend/src/modules/fluenteditor/components/RichTranslationForm.js
- frontend/src/modules/fluenteditor/components/RichTranslationForm.test.js
And keep default cursor above read-only `<textarea>` elements.
> Fix bug 1579746: Set read-only attribute in Fluent Rich Editor

- frontend/src/core/editor/components/connectedEditor.js
- frontend/src/core/editor/components/connectedEditor.test.js
- frontend/src/modules/fluenteditor/components/SourceTranslationForm.js
- frontend/src/modules/genericeditor/components/GenericTranslationForm.js
- frontend/src/modules/genericeditor/components/GenericTranslationForm.test.js
This patch is basically copying and pasting code from `GenericTranslationForm.{test.}js` to `connectedEditor.{test.}js` and reusing it in the source editor.
Specifically, it:
* Wraps connectedEditor component into a withActionsDisabled HOC
* Moves handleShortcuts to connectedEditor and reuses it in Generic and Source Editor
* Moves handleShortcuts tests from GenericEditorForm to connectedEditor
* Keeps handleShortcuts in RichEditor, which uses custom functions
> Fix bug 1543345: Implement Fluent Source Editor shortcuts

- frontend/package.json
- frontend/src/modules/search/components/TimeRangeFilter.js
- frontend/yarn.lock
That way we no longer need a workaround to force a 4-digit YYYY format.
> Update date-and-time to a version that handles YYYY correctly
